### ISSUE TITLE
Add Annotator Window - cannot save new annotator

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#1]
Steps to reproduce:
Menubar > Macro Unit > Edit Macro Unit
Add new annotator
Click New
Fill in name and label, click Save
No response at this point - marking as bug

**Comment by blazetravis** [comment]
This is fixed.

**Comment by kwasiopoku** [comment]
Closing this ticket on behalf of @blazetravis
