### ISSUE TITLE
Gloss Window - one frame glosses

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#10]
One-frame gloss should be necessarily the same start/end handshape (this should be enforced) and in the window it should only display one icon of the handshape, instead of two as currently displays. Should also disallow greater than one handshape being selected in the first place.

**Comment by kwasiopoku** [comment]
Ultimate display is to have one handshape since this is only a one frame object.

**Comment by gregorydimitriadis** [comment]
Including reference to bug #52 here as it is very related.

**Comment by blazetravis** [comment]
Partially fixed. I AM disallowed from selecting more than one handshape, but it is not enforcing "Same START/END hs" ie the option box is not grayed-out.

![screen shot 2015-11-17 at 1 41 35 pm](https://cloud.githubusercontent.com/assets/13489587/11221030/f3e30178-8d30-11e5-8c8f-f90b89693f41.png)

**Comment by gregorydimitriadis** [comment]
This looks like it is not greyed out because Lexical is selected?

**Comment by blazetravis** [comment]
Should this matter? In your description you wrote:

> One-frame gloss should be necessarily the same start/end handshape (**this should be enforced**)

**Comment by gregorydimitriadis** [comment]
Linking this one to issue #8 for the discussion on start/end behavior.

**Comment by blazetravis** [comment]
When retesting this issue today, I encountered another bug.
1. I created a new gloss.
2. I set the new gloss.
3. I left it at one frame to test.
4. I opened up Morph-phon info
5. I tried to change START/END hs and was successfully given a warning message.
6. I went to select handshapes and tried to add 2 handshapes and was successfully given another warning.
7. I deleted the 2 hand shapes and reselected one hand shape.
8. Got the output below in that SignStream populates both the Right and Left hand, even though the gloss was a one-handed sign from the start.

![screen shot 2015-12-01 at 2 02 28 pm](https://cloud.githubusercontent.com/assets/13489587/11511061/dea784c8-9834-11e5-8d3e-bd6d8b8e4a44.png)
1. Went to press enter anyway, and the Morph window would not close.
2. Pressed enter several more times, nothing. So I hit cancel and the window closed, yet it created a new gloss and displayed everything correctly. Strange.

![screen shot 2015-12-01 at 2 08 23 pm](https://cloud.githubusercontent.com/assets/13489587/11511093/0658273e-9835-11e5-8493-5f33972c69ca.png)

**Comment by gregorydimitriadis** [comment]
That is indeed strange, and definitely a new bug.
Blaze, could you please create a new bug with those same details (assuming this current bug, relating to one-frame gloss start/end handshape behavior, is complete and can be closed).

**Comment by blazetravis** [comment]
This issue is fixed otherwise
