### ISSUE TITLE
Not able to start new file

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#100]
Hi - Using the latest version of SignStream (as downloaded from Dropbox just now, with no patches installed), I try to link in a new video file (one we have actually used before, so there shouldn't be a problem); I enter annotator and participant names.  The movie does not play.  I am unable to set up utterances at the highest level, because the movie does not advance.  When I drag and release the mouse, it bounces back to the only visible frame.  If I try to edit the macro unit (from the menu), it does not allow this.
![screen shot 2016-07-26 at 1 17 21 pm](https://cloud.githubusercontent.com/assets/13629122/17148028/64cb9e5e-5333-11e6-8aa1-a72c293db593.png)
![screen shot 2016-07-26 at 1 16 56 pm](https://cloud.githubusercontent.com/assets/13629122/17148029/64d44df6-5333-11e6-990c-3ef6c5a3c4f1.png)

Once we get this working, we should be sure to have students testing the program for creating new files, as well as for editing existing files...

thanks

**Comment by gregorydimitriadis** [comment]
Is this only occurring for this file and/or video? Is the same issue noticeable with other collections?

**Comment by cneidle** [comment]
Hi,

It happens when I try to start a new collection, regardless of what video file
I attempt to link in… 

I am able to open some collections that have been created previously, with their annotations,
without a problem (e.g., Rachel 53).

But when I just tried to open Cory 107, I can’t relocate the video file because
I am not allowed to edit the Macro Unit (“please select a Macro Unit to rename”).

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
That warning about the macro unit displays when nothing is selected on the left side panel. Try to click the text "macro_unit_1" under the expandable "Collection 7 26 2016 ..." on the left, and then re-try to edit the macro unit.

**Comment by cneidle** [comment]
Hi,

Ok, yes, that works.

So the problem is just with creating new files (although this problem with
not being able to edit the macro unit from the menu command is obviously
a bug that needs to be addressed at some point).

thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
Thanks. When you or one of the students get a chance, can you/they please run the debugger script during this error? I don't experience the same thing on my local machine so I'm not sure exactly what is happening.

**Comment by gregorydimitriadis** [comment]
Debugged this via email with Carol - issue turned out to be the file permissions on the signstream_uat archive jar files. Closing this out.
