### ISSUE TITLE
Sprint 16 Deployment Issues

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#103]
I deployed the new version of SignStream today and ran into two different but possibly related significant issues:

1) When using the new version right out of the download folder, it works perfectly at first. It has full functionality and I can do everything I have tested (i.e. make a new nonmanual event, change an existing event label, etc.) but then it will suddenly freeze and the cursor will turn into the rainbow spinning wheel. This happens at seemingly random times, but fairly reliably when trying to quit the program. It will not "unfreeze" no matter how long I wait and I end up having to force quit the program.

2) Trying to make a desktop shortcut to the new version does not seem to work. My guess is that there is an issues with creating aliases. I have tried multiple different ways to make a shortcut and all of them yield the same result: Double clicking the icon brings you to the usual opening screen. Then trying to open a file (Collection --> Open --> Current --> (name of signer) --> (file #) brings you to a blank screen:
![screen shot 2016-09-12 at 11 57 48 am](https://cloud.githubusercontent.com/assets/15836242/18443100/73614058-78e1-11e6-9c77-b34e66f7612d.png)

There are no macro units attached or coded data.

I also tried adding the videos and annotator manually before opening a file, but then clicking "Confirm Selections" does not do anything and the program stays stuck on this page. No other functionalities are accessible and the only thing to do is quit the program. Quitting normally works about 50% of the time and the other 50% it freezes and I have to force quit. 
![screen shot 2016-09-12 at 12 13 00 pm](https://cloud.githubusercontent.com/assets/15836242/18443489/264f1c84-78e3-11e6-8143-c37d3d5228de.png)

**Comment by gregorydimitriadis** [comment]
I believe aliases will indeed not work, since many of the functionalities in Signstream depend on folders being in certain locations (such as /newXMLfiles and /handshapes) and an alias would locate those incorrectly on the file system.

As for the freezing up, can you please run the debugger and go until there is a freeze and you're forced to manually quit? I can check the output file to see if there were any errors which made the freeze happen.

**Comment by gregorydimitriadis** [comment]
@hammondcl Also, is there any particular scenario where it's more likely to freeze? You mentioned when you're about to close the program - is there any pattern of which windows are open/showing when this happens or is that also random?

**Comment by hammondcl** [comment]
Where can I find the debugger file? Also there does not seem to be a pattern of when it is more likely to freeze during regular use, but it is quite reliable when quitting the program.

**Comment by hammondcl** [comment]
There have been almost no freeze/ crash issues in the latest deployment, so this seems to be closable
