### ISSUE TITLE
Rachel 61 U20 - Odd lack of time bar for handshapes

### ISSUE THREAD

**Issue by geograil** [DCS-LCSR/SignStream3#105]
This is just something I noticed as odd. I wanted to make sure it wasn't some sort of issue. 

In Rachel 61 U20, the #NO and NOT handshapes have neither the time bar with them nor the blue time frame markers at the end of their assigned time points. Handshapes usually do have these, even in the one frame glosses like the one between these two oddballs. I tried deleting and re-adding them in, but it appears the same. The handshapes do HAVE an assigned time span, but it just isn't showing it in the handshape fields. They are sometimes hard to see, so I zoomed in to check but I still don't see them. 

Hopefully it isn't anything to worry about, but I'm not sure. 

How it appears when the gloss is not selected:
![screen shot 2016-10-14 at 1 52 43 pm](https://cloud.githubusercontent.com/assets/19953651/19397625/917b6c50-9216-11e6-94b5-1ce3e597ce53.png)

Appearance when it is selected, showing the assigned time span in the boxes at the top:
![screen shot 2016-10-14 at 2 01 51 pm](https://cloud.githubusercontent.com/assets/19953651/19397669/ce2264ec-9216-11e6-8bad-aa867c81a8a7.png)

**Comment by gregorydimitriadis** [comment]
Hi @geograil - I think you may be referring to just the blue markers demarcating the start/end of the glosses? Those do not indicate the timeframes, only that the gloss is "locked" to its handshapes. Locked means that if you +/- the frame, the handshape line will move as well. Unlocked means that they are independent, and moving +/- on the main gloss line only moves that line and ignores the handshape line.

To lock those glosses you can right-click the gloss and select "Lock Gloss-Phon" (something like this) and then blue markers should return. If this works, then that is as expected and it's not a bug. Please confirm if that is the case.

Thanks!

**Comment by geograil** [comment]
Bad news...

I went in to check them and it ended up dropping one of the NOT handshapes after I adjusted that setting back and forth. These are the steps I took:
- Control double clicked the #NO gloss to see that the Gloss-Phon information was locked; I did the same for NOT and it was also locked. (This screenshot shows the NOT after it dropped one of the handshapes. I didn't have a screenshot before that happened)

![screen shot 2016-10-14 at 2 36 16 pm](https://cloud.githubusercontent.com/assets/19953651/19398824/76e16a10-921c-11e6-88ee-a0d9834e0c95.png)
- I checked the HAVE gloss next to it for comparison. Those were locked as expected.
- I felt I should check if anything changed when I changed that setting to unlocked. I control double clicked NOT and selected the "Unlock Right Gloss-Phon Alignments". No change occurred.
- I decided to change it back to locked since that is the correct setting to have there and because I thought it might fix the original issue. I control double clicked NOT and clicked the "Lock Right Gloss-Phon Alignments" option. 
  It dropped the first/leftmost "10" handshape that was there before (previous as shown in the original comment). The Morph-Phon Info dialog box confirms that the handshape was actually dropped.

![screen shot 2016-10-14 at 2 52 07 pm](https://cloud.githubusercontent.com/assets/19953651/19399117/df11b8dc-921d-11e6-811e-84c6d85f217d.png)

---

Since NOT is a one-handed gloss with the same start and end handshape, I know that it is originally put in with only one handshape indicated. SS3 actually adds the second copy of the given HS to show that the start/end HS are the same, at least in what I've seen with it. 
I'm not sure whether it's dropping the first handshape in the sequence or whether it is reverting to the original handshape input given when the gloss was first inserted. 

I guess this leaves two questions: 
1. How should I proceed with this specific file? Should I add the handshape back in and save it, leave the handshape out and save the file, or should I quit out of SS without saving to see if the original pair of handshapes are there when I reopen it?
2. I was going through Rachel 62 in the meantime to look for 1F drops and I noticed this happening there as well. How do you want to proceed with it?

**Comment by gregorydimitriadis** [comment]
I would first try quitting without saving, and seeing if the same problem can be duplicated the next time you open SS3. 

It's strange the #NO gloss without the blue markers thinks it is locked - perhaps this is actually a new bug.

**Comment by geograil** [comment]
Well, it gets a little more weird. What's also strange is that when I made the original post, the handshapes didn't even have the black line above them to mark the time. It was kind of like they were just sitting there and not even being associated with NOT. Then when I checked the locked/unlocked status to see if you were right, I just noticed that the black lines were there, just without the blue markers. Hm.

Anyway, I quit without saving, and when I reopened it, the file did show both 10 handshapes for the NOT gloss as well as that black line, just no blue markers. 

![screen shot 2016-10-14 at 3 16 49 pm](https://cloud.githubusercontent.com/assets/19953651/19399853/7870d23a-9221-11e6-8472-c52a0ae3aa54.png)

I checked NOT, and it still thinks it's locked. 
![screen shot 2016-10-14 at 3 18 52 pm](https://cloud.githubusercontent.com/assets/19953651/19399874/962394ac-9221-11e6-9be5-52a8b11c9f37.png)

I then unlocked it and nothing changed. I locked it, and it did indeed drop the handshape.
![screen shot 2016-10-14 at 3 20 50 pm](https://cloud.githubusercontent.com/assets/19953651/19400037/4e693a26-9222-11e6-8bc2-28dd69112ff5.png)

However, when I went to see if it would do the same thing with #NO, it unlocked and locked with no issues. The blue markers never came up, but it didn't drop the handshape. This is the Morph-Phon info after I unlocked and relocked it. 
![screen shot 2016-10-14 at 3 21 41 pm](https://cloud.githubusercontent.com/assets/19953651/19400071/745fcd1c-9222-11e6-8bcb-1c5c2319bc74.png)

Interesting observation that may involve the 1F drop bug -- This utterance conveniently has a 1F gloss in it. While that isn't being impacted by the fiddling with the lock/unlock of NOT and #NO, it is showing up differently than HAVE. HAVE shows the blue markers on both of the gloss 1 and 2 fields and on both of the handshape fields. The IX-1p one frame gloss only shows the blue markers on the handshape, but not the gloss field, which also appears to be the case for any one-handed gloss/sign; I'm sure there's a reason that one-handed glosses don't have the markers on the gloss and the HS, but I don't know what that reason is or what it could be. That said, I'm only thinking about them from the perspective of the one-handed signs being dependent on HS just as the two-handed ones are in terms of the ASL. Regardless, If the locked/unlocked issue with the blue markers is causing NOT to drop its first listed handshape, maybe that's involved in what's causing the 1F glosses to drop their handshape. Since they are one frame long, they only have the one HS - so if those are also dropping the first listed handshape assigned to them, that would indeed look like the 1F drops we're seeing.

**Comment by gregorydimitriadis** [comment]
@geograil What are the names of the video files in this collection - Rachel 61? I tried opening it but I didn't have videos of the proper type (I believe) so I couldn't look through the utterances.

Do they have "for-ss3" in the names? If so, I may need those video files in order to open the collection and test this one.

**Comment by gregorydimitriadis** [comment]
Note on bugs #104, #105, #108:

There were some issues in the data saved in the annotation files themselves, so to the best of my ability I have corrected any dropped or missing information, but some of it is lost. For example, for most of the handshape drops, the data is missing and can't be retrieved based solely on the annotation file, so those glosses must be re-created. Once they are re-created, the dropping issue should not reoccur.

**Comment by hammondcl** [comment]
This appears to be resolved. There have not been any new drops reported.
