### ISSUE TITLE
Nonmanual eyebrow menu

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#106]
I noticed today that in Rachel 43, U3, one of the labels on an eyebrow event was dropped. I checked the rest of the file and no others had dropped. When I tried to re-add the label (which is "raised-furrowed"), there were two labels in the double click menu that were labeled "raised-furrowed". I think this may be related to why it dropped and am not sure which of the two identical labels I should use. 

![screen shot 2016-11-02 at 11 25 47 am](https://cloud.githubusercontent.com/assets/15836242/19935213/9a497f7e-a0ef-11e6-82e4-4989cd4d4998.png)

**Comment by gregorydimitriadis** [comment]
Hi Chelsea. This looks to be related to issue #75, which was resolved a few months back. However, I did check on my end as well and I see the missing label, which I would assume is from the same cause. But the new thing here is the duplicate label in the dropdown, which I can also duplicate. So I'll mark this as a bug for now.

**Comment by cneidle** [comment]
I think this goes back to a time when we didn’t have a value for that;
so there was a “new value” created within that file.  Subsequently
that value was added to the general repertoire.

Not sure of the best way to resolve this…

Carol

**Comment by gregorydimitriadis** [comment]
Ah, it appears you're right. If you go to edit the 'eye brows' field, then you see two value options for "raised-furrowed." (not the case for some other collections I checked)

I would say one of the values can simply be deleted from the official collection file. The worst-case effect would be that any instances of that duplicate label in the file will be deleted - but they could all be subsequently re-added with the proper value anyway.

**Comment by gregorydimitriadis** [comment]
So to resolve this bug, when the next package is released, the *second* "raised-furrowed" value should be deleted from the eye brows field in this specific collection (Rachel 43; to my knowledge the same issue is not occurring in any other collection). This will only work when the new package is released because there was a secondary issue in deleting values, which will be resolved at the time of release.

**Comment by hammondcl** [comment]
In Rachel 43, there are still two "raised-furrowed" labels available. All other files appear to only have one "raised-furrowed" option. 
![screen shot 2017-02-27 at 11 39 18 am](https://cloud.githubusercontent.com/assets/15836242/23370056/7212302a-fce1-11e6-9215-58905cd5f26d.png)

**Comment by gregorydimitriadis** [comment]
@hammondcl The second raised-furrowed value can be deleted manually, which should solve this issue for this particular collection.

**Comment by gregorydimitriadis** [comment]
@hammondcl Hi Chelsea - lemme know when this is resolved and can be closed.

**Comment by hammondcl** [comment]
I'm not sure what to do about this because it is only in Rachel 43 and that file has been closed out for upload to the DAI, so we are not supposed to edit it anymore. @cneidle what do you suggest?
