### ISSUE TITLE
Rachel 66- Event chain overlaps

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#108]
Some of the utterances in Rachel 66 are overlapping, which makes it very difficult to work on those utterances. It means that you cannot see where one utterance begins or ends while in the utterance view and that some coding may overlap between two utterances. In other files, the program will not allow you to create utterances that overlap, so it appear that this function is working in other places, but not in Rachel 66.

![screen shot 2016-11-02 at 1 56 25 pm](https://cloud.githubusercontent.com/assets/15836242/19940772/2d1e6b16-a104-11e6-8c92-372d267adb62.png)

Also in this file, I have found an instance of a nonmanual event offset overlapping with a new event (U40, hp: tilt side (-right) and (left)). I have not found any other nonmanual events overlapping in this file, but I also have not checked it in its entirety yet. 

![screen shot 2016-11-02 at 2 00 40 pm](https://cloud.githubusercontent.com/assets/15836242/19940980/cff91700-a104-11e6-826c-8e558c9264a0.png)

**Comment by gregorydimitriadis** [comment]
This is now fixed. But in the files in which this bug has occurred, the times are saved incorrectly, so they must be fixed manually. After that, it should not reoccur.

**Comment by gregorydimitriadis** [comment]
Note on bugs #104, #105, #108:

There were some issues in the data saved in the annotation files themselves, so to the best of my ability I have corrected any dropped or missing information, but some of it is lost. For example, for most of the handshape drops, the data is missing and can't be retrieved based solely on the annotation file, so those glosses must be re-created. Once they are re-created, the dropping issue should not reoccur.

**Comment by hammondcl** [comment]
This appears to be fixed, but because these are kind of freak occurrences, it's difficult to be 100% sure on my end
