### ISSUE TITLE
Enhancement: Utterance Window - resizing issues

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#11]
1. Within the Utterance Window, the lines for gloss1 and gloss2 should always be visible, even in the case of window-resizing or limited screen space

**Comment by gregorydimitriadis** [comment]
This is completed, due to the fact that we can now show/hide individual segments and we can also resize the percentage of the screen devoted to the nonmanual section vs. the manual section. So we can make sure gloss1 and gloss2 are always viewable.

**Comment by blazetravis** [comment]
This enhancement is now in place.
