### ISSUE TITLE
Macro Unit Enhancement Request

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#112]
Currently, when creating a new file, the window looks like this:
![screen shot 2016-11-16 at 11 54 04 am](https://cloud.githubusercontent.com/assets/15836242/20356737/71b23f9c-abf3-11e6-94d4-8c7fa1f0bd35.png)

You must click on the collection line on the left to select it in order to add a macro unit, but this seems unintuitive because the yellow SignStream window where you have to select the collection is behind the active grey window. We would like it so that when you open this window, the collection is automatically selected.

**Comment by gregorydimitriadis** [comment]
Related to #132

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

fixed.
