### ISSUE TITLE
Can't edit glosses with + markers without adding to Sign Bank; won't let me add them to the Sign Bank

### ISSUE THREAD

**Issue by geograil** [DCS-LCSR/SignStream3#114]
File: Rachel 65, U7

I was trying to check/edit the gloss information for BUY+++, but once I open the Morph-Phon Info Box, it won't let me close out of it unless I click the red close button. However, if I've edited something, that won't save it. It won't allow me to put anything with a + marker into the gloss unless one already exists with that exact number of + markers in the Sign Bank. Then when I try to add it, it won't let me do that either because it won't allow the + character. 

Gloss as it appears normally, BUY+++: 
![screen shot 2017-01-27 at 3 18 52 pm](https://cloud.githubusercontent.com/assets/19953651/22386434/0bbd22f2-e4a5-11e6-81f8-0996029506df.png)

When I try to hit Enter after I'm done in the Morph-Phon Info Box:
![screen shot 2017-01-27 at 3 19 15 pm](https://cloud.githubusercontent.com/assets/19953651/22386447/20d02ff4-e4a5-11e6-8493-d77f543657ef.png)

I then search for it in the Sign Bank, and it doesn't show up: 
![screen shot 2017-01-27 at 3 19 31 pm](https://cloud.githubusercontent.com/assets/19953651/22386460/2e92aa04-e4a5-11e6-981a-7443ad191b46.png)

I then looked up BUY without the + marker and got some results: 
![screen shot 2017-01-27 at 3 19 45 pm](https://cloud.githubusercontent.com/assets/19953651/22386472/4190d1c6-e4a5-11e6-9d86-b2feeb184ec3.png)

BUY++ was the closest thing, so I added those labels in:
![screen shot 2017-01-27 at 3 20 05 pm](https://cloud.githubusercontent.com/assets/19953651/22386487/599910e4-e4a5-11e6-8165-c5fcbc0ad3dc.png)

I thought I could just add the third + and be okay, but it gave me the same notification as before that it wasn't in the Sign Bank: 
![screen shot 2017-01-27 at 3 20 25 pm](https://cloud.githubusercontent.com/assets/19953651/22386510/73d62c08-e4a5-11e6-8f68-2b1704449e69.png)

I figured I then had to add it in, so I was going to add it under a Primary Entry of BUY since it's just a repeated variant of that, but it won't let me because it won't let anything with those characters be added: 
![screen shot 2017-01-27 at 3 32 45 pm](https://cloud.githubusercontent.com/assets/19953651/22386617/eed5738c-e4a5-11e6-89d7-18e82cc3d0db.png)

---

Luckily, I don't have to change anything in the Morph-Phon Info for this gloss, but I'm not sure how I would be able to if the need arose.

**Comment by gregorydimitriadis** [comment]
@cneidle Carol - since this may have implications/relations to what we discussed earlier today in our meeting regarding searching the sign bank with queries containing trailing "+' signs - what do you propose should be the solution to this situation? The base issue is that the gloss "BUY+++" was in place before these Sign Bank rules were implemented, otherwise Signstream would not have allowed it to be added in the first place. Most likely we'll come across other instances similar to this in other files also. I could envision a few fixes:

1) Users can be given the ability to add values to the Sign Bank with "+" in them

2) The gloss must be manually deleted and re-created according to the now in-place Sign Bank rules.

**Comment by geograil** [comment]
Hi Greg, 

I'm unsure how this works on the coding side, but as for use and accurate analysis, we need to be able to add "+" signs freely to glosses. The repetition is highly significant in conveying the correct meaning/intensity of an action in ASL, so if I can't mark it, it won't be accurate in terms of the linguistic analysis. 

That said, the repetition of a sign is _often_  a variant of the underlying sign, so if I can add them in to specific glosses when they appear and not necessarily have to add them as variants each time a new number of repeats occurs, then that could work from the perspective of analyzing the sign correctly.

**Comment by geograil** [comment]
Is there something I should/can do with these glosses in the time until Sprint 21 is released? I'm unsure if there is any way I can properly edit and save changes to them or if I should just continue making a list of the ones I need to fix once this change comes through

**Comment by geograil** [comment]
This appears to be resolved
