### ISSUE TITLE
Sprint 20 - Nonmanual double click menu missing

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#116]
In new sprint 20 deployment, nonmanual double click menu is missing. It is accessible when creating a new event, but it is not possible to alter the label of an existing nonmanual event.

**Comment by gregorydimitriadis** [comment]
@hammondcl Hi Chelsea - this issue is related to #110 - the new keyboard shortcuts included in this sprint. The new mechanism to open the nonmanual label menu is to click-and-hold.

**Comment by cneidle** [comment]
Hi,

The keyboard shortcut has changed!  Please read the notes
carefully explaining the new keyboard shortcuts.

Thanks,
 Carol

**Comment by hammondcl** [comment]
Unfortunately, we did not receive notes with this deployment, so we are kind of flying blind. 

As for the new commands, I think click+hold is less intuitive than double click. In my mind, that's opening a menu and typically double-click opens something.

**Comment by hammondcl** [comment]
This is fixed with Sprint 21!
