### ISSUE TITLE
Selecting "Save" in dialogue box does not save work

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#117]
This appears to be an issue across files, not confined to one file. 

After making changes to an utterance and clicking the red "x" to close the program, a dialogue box asking if you want to save appears. Clicking "Save" closes the program. Upon reopening program, changes are not saved. Using the command + s keyboard command does save work. Also, using the "Quit" option from the menu bar does not prompt you to save work. 

Steps to reproduce: 

1) Open any file (Collection --> Open --> CURRENT --> [file]). Used here for an example is Rachel 51. Open any utterance. Used here is utterance 1. 
![screen shot 2017-02-08 at 11 20 56 am](https://cloud.githubusercontent.com/assets/15836242/22746181/fa3a9f6e-edf0-11e6-939c-ff1126662878.png)

2) Change a nonmanual label. Here, eye aperture is changed from -wide to blink.
![screen shot 2017-02-08 at 11 21 46 am](https://cloud.githubusercontent.com/assets/15836242/22746218/124c9a12-edf1-11e6-9bfb-c7f80d614109.png)

3) Click red "x" close button on top left of yellow SignStream window, dialogue box appears. Click "Save". Program closes all windows. "Don't Save" is the default option. 
![screen shot 2017-02-08 at 11 22 02 am](https://cloud.githubusercontent.com/assets/15836242/22746266/30e39250-edf1-11e6-98a3-744648edf1dd.png)

4) Reopen program, file, and utterance. Changes are not saved. 
![screen shot 2017-02-08 at 11 22 45 am](https://cloud.githubusercontent.com/assets/15836242/22746291/47c8085c-edf1-11e6-95b6-918c06b327aa.png)

**Comment by gregorydimitriadis** [comment]
Clicking the red 'x' was indeed a bug - saving improperly, which has now been fixed.

The option to save on quitting from the application menu (or from force quit: cmd-Q) was never actually implemented - that will be added at a later date.

**Comment by hammondcl** [comment]
The application now saves correctly when clicking the red 'x', but obviously there is still no prompt to save when quitting out of the program.

**Comment by gregorydimitriadis** [comment]
Created a new issue #122 to track the application quit option to save, and closing this one.
