### ISSUE TITLE
Event Overlaps

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#118]
Some nonmanual events are overlapping in this newest deployment. I have noticed it in Rachel 43, Rachel 45, and Rachel 51 so far. I think it is probably best to manually fix these to ensure accuracy, but let me know if that's not the case. It also exists in a variety of nm fields, so it's not an issue with just one field. I cannot seem to make events overlap myself, but I know they did not previously overlap. 

![screen shot 2017-02-13 at 11 20 01 am](https://cloud.githubusercontent.com/assets/15836242/22891949/ef7ec02c-f1de-11e6-91e3-c88aa80472fd.png)

**Comment by hammondcl** [comment]
Update: 

- None found in Rachel 43 (I think there may only have been one and I fixed it, thinking it was just an oddball). 

- The ones I've found so far are Rachel 45 (U: 2, 4, 5, 6, 7, 11, 13), Rachel 50 (U: 12, 19, 22), Rachel 51 (U: 13), Rachel 52 (U: 9, 11, 19, 20), Rachel 53 (U: 11), Rachel 55 (U: 15, 17).

- Something a little strange is that they are almost exclusively related to the eye (i.e. eye gaze, eyebrows, eye apert). There are a couple that are topic/focus or something else, but almost all are eye.

**Comment by gregorydimitriadis** [comment]
Chelsea - yes, feel free to manually edit the ones you come across. I'll simultaneously take a look at the code to look at what's causing it.

**Comment by gregorydimitriadis** [comment]
@hammondcl Have all of the items you mentioned above been fixed already in the canonical files (the ones in dropbox) or are there any left available to view?

**Comment by hammondcl** [comment]
There are still some unedited ones in Cory 107: utterances 4 (eyebrows), 19 (eyebrows), 36 (hm: jut, eye gaze, eye aperture-- all offsets overlapping events)

**Comment by gregorydimitriadis** [comment]
@hammondcl I see the issue here. It is related in the same way to #123 with legacy timeframe calculations versus the new way. I imagine that for all such collections, when it tries to render the screen with a legacy timeframe, it displays as overlapping with a side-by-side one. As with that one, the best solution going forward with these mixed collections will be to use the "Set" button mechanisms to fix them as they appear.
