### ISSUE TITLE
New sprints do not save local annotators

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#120]
After deploying a new sprint, all newer local annotators are not listed and must be manually re-added. The annotators that remain are: Indya, Isabel, Rebecca, Betsy, and Reema, as well as the global annotators, Carol, Jess, and Ben. Any annotators added to the previous sprint do not carry over into a new sprint. I'm not sure if this is changeable and it does not really cause much of an issue for us, but I think it could cause issues in future use of the program. I also wonder if it impacts the saved data, for example, if I do something in Sprint 20 and my annotator label is on it, does it still have my label on it in Sprint 21 even though Sprint 21 does not have my label until I manually re-add it? 

In this screenshot, I had already added myself again
![screen shot 2017-02-15 at 11 48 32 am](https://cloud.githubusercontent.com/assets/15836242/22984855/b2f2f7f8-f374-11e6-9918-8d5c257c3306.png)

**Comment by gregorydimitriadis** [comment]
@hammondcl @cneidle Hi Chelsea - for now the annotators and participants are both tracked via .xml files, found under /newXMLFiles/ in each package I release. The copies that get sent out in the package are base and contain only the names you mention there. The best and most immediate solution here might be to copy the old localAnnotators.xml file from the old package and paste it into (and over) the same file in the new package when it gets released. This way, anything that gets added can be carried over between versions.

Note: this also applies for anything locally added to the sign bank. (One caveat is that with sign bank files, don't go back to any file before the current version, as the format of some of the data has changed there and any older versions of sign bank files would not work going forward).

**Comment by gregorydimitriadis** [comment]
Note: This may be part of a broader fix in terms of how upgrading Signstream to a new version will work in the future. If it is done "in-app" the upgrade of the software can occur "around" the xml files, so the user wouldn't have to worry about copy/pasting from the old to the new pkg. (as per recent meeting with Carol, 2017-08-16)

Making this into an enhancement.

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

fixed.
