### ISSUE TITLE
"Event Chain Overlap" warning even when events not overlapping

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#123]
This intermittent bug has existed since before I started working here, but I am not sure that it's ever been reported for nonmanuals. 

When extending an event or on/offset, sometimes a warning box comes up telling you "The events chain cannot overlap with another events chain..." As you can see in the screenshot, the onset that I was adjusting would not have overlapped the "hp:tilt side right" event, merely abutted it. The workaround for this issue is as follows: 
1. Select the event (in this case, "hp:tilt side right")
2. Align the green line with the problematic boundary of that event (one frame left of where it is in this screenshot)
3. Click the right "Set" button. This changes the numbers in the righthand window by the "Set" buttons 
![screen shot 2017-02-21 at 11 48 24 am](https://cloud.githubusercontent.com/assets/15836242/23174883/c30050c6-f82b-11e6-938e-6096aa841be9.png)

4. Select the onset, leaving the green line where it is
5. Click the left "Set" button. 

Because this workaround is always successful, I think the problem is related to the initial event, not the onset of the second event. It also can happen with events if they are supposed to abut, so it's not restricted to on/offsets and can happen either moving left or right in the utterance. It is not specific to any one file. 

![screen shot 2017-02-21 at 11 31 56 am](https://cloud.githubusercontent.com/assets/15836242/23174596/e777fe50-f82a-11e6-8d87-9ded8a9d1043.png)

**Comment by gregorydimitriadis** [comment]
@hammondcl Your thinking in the last paragraph is correct. Events now are saved using timeframes according to how long the video frames are. This was not always the case, so for events saved years ago they may not be matching the current standard. When you try to go back/forward on certain frames, it checks against the current video frame standard, and so there is the possibility of a mismatch between "legacy" and "new" events. The way you have been getting around it is correct and in fact the only way I can imagine to resolve it going forward where collections still have both types of events.

Let me know if I can close this issue or if there is anything else related to it.

**Comment by hammondcl** [comment]
Okay, if that's the best fix, then we can close this!
