### ISSUE TITLE
"add new value" option in non-manual double click menu does not appear

### ISSUE THREAD

**Issue by aimeeaylward** [DCS-LCSR/SignStream3#124]
When I was working with the Rachel 56 file, I tried to add a new value name in the mouth field and the dialogue box did not appear. I double clicked on the event and clicked "add new value" and the box flickered but never fully appeared. I checked and it did not open behind any windows. I also tried this in other fields and the same issue occurred.

**Comment by hammondcl** [comment]
At this time, this bug is significantly interfering with our work as it is preventing us from completing several files. Is there a timeline for when we might be able to have this resolved? As of now, there is a push for us to have completed files and this bug is preventing us from completing four.

**Comment by gregorydimitriadis** [comment]
Hi there - I'll add this issue to my priority list, for which I hope to release fixes for within about a week or so.

As for the very short term - can a workaround for this be to go in to edit the field itself, then add the new value from that screen? Then the new value should show up when a specific event is double-clicked.

**Comment by hammondcl** [comment]
In the interim, yes that works

**Comment by hammondcl** [comment]
Actually, should I be doing that or is it going to create the same issues as in Rachel 43 with the raised-furrowed eyebrow event where there are two labels? 

If that's the case, then I think the label "left tense" should be added as a global label because it comes up quite a bit for Rachel. (The reason we found this bug and it continues to give us problems is because we need the label "left tense" for Rachel, so that's why that label is my focus here)

**Comment by gregorydimitriadis** [comment]
@hammondcl The list of visible fields/values now currently in use should be complete, so anything which is a current value for a nonmanual field should be assumed to be correct, and any additions (user-added) on top will be fully custom and okay. I don't believe we will encounter another situation where a custom field value is added which has the same name as an already existing value, and there are mechanisms in the application to prevent same-named values also.

**Comment by hammondcl** [comment]
So I should just manually add it to each file?

**Comment by gregorydimitriadis** [comment]
Yes, since each collection keeps track of its own local field values individually.

**Comment by hammondcl** [comment]
The new label window still does not appear in the new version

**Comment by hammondcl** [comment]
This is resolved in the new version!
