### ISSUE TITLE
Adding annotators not working

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#127]
In the new release of SignStream, the program is not allowing me to add annotators. I open a file and am prompted to input an annotator as usual, but there are none available from the drop-down: 
 
![screen shot 2017-04-12 at 11 33 04 am](https://cloud.githubusercontent.com/assets/15836242/24966185/42ea890e-1f74-11e7-8b3c-aedb7676882d.png)

I then clicked "Add Annotator" and selected my name from the list

![screen shot 2017-04-12 at 11 34 26 am](https://cloud.githubusercontent.com/assets/15836242/24966231/5c00e492-1f74-11e7-9493-d9352d422f32.png)

I clicked "Add Selection" and was returned to the same blank menu as before without an annotator

![screen shot 2017-04-12 at 11 34 50 am](https://cloud.githubusercontent.com/assets/15836242/24966269/7702042e-1f74-11e7-8203-78f5dea34e01.png)

**Comment by hammondcl** [comment]
(This was apparently not in the new version, so it can probably be disregarded)

**Comment by gregorydimitriadis** [comment]
Worth testing at least once more though, as it's one I had not seen previously.

**Comment by hammondcl** [comment]
It's yet to happen now with the new version, but I'll keep my eye on it!

**Comment by aimeeaylward** [comment]
Another thing happening with the Annotator Selection window is a slight issue with where the window opens. When you click "New", the "Create or Edit Annotator" window opens up behind the window already open, the "Annotator Selection" window; this is showed in the screenshot below. 
![screen shot 2017-06-07 at 12 11 53 pm](https://user-images.githubusercontent.com/25349160/26889026-bf9ab7d0-4b7a-11e7-9f76-f6eef645764b.png)
Inputting a new annotator and saving the selected annotator works correctly, but this was just something that we noted that doesn't look right.

**Comment by gregorydimitriadis** [comment]
Windows appearing in odd orders is from the README.txt issue_2 from SignStream release pkg 3.0.8
