### ISSUE TITLE
Creating text events squishes multiple events together

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#129]
The use case:
Create some text on the gloss1 line, two words with a space between. Set the time for the first word, and make its end time past the second. It'll act strange, reverse the strings possibly, and make the second un-clickable. 

Squishing the residual text together (as long as they all remain clickable) is a workable solution if possible - or some other way to deal with it.

**Comment by cneidle** [comment]
seems fixed :-)  thanks.
