### ISSUE TITLE
Text events disappear when new segment tier created - est. 5 hours

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#130]
Use case:
Either on clicking new segment tier, or after it, the text events in a ST disappear.

**Comment by gregorydimitriadis** [comment]
@cneidle @bugspotter33 has this ever been observed? I'm not entirely certain what the use case is that I reported above

**Comment by cneidle** [comment]
don't think so.

**Comment by cneidle** [comment]
lowering priority

**Comment by gregorydimitriadis** [comment]
Assuming 'low priority' for this one - based on the ones its grouped with in the list.

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

cann't reproduce...assume fixed.
