### ISSUE TITLE
New collections - movies don't get saved

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#132]
On an initial creation of a new collection, there are issues with the movies saving to file.

**Comment by cneidle** [comment]
Would it be possible (easy?) to have the movie windows open initially in front, rather than behind, the non-video window?   It is easy to think that the video windows haven't opened when they are there, but invisible,  upon opening the collection.  Thanks if that can be changed.

**Comment by cneidle** [comment]
If you open a new collection, select video files, annotator, and participant, save, and exit the program (before doing any other editing), the program will be saved, but when it is reopened, there are no videos, and there is no macro-unit (although the selections in the macro unit had been previously confirmed).  When the collection opens, this is what I see:
![screen shot 2017-06-07 at 1 26 27 pm](https://user-images.githubusercontent.com/13629122/26892024-fc331764-4b84-11e7-825e-40d8f21e88a5.png)

When I go to attempt to edit the macro-unit, from the menu, I get the same error message.  

I think this is probably what I had previously reported, in saying that the video files were not saved.   

If the file is not going to be openable, because nothing has yet been annotated, it might be good to have an alert to the user at the time the user attempts to save the file, rather than letting the user save the file thinking that this work has been saved...

**Comment by gregorydimitriadis** [comment]
1. I can make the videos appear in front by default. That should be easily done.

2. I still cannot reproduce the issue with saving/reopening - I may need to see the steps being done in order to understand this one better.

**Comment by cneidle** [comment]
I am not able to reproduce the problem with selecting videos, saving, and then not having them be present upon reopening the collection, with the current (rc2) version.  However, there is an error message if the user attempts to try to save the collection before confirming the selections in the macro unit information window.  This error message is not hugely informative, either.  
<img width="386" alt="screen shot 2017-08-04 at 10 07 36 pm" src="https://user-images.githubusercontent.com/13629122/28992091-7548a222-7961-11e7-8d11-49a8b3eab704.png">

Ideally, saving should be disallowed until there is enough data to save...   

In any case, the statement of "known issues" is inaccurate/ unhelpful as it stands:

"1) Videos which are not selected in the Macro Unit window are not saved after leaving screen via the Enter button."  I don't know what that is supposed to mean even.

**Comment by gregorydimitriadis** [comment]
I've edited the README for now.

The issue with the message still remains.

**Comment by gregorydimitriadis** [comment]
README will now say:

"1) Attempting to save the collection while still on the Macro Unit window will result in an error. "

**Comment by gregorydimitriadis** [comment]
@cneidle - Can this one be closed?

**Comment by cneidle** [comment]
No - we have an infinite loop.

I start a new collection, add a movie file, participant, and annotator, and save those selections.
Then I do a "save as" for the collection as a whole.

This is what I get, in chronological order:

![screen shot 2017-10-12 at 5 01 26 pm](https://user-images.githubusercontent.com/13629122/31519096-4ce805f4-af6f-11e7-8796-21fa99d35f8c.png)

![screen shot 2017-10-12 at 5 01 47 pm](https://user-images.githubusercontent.com/13629122/31519103-50822e24-af6f-11e7-8e56-5ed5823797d8.png)


![screen shot 2017-10-12 at 5 01 55 pm](https://user-images.githubusercontent.com/13629122/31519116-5ae09cca-af6f-11e7-9f71-624e8921a93d.png)

![screen shot 2017-10-12 at 5 02 02 pm](https://user-images.githubusercontent.com/13629122/31519125-625a5b4e-af6f-11e7-8fd7-c0e50cd3235e.png)

![screen shot 2017-10-12 at 5 02 09 pm](https://user-images.githubusercontent.com/13629122/31519135-6e9b717c-af6f-11e7-8011-96b3e8e27f6b.png)

**Comment by cneidle** [comment]
This latest infinite loop problem is not limited to this context.  I was editing another file; did save-as, then attempted to close the window and ended up with this same problem.  

![screen shot 2017-10-13 at 9 55 06 am](https://user-images.githubusercontent.com/13629122/31549610-aeb38794-affc-11e7-89c0-7e4bab3a5c39.png)

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Still need to put video and audio windows in front.

**Comment by gregorydimitriadis** [comment]
@gregorydimitriadis seems fixed in working version - verify for next release

**Comment by douglas-motto-at-rutgers** [comment]
Not fixed as of 2021_10_11_1216 for new collections.  Opening old collections seems to work, but not when creating new collections.

**Comment by gregorydimitriadis** [comment]
@douglas-motto-at-rutgers cannot reproduce - please share steps

**Comment by gregorydimitriadis** [comment]
Remaining issue being the windows in front or behind - spun off to new issue. Infinite loop on saving an other errors should be resolved.
