### ISSUE TITLE
Closing the "new segment tier" dialog doesn't work

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#134]
Click the red 'x' to get out of the "new segment tier" dialog from the utterance view - does not work.

**Comment by aimeeaylward** [comment]
This is still occurring in the latest version.

**Comment by aimeeaylward** [comment]
The "new segment tier" dialog box would not close, and because I couldn't exit out of the box I was unable to do anything else. I tried to quit the program but it wouldn't quit.

**Comment by gregorydimitriadis** [comment]
Hi @aimeeaylward - just to confirm which dialog is being referred to: are you referring to the dialog which comes up when inside the utterance view, and the "New" button is clicked from the bottom left corner of the screen? Or the dialog which is accessed from the top menubar of the application and going to (Macro Unit -> Segment Tier -> New Segment Tier) ?

**Comment by aimeeaylward** [comment]
I was referring to the dialog from the top menu when this occurred. I just attempted this from the "New" button in the bottom left corner and the box exited using the red X with no problem.

**Comment by gregorydimitriadis** [comment]
I believe this issue report was only for the bottom left corner dialog for "new segment tier." The ones from the menubar are a little more difficult to allow to be closed as they have dependent operations which follow them and might be disturbed. I'll ask if @cneidle wants that change as well, which may just involve some more detailed changes.
