### ISSUE TITLE
Extending Onsets in New Version of SignStream 

### ISSUE THREAD

**Issue by aimeeaylward** [DCS-LCSR/SignStream3#137]
I am working in Cory 113 file and came across a bug when adding or extending onsets on events. This first came up when I added a body lean field, drew an event, and added an onset. All of this worked fine, but when I moved the green bar and clicked the set button to change the beginning of the onset, it didn't change. I then tried a few different things: using the - button, extending an already existing onset in the file using both set and - buttons, and trying all of this in a different utterance, but all of these would not change the start point of the onset. I also tried this in Rachel 55 to be sure, and tried again once quitting and reopening SignStream, and the same issue still occurred. Offsets work fine using both the set and the + buttons- it is only occurring for onsets.

**Comment by gregorydimitriadis** [comment]
Reproduced this bug. This actually also occurs for any event in the nonmanual section: onsets, regular events, and offsets. If you try to edit the start time of any of those types of events by any method (+/- or using the set button) you will encounter this error.

**Comment by aimeeaylward** [comment]
Since this bug is hindering the process of editing files, it is causing problems for a big part of the work I've been doing and slowing things down, so when possible would be most important to fix.

**Comment by gregorydimitriadis** [comment]
@aimeeaylward Emailed a new build to address this issue.

**Comment by aimeeaylward** [comment]
Hello,

It appears this fix worked! Thank you for your help.

Aimee Aylward

On Mon, Jun 12, 2017 at 12:48 PM, Greg Dimitriadis <notifications@github.com
