### ISSUE TITLE
quitting SignStream - user not asked to save changes

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#138]
If one closes a collection without saving changes, there is, appropriately, a dialog box that appears asking if changes should be saved.  However, if one instead chooses to quit the program, this doesn't happen, although it should..  The collection is presumably just closed without changes being saved.

**Comment by cneidle** [comment]
sorry - i see this was already reported as #122.  I hadn't found it before submitting this.

**Comment by gregorydimitriadis** [comment]
Closing this issue in favor of #122
