### ISSUE TITLE
Resize database view of segment tiers/temporal partitions

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#139]
Low priority:  Since the pane that has the information about temporal partitions and segment tiers is not resizable (which would be the ideal), it would be great to make it at least a little bit wider, since it is very difficult to see the names.  

This is not at all critical, however; low priority relative to other issues.

![screen shot 2017-06-07 at 12 44 13 pm](https://user-images.githubusercontent.com/13629122/26890339-3594cb48-4b7f-11e7-95f0-7b2c73bd2833.png)

**Comment by gregorydimitriadis** [comment]
See also #136 if possible to combine issues or do in the same fashion.

**Comment by gregorydimitriadis** [comment]
Undecided as to whether it's best to toggle or implement a drag-and-drop divider.

**Comment by gregorydimitriadis** [comment]
This bug will now encompass both the Utterance View as well as the Database View, in terms of layout of the panels and windows in terms of space.

**Comment by cneidle** [comment]
I would be MUCH better to have a draggable divider.

thanks,
 Carol

**Comment by cneidle** [comment]
Beautiful.  Thank you!
