### ISSUE TITLE
Participant Selection process - not working properly

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#141]
When I attempt to add a new Participant, and I enter information about the participant, I cannot "cancel" or close the window without deleting all of the information I may have entered.  If I do cancel (i.e., I have changed nothing), I get a warning to save information or it will be discarded (inappropriate).  If I choose Discard and return to the Macro Unit Information window and choose Cancel, I again get a warning to save.  

OK, so I choose Discard.  I return to the Participant Selection window, to delete the silly new test participant I had created, and I am not allowed to remove it (or any other participant); the "Remove" button is grayed out.  Perhaps that is intentional?? 

If I add a new participant, choose Save when warned that information will otherwise be deleted.  Then I return to the main window (see illustration) and choose "Add" in the 3rd participant slot, I again get a warning about saving or discarding, which really makes no sense in this context.

![screen shot 2017-06-12 at 3 59 57 pm](https://user-images.githubusercontent.com/13629122/27052628-4734dafc-4f88-11e7-9b26-e61d8ff03112.png)
 

I am able to cancel addition of a new annotator even if I have typed information in those fields, fwiw.

Apologies if this has already been reported; I couldn't find it among the issues.

**Comment by gregorydimitriadis** [comment]
Carol,


As far as the remove button being grayed out...  the logic in place for this currently checks whether the participant selected was just created, and if so then it grays out the remove button. I'm not sure of the motivation for this, but perhaps there was a reason for it? If not, then that check can be removed and the remove button should always be click-able. Would that be more appropriate?


-Greg

________________________________

**Comment by gregorydimitriadis** [comment]
@cneidle For this one, it should be mostly fixed. The save/discard dialog should not appear if no changes were made. The remove button being grayed out remains intentionally for newly created participants, since they are the only ones which haven't been saved to the xml file yet.

**Comment by douglas-motto-at-rutgers** [comment]
Participant and Annotator selection works, but needs to be improved greatly.

Leaving open for now.

**Comment by gregorydimitriadis** [comment]
This issue fixed. Further discussion on participants/annotators here: #530
