### ISSUE TITLE
Problem when gloss labels include "

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#142]
We do have some gloss elements that include quotation marks, such as the gloss:  "WHAT"  or classifiers or gestures (  BCL"running" or  ICL:S"holding carrier" or   5"leave it at that" or "um").

However, after typing a gloss label that includes ", upon hitting Return, the entire text disappears; see example below.

before and after hitting Return
![screen shot 2017-06-13 at 3 29 09 pm](https://user-images.githubusercontent.com/13629122/27100916-baa22f10-504d-11e7-9b82-9b1705c6c7cd.png)
![screen shot 2017-06-13 at 3 29 20 pm](https://user-images.githubusercontent.com/13629122/27100918-c02cd200-504d-11e7-830e-d209a8a1f0b2.png)

**Comment by gregorydimitriadis** [comment]
@cneidle I believe this has been fixed. Can you confirm?

**Comment by cneidle** [comment]
yes - thanks
