### ISSUE TITLE
unlocking and then relocking left-right hand alignments results in messing up the handshapes on one of the hands

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#143]
If I unlock the left-right handshapes, and then relock them, the handshape display is adversely affected.  Depending on whether I invoke this command from the dominant hand (as shown in picture 2 below), or the non-dominant hand (as shown in picture 3 below), the handshapes are affected on for the opposite hand.

![screen shot 2017-06-13 at 3 58 31 pm](https://user-images.githubusercontent.com/13629122/27101822-334f44ea-5051-11e7-9e2f-e0971c5567bf.png)
![screen shot 2017-06-13 at 3 54 18 pm](https://user-images.githubusercontent.com/13629122/27101835-3efd46ac-5051-11e7-9a2c-cacdf970c519.png)
![screen shot 2017-06-13 at 3 56 39 pm](https://user-images.githubusercontent.com/13629122/27101841-4183e41c-5051-11e7-88c8-0f1847f409f0.png)

**Comment by cneidle** [comment]
This same bug affects the unlocking and relocating of the left or right  gloss/phon alignments as well.

**Comment by gregorydimitriadis** [comment]
@cneidle I believe this has been fixed. Can you confirm?

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

fixed.
