### ISSUE TITLE
inconsistent alignment with holds

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#144]
Hi,

I have not unlocked anything.  I created a gloss, added an initial and final hold, then inserted the handshape information.  The alignment of the handshapes with respect to the holds is not consistent on the left and right hand.

![screen shot 2017-06-13 at 5 07 33 pm](https://user-images.githubusercontent.com/13629122/27104666-fcd4f90a-505a-11e7-909a-3f0b62128d31.png)

Note that if I adjust the start point of the initial hold, things regularize:

![screen shot 2017-06-13 at 5 10 29 pm](https://user-images.githubusercontent.com/13629122/27104804-4f5904b4-505b-11e7-8e11-a72b5f8f4d55.png)

**Comment by gregorydimitriadis** [comment]
@cneidle I believe this has been fixed. Can you confirm?

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

fixed.
