### ISSUE TITLE
Question: about local vs. global annotators and participants for the initial release

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#146]
For the version to be publicly released (i.e., to be used outside of our group), I am assuming that it will not be populated with any global annotators or participants.  So I assume that all participants and annotators will be local, and thus this distinction does not need to be addressed explicitly in the documentation.  Please let me know if this assumption is incorrect.  Thanks.

**Comment by gregorydimitriadis** [comment]
@cneidle 

As of now in all releases of the Signstream application, there are people in the global annotators file, so those are currently viewable by anyone who downloads the app. If we want to not show those, then we could remove those people from the file manually before the public release. If this were to occur, then there is no way for a regular user of the Signstream application to add a global annotator, so it would be a moot point as far as documentation is concerned - indeed. Would that be the desired course of action?
