### ISSUE TITLE
Small typos - in error message

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#148]
When the user chooses "Prev Utterance" from U1 (i.e., when there is no previous utterance), there are two spelling errors:

![screen shot 2017-06-14 at 3 54 51 pm](https://user-images.githubusercontent.com/13629122/27151905-0dd8a1f6-511a-11e7-95c1-fe43e4e5d393.png)

"Resouce"  should be "Resource"   
and
"utternance"  should be "utterance"

**Comment by gregorydimitriadis** [comment]
This has been fixed.
