### ISSUE TITLE
SignBank:  Problem with compounds

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#149]
We have a problem with the inconsistent representation of compounds between the SignBank and the SignStream application.  Although a compound is a single word (like 'blackbird' in English), the way that these are annotated in SignStream is that the separate parts are first coded, and then the menu item is invoked from the contextual menu, so that one gloss will be linked to an adjacent gloss, so that it will be interpreted as a compound.

What that means, it seems to me, is one of two things: (1) that the SignBank options that should be available to be selected and directly entered by the SignStream user should only include the component parts of any compound (ideally the compound forms would be visible, but not directly enterable); or (2) that the compound, when entered, should be entered as multiple connected items, thereby resulting in the appropriate SignStream representation for the connected parts (although this would require the user to set the start and endpoints of those parts).  

Currently, if I want to enter a compound, like (1h)HAPPY++NEW+YEAR, I can locate it easily in the SignBank, but it gets added in a form that is not how compounds should be represented in SignStream 

![screen shot 2017-06-15 at 5 12 45 pm](https://user-images.githubusercontent.com/13629122/27202042-fd0b0dee-51ed-11e7-96dc-30494f052810.png)

Compare with:

![screen shot 2017-06-15 at 5 14 19 pm](https://user-images.githubusercontent.com/13629122/27202071-22510e00-51ee-11e7-8c10-14c6925fbfe2.png)

Perhaps this is something that should be discussed with Augustine ??

I'm also not sure that we are getting the right behaviors in entering items with varying numbers of +'s (which don't represent distinct dictionary forms).

**Comment by cneidle** [comment]
I believe this will be mostly resolved with the next version of the Sign Bank that Augustine will provide, which will include only the parts of compounds, e.g., PART1*, *PART2.  However, these will be listed with the containing compound: 

    PART1*  (PART1+PART2)

and it would be good to add view options for the video of the individual sign and the containing compound.

The * should be ignored (like +'s), in terms of categorizing the sign; also, when the user sends the information to the Morph-Phon window, no "*" should be transferred.

**Comment by gregorydimitriadis** [comment]
This will mostly be subsumed by changes in #168, but as per meeting with Carol this morning this is my takeaway on how SignStream should treat compounds:

For semantics I will consider "ACTION" to be called the base form of a constituent part of a compound "ACTION*"

* The sign bank file which SignStream receives will not contain full-formed compounds; it will only receive the constituent parts of a compound word, as in Carol's last post.
* When either a base form or constituent part of a word is searched for in the sign bank, both types will appear in the results
* When a gloss of a constituent form (with a * at the end or beginning) is selected from the results and added back to the MorphPhon window, it will do so in the base form.
* Signs of a constituent form cannot be added to the local sign bank (the app will prevent a user from doing so)
  * Implying that if they want to build a compound within the app they should follow the steps Carol laid out above and make each gloss individually and then link them.

**Comment by cneidle** [comment]
Thanks.

For clarification:

> On Oct 6, 2017, at 2:51 PM, Greg Dimitriadis <notifications@github.com> wrote:
> 
> This will mostly be subsumed by changes in #168 <https://github.com/DCS-LCSR/SignStream3/issues/168>, but as per meeting with Carol this morning this is my takeaway on how SignStream should treat compounds:
> 
> For semantics I will consider "ACTION" to be called the base form of a constituent part of a compound "ACTION*"
> 
> 

If we consider a compound, such as  ACT+AGENT, it has two constituent parts:  ACT* and *AGENT,
the base forms of which are, respectively, ACT and AGENT.

> The sign bank file which SignStream receives will not contain full-formed compounds; it will only receive the constituent parts of a compound word, as in Carol's last post.
The sign bank entries for the above would be

ACT
   ACT*  (ACT+AGENT)

and

AGENT
   *AGENT (ACT+AGENT)


Each entry will be listed with the compound of which it is a constituent in parentheses,
and the user will be able to play the video of that compound, as we discussed,
but only the base form of the given compound constituent would be passed
back to the Morph-phon window.

> When either a base form or constituent part of a word is searched for in the sign bank, both types will appear in the results
Searching for ACT should display all occurrences of  ACT, *ACT,  and ACT* (and variants of those with different numbers of plus signs).

> When a gloss of a constituent form (with a * at the end or beginning) is selected from the results and added back to the MorphPhon window, it will do so in the base form.
yes
> Signs of a constituent form cannot be added to the local sign bank (the app will prevent a user from doing so)
		If you mean that a compound (i.e., a sign containing more than one base form) cannot be added directly to the local sign bank, that makes sense.
		There would be no way to do that, since there can be only one base form displayed at a time in the Morph-phon window from which “add to Sign Bank” is an option.
> Implying that if they want to build a compound within the app they should follow the steps Carol laid out above and make each gloss individually and then link them.
yes

Thanks,
 Carol

**Comment by cneidle** [comment]
Presumably this will need to be tested with the newest Sign Bank.  Currently, AGENT shows up without any indication of the compound that contains is (in parentheses).

**Comment by cneidle** [comment]
fixed?

**Comment by gregorydimitriadis** [comment]
@cneidle Currently SignStream does not allow one to enter a compound found from searching the sign bank. Is the desired behavior that, or is it this from above?

> but only the base form of the given compound constituent would be passed
back to the Morph-phon window.

**Comment by cneidle** [comment]
This was resolved a long time ago.  The current behavior is correct!   Compounds should not be showing up in the list of things from the Sign Bank that can be inserted directly.  The component parts of existing compounds should be available for insertion.  Once the parts have been inserted, they can be linked into a compound in the usual way.  Please let me know if anything about this is unclear. Thanks.

**Comment by gregorydimitriadis** [comment]
Indeed, this is the case currently. So I believe this is fixed, if not in the current release then in the next release.
