### ISSUE TITLE
display issue -- with handshape Palettes

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#150]
Expanding the triangles for handshape options works perfectly.

"Expand all" shows the expected handshapes, but the visual
representation of the triangles fails to indicate that the expansion
has occurred.  The same problem occurs with "Collapse all."

Manually expanding one:

![screen shot 2017-06-16 at 4 40 46 pm](https://user-images.githubusercontent.com/13629122/27244015-aef3a68c-52b2-11e7-8cca-b6c1817dc9fc.png)

Choosing Expand All:

![screen shot 2017-06-16 at 4 40 57 pm](https://user-images.githubusercontent.com/13629122/27244026-b2c049a0-52b2-11e7-99c8-9320ba801705.png)

Furthermore the state of these triangles (having gotten out of sync
with what is actually being displayed) perseverates even after the
Palette is closed.  When it is reopened (within the same utterance)
the triangles remain  misleading,  e.g.

![screen shot 2017-06-16 at 4 39 11 pm](https://user-images.githubusercontent.com/13629122/27243960-60ee063a-52b2-11e7-86c1-9a62c650b739.png)

Closing the whole utterance seems to refresh to the default state of
the palette, though.

**Comment by gregorydimitriadis** [comment]
@cneidle I believe this has been fixed. Can you confirm?

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Appears fixed.
