### ISSUE TITLE
Alignment of English translation field is off for U1 / color [w/ 237 - est. 4 hour]

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#151]
It looks like the alignment of the English translation is off for the first utterance (at least in file 55).  Will check other files later.  It is aligned with the start of the entire video file, rather than the start of the video for U1.

<img width="484" alt="screen shot 2017-06-20 at 9 37 29 am" src="https://user-images.githubusercontent.com/13629122/27336054-6f4cf5fa-559c-11e7-9cd1-311021446153.png">

<img width="564" alt="screen shot 2017-06-20 at 9 37 35 am" src="https://user-images.githubusercontent.com/13629122/27336058-7133d276-559c-11e7-9709-fe507ddf6c16.png">

Also, at least in this file, the English translation sometimes appears in blue, sometimes in black.  Not sure why this is.  Presumably the color, whatever it is, should be constant.  In this file 11/26 utterances have the translations appearing in blue.

**Comment by cneidle** [comment]
I have been working with that same file (conducted a search and then closed the search window), and now that translation field in U1 has completely disappeared... 

<img width="678" alt="screen shot 2017-06-20 at 10 35 40 am" src="https://user-images.githubusercontent.com/13629122/27338903-5a5321e4-55a4-11e7-89fa-736c60145832.png">

**Comment by gregorydimitriadis** [comment]
Possibly related to #237

**Comment by gregorydimitriadis** [comment]
@cneidle May I get the 55 collection? Thanks.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_12_1056_cbb91a73

Translations lines have been improved.
Translations tied to Utterance starts.  Will move with change in Utterance start.  Will be removed if Utterance is removed.

Closing.
