### ISSUE TITLE
Minor: Closing the window of a collection should not cause the program to Quit

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#152]
Hi - Not critical, obviously, but the expectation when one closes a file is that the application remains open so that another file could, in principle, be opened.  Closing the window of a collection results in the program quitting entirely.  For what it's worth.

**Comment by gregorydimitriadis** [comment]
This is also issue_9 from the README.txt as of SignStream release pkg 3.0.8

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

fixed...an active collection may be closed and new or existings ones opened.
