### ISSUE TITLE
Color selection very flaky - mostly doesn't work - est. 5 hours

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#153]
I have succeeded very occasionally in getting the field color to change, but mostly it doesn't change.  E.g., I set the "eye aperture" color to blue.  Nothing happens.  I then also set the Face color to red.  The the label "eye aperture" appears in red and NOW the "eye aperture" lines do appear in the color I had set previously...   There seems to be a big random factor in what is happening, however.

I tried to set the color of of hp: tilt fr/bk to purple.  Nothing happened.  I scrolled forward and back, thinking that it might be a screen redrawing problem.   But instead this is what I see, with the field borders being extended beyond the utterance boundaries.

<img width="1116" alt="screen shot 2017-06-22 at 12 07 19 am" src="https://user-images.githubusercontent.com/13629122/27416997-f0e097f0-56de-11e7-9428-fc7a4c737ade.png">

**Comment by gregorydimitriadis** [comment]
This is also issue_5 from the README.txt as of SignStream release pkg 3.0.8

**Comment by cneidle** [comment]
raised priority; related to #154?

**Comment by gregorydimitriadis** [comment]
@cneidle yes, somewhat related - won't have the same fix necessarily, but not entirely orthogonal.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

appears fixed.
