### ISSUE TITLE
Creation of new field:  "Value Prefix" doesn't work.  Other field properties also not working.  - est. 5 hours

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#154]
Not a big deal, but if it doesn't work, it should probably be removed.

The original program had the option of prefixing something to all field values.  For example, the "role shift" field would pre-pend to the value "rs:"  So it the user entered "John" as the value, it would appear as "rs:John"

The user can just type all of that, but if the functionality doesn't work, we should just get rid of it.

It looks like the other field property settings (alignment; free text vs. menu) also don't work when one sets up a new field.  That's ok, but I should make a point of alerting users to this fact in the documentation.

**Comment by gregorydimitriadis** [comment]
This is also issue_6 from the README.txt as of SignStream release pkg 3.0.8

**Comment by cneidle** [comment]
This is still broken.  It needs to be fixed.  Thanks.  The window appears for adding a new value, but it disappears instantly.  Thanks.

**Comment by douglas-motto-at-rutgers** [comment]
alignment changes should now work.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_12_1056_cbb91a73

free-text/menu should be working.

Disabled changing menu to text for existing non-manual fields and vice versa.

Closing.
