### ISSUE TITLE
Event at beginning of utterance won't delete - est. 4 hours

### ISSUE THREAD

**Issue by aimeeaylward** [DCS-LCSR/SignStream3#155]
I am working in the file Cory 113 and came across an event in utterance 16 that is unable to be deleted. It a raised eye brow event and when double clicked, it won't be selected in order to extend or shorten it, and when using option+click the event bar does not become selected. 
![screen shot 2017-06-26 at 12 04 51 pm](https://user-images.githubusercontent.com/25349160/27548797-05550180-5a68-11e7-9dea-555dd104d94d.png)
There is a small portion of the event bar that can be highlighted with both double click and option+click, but once I  choose delete and proceed, nothing is actually deleted from the event. 
![screen shot 2017-06-26 at 12 06 01 pm](https://user-images.githubusercontent.com/25349160/27548813-15b59f9e-5a68-11e7-98db-b26e6859b2b0.png)
I tried extending the utterance to see if the event was somehow too long and tried selecting it using double click and option+click, but the event was not any longer than previously shown and still would not be selected or deleted.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

We no longer have utterance boundary requirements...so this doesn't appear to exist to be a problem now.

Fixed.
