### ISSUE TITLE
Search problems

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#156]
Return to Original State does not seem to work.

After a search result has been opened, the "play utterance" option seems very flaky.  I have gotten it to work, but often it doesn't seem to work.  Not sure what makes it work vs. not.

Also - users will have to be warned not to close the window with the search results, because that immediately quits the whole program.  (not an expected behavior; also no warning to save or anything)

Also, clicking on search results sometimes goes to the wrong sentence.  In this example, the first two work properly, but the 3rd and 4th don't:

![screen shot 2017-06-26 at 4 14 29 pm](https://user-images.githubusercontent.com/13629122/27558233-a7e71f24-5a8a-11e7-9b4b-8f42d4cef3be.png)

![screen shot 2017-06-26 at 4 14 38 pm](https://user-images.githubusercontent.com/13629122/27558237-ac2a08bc-5a8a-11e7-88ed-a3d7fd559bdb.png)

**Comment by cneidle** [comment]
One correction:  This time I did get a dialog box asking me to save changes before closing the utterance window showing a specific search result.   Perhaps there had not been any unsaved changes previously.  Sorry.  But that's just a minor point in the issues reported above...  thanks.

**Comment by gregorydimitriadis** [comment]
This is also issue_8 from the README.txt as of SignStream release pkg 3.0.8

**Comment by gregorydimitriadis** [comment]
Also relevant to #152 - window closing is an aspect of search as well.

**Comment by cneidle** [comment]
Return to original state seems to work, and I have not had problems clicking on search results.

(Closing the search results window does close the file, without a warning, but that is presumably part of another ongoing issue.)

**Comment by gregorydimitriadis** [comment]
Indeed - that is issue #152

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Closing fixed.
Finding fixed.
Playing Utterance fixed.

Need to remove back to original option.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_12_1056_cbb91a73

Removed "back to original"

Closing.
