### ISSUE TITLE
Enhancement request - for display of search results

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#157]
Perhaps this can be resolved along with the other enhancement requests to be able to enlarge regions of other windows.  In any case, for the display search results, it would be nice to be able to enlarge the display area for results without having to enlarge the window as a whole, i.e., to be able to drag the border line between the query area and the results area to adjust their relative sizes.

![screen shot 2017-06-27 at 11 23 39 am](https://user-images.githubusercontent.com/13629122/27595729-7dd5a92a-5b2b-11e7-848b-9b5619dcd37d.png)

**Comment by cneidle** [comment]
There should also be a CLEAR button in the Search window, e.g.

![screen shot 2017-06-27 at 11 58 11 am](https://user-images.githubusercontent.com/13629122/27597311-fda212ac-5b2f-11e7-97a0-60cc16ede467.png)

**Comment by gregorydimitriadis** [comment]
@cneidle Does clear here mean to just remove all the entered information from existing rules? Or does it also mean to clear the screen down to just one blank rule (as exists when you first open the window)?

**Comment by cneidle** [comment]
I would think the latter - that is, if one wanted to do a new search, one would start all over again.
So one should see the screen in the same state as when you would first open that window.  Thanks.

**Comment by cneidle** [comment]
Looks much better - thanks!
