### ISSUE TITLE
Controlling the view of multiple Temporal Partitions/Segment Tiers

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#158]
It seems to me the Remove, Up, and Down buttons are not working.  Perhaps I just don't know how to select the one that is to be removed or moved ?  Or perhaps this has not yet been implemented ??

![screen shot 2017-06-30 at 3 12 39 pm](https://user-images.githubusercontent.com/13629122/27750670-cd012e8e-5da6-11e7-9f05-8bf3efda9bcc.png)

**Comment by gregorydimitriadis** [comment]
@cneidle To select the segment tier, you can click where it the string of "Annotator: x" is - this is the only click-able place.

**Comment by cneidle** [comment]
Ok!  Got it.  This will be even more logical once "Annotator" is replaced by "Participant"  :-)

Thanks very much.

**Comment by gregorydimitriadis** [comment]
HI @cneidle  - can I close this one?

**Comment by cneidle** [comment]
Yes :-)   Thank you very much.
