### ISSUE TITLE
Failure to save local participants and annotators

### ISSUE THREAD

**Issue by kwasiopoku** [DCS-LCSR/SignStream3#16]
When adding new participants and annotators via the macro unit screen, SignStream3 doesn't actually save the new values on save.  The data is lost when the application is relaunched

**Comment by blazetravis** [comment]
This is half fixed. New values are now saved. But edited values are not saved upon re-launch.

I added myself as a new annotator and deliberately misspelled my name. I added Cory as a new participant. I saved and relaunched. This was correctly saved and displayed. When I went back to the Macro Unit and selected the edit annotator option, I was able to respell my name. I saved and relaunched. This corrected/edit annotator information was not saved upon relaunch.

**Comment by kwasiopoku** [comment]
This ticket has unresolved components that were identified in UAT. The remaining issues will be addressed in Sprint 2.  This is the same as item #24

**Comment by blazetravis** [comment]
Cannot click on annotators or participants currently.

**Comment by blazetravis** [comment]
This bug has been fixed.
