### ISSUE TITLE
Weird overlap of glosses in Cory 107 - U 61 - est. 12 hours

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#161]
![screen shot 2017-08-16 at 10 36 23 am](https://user-images.githubusercontent.com/13629122/29368902-077c69ec-826f-11e7-9761-0f3915816eb2.png)

I clicked on that one overlapping item, and chose 'delete' and a whole bunch of stuff got deleted!

![screen shot 2017-08-16 at 10 40 25 am](https://user-images.githubusercontent.com/13629122/29369012-59de5b64-826f-11e7-96a8-25a89ac0ddbe.png)

I'll email the before and after files.

thanks.

**Comment by gregorydimitriadis** [comment]
Possibly related:

#123 

#118 

#86

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Believed fixed....preventing overlap.
