### ISSUE TITLE
Participant information not displayed in Utterance Window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#162]
Hi,

This file originally had no participant defined.  I added a participant -- and this was displayed in the Tier label 

![screen shot 2017-08-16 at 11 49 56 am](https://user-images.githubusercontent.com/13629122/29372523-6607a670-8279-11e7-9001-1e254944ed2d.png)

but not in the Utterance Window

![screen shot 2017-08-16 at 11 49 46 am](https://user-images.githubusercontent.com/13629122/29372536-71a87a86-8279-11e7-8ddd-64bd6be0332d.png)

I tried saving the file and reopening it, but that made no difference.

**Comment by cneidle** [comment]
SORRY - MY MISTAKE - PLEASE IGNORE THE ABOVE.

I had added the Participant to the Macro Unit, but had not taken the further necessary step (showing how confusing this is) of adding it to the Segment Tier, which I had already relabeled, making me think that the participant had already been set there.   Anyway, SORRY.

**Comment by gregorydimitriadis** [comment]
@cneidle  I think this one basically the resolution will be to ensure that all segment tiers which exist must be correlated with a participant, either by choice or by assumption. This may need to be accomplished by forcing the user to select a participant in the macro unit window (similar to how now at least one annotator must be selected as well).

**Comment by gregorydimitriadis** [comment]
@cneidle  Also between this issue and #145 - which should we keep?

**Comment by cneidle** [comment]
I suggest deleting this issue, in favor of #145 -- to answer the question you sent.

I agree with requiring at least one participant to be selected in the Macro Unit Information window, and assigning that participant (if there is only one) by default to the first segment tier that is created.  Thanks.

**Comment by gregorydimitriadis** [comment]
Closing as duplicate

**Comment by cneidle** [comment]
This was fixed.  But it's broken again.

<img width="1175" alt="screen shot 2018-04-28 at 3 05 09 pm" src="https://user-images.githubusercontent.com/13629122/39399986-b2c9a3c4-4af5-11e8-9900-086eede99cd8.png">

**Comment by gregorydimitriadis** [comment]
@cneidle is that the only segment tier in the collection? Also what happens when you add a new segment tier? If the segment tier already exists, signstream will not automatically assign the participant to it - only for new creations.

**Comment by cneidle** [comment]
Hi Greg,

Yes, that is the only segment tier in the collection.

And yes - when I create a new one, the participant name does appear.
But it is impossible to manually enter the information so that the names
are uniform, since the new one necessarily contains a : and the old one
cannot include a : when it is renamed.

Not a big deal.

But that still doesn’t explain this:



Participant: N/A shows up in every screen for the older files
(which is every file in our corpus).

It’s redundant information (since the participant name appears
above); so not a big deal that it is missing, but kind of hard to explain 
in a demo what it’s doing there.

Again, just a blemish — not critical for functionality -- but one that literally 
appears in every screen.   If there is only one participant defined for the
Collection, then it’s clear who the participant is, I would think.
I really did think that had been fixed...

For some other time, I guess.


Thanks,
   Carol

**Comment by cneidle** [comment]
OK - I found a way to do it - by renaming the participant.  DONE :-)

[ too late for the demo I recorded this weekend for LREC, but c’est la vie ]

Thanks,
 Carol
