### ISSUE TITLE
Identifying any requirements for video files working with SignStream

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#166]
Limited by our video playback component?  Can we refer the user to some set of video formats that can be read by Xuggler or whatever?? I anticipate that we will be getting questions about this very soon from users: “What video formats can SignStream work with?” and it would be good to have an answer to that.

**Comment by cneidle** [comment]
thanks.

**Comment by cneidle** [comment]
As we discussed, would be good to add this information to the readme, and I will add it to future versions of the user guide.

**Comment by gregorydimitriadis** [comment]
Adding to the README file - will do, prior to our next public release. Closing this out for now - thanks.
