### ISSUE TITLE
Better way to deal with upgrading (without overwriting local files) - est. 20 hours

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#169]
Per Carol: Better way to deal with upgrading (without overwriting local files).  Other programs deal with this by storing preference-like information in a location that does not get overwritten by an upgrade, e.g., in the system Library. Could SignStream do that? 

--

Upgrade could occur "in-app" and occur "around" the local files, so as not to touch them while upgrading everything else around it.

Related to #120

**Comment by cneidle** [comment]
would be important to incorporate this in the next release

**Comment by gregorydimitriadis** [comment]
Possibly a big task - could be upwards of 20+ hours

**Comment by gregorydimitriadis** [comment]
Mostly done for now.

**Comment by gregorydimitriadis** [comment]
Re-classifying as an open/ongoing issue - to explore better options than our current update scripts.

**Comment by gregorydimitriadis** [comment]
closing as obsolete
