### ISSUE TITLE
Video Lookup Function - est. 10 (?) hours

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#171]
From the Macro Unit window - often the lookup function does not behave as expected. 

See #81 for more possible information.

**Comment by cneidle** [comment]
Just curious: How is this being done?  Would it not make sense to have a local file that keeps track of the likely locations of the video files, i.e., where they have been found before?  Or is that what is now (supposed to be) happening?

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

the Lookup but has been removed.
