### ISSUE TITLE
unable to reset start time of utterance in Database View window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#175]
Even when all items have been removed from the initial portion of the utterance (including the translation), it is impossible to make the start time later.

![screen shot 2017-08-22 at 10 10 59 am](https://user-images.githubusercontent.com/13629122/29569779-8390bc10-8722-11e7-8cd6-ebc99b51a8da.png)

![screen shot 2017-08-22 at 10 11 19 am](https://user-images.githubusercontent.com/13629122/29569780-84c61788-8722-11e7-86d3-6f0c0947bf54.png)

This is file 110, U 31, fwiw.

**Comment by gregorydimitriadis** [comment]
@cneidle - Is the latest version of this file currently under "2012/CURRENT/Cory" ?

**Comment by cneidle** [comment]
No - I will email the latest version of file 111 to Greg.

thanks,
 Carol

**Comment by cneidle** [comment]
Still a problem, e.g., file 59, U 11 and U 22.   When exported to the DAI, the start image of these sentences will be entirely black, because I am unable to reset the start time of the utterance (which needs to be one frame later than it currently is).  Deleting all elements near the start of the utterance doesn't help.

**Comment by cneidle** [comment]
This is still a problem.  It is also impossible to reset the end frames of utterances in the database view.  The error suggests that this conflicts with what is already annotated, but it doesn't.

**Comment by cneidle** [comment]
This should be a high priority for fixing.  It is really a problem, e.g.
in this sentence, where the current end of one of the video files is problematic, and
the utterance needs to be shortened.  There is nothing that should prevent doing that.

<img width="1163" alt="screen shot 2018-06-21 at 7 15 40 pm" src="https://user-images.githubusercontent.com/13629122/41750039-bd1faee2-7587-11e8-838d-fcb514034583.png">

<img width="1321" alt="screen shot 2018-06-21 at 7 18 15 pm" src="https://user-images.githubusercontent.com/13629122/41750061-e29f1310-7587-11e8-8075-7e7000f135c8.png">

**Comment by cneidle** [comment]
So the final frame for the SIDE view in the DAI, which is in fact a front view (an error in video processing) can't be removed from this utterance.

<img width="430" alt="screen shot 2018-06-21 at 7 20 01 pm" src="https://user-images.githubusercontent.com/13629122/41750138-48d486ba-7588-11e8-9e7c-90cee653849b.png">

**Comment by gregorydimitriadis** [comment]
Fixed in v3.1.1

**Comment by cneidle** [comment]
Confirmed as fixed :-)
