### ISSUE TITLE
Show non-empty field button should apply to current utterance, not just what is visible in the window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#183]
SO, I am looking at Rachel 43, U14.

I can't see the whole utterance in the gloss window (and I can't eliminate empty space at the beginning of the utterance because of the bug I reported about not being able to change the start time of the utterance).  So this is what I see when I open that utterance, after I have clicked on the show non-empty button.

<img width="1279" alt="screen shot 2017-08-23 at 4 09 45 am" src="https://user-images.githubusercontent.com/13629122/29605486-05e9294a-87b9-11e7-953e-7662032ac226.png">

So when I scroll through to see the glosses, this is all I see:

<img width="1279" alt="screen shot 2017-08-23 at 4 09 45 am" src="https://user-images.githubusercontent.com/13629122/29605489-0a33e882-87b9-11e7-8ed8-73f59e501a8c.png">

until I hit the "non-empty fields" button again:

<img width="1274" alt="screen shot 2017-08-23 at 4 11 12 am" src="https://user-images.githubusercontent.com/13629122/29605514-226fcc40-87b9-11e7-93c2-370b0ff25228.png">

I should not have to hit that button every time the window scrolls.  It should apply to all non-empty fields for the selected utterance when it is invoked.

thanks.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

These buttons are being redesigned.  Closing these old requirements.
