### ISSUE TITLE
Change in value not getting saved

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#184]
File 43 - U 18

I  changed the value of a Topic/Focus event from "foc/ref" to "topic" and saved the file.
The original value persists.  When I close the file and reopen, the change has not been preserved.

<img width="737" alt="screen shot 2017-08-23 at 5 15 30 am" src="https://user-images.githubusercontent.com/13629122/29608653-cff052be-87c2-11e7-9318-23b902561536.png">

**Comment by cneidle** [comment]
This appears to be related to the search window having been open.  I had done a search for that value, found it, attempted to change it (all with the search window still open), and the change didn't stick. When I attempted the same change but without having the search window open, there was  not a problem.  

This is obviously a serious bug, as using the search window to find something so it can be changed is a pretty  common use case... 

<img width="958" alt="screen shot 2017-08-23 at 5 16 20 am" src="https://user-images.githubusercontent.com/13629122/29608880-7735ccc0-87c3-11e7-9c4e-f718292ee519.png">

**Comment by cneidle** [comment]
FWIW:  It's not enough to close the search window before making and saving a change.  Once the search window has been opened, it's not possible to make a change that will stick.  It's necessary to quite the program, open it again, and then make and save the change without opening the search window.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_10_1855_c60918b0

The change in value appear to persist with or with the search window open.

Closing.
