### ISSUE TITLE
NO_OF_HANDS incorrectly saved for some two-handed glosses

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#185]
See below email exchange and attached collection for details:

[signstream_bug_handedness.pdf](https://github.com/DCS-LCSR/SignStream3/files/1277812/signstream_bug_handedness.pdf)
[Rachel_2012-02-14_sc65.zip](https://github.com/DCS-LCSR/SignStream3/files/1277816/Rachel_2012-02-14_sc65.zip)

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_12_1409_1055ffd9

Was informed that that this has been fixed.

Closing.
