### ISSUE TITLE
SignStream 3.0.9 does not launch

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#186]
I follow the usual steps (including running DisableQuarantine script).  The program launches but immediately quits.

Here's the text from the log file:

<?xml version="1.0" encoding="MacRoman" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2017-09-06T08:59:23</date>
  <millis>1504702763514</millis>
  <sequence>0</sequence>
  <logger>edu.bu.signstream.ui</logger>
  <level>INFO</level>
  <class>edu.bu.signstream.ui.SS3SignStreamApplication</class>
  <method>&lt;init&gt;</method>
  <thread>10</thread>
  <message>Starting the Sign Stream application... </message>
</record>
<record>
  <date>2017-09-06T08:59:23</date>
  <millis>1504702763556</millis>
  <sequence>1</sequence>
  <logger>edu.bu.signstream.ui</logger>
  <level>INFO</level>
  <class>edu.bu.signstream.common.util.signbank.SignBankParser</class>
  <method>createSignBankResourceCollection</method>
  <thread>10</thread>
  <message>Accessing sign bank directory: signbank</message>
</record>
<record>
  <date>2017-09-06T08:59:23</date>
  <millis>1504702763557</millis>
  <sequence>2</sequence>
  <logger>edu.bu.signstream.ui</logger>
  <level>INFO</level>
  <class>edu.bu.signstream.common.util.signbank.SignBankParser</class>
  <method>createSignBankResourceCollection</method>
  <thread>10</thread>
  <message>Priorities file does not exist: signbank/priorityList.xml</message>
</record>
<record>
  <date>2017-09-06T08:59:23</date>
  <millis>1504702763557</millis>
  <sequence>3</sequence>
  <logger>edu.bu.signstream.ui</logger>
  <level>INFO</level>
  <class>edu.bu.signstream.common.util.signbank.SignBankParser</class>
  <method>createSignBankResourceCollection</method>
  <thread>10</thread>
  <message>Reading priorities file: signbank/priorityList.xml</message>
</record>
<record>
  <date>2017-09-06T08:59:23</date>
  <millis>1504702763573</millis>
  <sequence>4</sequence>
  <logger>edu.bu.signstream.ui</logger>
  <level>INFO</level>
  <class>edu.bu.signstream.common.util.signbank.SignBankParser</class>
  <method>createSignBankResourceCollection</method>
  <thread>10</thread>
  <message>Parsing priorities file: signbank/priorityList.xml</message>
</record>
</log>

**Comment by gregorydimitriadis** [comment]
@cneidle Currently looking into this

**Comment by gregorydimitriadis** [comment]
@cneidle It was a typo on the release script to build the package. Fixed and rebuilt here:
http://dai.cs.rutgers.edu/SignStream/download/release/SignStream3-3.0.9.zip
