### ISSUE TITLE
Macro Unit Information Window remains open

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#187]
I launched SignStream (3.0.10), and then immediately opened an existing collection.

The Macro Unit Information unit (blank -- from when i launched the program) remained visible.

![screen shot 2017-10-06 at 9 56 52 am](https://user-images.githubusercontent.com/13629122/31281264-e7f3aa3c-aa7c-11e7-8135-2ae1d133ada2.png)

Edit Macro Unit is not available from the top menu.  It is grayed out.  In fact, everything in both the Collection and Macro Unit menus is grayed out.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

fixed.
