### ISSUE TITLE
Left/RightHandShapes always inserts "diff"

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#190]
If you search a sign in the sign bank and "insert all data" of that sign, no matter what information is in the box in the sign bank, (SAME or DIFF), it always checks the diff box in the morph-phon information. 

For example, the sign DECIDE, I have input all data from the sign bank. From the screenshot you can see the information in the sign box "LeftRightHandShapes: SAME, however it inputs "Diff't START/END hs" in the Morph-Phon info box. 

This happens for any sign that you insert all data from, it will always input "Diff't START/END hs" and you have to manually change it to the correct SAME or DIFF code. 
![screen shot 2017-10-31 at 12 58 44 pm](https://user-images.githubusercontent.com/15836242/32237761-3908ec84-be3c-11e7-9e5a-6e29ddc318c9.png)

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

fixed.
