### ISSUE TITLE
Insert All Data Bug: Low Priority  - est. 2 hours

### ISSUE THREAD

**Issue by claireettlin** [DCS-LCSR/SignStream3#191]
When you are coding a one handed sign, and you search it in the sign bank, then go to  "insert all data", it will add the selection line that says " Same HS left/Right", which should only appear when you have inserted data from a two handed sign (Left and Right). 

![screen shot 2017-11-03 at 12 02 08 pm](https://user-images.githubusercontent.com/32074197/32385812-ad509604-c095-11e7-99a1-e411ae1079e2.png)
![screen shot 2017-11-03 at 12 03 02 pm](https://user-images.githubusercontent.com/32074197/32385813-ae8762dc-c095-11e7-9292-52f36b555c27.png)

**Comment by gregorydimitriadis** [comment]
Seems related to #190

**Comment by gregorydimitriadis** [comment]
@cneidle 

Issue is that in the sign bank file - the field coming across in one-handed signs is START_END_RIGHT_HS, with nothing for START_END_LEFT_HS -- In my opinion, it should just come across for the field START_END_HS (which is how SignStream interprets things - if there is no left/right, then START_END_HS is what's used.

But be that as it may - if it stays this way, SignStream has to change. If the SignBank changes, SignStream can stay the same.

This having implications for signstream vs. sign bank, I figure I'll leave that up to you.

**Comment by cneidle** [comment]
Sorry - I don't fully  understand this.  @kwasiopoku Augustine should be brought into this discussion.

**Comment by douglas-motto-at-rutgers** [comment]
Signbank still says...<START_END_RIGHT_HS>SAME</START_END_RIGHT_HS>

But it works as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

so SignStream must have changed...issue fixed.
