### ISSUE TITLE
Save-as not working properly

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#193]
Working with file Jonathan_2012-11-27_sc90-new.ss3 (but the same is true for other files):

When I try to save it with the same name in a new folder, I get this error message:

![screen shot 2017-11-17 at 12 08 24 pm](https://user-images.githubusercontent.com/13629122/32959687-6a1d470a-cb90-11e7-8c4f-f9015de772ab.png)

However, it does appear to be saved in the folder I had designated, but as a FOLDER, and without the
.ss3 ending, as follows:

![screen shot 2017-11-17 at 12 12 02 pm](https://user-images.githubusercontent.com/13629122/32959729-93c1f2cc-cb90-11e7-9f53-f3ed605c23b7.png)

The problem appears to be that the presence of the .ss3 in the filename I had entered, but this is not intuitive.

If you save, e.g., a Microsoft word document, the program is smart enough to add the .doc(x)
suffix if the filename you entered lacked that, but to deal with a request to save a document as 
"filename.docx".

A user might very reasonably attempt to save a file with the exact name it has had into a different folder.  At the very least, an error message that would warn the user to be sure not to include ".ss3"
in the filename when attempting to save would be helpful, but even better would be for the program to deal appropriately with the request to save as   x.ss3

thanks.

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

done...adds .ss3 to filenames without extension given.
