### ISSUE TITLE
Search Sign Bank window - problem with "enter"  - est. 5 hours

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#195]
If I have a sign that is already in the sign bank -- and I assume this is intended -- as with MOTHER,
the Morph-Phon window gives me the option of entering it without looking it up in the sign bank (this is for a sign that had previously been annotated):

![screen shot 2017-11-17 at 12 31 32 pm](https://user-images.githubusercontent.com/13629122/32960563-51431806-cb93-11e7-9fe2-adce0731a690.png)

However, when I try the same thing with NICE/CLEAN (both of these from Jonathan 90, U 8),
this is what happens -- whereas this should NOT be added to the Sign Bank:

![screen shot 2017-11-17 at 12 30 19 pm](https://user-images.githubusercontent.com/13629122/32960583-6dc4459a-cb93-11e7-9a57-157e0a298337.png)

This irregularity occurs with many signs; not sure why some signs produce this problem and others don't.

Alli had reported the following, which I have not observed myself, but I will ask her to show me:

I noticed if I check a sign and it is not in the sign bank, but I accidentally press enter instead of bypass sign bank, it then adds the sign to an unnamed folder. I deleted the sign I accidentally did this with, but I wanted to know if this is supposed to happen or if it is a bug I should report. I can replicate it if necessary.

"Enter" should only be an option if the sign already exists in the Sign Bank; otherwise "Bypass sign bank" or "Add to sign bank" should be the only options, in any case.  SO something is definitely wrong here...

**Comment by cneidle** [comment]
OK - Now I understand what Alli meant when she said that the sign gets added to an empty folder when the message "added to sign bank" appears after hitting the "enter" button, this is what she was referring to.  Note that MANY exists.  If I added a + (making it MANY+) and hit "enter" this is where the new entry goes:

![screen shot 2017-11-17 at 1 37 07 pm](https://user-images.githubusercontent.com/13629122/32963065-c3ff9b86-cb9c-11e7-88e0-b5d2ba39a46c.png)

This should most definitely not happen when the difference is the addition of a +, which does not distinguish signs within the Sign Bank.

Is this intended for other new additions to the Sign Bank ????   Minimally there should be a name for that folder, such as "LOCAL SIGN BANK ADDITIONS" or something.

Not sure how this is supposed to work, but the functionality is not working properly.

Here's a similar screen shot from Alli:

![screen shot 2017-11-17 at 1 30 19 pm](https://user-images.githubusercontent.com/13629122/32963157-0c39caca-cb9d-11e7-9d1e-1a1215757c37.png)

As for Alli's having deleted the sign that had been incorrectly added, deletion of signs from the local sign bank is fine.  Deletion of signs from the global sign bank is not.  When I attempted to delete MANY, which should not be allowed, this is what I saw:

![screen shot 2017-11-17 at 1 43 08 pm](https://user-images.githubusercontent.com/13629122/32963225-4b5a437e-cb9d-11e7-8eaf-298f344deee7.png)

?

**Comment by cneidle** [comment]
FYI - the problem with deleting signs was fixed.

However, the issue with the Enter button being grayed out even when the sign is in the Sign Bank seems to persist, at least on the first attempt to do this.

![screen shot 2018-04-04 at 11 33 28 am](https://user-images.githubusercontent.com/13629122/38318103-99b50d3a-37fc-11e8-804f-e9e5f1216be8.png)

One that window is closed, subsequent attempts to open the Morph-Phon window for that or other signs produce the expected behavior.

![screen shot 2018-04-04 at 11 34 44 am](https://user-images.githubusercontent.com/13629122/38318091-93b897a8-37fc-11e8-882f-42c4a140ff2e.png)


Not a critical bug, but also not completely fixed.  Just FYI.

**Comment by gregorydimitriadis** [comment]
completed for next release

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

fixed.
