### ISSUE TITLE
English translations disappearing !    

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#196]
Working again on file 90, I can see NO English translations.  I was trying to investigate Alli's report that the translation was sometimes starting before (and outside of) the defined utterance.

I can still see no translations in that file, although all sentences had translations.  When I went down to
look at the file in Alli's office, many of the translations were missing, but some were still there.

The only thing I had done to the file in between Alli's working on it last (when all translations were visible) and today, was to add the participant information.  (SS was allowing the Macro Unit window to be closed without a participant selected, by the way, which I thought it was no longer supposed to allow.)  And a I renamed the Segment Tier to "Jonathan".  Neither of those things should have affected the translation fields.

Furthermore, the Morph-Phon window had a double display of the ASLLRP-BU user, with no possibility of deleting either.

**Comment by cneidle** [comment]
Just to follow up on the last part of this comment, although this should probably be set up as a separate issue, the same thing happens with other files:  1) no participant is forced to be selected before closing the Morph-Phon window, and 2) duplicate instances of annotator BU-ASLLRP cannot be eliminated.

![screen shot 2017-11-20 at 10 59 17 am](https://user-images.githubusercontent.com/13629122/33027885-53f7e5b2-cde2-11e7-9ff1-f163d25d26e7.png)

**Comment by cneidle** [comment]
(Note that wrt to above image, I went back to add "Rachel" as a participant after having successfully confirmed selections with no participant selected.)

**Comment by cneidle** [comment]
Could you please let me know as soon as this bug is fixed?  We're waiting to add back translations to files from which they have disappeared until this is fixed...  thanks very much!

**Comment by gregorydimitriadis** [comment]
Hopefully should be fixed before the next rollout, in the next few days.

**Comment by gregorydimitriadis** [comment]
Closing in favor of #237
