### ISSUE TITLE
Display non-empty not happening when a new sentence is selected

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#197]
When I choose a new sentence by clicking in the left-hand index, the sentence should be displayed along with all non-empty fields for that utterance.  But it isn't.  Compare the two screenshots, the first after going from U7 to U8 by clicking on the left, and the second after clicking on the show non-empty fields button.  This problem does not seem to occur with the Prev Utterance or Next Utterance button, but the effect should be the same if the user selects the utterance from the index on the left.

![screen shot 2017-11-20 at 11 49 42 am](https://user-images.githubusercontent.com/13629122/33030402-37cd0320-cde9-11e7-8ba4-5dc20b54dd28.png)

![screen shot 2017-11-20 at 11 49 55 am](https://user-images.githubusercontent.com/13629122/33030410-3c606b34-cde9-11e7-96f2-4111c8c999d6.png)

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

fixed.
