### ISSUE TITLE
v.13 - serious bug with 'play utterance'

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#199]
Play utterance is not working.  

I select a sentence, or select an item within a sentence.  Play utterance seems to start playing the movie from the beginning of the movie file !

The first picture below shows me having selected an utterance.

The second picture shows (with a few second delay) the movie being played from the beginning of the file... 

<img width="1171" alt="screen shot 2017-12-20 at 11 25 52 am" src="https://user-images.githubusercontent.com/13629122/34217159-be9fd174-e578-11e7-8c3f-dc013debb650.png">

<img width="1155" alt="screen shot 2017-12-20 at 11 26 03 am" src="https://user-images.githubusercontent.com/13629122/34217165-c2c0998c-e578-11e7-8fd1-e5ac704520a9.png">

**Comment by cneidle** [comment]
Not able to reproduce this.  I closed and reopened the file, and the problem did not recur.  Tried another file, and this also did not happen.   FWIW.

**Comment by cneidle** [comment]
We should put this on hold until/unless it occurs again.

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

does not exist....fixed.
