### ISSUE TITLE
Overview Window - Display Time Period line

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#2]
Keystroke Option + Left-Click & drag on the "Display Time Period" line should select all utterances within the resulting start/end frame

**Comment by gregorydimitriadis** [comment]
Question for Carol: Isn't this the keystroke for creating a new utterance?

**Comment by kwasiopoku** [comment]
Should be able to select any portion of the video for playback.  Could include multiple utterances or portions of multiple utterances.

**Comment by cneidle** [comment]
we should discuss.

**Comment by gregorydimitriadis** [comment]
closing in favor of #420
