### ISSUE TITLE
Scroll bar does not appear - est. 6 hours

### ISSUE THREAD

**Issue by rklopez** [DCS-LCSR/SignStream3#20]
When you open up SS3 and open a file, you cannot scroll until you zoom in, then the scroll bar appears.

**Comment by hammondcl** [comment]
This appears to be functioning normally now.

**Comment by gregorydimitriadis** [comment]
The scrollbar is there once a file is opened, but it is not the proper length (it's not the length of the entire video file, so it cuts off too early). So the auto-lengthening on startup without needing to zoom in is still to be fixed

**Comment by hammondcl** [comment]
This still occurs inconsistently

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17.

Scroll handle in Utterance view not correct size until scroll starts.

Scroll handle in Utterance view not correct size at end of video.

**Comment by douglas-motto-at-rutgers** [comment]
May not be fixable with Swing.

Closing for now.
