### ISSUE TITLE
Bug (v. ... 14) with Dialog box about saving changes from Morph-phon window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#202]
When I attempt to quit the Morph-phon window regardless of whether or not I have made changes (this should only happen when information has been modified, of course), this appears:

![screen shot 2017-12-28 at 10 12 14 am](https://user-images.githubusercontent.com/13629122/34414552-f2126360-ebb7-11e7-8f5a-256eb67389a8.png)

But I am -- sometimes -- unable to click on the default option, nor to invoke it by hitting a carriage return.  I can close that window with the red button in the upper left corner, but I then seem to get inconsistent behavior with respect to whether the changes actually get entered.

**Comment by cneidle** [comment]
Also having (sporadic) problems with the Bypass Sign Bank Check button.  Clicking on it in the instance shown has no effect:

![screen shot 2017-12-28 at 10 37 48 am](https://user-images.githubusercontent.com/13629122/34415180-433c5eaa-ebbb-11e7-9705-7efa8671cc7a.png)


It seems that things in the morph-phon window are not functioning as they should be.

**Comment by cneidle** [comment]
**Needs to be fixed prior to next release.**

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

fixed.
