### ISSUE TITLE
Play utterance starts too soon - est. 5 hours

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#203]
Relatively minor bug, but this should not be happening.

If I am viewing an utterance:

![screen shot 2018-01-13 at 12 05 14 pm](https://user-images.githubusercontent.com/13629122/34908203-32743e3e-f85a-11e7-91a8-4dbfa3696962.png)

and then click on Play Utterance, the player goes to a frame before the start  (which often results in the entire utterance ceasing to be visible):

![screen shot 2018-01-13 at 12 05 52 pm](https://user-images.githubusercontent.com/13629122/34908204-389ab810-f85a-11e7-8923-d68e2d38750d.png)

**Comment by gregorydimitriadis** [comment]
@cneidle Is this one that the video actually plays a frame before start, or just that the scroll takes it back so about half the screen is the empty space prior to the utterance? The second part I believe to just be resulting from always keeping the green scroll bar in view, and if not in view then re-centering it.

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

fixed.
