### ISSUE TITLE
Search in Sign Bank not working right

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#204]
Try looking up "LOOK-UP"  

No results found.   But there should be matches...

I thought it might be a problem with the hyphen.  Including the hyphen does give some results, but not all.   Also a problem with a "." in the gloss.

<img width="986" alt="screen shot 2018-01-23 at 6 16 54 pm" src="https://user-images.githubusercontent.com/13629122/35306177-7c7bb756-006a-11e8-8182-b771ee98c8cf.png">

<img width="1156" alt="screen shot 2018-01-23 at 6 19 40 pm" src="https://user-images.githubusercontent.com/13629122/35306197-8adb36aa-006a-11e8-8033-13b7d3172169.png">

<img width="1217" alt="screen shot 2018-01-23 at 6 20 41 pm" src="https://user-images.githubusercontent.com/13629122/35306218-977769e2-006a-11e8-8444-700d36c74f20.png">

<img width="1028" alt="screen shot 2018-01-23 at 6 21 10 pm" src="https://user-images.githubusercontent.com/13629122/35306229-a099b67e-006a-11e8-81d5-be6112d02a3d.png">

<img width="1114" alt="screen shot 2018-01-23 at 6 21 39 pm" src="https://user-images.githubusercontent.com/13629122/35306233-a52bde10-006a-11e8-862b-a889eb94d4a2.png">

**Comment by gregorydimitriadis** [comment]
@cneidle Should this be in the DAI project?

**Comment by cneidle** [comment]
Very sorry about that!   Please ignore.
