### ISSUE TITLE
"Show non-empty buttons" logic error

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#205]
Discovered new bug while working on issue #198 

The "show non-empty" button logic works by looking at the selected thing in the utterance list on the left side panel. This now has multiple "modes" of highlighting for selection activated now (gray for what is visible on screen and blue for what was clicked by user and is thus the "operative" selected utterance which is called upon when "play utterance" is clicked).

So the non-empty logic is looking at the blue selection of utterances, whereas it needs to be looking at blue+gray selection of utterances in sum.

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

this has been redesigned.
