### ISSUE TITLE
Enhancement request - not urgent - "expand all" option in Search Sign Bank window - possibly cannot do (!) - will lag app

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#206]
It would be great to be able to see all the sign bank main entries and entry variants, as displayed in the DAI 2 SignBank, without having to manually expand every main entry folder.  So 2 buttons, one for "expand all" and one for the reverse, would be much appreciated.  But not mission critical.  Thanks.

![screen shot 2018-04-09 at 9 49 07 am](https://user-images.githubusercontent.com/13629122/38501551-48850cca-3bdb-11e8-8163-6994abb8f337.png)

vs.

![screen shot 2018-04-09 at 9 49 43 am](https://user-images.githubusercontent.com/13629122/38501582-5d0d5f08-3bdb-11e8-9087-8b3333a5b861.png)

**Comment by cneidle** [comment]
Alternatively, having them all expanded by default, as in the DAI, would be far preferable to the current display -- in case that is trivial to do.   THANKS.

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

expand/collapse all button added.

done.
