### ISSUE TITLE
minor bug:  entry of non-manual information - 3 hours

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#208]
It is possible to enter a line in a non-manual field with no menu showing up for selection of the value. That results in something that is ill-defined.  That should not be allowed.  It seems to me that a line without a value attached to it should not be retained in the file...  

Low priority - but mentioning it while I am noticing it.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_10_1855_c60918b0

Believed Fixed.  Reopen new issue if still found.
