### ISSUE TITLE
Dominant Hand  mapping to right vs. left (for participants who are right- vs. left-handed) [est. 2-10 hours, depending]

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#209]
I was looking at the Morph-Phon info window, and noticing that the Location, Orientation, and Movement tabs are not grayed out, although they are not functional, and presumably should be.  (I thought this had been done, actually.)

On the other hand, I see that the Dominant Hand selection of R vs. L *is* grayed out.

That's not a problem for us, since our signers are all right-handed, but it is pretty odd to be distributing a program that cannot accommodate left-handed signers.

I assume that what is involved is the mapping between gloss 1 and gloss 2 with right hand or left hand fields just below, in the utterance window.

Obviously this is not going to be fixed in the next week.

But it seems to me that we should stick with dominant and non-dominant if we can't map properly to right and left hands.  

It would be pretty simple to change:

"right hand"  to "dom hand"
"rhshape" to "domhshape"
"left hand" to "nd hand"
"lhshape" to "ndhandshape"

*if* it's not possible to reverse the mapping when 'dominant hand = left' is checked for the participant.

But I would have thought this would not be hard.

The participant information does include that information. 

Anyway, something to discuss at some point.

thanks.

**Comment by gregorydimitriadis** [comment]
Completed with the simple part - just renaming on the frontend. To change the backend I've determined is quite a lot of work, as notions of "right" and "left" (any their many derivations - R/L, RIGHT/LEFT, etc) are hardcoded in too many places all around the codebase.

**Comment by travisnguyen** [comment]
Discrepancy: This bug has been noted as fixed in the release notes for 3.1.2, but has only been partially addressed.

Some issues still present:

- Location, Orientation, and Movement tabs are still not grayed out
- Descriptions of left and right hand are still present in the Morph-Phon information window (rather than being replaced with terms denoting hand dominance)
    - "L" and "R" for the "Dominant Hand" radio buttons
    - "L" and "R" for the "One-handed" radio buttons
    - "Right Hand" and "Left Hand" in the Selected Handshapes section

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

changed.
