### ISSUE TITLE
Clicking out of an utterance brings you to U1

### ISSUE THREAD

**Issue by rklopez** [DCS-LCSR/SignStream3#21]
If I am working on U73 and I finish the utterance, I click out of the utterance and to the main file. I should be looking at U73 and the utterances that surround it, but instead it brings you back to U1 and you have to scroll all the way back to the utterance you were working on to get to the next one.

**Comment by kwasiopoku** [comment]
This is not always consistent.  In some cases you get taken back to the last utterance but in most cases you are returned to UI

**Comment by hammondcl** [comment]
This no longer appears to be a problem.
