### ISSUE TITLE
Unable to create new utterances in Segment Tiers - est. 3 hours

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#210]
Hi,  This is Carol with Indya.

We are using the latest version (17) and the latest Sign Bank file (from yesterday), just FYI.

We have reached a point where we are unable to create new utterances in any of our segment tiers.  Option clicking has no effect.  We have tried closing and reopening SignStream.  Makes no difference.

![screen shot 2018-05-01 at 11 02 22 am](https://user-images.githubusercontent.com/13629122/39478067-3ce7f9b2-4d2f-11e8-8059-7a2def6451ab.png)

**Comment by gregorydimitriadis** [comment]
@cneidle Tested and reproduced. Not sure why it's happening yet, but I found a workaround: delete the first utterance of the segment tier to return the state to normal - i.e. can add utterances, etc. 

Will investigate further at the next opportunity.

**Comment by bugspotter33** [comment]
Hi Greg,

I deleted the first utterance from tier 3 and was able to add U1-U11. After U11 I can no longer add anymore utterances. I tried deleting U11 and adding it again but no luck with utterances after that. 

Indya 

![screen shot 2018-05-02 at 12 35 00 pm](https://user-images.githubusercontent.com/38887034/39536912-03fadafc-4e06-11e8-85e9-4641a4ca5955.png)

**Comment by bugspotter33** [comment]
/Users/asllrp/Desktop/Screen Shot 2018-05-02 at 12.35.00 PM.png

**Comment by bugspotter33** [comment]
Hi,
If I zoom out then I am able to add utterances, however if I am zoomed in I cannot

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

appears to no longer exist.
closing
