### ISSUE TITLE
Cannot select one handed in Morph-Phon Info

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#212]
When trying to enter in handshape information I clicked on the one-handed option and didn't see the drop down menu appear to select if the handshapes were the same or different for both hands. If I click the two-handed option it doesn't give me the drop down menu to select differing handshapes for both hands. 

![screen shot 2018-05-04 at 10 15 30 am](https://user-images.githubusercontent.com/38887034/39632806-1c36f9aa-4f84-11e8-936f-78c8725c1056.png)
![screen shot 2018-05-04 at 10 15 18 am](https://user-images.githubusercontent.com/38887034/39632809-1e876d02-4f84-11e8-95dd-973771822c7f.png)

**Comment by cneidle** [comment]
I just clarified this with Indya.  There is no problem.

Never mind - sorry about that.   Thanks.
