### ISSUE TITLE
options for fingerspelled words - est. 2 hours

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#214]
This isn't a major issue but when glossing a fingerspelled word, my understanding is that there should not be an option to select whether or not the handshapes are the similar or different. I have been seeing the option to select similar/different for the start/end handshapes. The first screenshot shows what I have been seeing and the second screenshot shows what should be happening instead.

![screen shot 2018-05-07 at 11 48 04 am](https://user-images.githubusercontent.com/38887034/39711238-24c012c6-51ed-11e8-8d4b-e710147179d4.png)
![screen shot 2018-05-04 at 10 15 18 am](https://user-images.githubusercontent.com/38887034/39711247-2b1692d0-51ed-11e8-95c4-861c854994ed.png)

**Comment by gregorydimitriadis** [comment]
@bugspotter33 @cneidle should the dropdown for start/end handshapes **not show up** for {fingerspelled, two-handed} either?

**Comment by cneidle** [comment]
that is correct.

For fingerspelled signs, no [start and end same/different handshape] menu is relevant.

thanks!

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

still exists.

**Comment by gregorydimitriadis** [comment]
Fixed in latest release.
