### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#215]
New feature for 2017-2018 year

**Comment by gregorydimitriadis** [comment]
Note - easy tweak: increase thickness of the graph line width, for easier visibility.

**Comment by douglas-motto-at-rutgers** [comment]
I believe this is the graph data.  That's been implemented and exists at least at 
SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

closing.
