### ISSUE TITLE
"exact word" option not working in Search window - est. 3 hours

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#217]
Compare

<img width="960" alt="screen shot 2018-05-11 at 1 42 39 pm" src="https://user-images.githubusercontent.com/13629122/39938549-51cc4c26-5521-11e8-8dfb-05c9baf42271.png">

<img width="963" alt="screen shot 2018-05-11 at 1 42 49 pm" src="https://user-images.githubusercontent.com/13629122/39938556-54b41c34-5521-11e8-8279-7e4120430d93.png">

**Comment by gregorydimitriadis** [comment]
Hi @cneidle 

Can we get the collection this was seen on? Thanks..

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
working.
