### ISSUE TITLE
missing handshapes - est. 8 hours

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#226]
I am working on U69 in Cory 113 file and I just edited a gloss that looked strange. When I opened the utterance the gloss ALL-DAY looked like it was missing handshapes. When I opened the morph-info I could see that there wasn't any data entered. I then entered the correct data and the gloss changed but is still missing handshapes. 

![screen shot 2018-06-07 at 10 57 48 am](https://user-images.githubusercontent.com/38887034/41108301-3024f84e-6a42-11e8-9111-8be3311dbe03.png)

![screen shot 2018-06-07 at 10 57 58 am](https://user-images.githubusercontent.com/38887034/41108308-33658fdc-6a42-11e8-952e-dedf598db843.png)

![screen shot 2018-06-07 at 11 03 58 am](https://user-images.githubusercontent.com/38887034/41108443-866625d4-6a42-11e8-86c1-1b8199f30d99.png)

![screen shot 2018-06-07 at 10 55 51 am](https://user-images.githubusercontent.com/38887034/41108333-3cbdf268-6a42-11e8-9659-a2f382d3d39f.png)

I am also noticing an issue with the final hold at the end of a gloss. I was looking over Cory114 and I noticed that the handshapes weren't at the start and end of a gloss that had a final hold. I went into the morph info and everything looked correct so I clicked bypass sign gloss and the handshapes appeared at the start and end like they should. However, in some cases the final hold got deleted (u36) so I had to add it again but I found this issue in (U36 classifier, U73KISS-FIST and U84HUG) I've made the changes and saved them so hopefully they will stay saved. 

![screen shot 2018-06-11 at 9 16 47 am](https://user-images.githubusercontent.com/38887034/41234250-ae5a1a18-6d59-11e8-842b-f7d8002c74f0.png)

![screen shot 2018-06-11 at 9 17 01 am](https://user-images.githubusercontent.com/38887034/41234264-b3b18a8c-6d59-11e8-83d0-b6f816e3f37d.png)

![screen shot 2018-06-11 at 9 17 09 am](https://user-images.githubusercontent.com/38887034/41234269-b6aa1c86-6d59-11e8-9bdb-6b43241dce4e.png)

![screen shot 2018-06-11 at 9 17 25 am](https://user-images.githubusercontent.com/38887034/41234273-b967cf22-6d59-11e8-8a19-0764d71d9daf.png)

![screen shot 2018-06-11 at 9 17 37 am](https://user-images.githubusercontent.com/38887034/41234282-bcad7b64-6d59-11e8-965e-f70f5b359d0b.png)

![screen shot 2018-06-11 at 9 21 05 am](https://user-images.githubusercontent.com/38887034/41234288-bec78688-6d59-11e8-9e34-66c4c8718702.png)

**Comment by gregorydimitriadis** [comment]
@bugspotter33 @cneidle

Hi - can you please send the collection file this was seen in? Thanks

**Comment by bugspotter33** [comment]
Final holds seem to do something weird to the glosses. An issue I ran into today was when I tried to gloss a two handed sign (TABLE) and it didn't matter if I deleted the final hold and re-added it, it still disrupts the gloss. This is Cory 107 U1

![screen shot 2018-06-21 at 10 33 52 am](https://user-images.githubusercontent.com/38887034/41726072-5a9b8fcc-753f-11e8-88e1-8feff818d6a4.png)

**Comment by bugspotter33** [comment]
Same issue occurring with final holds in Cory 107 U35 

![screen shot 2018-06-29 at 9 58 20 am](https://user-images.githubusercontent.com/38887034/42096314-fa283b1e-7b82-11e8-8128-c9bee097e797.png)

**Comment by cneidle** [comment]
This is systematic, it seems.  Should be a high-priority fix.  thanks!

**Comment by gregorydimitriadis** [comment]
For the initial reported case (ALL-DAY in U69) - another issue is that the gloss is marked as a one-handed where it's actually two-handed - is that right?

**Comment by bugspotter33** [comment]
ALL-DAY is typically a two-handed sign so unless this is signed with one
hand it should be marked as two-handed.

**Comment by gregorydimitriadis** [comment]
This is proving difficult to debug and solve. Moving on to the next issue and coming back to this later.

**Comment by bugspotter33** [comment]
I think I have a work around/fix for this bug. When marking the handshapes of a gloss that will have a final hold, typically what shows up in the morph info window is one handshape picture for the right hand and one handshape picture for the left hand. Once you press enter, the gloss looks wacky and handshapes aren't where they should be or aren't there at all. However, if you go back into the morph info window and select doubles of the handshapes instead of singles, then the gloss looks as it should once you press enter. So maybe SS thinks that the left and right hand have a starting handshape but no ending handshape when there are only single handshape pictures entered thus producing a gloss that looks wacky. But when you add doubles of the handshape (depending on whether or not start/end are the same) as long as you have two handshape pictures on the right and on the left hand, the gloss and final hold looks as it should. 

These are what we see now:
![screen shot 2018-09-26 at 7 00 02 pm](https://user-images.githubusercontent.com/38887034/46119143-960a3b00-c1be-11e8-86cf-fc369f4aafb6.png)

![screen shot 2018-09-26 at 7 00 12 pm](https://user-images.githubusercontent.com/38887034/46119149-9b678580-c1be-11e8-8bed-b8c9213f073a.png)

This is what I did as a work around/fix:
![screen shot 2018-09-26 at 6 59 38 pm](https://user-images.githubusercontent.com/38887034/46119161-aa4e3800-c1be-11e8-99dc-2290eb45de23.png)


![screen shot 2018-09-26 at 6 59 21 pm](https://user-images.githubusercontent.com/38887034/46119163-acb09200-c1be-11e8-9f70-08de058f4ed8.png)

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Handshape display and alignments were worked on and believe corrected.

Should no longer be an issue.

Closing.
