### ISSUE TITLE
low-priority bug - est. 1 hour

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#227]
Hi,

Hitting Carriage Return ought to. have the same effect as clicking on OK when the SAVE dialog box comes up, but it doesn't.

<img width="358" alt="screen shot 2018-06-07 at 5 50 49 pm" src="https://user-images.githubusercontent.com/13629122/41128254-82470aac-6a7b-11e8-9fcc-4f8dff40cd6f.png">

**Comment by cneidle** [comment]
This is not the only place where this should happen...

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Still exists in many places.  Leaving this open to address later.

**Comment by gregorydimitriadis** [comment]
This specific issue is fixed. If a similar issue occurs elsewhere another thread will be opened.
