### ISSUE TITLE
Things to look out for - est. 2 hours

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#228]
I am working on Cory 114 (all utterances involved) and I am noticing overlap within the non-manuals. This was a bug in the past because we weren't able to separate or delete the overlapping and now we can. I am just stating that we be on the look out for this as it can be easily overlooked. Also, on rare occasion when there is a gloss that starts with CL ex's CLEAR, CLASS, CLOSE, etc. the morp-info of these glosses marks them as classifiers when they are just lexical signs. This was also a bug in the past and once it was fixed, no one ever went back into the files to make the necessary changes. So it is important to keep an eye out on this as well. I am making and saving the necessary changes and hopefully they stay saved. I will keep you updated if I see otherwise. 

![screen shot 2018-06-08 at 11 12 47 am](https://user-images.githubusercontent.com/38887034/41173332-7ed460d2-6b24-11e8-9a37-96d700e312d7.png)

![screen shot 2018-06-08 at 2 03 16 pm](https://user-images.githubusercontent.com/38887034/41173402-be9f1162-6b24-11e8-9271-15618c4badb2.png)

![screen shot 2018-06-08 at 11 18 20 am](https://user-images.githubusercontent.com/38887034/41173340-810756ac-6b24-11e8-8132-c962ad912436.png)

**Comment by gregorydimitriadis** [comment]
@cneidle other than the comment i made in #216 just now about this - is there anything for me to edit/change for this paritcular issue?

**Comment by cneidle** [comment]
Assuming that this is resolved for going forward, this is mainly an issue of our having to search through the data and correct errors that have crept in because of this.  So, no, I don't think there is anything specific for you to do in relation to the above, beyond the more general fix.  Thanks.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

The overlapping of signs were worked on.  Believe this is no longer an issue.

Closiing.
