### ISSUE TITLE
Skip from 00:00:00;00 - 00:00:00;12

### ISSUE THREAD

**Issue by rklopez** [DCS-LCSR/SignStream3#23]
When using SS3, there is a skip from 00:00:00;00 - 00:00:00;12 in the beginning of every file.

**Comment by cneidle** [comment]
We have typically seen this only at the very beginning of video files.  And in particular, this problem does not occur with the same file, utterance, and videos when using versions of SignStream prior to this latest one being tested.  Rebecca:  Please correct me if I am wrong about this.  So it seems that something may have changed to create/worsen this problem.  fwiw.

**Comment by cneidle** [comment]
One speculation:  Rebecca mentioned that things were very slow, possibly suggesting a memory problem that could be interfering with the video playback...   Just a thought.  (Feel free to ignore, of course!)

**Comment by blazetravis** [comment]
This bug is fixed.
