### ISSUE TITLE
Windows associated with a collection should close when the collection is closed - est. 1 hour

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#234]
I opened the Morph-Phon window while working with one file.

I then open a different collection, causing the first one to clause.  But the Morph-Phon window remains open, with data from the now-closed file.  

This should not happen.

<img width="1166" alt="screen shot 2018-07-03 at 11 14 38 am" src="https://user-images.githubusercontent.com/13629122/42228724-a59c02e6-7eb2-11e8-8b42-5f6f9c0fe8f7.png">

<img width="1213" alt="screen shot 2018-07-03 at 11 15 10 am" src="https://user-images.githubusercontent.com/13629122/42228733-a9595dca-7eb2-11e8-9111-62100b307f94.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

corrected.

Closing.
