### ISSUE TITLE
Keyboard shortcut for "hide others" does not work [ est. ? ]

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#235]
The menu item works, but the listed keyboard shortcut does not.

<img width="183" alt="screen shot 2018-07-03 at 11 28 36 am" src="https://user-images.githubusercontent.com/13629122/42229532-afc7ea3a-7eb4-11e8-8c05-ff40fff67003.png">

If the menu is being displayed, the keyboard shortcut will highlight that item in the menu.

<img width="190" alt="screen shot 2018-07-03 at 11 29 16 am" src="https://user-images.githubusercontent.com/13629122/42229506-a061bfe4-7eb4-11e8-943a-0760dc4b6642.png">

But it will not actually 'hide others'.

FYI - obviously not a critical functionality.  It would be nice, but if it doesn't work, it should not be listed in the menu as a shortcut.

**Comment by gregorydimitriadis** [comment]
@cneidle tested this, but it appears to work for me. To confirm, this shortcut is "option+command+h" (lowercase h needed, no shift-press)

Also, I'm not sure we can disable the menu item showing up -- i.e. it is common to all mac osc apps.

**Comment by cneidle** [comment]
Ok great.  

No need to disable the menu item !

Thanks

**Comment by cneidle** [comment]
This is working now.
