### ISSUE TITLE
Cannot adjust start and end points of (nearly) adjacent non-manual items - reported error of overlap when there isn't - est. 3 hours

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#236]
Apologies if there is already a thread for this; I didn't find it.

In the case illustrated below, I cannot adjust the onset of raised brows to make it start one frame earlier, nor can I adjust the endpoint of the -raised event to make it one frame later, despite the fact that these two are one frame apart.  We have seen this before...

Thanks,
 Carol

![screen shot 2018-07-06 at 1 06 53 pm](https://user-images.githubusercontent.com/13629122/42391623-f9931764-811d-11e8-8b2f-3d396b609741.png)

![screen shot 2018-07-06 at 1 07 04 pm](https://user-images.githubusercontent.com/13629122/42391626-fd320c04-811d-11e8-8204-582ad1fcec6c.png)

**Comment by gregorydimitriadis** [comment]
@cneidle 

This appears to be similar to issue #18 and has the workaround I mentioned back then:
https://github.com/DCS-LCSR/SignStream3/issues/18#issuecomment-133460955

**Comment by gregorydimitriadis** [comment]
@cneidle 

Rather, this comment which references the above:
https://github.com/DCS-LCSR/SignStream3/issues/25#issuecomment-149915833

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Corrected.  Closing.
