### ISSUE TITLE
English Translations Deleted - est. 4 hours

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#237]
When trying to adjust the starting time of an utterance (U25 Jonathan 90) the English translation of this utterance was deleted. When trying to reproduce the issue, the translation moved outside of the data field then disappeared. 

![screen shot 2018-07-10 at 11 01 52 am](https://user-images.githubusercontent.com/38887034/42518963-f8625114-8430-11e8-86e8-98fbd887122b.png)
![screen shot 2018-07-10 at 11 02 36 am](https://user-images.githubusercontent.com/38887034/42518964-f9d84ce2-8430-11e8-8125-9e078c54a82f.png)
![screen shot 2018-07-10 at 11 03 43 am](https://user-images.githubusercontent.com/38887034/42518970-fb6c28a8-8430-11e8-81d1-bf24d2359ce9.png)

**Comment by gregorydimitriadis** [comment]
@bugspotter33 was this trying to update the utterance start time from the databaseView or the utteranceView ? (picture seems like from the utteranceView)

**Comment by bugspotter33** [comment]
This is from the utterance view

**Comment by gregorydimitriadis** [comment]
@bugspotter33 I think the only valid way to attempt to change the start time of an utterance would be from the database view. Operations from within the utterance view are meant to be limited to gloses/nonmanuals/etc

**Comment by cneidle** [comment]
This change WAS made from the DB view. The picture shows what was visible in the utterance view after that happened. 

Sorry for any confusion about that

**Comment by cneidle** [comment]
moved this up a bit higher in the priority list

**Comment by gregorydimitriadis** [comment]
@cneidle can I get the collection for this? Thanks.

**Comment by gregorydimitriadis** [comment]
@cneidle scratch that - I was able to reproduce with the 113 collection as well.

**Comment by travisnguyen** [comment]
This bug seems to have been resolved in version 3.1.2.
