### ISSUE TITLE
Can't enter in onsets/offsets - est. 5 hours

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#238]
I am working with new data, Ben Introduction file, and I started entering non-manual data but I can't enter any onsets/offsets. When right clicking on any given event, a drop down menu isn't displayed to give me onset/offset options. This is throughout the file. This seems to only be an issue when I have both temporal partitions 1 and 2 displayed at the same time. 

![screen shot 2018-07-12 at 3 47 13 pm](https://user-images.githubusercontent.com/38887034/42655700-e3f9f1a8-85ea-11e8-8682-4ee92b5c0af4.png)

**Comment by cneidle** [comment]
increasing priority a bit

**Comment by gregorydimitriadis** [comment]
@bugspotter33 @cneidle which collection is this? Possibly need a copy to test.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Phases for non-manuals were worked on.  Believe no longer an issue.

Closing.
