### ISSUE TITLE
Empty fields do not collapse automatically when switching between utterances - est. 3 hours

### ISSUE THREAD

**Issue by aimeeaylward** [DCS-LCSR/SignStream3#239]
I am currently working on the Cory 108 file, though I have noticed this in previous files, as well. When using the next utterance button to skip forward one utterance, fields that had events in the previous utterance remain open even though they do not contain events in the second utterance. 

In the second screenshot of utterance 9, the hm:shake and yes-no question fields still appear even though they are empty, whereas in the first screenshot of utterance 8 those fields were present but contained events. 

<img width="1280" alt="screen shot 2018-07-13 at 1 34 40 pm" src="https://user-images.githubusercontent.com/25349160/42706315-4dd5c840-86a4-11e8-9d6b-4226dc192a06.png">
<img width="1280" alt="screen shot 2018-07-13 at 1 34 20 pm" src="https://user-images.githubusercontent.com/25349160/42706317-4fbc3194-86a4-11e8-9de7-e9445f4ce9cc.png">

This does not happen consistently every time I switch utterances, even when the next utterance contains fewer fields than the previous one.

**Comment by aimeeaylward** [comment]
Also, it doesn't happen consistently with every field from the previous utterance that isn't present in the next utterance, i.e. the negative field in utterance 8 doesn't appear in utterance 9.

**Comment by travisnguyen** [comment]
This bug seems to be resolved in version 3.1.2.
