### ISSUE TITLE
Save timescale value in collection XML - est. 5 hours

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#240]
In addition to: 
* movie duration
* packet duration

We must also save...
* timescale

...in the collection to perform the proper conversion from signstream time to real time (seconds)

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Timescales will no longer be used.  But for backward compatibility, converted properly.

Closing.
