### ISSUE TITLE
Enhancement;  Include "translation" in list of fields that can be explicitly searched

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#241]
In the Search window, all the available fields seem to be listed, except the translation field.  It is still possible to include the translation field in what is searched (by selecting "Any" field and a specific value), and we can include this in future documentation as a work-around for not being able to search the translation field specifically, but it would be useful to add that field to the menu.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Search working with translations.

Closing.
