### ISSUE TITLE
Playing last utterance jumps back to first utterance - est. 10 hours

### ISSUE THREAD

**Issue by aimeeaylward** [DCS-LCSR/SignStream3#243]
I am working on Jonathan 94 and noticed a minor bug. When I'm on the last utterance and click "play utterance" (U72), it plays through the utterance fine, and then once it reaches the end the window jumps back to the first utterance, though the last one is still selected. 

Before selecting "play utterance":
<img width="1279" alt="screen shot 2018-07-26 at 6 24 52 pm" src="https://user-images.githubusercontent.com/25349160/43291931-614261a6-9101-11e8-9bf1-5b08dba91d11.png">

after the utterance plays: 
<img width="1280" alt="screen shot 2018-07-26 at 6 25 15 pm" src="https://user-images.githubusercontent.com/25349160/43291942-6b7b0966-9101-11e8-8195-72161a51e2d8.png">
<img width="1280" alt="screen shot 2018-07-26 at 6 25 24 pm" src="https://user-images.githubusercontent.com/25349160/43291946-6df8d7fe-9101-11e8-86ee-1c674c1b164b.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Playing utterances was reworked.  Should no longer be an issue.

Closing.
