### ISSUE TITLE
Quarantine script hangs - High Sierra

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#244]
Per email from Carol:

"
Still one problem with High Sierra though:  disable quarantine consistently hangs

I did succeed however in copying the command from that window directly into the terminal window, and that worked.

So there is a workaround.  But I suspect that anyone attempting to install in High Sierra will not succeed in getting the programs to run, as it stands. 
"

**Comment by gregorydimitriadis** [comment]
Note: also test newest OS

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
working on 10.14 and above.
Closing.
