### ISSUE TITLE
Video Time Sync error - est. 8 hours

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#245]
Per Doug:

"
Carol and Greg,

I just tested on version 3.0.1-rc1 of Signstream.

The video sync on utterance start/stop time change situation as shown to us from Carol today appears to happen with more than just the new video.  I see this same issue with the old video...

2012-02-09_0059-cam3-for-ss3.mp4

So in my mind, this is a code bug.

Doug

P.S. The original formatted video in h264 had laggy performance problems, but still seemed to work.  After converting that video to another format it seemed to perform better.  But in all 3 cases I tried, the issue of the utterance time change still happened.
"

**Comment by gregorydimitriadis** [comment]
@cneidle I don't recall exactly how to reproduce this issue - can you help?

**Comment by cneidle** [comment]
Working at the utterance level, I was attempting to set the start and end points of an utterance.  I selected, e.g., "U1" once I had created it, and then used the plus button to try to extend the endpoint until the utterance ended.  It went way beyond where the utterance really extended.  Using the minus button likewise did not allow me to get to the actual endpoint, and the plus and minus buttons gave different results for where the endpoint was.  Hope that's clear.

**Comment by gregorydimitriadis** [comment]
@cneidle Thanks, got it

**Comment by gregorydimitriadis** [comment]
@cneidle can I close this one?

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

The video player code was replaced.  Should no longer be an issue.

Closing.
