### ISSUE TITLE
Visualization: Order for display of fields

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#247]
Per Carol:
> WIth the new computer-generated fields, however, I’m finding that I am spending a lot of time for viewing each sentence in getting the fields arranged logically in relation to one another, and then the minute I go the another sentence (unless I scroll through directly from the main area of the utterance window), the field order reverts to the default.

> It would be great if there is either a way to set the default order differently, and/or to allow the user selection of order of fields to remain in place when the user goes to another utterance.

Per Doug:
> For your second option "allow the user selection of order of fields to remain"...this would be just for the current SS session, correct?  If one closed and reopened the collection, the default ordering would return.  OK?

Per Carol:
> If we could also set a reasonable default order for display of fields, then it would be sufficient to save the relative ordering chosen by the user only for the duration of the session.  (I could suggest such an ordering.)

**Comment by gregorydimitriadis** [comment]
Hi @cneidle this issue (and most of visualization) is mostly complete - if there is a default ordering you wish to see can you provide it here?

Currently the default ordering is:
* hp: tilt fr/bk
* comp: yaw
* hp: turn
* comp: pitch
* hp: titl side
* comp: roll
* eye brows
* comp: eye brows
* eye apert
* comp: eye apert
* (the rest of the fields)

**Comment by cneidle** [comment]
Hi Greg,

I am confused about why hm:    fields are not also included among the options here…
Why only the hp:   fields?

?

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
@cneidle 

Hi Carol -- I think I had put 'head position' for the SignStream fields corresponding to the yaw/pitch/roll of the visualization file. The other fields, including head movement and others, are possible to be ordered, but they are not included in the 'default' ordering of the fields. All the fields can be rearranged and then that ordering would be saved, but initially it would just be the visualiztion-related fields. We can change this easily, if you like.

**Comment by douglas-motto-at-rutgers** [comment]
Working on saving field ordering across sessions.
Removing the default ordering.

Keeping open.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_10_1855_c60918b0

Field ordering is now saved within the collection file.

If the default static order needs updating, create a new issue.

Doug
