### ISSUE TITLE
Visualization: click to change field sizes

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#248]
Need a user-level action mechanism to increase the size (in pixels, height) of the display of the visualization graphs.

Proposed: double click on field label - the field will expand to a predefined maximum size. Double click again to return to the default/minimum size. Exact size can be determined.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Done. Closing.
