### ISSUE TITLE
Cannot touch the ends of events to the start of onsets/events

### ISSUE THREAD

**Issue by rklopez** [DCS-LCSR/SignStream3#25]
This is similar to the old bug where offsets could not touch the beginnings of onsets and events. In the new SS3, offsets can be edited to touch the beginnings of events/onsets. 

Now if I try adding a new event and editing it to touch the beginning of an onset or another event, a warnig message appears. 

![screen shot 2015-08-06 at 7 18 10 pm](https://cloud.githubusercontent.com/assets/13489569/9125571/4e897038-3c70-11e5-9a87-ea0a761363fb.png)
![screen shot 2015-08-06 at 7 18 16 pm](https://cloud.githubusercontent.com/assets/13489569/9125570/4e8933a2-3c70-11e5-8326-08f645e7155d.png)

**Comment by rklopez** [comment]
I have found that offsets are unable to touch events and onsets in the new version of SS3, but only sometimes. I'm not sure why it works sometimes and not others.

**Comment by gregorydimitriadis** [comment]
This issue has the same cause and workaround as noted in bug #18 
The fix which went in place for event start/end times will work if you reset the frames of an existing event.

**Comment by blazetravis** [comment]
This bug is fixed.
