### ISSUE TITLE
Changing Start and End Times of Final Hold for Two-Handed Sign Changes Start and End Times of Non-Dominant Hand

### ISSUE THREAD

**Issue by travisnguyen** [DCS-LCSR/SignStream3#250]
Hi all,

I recently encountered an issue with changing the start and end times of final holds for two-handed signs. (This specific bug hasn't been described in past bugs about final holds and alignment issues, but I presume they could be related.)

Here's a description of the issue (using video 94 and U21 as an example):

1. A two-handed sign (here, HUG) is given a final hold as an additional element:

![screen shot 2019-02-22 at 4 08 47 pm](https://user-images.githubusercontent.com/4441077/53512356-8dc96b00-3a90-11e9-8cbb-a561136d98a3.png)

![screen shot 2019-02-22 at 4 09 20 pm](https://user-images.githubusercontent.com/4441077/53512367-93bf4c00-3a90-11e9-9087-477df2b2c617.png)

2. Editing the start time of the final hold causes the start and end times of the non-dominant hand to reset to where the start of the final hold is:

![screen shot 2019-02-22 at 4 09 51 pm](https://user-images.githubusercontent.com/4441077/53512473-e0a32280-3a90-11e9-8254-fce151883ea1.png)

3. Luckily, the start time of the annotation for the non-dominant hand can be reset:

![screen shot 2019-02-22 at 4 12 58 pm](https://user-images.githubusercontent.com/4441077/53512532-fdd7f100-3a90-11e9-899a-0f4025ace4e8.png)

4. Unfortunately, any further editing of the final hold (e.g., length on the timeline) causes the annotation for the non-dominant hand to extend from the start of the annotation of the non-dominant hand to the end time of the final hold (i.e., the annotation and the final hold overlap one another on the timeline):

![screen shot 2019-02-22 at 4 13 12 pm](https://user-images.githubusercontent.com/4441077/53512678-5f985b00-3a91-11e9-955b-1f0c18a61ff1.png)

![screen shot 2019-02-22 at 4 13 24 pm](https://user-images.githubusercontent.com/4441077/53512684-632be200-3a91-11e9-84eb-9f3cb84c3feb.png)

**Comment by gregorydimitriadis** [comment]
Hi @travisnguyen -- what version was this noticed in?

**Comment by travisnguyen** [comment]
> Hi @travisnguyen -- what version was this noticed in?

3.1.2.

**Comment by gregorydimitriadis** [comment]
@travisnguyen when you are in possession of v3.1.3, can you please check this one again? I just tested on this latest version and cannot reproduce it there.

**Comment by travisnguyen** [comment]
@gregorydimitriadis Just installed version 3.1.3, and it looks like the problem I described in the OP is resolved in the latest version.

**Comment by gregorydimitriadis** [comment]
@travisnguyen awesome - mind if I close this one?

**Comment by travisnguyen** [comment]
@gregorydimitriadis I can close it. Thanks.
