### ISSUE TITLE
Missing Selected Handshapes in Morph-Phon Info

### ISSUE THREAD

**Issue by travisnguyen** [DCS-LCSR/SignStream3#251]
Hi everyone,

I'm noticing a recurrent bug in the latest version of SignStream (3.1.3). When I right-click a gloss and select "Morph-Phon Info", sometimes none of the handshapes show up under "Selected Handshapes" (i.e., in the "Dominant Hand" and "Non-Dominant Hand" fields):

<img width="1418" alt="Screen Shot 2019-03-25 at 1 06 52 PM" src="https://user-images.githubusercontent.com/4441077/54939571-4a331700-4eff-11e9-8858-458b22996498.png">

If I close the Morph-Phon Info window and open it again, the handshapes appear:

<img width="1418" alt="Screen Shot 2019-03-25 at 1 07 34 PM" src="https://user-images.githubusercontent.com/4441077/54939614-633bc800-4eff-11e9-9103-72a37d07f784.png">

However, if I open the Morph-Phon Info window for a second gloss, close it, and then re-open the Morph-Phon Info window for the first gloss (in the example, fs-BOB), the handshapes disappear again.

For what it's worth, the handshapes are still visible at the utterance level, underneath the gloss of the sign and the line between its start and end points (see handshapes B, O, and B underneath the gloss fs-BOB):

<img width="1462" alt="Screen Shot 2019-03-25 at 1 07 44 PM" src="https://user-images.githubusercontent.com/4441077/54939827-ea893b80-4eff-11e9-9df8-6b9b3c363954.png">

This bug surfaces for at least half of the times I select to view the Morph-Phon info for any gloss, regardless of utterance or sign.

**Comment by gregorydimitriadis** [comment]
@travisnguyen I could reproduce this as well - possibly only for fingerspelled (fs-) glosses (?)

**Comment by travisnguyen** [comment]
@gregorydimitriadis It also affects lexical signs, although not as common (cf. TRIP in any utterance in the same video file). In my experience, the bug seems to show up most often with indexicals and fingerspelling.

**Comment by travisnguyen** [comment]
@gregorydimitriadis Here's a short (non-exhaustive) list of the glosses where I encounter the bug in file 0094:

U33 IX-loc:i
U34 #HS
U35 #HS
U36 IX-3p:i
U37 TRIP
U38 TRIP
U39 TRIP
U41 #VP
U42 ADDICTED
U42 (25) WHY
U43 IX-2p
U44 IX-1p
U45 #WHEN
U45 FUTURE
U46 DEPART
U46 IX-1p
U46 YES
U47 DEPART

**Comment by gregorydimitriadis** [comment]
Hi @travisnguyen - when you next get a chance can you email me the collection file for this one (0094)?

**Comment by travisnguyen** [comment]
@gregorydimitriadis Just sent the file.

**Comment by gregorydimitriadis** [comment]
completed for next release

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

working.

Closing.
