### ISSUE TITLE
Change in Video Playback Quality

### ISSUE THREAD

**Issue by travisnguyen** [DCS-LCSR/SignStream3#252]
Video playback quality seems to have changed with the latest migration of the basement lab computer to a new Mac. Videos show an increased rate of compression artifacts per frame as well as slightly unsmooth playback (compared to the old computer).

Here are screenshots of video frames containing the artifacts mentioned above (videos from 0094 for U56):

<img width="460" alt="Screen Shot 2019-03-26 at 5 30 34 PM" src="https://user-images.githubusercontent.com/4441077/55035085-66ad7d00-4fed-11e9-8fea-220b90d7dd8c.png">

<img width="460" alt="Screen Shot 2019-03-26 at 5 30 43 PM" src="https://user-images.githubusercontent.com/4441077/55035086-66ad7d00-4fed-11e9-8bc0-509fd6df8dd2.png">

Here are also some of the new computer's stats:

OS: macOS Mojave (Version 10.14.3)
Processor: 3.4 GHz Intel Core i5
Graphics: Radeon Pro 570 4096 MB

Currently encountering this issue while using SignStream version 3.1.3.

**Comment by gregorydimitriadis** [comment]
@travisnguyen for reference, does this same thing appear to occur in previous signstream versions?

**Comment by travisnguyen** [comment]
> @travisnguyen for reference, does this same thing appear to occur in previous signstream versions?

Just checked 3.1.1, 3.1.2, and 3.1.3.

3.1.2 has good playback quality, but 3.1.1 and 3.1.3 both have choppy playback quality.

**Comment by gregorydimitriadis** [comment]
Hi @travisnguyen @cneidle  - for testing on our side this is what we did:

We used the same MacOS version and opened Signstream 3.1.1, 3.1.2, and 3.1.3 all on the same collection file with the same video noted above. We took 10 screenshots of the video windows from each version of Signstream each at the same timestamp in the video and then compared the screenshots using an image diff tool (pixel by pixel comparison), and there was no difference. 

What is meant exactly by compression artifacts? If possible you can video record (e.g. quicktime) the differences in playback quality between 3.1.2 and 3.1.3?

**Comment by travisnguyen** [comment]
@gregorydimitriadis 

GitHub doesn't support .mov file types, so I'll send you examples from collection file 95, utterances 1, 2, and 3, for versions 3.1.1, 3.1.2, and 3.1.3 via e-mail.

As for video compression artifacts, I think it's best to explain with an image. Please see the images described as "Original image, with good color grade" and "Loss of edge clarity and tone 'fuzziness' in heavy JPEG compression" (on the right-hand side) of the following Wikipedia article:

https://en.wikipedia.org/wiki/Compression_artifact

**Comment by gregorydimitriadis** [comment]
@travisnguyen Sure, will wait for those emails. Thanks in advance.

**Comment by travisnguyen** [comment]
@gregorydimitriadis Done. The videos don't show any jarring examples of compression artifacts, but there is a slight difference in playback quality. Let me know if you have any questions.

**Comment by travisnguyen** [comment]
Also, let me know if you need the specs of the computer I'm using.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

The video player as completely replaced.  Assuming this is no longer an issue.

Closing.
