### ISSUE TITLE
Translations have ceased to be visible

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#254]
Translations were viewed perfectly through SignStream v. 3.1.3. However, in 3.1.4 and 3.2 (essentially the same new version), nothing appears in any of the translation fields. HELP !

Thanks.

**Comment by gregorydimitriadis** [comment]
@cneidle Looking into this now

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Translations are viewable.

Closing.
