### ISSUE TITLE
handshape selection palettes:  Left and Right hands are reversed!

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#256]
The handshapes should be restricted on the NON-DOMINANT hand (usually the left hand, since all of our signers are right-handed), but this is backwards!

<img width="936" alt="Screen Shot 2019-05-30 at 12 58 24 PM" src="https://user-images.githubusercontent.com/13629122/58649684-c15ba180-82da-11e9-9f8c-35879f0878a1.png">

**Comment by gregorydimitriadis** [comment]
Attempting to reproduce this - like so:
* click on a two-handed gloss, on the gloss1 line
* see 'dominant hand' selected (grayed out)
* select diff left/right hs
* open palette
* see the right hand populated with more handshapes (different than your picture)

* exit panels, then:
* click on the same two-handed gloss, on the gloss2 line
* see 'non-dominant hand' selected (grayed out)
* select diff left/right hs
* open palette
* see the left hand populated with more handshapes (same as your picture)

@cneidle - is it correct to say that whatever hand comes up as 'non-dominant' should be the one in the handshape palette window to have restricted options (which I take to mean the 'Unmarked' option from the dropdown)?

**Comment by cneidle** [comment]
Hi Greg,

I just tried to reproduce this and it was OK.

It’s possible that Justin entered the text on the gloss 2 line instead
of the gloss 1 line.

But we really need to discuss the issue of dominant vs. non-dominant hand.

Right now we can only annotate right-handed signers, and this is kind of embarrassing.

For a right-handed signer, the right hand is always the dominant hand.

For a 2-handed sign, the dominant (= right, in this case) hand should have the full
range of possible handshapes, and the non-dominant (= left, in this case) should
have the restricted set, by default.

For a 1-handed sign, produced with either hand, all handshape options should be
available.

The original plan was that the information about handedness, which is encoded
with the participant (or should be!), is what determines that mapping of 
dominant and non-dominant hand (to right and left, respectively, for right-handed
signers, and the reverse for left-handed signers).

So, for a right-handed signer, the top line of the 2-line gloss fields would correspond 
to the right hand, and the bottom to the left hand, whereas it would be the reverse
for lefties.

But the display in the handshape selection window would also be reversed:

[  RIGHT HAND  ]  = dominant hand for right-handed signers		[ LEFT HAND ] = non-dom for rh signers

[ RIGHT HAND ] = non-dominant hand for left-handed signers  		[ LEFT HAND ] = dom for lh signers

So in general, it’s preferable to use dominant and non-dominant
rather than right vs. left, where possible, because it is maximally 
general.

But for display, where the right and left hands need to be displayed as such,
then their linkage to dominant vs. non-dominant needs to be dependent on 
the handedness of the signer.

It may be easier to discuss this rather than trying to do it over email…

Thanks !!

Carol

**Comment by gregorydimitriadis** [comment]
@cneidle with the sign bank, we have glosses saved with 'dom' and 'nondom' hands. When transferring signs from the sign bank back into the MorphPhon window - will whatever is 'dom' in the sign bank correspond to the current participant's 'dom' hand? I.e. for a left-handed dominant person, the gloss in the sign bank having HandShapeA for DomHand and HandShapeB for NonDomHand - HandShapeA would be transferred to their left hand, which is dominant - is that right?

**Comment by cneidle** [comment]
Hi Greg,

When we modify the way SIgnStream deals with right- vs. left- hands
in relation to dominant vs. non-dominant, we will need to be in consultation
with Augustine to make sure that we are all on the same page about what
should happen and how things should correspond.

Currently all of our signers are right-handed.  So we have not yet dealt
in any way with issues related to left-handed signers.

For display purposes in the Sign Bank, we should, I believe, continue to 
display all examples with the dominant  hand to the left  and the non-dominant 
hand to the right.

This is to normalize the representations.

So, for example, for this sign:




we would want the handshapes displayed in the same positions for a left-handed signer,
even though the handshapes would be on the opposite hands.

Similarly for utterance display, there would be no change from what we have now:
The top line would be interpreted to be the dominant hand (right for right-handed
signers, left for left-handed signers); the bottom line would be interpreted to be the
non-dominant hand.

e.g.



So I am thinking that we can keep the adaptation to SignStream to deal with
left-handed signers as simple as possible.

The main difference would be in the interface for entry of handshapes, changing from
the top view to something like the bottom view below:








The basic Sign Bank display can remain as it is:



However, all references currently to RightHand and LeftHand should be changed to DomHand and NonDomHand — at the bottom of the above screenshot and wherever else these are represented.

Perhaps there are other issues that are eluding me.  We can perhaps discuss when we talk later?

Thanks!

best,
 Carol

**Comment by gregorydimitriadis** [comment]
@cneidle this all makes sense - I believe we are also mostly on the same page. In my opinion we shouldn't have to change anything about how the data is encoded in the sign bank file itself. The difference would be, as you said, how the search in the sign bank occurs with relation to the current participant and then sending those glosses back to the participant.

And indeed, let's discuss more later today.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Lots of changes converting right/left to dom/ndom.  displaying and using where appropriate.

Should re-evalutate the new version and create a new issue if further changes are still desired.

Closing this issue.
