### ISSUE TITLE
problem with opening selected gloss items - latest release version, new computer

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#257]
When a gloss item is selected and you double-click on it, nothing seems to happen. You can try multiple times and still nothing happens.  It is possible to get to the morph phon window by using the menu, but even that takes multiple tries before it will open.  Don't know why this should be happening.  It works ok (same version of SignStream, same file) on my laptop running Sierra (10.12.6).  

We are losing a lot of time with how many attempts it takes to get into the morph phon window... 

Have not yet tried this with non-manuals to see if we have the same problem.

**Comment by gregorydimitriadis** [comment]
@cneidle can you send the collection this was seen in? Is it multiple collections?

**Comment by cneidle** [comment]
Hi Greg,

This is the collection we were working on most recently.

But I do not believe the problem is specific to any given collection.

I was noticing this the other day also when we were working with different files.

This one uses the videos for file 96.

Thanks!
  Carol

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Does not appear to exist.

Assuming this is fixed.

Closing.
