### ISSUE TITLE
Association between a particular gloss and what is displayed in the morph-phon window.

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#258]
Here is a scenario:

You are looking at an annotated file.  You double-click on a gloss item and thereby (hopefully) open the morph-phon window.  You have a look.  Everything looks fine.  you don't change anything.  Or maybe you make a change.  You click on another gloss but you fail to close the morph-phon window before doing so.  You then notice that the morph-phon window is open and you click Enter.  What is in the morph-phon window gets applied to the newly selected item that it was never supposed to be associated with.  This is not a desirable behavior. 

Not sure what the best solution is.  Ideally you should be forced to close that window before you move on.  Perhaps a dialog box that appears when you attempt to click on another item -- that says  "please choose enter/save/cancel" (or whatever the actual text in the buttons at the bottom of that window say) -- before that gloss item can be deselected ??

thanks.

**Comment by douglas-motto-at-rutgers** [comment]
Still existing as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Needs requirements.

Leaving open.

**Comment by cneidle** [comment]
I suggested how it might work... 

>  Ideally you should be forced to close that window before you move on. Perhaps a dialog box that appears when you attempt to click on another item -- that says "please choose enter/save/cancel" (or whatever the actual text in the buttons at the bottom of that window say) -- before that gloss item can be deselected ??

**Comment by cneidle** [comment]
You should be able to view other things, but the gloss corresponding to a Morph-Phon window that is open should remain selected until that window is closed.

**Comment by douglas-motto-at-rutgers** [comment]
As of

SignStream4_4.1.0_pre_2021_05_28_2110_7a9f7c09
SignStream3_3.7.0_pre_2021_05_28_2112_68341ef3

must close morph-phon to refocus.

closing.
