### ISSUE TITLE
Incorrectly able to go-to start/end of Non-Manual event/entity even if none is selected

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#26]
Referring below to the buttons marked "|-" and "-|" before "Play Event" and "Play Entity" as  "GOTO start/end buttons"

Steps to reproduce:
-Click on a created non-manual event/entity
-Click away from it, so nothing is red
-Try to hit the GOTO buttons
-Green slider will still move to start/end of previously selected (and now currently UN-selected) event/entity, which is incorrect

This behavior is different than similar steps in the manual gloss fields.

**Comment by gregorydimitriadis** [comment]
Also applies to events on the Presentation layer (temporal partition line)

**Comment by hammondcl** [comment]
This is still occurring.

**Comment by hammondcl** [comment]
This is no longer occurring
