### ISSUE TITLE
Manual field toggles

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#264]
Requires completion of #261 and #263 first

Similar to how currently there is a nonmanual field selector (accessible by clicking the green plus sign on the utterance view) in this same panel we would have manual field selector. Include optional fields such as:
* sign type
* location
* ...anything else we can think of

**Comment by gregorydimitriadis** [comment]
@cneidle status of this one: I believe the code is complete for this issue - I have not yet tested it or integrated it into the main application. I will elevate this in priority accordingly

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Implemented some features.  Likely others are needed.

Closing this issue.  Open new for additional features.
