### ISSUE TITLE
Problem with arrow keys in Utterance window - introduced between 3.2.1 and 3.2.2

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#265]
In the Utterance window, the down arrow key still works correctly in 3.2.1 in moving from one utterance to the next in the left menu of utterances.  However, in 3.2.2, it does not do that.  When I first noticed this, it advanced from the first utterance to the last.  I closed the file and reopened it (after confirming that everything works fine in 3.2.1), and now the down arrow key seems to reduce the zoom.  Help!   Thanks.

The up arrow key has the same problem (affecting zoom rather than moving up in the utterance list by 1).

**Comment by cneidle** [comment]
This is very inconvenient - what would have changed between 3.2.1 and 3.2.2 that would have broken this?  Thanks!

**Comment by gregorydimitriadis** [comment]
@cneidle This was actually done intentionally. I had noticed that it was inconsistent whether the up arrows performs the zoom. The only situation where it did not was after clicking into the utterance view and/or between utterances on the list, so we changed it. We will change it back to the previous way.

**Comment by cneidle** [comment]
Hi Greg,

We definitely do not want to use the arrow keys for zoom
in the utterance window (and I don’t really care about using
them for zooming anywhere else either).

We want to use them for navigation in the menu on the left.

This is an old discussion we had, and a decision had been
made about the functionality of the arrow keys, which was
implemented long ago, as we had requested.

See #182 on github.

If you make changes like this, it would be good to check with me first,
preferably — or at least to notify me explicitly after the fact.

Thanks very much for changing it back :-)

**Comment by cneidle** [comment]
This still does not work in version 3.2.3.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

seems to work.

Closing.
