### ISSUE TITLE
some handshapes not showing up in Sign Bank search

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#266]
Handshapes are missing in this Sign Bank Search (3.2.2)

<img width="844" alt="Screen Shot 2019-06-23 at 10 00 04 AM" src="https://user-images.githubusercontent.com/13629122/59977337-ff787800-959d-11e9-9e9b-55a53390bee5.png">

**Comment by gregorydimitriadis** [comment]
@cneidle apparently this is due to the sign bank file itself not having the handshapes for this gloss

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Handshapes exist.

Closing.
