### ISSUE TITLE
still a problem keeping selected frame in the visual field, depending on level of zoom

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#267]
Subject header says it all.  Here's an example.  If I set the endpoint of the highlighted event to be the current frame, that frame dispappears from view:

<img width="1317" alt="Screen Shot 2019-06-23 at 2 55 53 PM" src="https://user-images.githubusercontent.com/13629122/59980680-47f85b80-95c7-11e9-9bf1-22c94ce9bf4e.png">

<img width="1412" alt="Screen Shot 2019-06-23 at 2 56 09 PM" src="https://user-images.githubusercontent.com/13629122/59980683-4e86d300-95c7-11e9-8ce5-453c87fc8d1e.png">

**Comment by douglas-motto-at-rutgers** [comment]
Need to check the latest version.  Was fixed..then broke...then fixed again.

Need to verify.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_07_1730_e1dd7d21

Fixed.

Closing.
