### ISSUE TITLE
Search window persisting 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#269]
If you conduct a search, and then open a new SignStream collection without closing the search window and then go to the search window, and you then change the search domain to be the file that is currently open, the program thinks the previous file is still open and threatens to close it.

<img width="1286" alt="Screen Shot 2019-06-24 at 7 27 45 PM" src="https://user-images.githubusercontent.com/13629122/60058412-48bbeb00-96b6-11e9-9041-4f96c508226a.png">

That is an example where I searched first in file 111 and then opened a different file.
The search would have happened in relation to file 111, but changing the search domain to the file that is now open has the above effect.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

changed so search does not cross collections, search window can only open in utterance view and search window can not remain open when returning to database view.  open/new collection closes search window.

Closing.

**Comment by cneidle** [comment]
It should remain possible to change the search domain, which would have the effect of
opening another file in which the search provided results.

Hopefully that functionality has not been removed.

**Comment by gregorydimitriadis** [comment]
@gregorydimitriadis estimate/investigate requirements

**Comment by gregorydimitriadis** [comment]
@gregorydimitriadis saved searches as an alternative? but priority is keeping search open across domains

**Comment by gregorydimitriadis** [comment]
This and #391 are now basically the same issue regarding switching search domains. Closing this one in favor of that one.
