### ISSUE TITLE
Just FYI - temp files seem to accumulate when you searches...

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#270]
<img width="613" alt="Screen Shot 2019-06-26 at 12 51 13 PM" src="https://user-images.githubusercontent.com/13629122/60199115-33a79f00-9811-11e9-9901-d3b7d1124336.png">

They seem to be mostly between 1 and 3 MB per file, so this will add up...

just FYI.

thanks.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

tmp files to not appear to generate when searching.

Closing.
