### ISSUE TITLE
Search window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#271]
1) When I search for the gloss "ANY", the seems to be interpreting this as a wildcard, rather than the string A + N + Y.

<img width="962" alt="Screen Shot 2019-07-04 at 1 15 45 PM" src="https://user-images.githubusercontent.com/13629122/60681640-0d5fb000-9e5e-11e9-8849-1f7ee7aae88a.png">

2)  Also a feature request:  It would be great if typing in the text box could automatically
toggle the setting from any to specific; rather than requiring multiple clicks
(i.e., first just typing in the box, instinctively; second changing 'any' to 'specific'; and third, returning to type in the text box).

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
ANY corrected and auto change to specific done.

Closing
