### ISSUE TITLE
small fix needed in Morph-Phon window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#272]
I can't believe I had not noticed this until now. It must be because there is no need to pay any attention to this, as it has not been functional.  However, in this screen shot:

<img width="542" alt="Screen Shot 2019-07-12 at 9 19 22 AM" src="https://user-images.githubusercontent.com/13629122/61131151-6a72eb80-a486-11e9-9e09-8b94a43f59a1.png">

it now says Dominant hand - and then there are radio buttons for dominant and non-dominant.
This is meaningless.

This was previously a choice between right and left hands: the radio buttons were for "L" and "R", which would serve to indicate whether the signer is right- or left-handed.  And this is important, even though all our signers have been right-handed until now.  This information is to come from the information that is entered for each participant.

I assume this was done when we wanted to avoid using the terms "right" and "left" in favor of "dominant" and "non-dominant".   But this is the one case where we need to keep "left" and "right".  

I'm sure this will be trivial to fix, but just wanted to let you know.

Thanks!

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

corrected.

Closing.
