### ISSUE TITLE
Enhancement:  Suggested default field order for the Visualization 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#273]
<img width="168" alt="Screen Shot 2019-07-17 at 9 55 00 AM" src="https://user-images.githubusercontent.com/13629122/61381437-0f236d80-a879-11e9-8c06-d62374cc3ede.png">

thanks !!

**Comment by gregorydimitriadis** [comment]
@cneidle do you want all of the fields listed here included in the ordering?

**Comment by cneidle** [comment]
Hi,

I was suggesting that that would be the default ordering for any fields that are selected.

I was not suggesting that all fields be displayed by default.

Is that what you were asking?

Or have I misunderstood the question?

Thanks!
 
Best,
 Carol

**Comment by gregorydimitriadis** [comment]
@cneidle ah, yes, we are on the same page. By 'include in the ordering' for those fields, I mean that *if* they are displayed in the utterance, then they will by default display in that order. Otherwise they will not display (as usual) - thanks

**Comment by douglas-motto-at-rutgers** [comment]
Working on saving field ordering across sessions.

Keeping open.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_10_1855_c60918b0

Field ordering is now saved within the collection file.

If the default static order needs updating, create a new issue.

Doug
