### ISSUE TITLE
Overlap/can't fix 

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#274]
In Deaf Speech Ben data Utterance 44 and 45 have an overlap and I'm not able to adjust the length of either utterances to undo the overlap. 

![Screen Shot 2019-07-19 at 4 45 57 PM](https://user-images.githubusercontent.com/38887034/61564737-1e571680-aa45-11e9-9de8-4793ab5386a9.png)

**Comment by cneidle** [comment]
Hi Indya,

I believe I can fix this for you.  Just let me know when the file is safe to edit :-)

Before changing the start or endpoint of U45 or U44, the items within the utterances
must be sure to be clear of those new start or endpoints. I can take care of this for you.
No problem.

Thanks,
 Carol


On Jul 19, 2019, at 4:49 PM, bugspotter33 <notifications@github.com<mailto:notifications@github.com>> wrote:


In Deaf Speech Ben data Utterance 44 and 45 have an overlap and I'm not able to adjust the length of either utterances to undo the overlap.

[Screen Shot 2019-07-19 at 4 45 57 PM]<https://user-images.githubusercontent.com/38887034/61564737-1e571680-aa45-11e9-9de8-4793ab5386a9.png>

**Comment by bugspotter33** [comment]
Okay I will be taking a break from working in about 30 minutes and it will
be available to be edited.

Indya

**Comment by cneidle** [comment]
all set :-)
