### ISSUE TITLE
SS unexpectedly quit

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#277]
I have been working on the Ben data and SS will close while I'm working. There isn't any way I can reproduce the issue I just know that I've been working on non manuals when it has happened. This is the 3rd time it has quit on me within the last week and a half.

**Comment by gregorydimitriadis** [comment]
Hi @bugspotter33 -- is this always with the same collection? Can you email the collection(s) this was experienced with?

**Comment by bugspotter33** [comment]
So far it has been with Ben Voice Life, Voice Identity and Deaf Speech.

**Comment by gregorydimitriadis** [comment]
@cneidle can I get a copy of this collection? Thanks

**Comment by bugspotter33** [comment]
I sent them to you yesterday

Indya

**Comment by bugspotter33** [comment]
New SS quit unexpectedly. Working on Julian B vocab file

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

hasn't happened in a long time.  

Closing.
