### ISSUE TITLE
Overlapping events in nonmanual field

### ISSUE THREAD

**Issue by rklopez** [DCS-LCSR/SignStream3#28]
In new UAT, events in the same field can overlap. This should not happen.

![screen shot 2015-08-18 at 11 33 27 am](https://cloud.githubusercontent.com/assets/13489569/9334494/1a4a3646-459d-11e5-9a8d-0bfedbd341c4.png)

**Comment by gregorydimitriadis** [comment]
What sequence of steps was taken to produce this?

**Comment by rklopez** [comment]
I opened the utterance, then went to add the new event and it started as overlapped. Normally, it won't allow you to do this. A warning message will appear if you try to add an event over another one.

**Comment by gregorydimitriadis** [comment]
This issue has the same cause and workaround as noted in bug #18 
The fix which went in place for event start/end times will work if you reset the frames of an existing event.

**Comment by blazetravis** [comment]
This bug is fixed.
