### ISSUE TITLE
Renumbering utterances

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#282]
Utterances get automatically numbered when created, plus-one after the highest existing "U#"

It's possible to delete an utterance, and then the numbers will be off next time you create an utterance.

There should be an automatic mechanism in the background which automatically renumbers utterances sequentially, on deletes and updates.

Alternatively, instead of automatically doing so, there could be a button on-screen which accomplishes the same effect manually.

**Comment by gregorydimitriadis** [comment]
@cneidle for this, how about a button on the menubar: under Macro Unit > Temporal Partition > Renumber Utterances

This would only apply to the selected temporal partition's utterances

**Comment by cneidle** [comment]
Hi Greg,

That sounds reasonable.

I would suggest a dialog box with a warning, describing exactly
what will happen and alerting that this action, if confirmed, cannot
be reversed.  Cancel should be the default in that dialog box,
with the user needing to explicitly click ‘confirm’.

Thanks!

Best,
 Carol

**Comment by douglas-motto-at-rutgers** [comment]
as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

done.

closing.
