### ISSUE TITLE
Search synonyms

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#283]
TBD: some way to query the web interface for synonyms for a gloss

**Comment by cneidle** [comment]
Note:  The Sign Bank on the DAI site now includes synonyms, which are searchable there. So this should be something that could be implemented within SignStream in the future.

**Comment by cneidle** [comment]
Can be incorporated with sign recognition - in terms of creating a way to copy a sign identifier from the DAI to SignStream.

**Comment by cneidle** [comment]
can delete this in favor of #593
