### ISSUE TITLE
problem with today's version - edit macro unit

### ISSUE THREAD

**Issue by careymballard** [DCS-LCSR/SignStream3#285]
HI Greg - This is Carol - with Carey.

When we create a new file, and go to attach a video file, by choosing "edit macro unit" it won't let us just do that:  
<img width="727" alt="Screen Shot 2019-11-08 at 3 07 59 PM" src="https://user-images.githubusercontent.com/51385350/68507401-d1888d00-0239-11ea-90a7-f2d8a69d3c9e.png">

**Comment by gregorydimitriadis** [comment]
Hello - @careymballard @cneidle 

This is odd. When you go to make a new collection (Command+N) it should bring you to the new panel, and a fresh macro unit window. Is this the point when the "Please select a macro unit" shows up? Or is it after doing new collection, and then manually clicking "edit macro unit" from the menubar?

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Believed fixed.

Closing.
