### ISSUE TITLE
problem entering location

### ISSUE THREAD

**Issue by careymballard** [DCS-LCSR/SignStream3#286]
Hi - We (carol and carey) are now trying to use the new version with a previously edited file.

In particular, we have been testing the new location functionality.

In one case, however, when we go into a gloss that has already been annotated with handshapes, to add the location information, we get an error message, as follows:

<img width="697" alt="Screen Shot 2019-11-08 at 3 50 00 PM" src="https://user-images.githubusercontent.com/51385350/68509764-b6208080-023f-11ea-94c3-a9f14fa475c7.png">

<img width="558" alt="Screen Shot 2019-11-08 at 3 50 07 PM" src="https://user-images.githubusercontent.com/51385350/68509765-b6208080-023f-11ea-9139-875754a84de5.png">

This is a complex example, as there are different signs on the two hands (and the dominant hand is also part of a compound):

<img width="482" alt="Screen Shot 2019-11-08 at 3 52 44 PM" src="https://user-images.githubusercontent.com/51385350/68509837-ecf69680-023f-11ea-99e0-84fdf9a8747c.png">

**Comment by gregorydimitriadis** [comment]
@careymballard @cneidle 

This is a bug, and will have a fix shortly.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_07_1730_e1dd7d21

Does not appear to still exist.

Closing.
