### ISSUE TITLE
Database view hide buttons for play entity

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#290]
In the Database view...if nothing is selected..."|-","-|","Play Entity" is always grayed out.

This was because there is no notion of 'entity' at the database level - so we should just hide those buttons in this view.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

An Entity is the same as an Event in the database view...of which the utterances are.

Leaving existing for now.

Closing.
