### ISSUE TITLE
Prevent closing last video window

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#292]
If you close the Video window...everything breaks.  Doesn't seem like there's a way to reopen the video.

Because of this, we should prevent the user from closing the (last) video panel. I say 'last' because there must be at least one video file open, but the user can close others (they can have up to 4 open at once).

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Video and Audio player was replaced.  Now it's safe to close all player windows.

Closing.
