### ISSUE TITLE
Field selector buttons broken

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#293]
In Utterance view...click "+" Field Selector.  Click checkbox for "Head"...Close window (not "Done" or "Cancel").  Reopen "+"...options still show "Head" checked"....Close window (not Dont/Cancel)....click the default fields selectors icon...Head does not show up.

P.S. After doing this...Cancel and Done buttons broke.....won't do anything after closing the window.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Fixed.

Closing.
