### ISSUE TITLE
Prevent attaching non-video files 

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#294]
Adding a video file that is NOT a real video file...does some weird things.

So due to this, we should prevent the user from choosing video files that are not within an approved list of file extensions (it is possible to limit the 'open-able' files on the file selector) to varieties of .mpeg, .mp4, etc

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Implemented.

Closing.
