### ISSUE TITLE
New collection utterance event bug

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#295]
Until anything is created inside an Utterance (or the utterance window is viewed and then returned to the database view)....the play icons "|-" and "-|" for an event in the database view seem not to work as expected.

New collection...create utterance...select utterance...click "|-" or "-|"

Steps to reproduce:
* new collection.
* make utterance.
* click on utterance.
* press "|-" or "-|" for Event
* error

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Utterance must be selected to play event/entity.

Buttons now work.

Closing.
