### ISSUE TITLE
Overlap when creating utterances

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#296]
To reproduce:
* create an utterance A
* start creating a second utterance after the end of A and drag it back before the beginning of A
* this will create an utterance before A
* you can do this repeatedly as well to get multiple overlapping utterances each of a single frame and hard to delete

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

now stops the second utterance from extending before the end of the first utterance.
fixed.

Closing.
