### ISSUE TITLE
Menubar items disabled until nonmanual event created

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#298]
To reproduce:
* make a fresh collection
* try to click the menubar options - but they are grayed out
* go to create an utterance, click inside, create a nonmanual event
* back back to database view
* click menubar - now the options are available

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Menu has been greatly improved.  

Closing for now.  If more improvement wanted, open new issue.
