### ISSUE TITLE
Frame numbers on utterance should be consistently displayed

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#299]
* db view
* select utterance via either temporal partition or segment tier lines.
* see start and end points values visible in the top
* go to utterance window by double clicking an utterance in the db view.
* go back to db view
* the line is still selected
* the values for start and end points aren't there.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

This has been fixed.

Closing.
