### ISSUE TITLE
Utterance Window - whitespace in gloss names

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#3]
All whitespace in gloss name entry should be treated as delimiters

TODO: verify this is the case in the XML representation of the data

**Comment by blazetravis** [comment]
How do I test this bug?

**Comment by kwasiopoku** [comment]
Add a new manual gloss
Set the start and end frame positions
Double click on the gloss name
verify that the name does not have a space after it.
(Ignore TODO: verify this is the case in the XML representation of the data )

**Comment by blazetravis** [comment]
This is fixed with newly added glosses.

**Comment by kwasiopoku** [comment]
I am closing this ticket on behalf of @blazetravis
