### ISSUE TITLE
CMD-w command doesn't always work

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#300]
Reproduced in a compiled application like so:
* open an existing collection
* try to close it via CMD-W -- doesn't work
* go into utterance view, then back again
* try again to close - this time it works

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

CMD-W works in db view, utterance view, and players.

Closing
