### ISSUE TITLE
Prevent user from attaching the same video twice

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#301]
Via the 'edit macro unit' window it is possible to add the same video twice. It will only have one video panel open, but two entries in the video file section will be filled with the same video. The app should prevent this from occurring.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

If two videos of the same location are added in the macro editor...only one is actually added to the database...and only one is added to the xml.

Closing.
