### ISSUE TITLE
New version of SIgnStream 3.2.5.1 with new videos - not going well

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#302]

**Comment by cneidle** [comment]
OK - I opened SignStream, attached a new video file (AMELIA_HENSLEY_VOCABULARY_WORDS_052418_TC_hb-for-ss3).  I set up two utterances, and renamed them both to "LIBRARIAN" and "PEA-BRAIN".  I could not save the file.  I went inside the first utterance and set the start and endpoint for the first two signs and connected them as 2 parts of a compound.  I saved using the keyboard shortcut, to the name that had been created by default.  I then double-clicked on the first, to go to the morph-phone window, and searched for the sign int he sign bank. The sign I wanted showed up in the list, but when I clicked on it, the Sign Bank window went blank, and I couldn't do anything in SignStream but Force-Quit.  

I restarted SignStream and re-opened the file.  This time I was able to get to view the item in the Sign Bank. And I was able to continue annotating...   I went to save it with a real filename, and I wanted to copy text from the name of the movie file to the "save as" menu, but "Paste" does not work.

**Comment by cneidle** [comment]
When I try to play the video in the sign bank, however, nothing happens.  A separate window opens up that shows a "play video" button and nothing else. No way to play the video.

THat window can't be closed either.

**Comment by cneidle** [comment]
There is a problem with overlap, which I believe you are aware of.
<img width="662" alt="Screen Shot 2019-12-27 at 12 17 19 PM" src="https://user-images.githubusercontent.com/13629122/71526063-e5985480-28a2-11ea-9a79-77c513d75a3b.png">

**Comment by cneidle** [comment]
(sorry - did not mean to close this!)

**Comment by gregorydimitriadis** [comment]
Hi @cneidle - working my way through this and other issues. One immediate question - what did you mean by 'renaming' the utterances? We had disabled that functionality (from the database view)

**Comment by gregorydimitriadis** [comment]
Inability to save the new collection likely related to #298

**Comment by gregorydimitriadis** [comment]
I think the sign bank window going blank was to due with loading/rendering all the handshape images in the loadout - not sure if this is correct, though.

**Comment by gregorydimitriadis** [comment]
Overlapping utterances is on #296 - in progress

**Comment by cneidle** [comment]
The problem persists…

Is there a solution?

Thanks!
   Carol

**Comment by gregorydimitriadis** [comment]
#306 will try to address the loading issue with the sign bank results

**Comment by gregorydimitriadis** [comment]
#317 for 'paste' not working

**Comment by gregorydimitriadis** [comment]
#159 for sign bank video bug

**Comment by gregorydimitriadis** [comment]
Closing this in favor of other opened issues to be worked on independtly
