### ISSUE TITLE
New version of SIgnStream 3.2.5.1 with new videos - entire video plays in a loop!

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#304]
Rather than having the playing of the video stop at the end of the video, it just continues playing right from the beginning again...

Is this a property of the video (i.e., is it set to loop for playback?) ?

or is this a problem with SignStream?

Thanks

**Comment by gregorydimitriadis** [comment]
@cneidle can you please send the collection and a note of which video(s) were used? Thanks

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

This does not or no longer exists.

Continuous Loop button.

Leaving open as a new feature request.

**Comment by cneidle** [comment]
Confused.  Is this fixed or not?

**Comment by gregorydimitriadis** [comment]
Fixed for next release
