### ISSUE TITLE
Problem with behavior of gloss labels that have not yet been time-aligned

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#306]
I am coding the DSP sentences.  I type in multiple glosses, e.g.

LEAVE-THERE     BOOK     THERE

I adjust the start and end points and I have gotten repeated errors  (cannot set end point outside of the sentence).  Usually when I try again, I don't get that message again. But what does happen is that even though I have not yet set times for any of those glosses, when I set the time for one gloss, it can overlap with and cover up the gloss to its right.  The desirable behavior would be for the program to automatically adjust the display of the next gloss so that is moved to the right of the endpoint that has just been set.

<img width="654" alt="Screen Shot 2019-12-29 at 11 41 04 AM" src="https://user-images.githubusercontent.com/13629122/71559856-df37e300-2a30-11ea-9555-9d1dc5ec165a.png">

<img width="751" alt="Screen Shot 2019-12-29 at 11 42 50 AM" src="https://user-images.githubusercontent.com/13629122/71559855-df37e300-2a30-11ea-96d1-cda472b3153d.png">

<img width="195" alt="Screen Shot 2019-12-29 at 11 43 23 AM" src="https://user-images.githubusercontent.com/13629122/71559854-df37e300-2a30-11ea-9095-d50abb27f02b.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_10_1855_c60918b0

Believe such alignment issues have been resolved.

Closing.  Open new ticket if still exiting.
