### ISSUE TITLE
Sign Bank Search:  Default selection for number of hands

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#307]
HI,  It would be very helpful if the default for searching the sign bank could be "either" rather than "1-handed".   Thanks!

**Comment by cneidle** [comment]
<img width="525" alt="Screen Shot 2019-12-29 at 11 55 32 AM" src="https://user-images.githubusercontent.com/13629122/71559988-31c5cf00-2a32-11ea-990c-9158d828b05a.png">

**Comment by gregorydimitriadis** [comment]
@cneidle currently what it does is take from the Morph Phon window - if that has 1-handed then 1-handed will transfer to the default to search in sign bank. Same if it's 2-handed. Do you want it to just default to 'either' regardless?

**Comment by cneidle** [comment]
Yes please :-)

No need for the user to code that before looking up the sign. 

Thanks!

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

done.

Closing.
