### ISSUE TITLE
Sign Bank Window:  Handshape search is not working

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#308]
This was reported in #207.  Still not working.

<img width="937" alt="Screen Shot 2019-12-29 at 12 25 28 PM" src="https://user-images.githubusercontent.com/13629122/71560330-9a16af80-2a36-11ea-9f5e-95b61e6c431d.png">

**Comment by gregorydimitriadis** [comment]
@cneidle I believe this is working - just that the checkbox for 'include handshapes in search' must be clicked for it to work.

I can see how it might be counter-intuitive though, to have the checkbox and the hs image selectors. Maybe we just get rid of the checkbox, and if there are any handshapes selected then include them in the search? Otherwise wildcard

**Comment by cneidle** [comment]
Ah!

It would be intuitive if the checkbox could be checked when the user
selects a handshape for one of those handshape search boxes.

(low priority relative to other things, obviously, but would be what
the use would expect)

Thanks,
 Carol

**Comment by cneidle** [comment]
Yes, that makes sense.  Use handshapes by default when there
are handshapes in one or more of those boxes.

Perhaps make the checkbox “do not include handshapes in search”
for the case where the handshapes appear (from having been entered
manually by the user before the search Sign Bank window is opened) ??

THANKS,
 Carol

**Comment by cneidle** [comment]
Can you have the "include handshapes" box checked when the user selects a handshape in conducting the search??   This has obviously not been done yet...  It makes it seem like the handshape search is not working.   FWIW.  

THANKS.

**Comment by gregorydimitriadis** [comment]
@cneidle will do

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Implemented.

Closing.
