### ISSUE TITLE
Location options

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#309]
I thought we had discussed this previously.
Could we please change the location positions to be

"initial"    "sole or medial"    "final" 

?

THANKS
<img width="551" alt="Screen Shot 2019-12-29 at 2 56 12 PM" src="https://user-images.githubusercontent.com/13629122/71561963-9c373900-2a4b-11ea-9e02-b13d1fac4a68.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

wording hanged.

Closing.
