### ISSUE TITLE
persistence of settings when opening a new blank collection

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#310]
Various settings remain in place when you go from viewing one collection to "open new blank collection" - including, for example, the zoom setting.  So, for example, if you have it way zoomed in, then this seems to change the scale of the zoom for the new file, with the default zoom corresponding to wherever the zoom level was.  More annoyingly, if you close the video window of the previous file before creating a new one, no video window appears. It's necessary to quit SignStream and restart.  (It's kind of nice, though, that new file opens with the gloss window having the same placement and sizing.  FWIW.)

**Comment by cneidle** [comment]
The problem of having no video window appear also occurs if you start by choosing to open a collection, then cancel, and choose to create a new blank collection.

**Comment by cneidle** [comment]
Example of the problem with zoom:  In collection being viewed, put zoom at max.  Open new blank collection.  The normal zoom is now associated with the maximum level, so it is impossible to increase the zoom level.


<img width="815" alt="Screen Shot 2019-12-30 at 8 27 09 AM" src="https://user-images.githubusercontent.com/13629122/71583998-b2420980-2ade-11ea-9743-acc637d428db.png">





<img width="745" alt="Screen Shot 2019-12-30 at 8 28 16 AM" src="https://user-images.githubusercontent.com/13629122/71583997-b1a97300-2ade-11ea-82cf-45b6dbf251a8.png">


<img width="678" alt="Screen Shot 2019-12-30 at 8 29 35 AM" src="https://user-images.githubusercontent.com/13629122/71583996-b1a97300-2ade-11ea-8b00-69718f6076ff.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_12_1056_cbb91a73

zoom and scroll are not remembers between collection opens (or new)

opening/closing a video can be done without restarting signstream

Closing.
