### ISSUE TITLE
low priority bug:  problem with  click-dragging to create new utterance when window auto-scrolls

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#311]
If you are click-dragging to create a new utterance and the event goes beyond the visible range of the window, the current mouse point jumps forward a huge amount.  Ideally when scrolling at a constant rate, the line should be drawn without this happening.  Just while I am noticing it...

**Comment by douglas-motto-at-rutgers** [comment]
Likely was fixed, but code changes reintroduced.

As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
still exists.

Keeping open.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_12_1056_cbb91a73

Scroll removed while creating utterance.  Need to add back in proper scroll.

Keeping open.

**Comment by gregorydimitriadis** [comment]
This is fixed in recent versions.
