### ISSUE TITLE
Unable to save file; seems to have been turned into a folder

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#313]
I was editing a file normally.  When I went to save it, I got an error message.

I was able to "save as" and a saw that a folder had been created from the original file.
<img width="887" alt="Screen Shot 2020-01-01 at 8 21 22 AM" src="https://user-images.githubusercontent.com/13629122/71641840-1b0cbb80-2c70-11ea-86c1-fd2ec7a6e8a4.png">

I wonder if it is because the original file ended in .ss3.ss3 (by mistake).

<img width="923" alt="Screen Shot 2020-01-01 at 8 25 52 AM" src="https://user-images.githubusercontent.com/13629122/71641866-73dc5400-2c70-11ea-9337-293fa03eb09b.png">

**Comment by gregorydimitriadis** [comment]
This is possible and likely - we will account for that case also (.ss3.s33 file extension)

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Appears fixed.

Closing.
