### ISSUE TITLE
Left and right arrow keys change function

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#314]
I have been working at the utterance level.  At some point, the left and right arrow keys cease to move the video to the preceding and following frame, but instead collapse and expand the temporal partition triangle.  I don't know what brings about this change, but restarting SignStream fixes it.

<img width="518" alt="Screen Shot 2020-01-01 at 12 34 32 PM" src="https://user-images.githubusercontent.com/13629122/71644242-29200380-2c93-11ea-9f8e-9750976609c0.png">

<img width="477" alt="Screen Shot 2020-01-01 at 12 34 26 PM" src="https://user-images.githubusercontent.com/13629122/71644243-29b89a00-2c93-11ea-9dae-f553660aa87b.png">

**Comment by douglas-motto-at-rutgers** [comment]
Still exist as of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17.

Leaving open.

**Comment by douglas-motto-at-rutgers** [comment]
When selecting the segment tier or temporal partition it happens.

**Comment by douglas-motto-at-rutgers** [comment]
This existed in 3.3.1 and 3.3.5.

**Comment by douglas-motto-at-rutgers** [comment]
Disabled the default functionality of arrow keys for the middle panel when focused.  Added the left/right to move the green bar.

As of

SignStream4_4.0.0_convergence_2021_05_12_1551_3d417a80

Closing.
