### ISSUE TITLE
Improve sign bank results load time

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#316]
Spinning off from #302 - but also a longstanding issue:

When the search results for the sign bank are particuarly large, some definite slowdown occurs when viewing this and opening words to look at the handshapes. Something should be done to improve the end-user experience of using this panel.

**Comment by gregorydimitriadis** [comment]
@cneidle quick question on this - do you prefer everything in the sign bank results set to be expanded already? Or the user must click to open each sign?

**Comment by cneidle** [comment]
HI GREG,

In either case, it would be great to have an option to expand
or contract all triangles !

It really all depends on the magnitude of the search results.
If there are relatively few results, it would be best to see thing
expanded initially.  For longer lists, it would be best to have
them contracted initially.

Would there be a way to have the display determined by the
number of results ??

THANKS,
 Carol

**Comment by gregorydimitriadis** [comment]
@cneidle we can do that

**Comment by cneidle** [comment]
Great!

Thanks,
 Carol

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

If more than one primary is in the result...the results are initially collapsed.
if only one primary is in the result...the results are initially expanded.

Closing.
