### ISSUE TITLE
Bug with playing sign bank video

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#318]
Spinning off from #302

"When I try to play the video in the sign bank, however, nothing happens. A separate window opens up that shows a "play video" button and nothing else. No way to play the video.

THat window can't be closed either."

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Issue still exists.  There is not handling if the internet is down, or the file unavailable on the server.

Keeping open.

**Comment by gregorydimitriadis** [comment]
Believe this is more or less the same issue as: https://github.com/DCS-LCSR/SignStream3/issues/474

Closing in favor of that one.
