### ISSUE TITLE
High priority: Problem with data entry from Sign Bank for parts of compounds

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#319]
Since our Sign Bank only includes individual signs, which in some cases constitute parts of compounds, when data is automatically entered from a part of a compound, only the information for that sign should be entered.

For example, for "AGENT"  -- which occurs in many compounds -- if it needs to be added, the gloss must be AGENT (not the compound).  Currently, the correct handshape and other information is copied, but the wrong gloss; the entry/variant should be listed as AGENT:

<img width="946" alt="Screen Shot 2020-01-03 at 7 20 01 AM" src="https://user-images.githubusercontent.com/13629122/71723175-a6658880-2df9-11ea-956c-2290cb7319e5.png">

<img width="557" alt="Screen Shot 2020-01-03 at 7 20 28 AM" src="https://user-images.githubusercontent.com/13629122/71723174-a6658880-2df9-11ea-93cc-2f75e5faf7ea.png">

**Comment by gregorydimitriadis** [comment]
@cneidle how can we programmatically determine that the variant should be "AGENT" here? What if a user made a search looking for the variant "*AGENT (MOTIVATE++AGENT" as you have selected, and wanted to insert that text as the variant? What should distinguish those cases?

If there is a distinguishing of those cases - is this just a matter of the sign bank file itself needing a variant for "AGENT" specifically?

**Comment by cneidle** [comment]
Hi Greg,

This is not an issue.

Compare the results of the following two searches, for the component parts of 
the compound LIBRARY + AGENT.

When the user searches for agent — requiring an exact match — this is what 
appears:

*AGENT (LIBRARY+AGENT)

The asterisk indicates that the occurrence is part of a compound with something
attached to the left.  The video this played (when the playing of videos works)
is the entire compound, as we do not have 1/2-compounds as viewable videos.

However, the handshapes and information that are listed are all correct for AGENT.

For the search for LIBRARY, this is reversed.

LIBRARY* (LIBRARY+AGENT)

HOWEVER, I notice that LIBRARY is listed as 2-handed rather than 1-handed !
See below.  Don’t know why this is happening… That is wrong.

The main problem, in any case, is that “insert all data” should only insert the text not 
in parentheses (and not including the asterisk) — as well as handshapes and 
properties of that particular sign (excluding what is in the rest of the compound in which
It appears).

Please let me know if this is not clear.

Thanks,
 Carol

PS. Note that the frames in the pictures do NOT correspond to the start and end frames;
Augustine explained to me that a somewhat random choice of frames is displayed, FWIW.

**Comment by gregorydimitriadis** [comment]
@cneidle I think I have a few issues/questions. 

1) There is in fact a record in the sign bank for {entry: AGENT, variant: AGENT} when you perform this search. Wouldn't the best thing to do be to select this variant for 'insert all data'?

2) I see it as (possibly?) a problem that when you select 'exact word' it forces the exact word on the entries (tree branches) but not the variants (tree leaves) - should this be so? Making exact word limit the variants as well might solve this problem, because if the search results only showed what matched entry/variant exactly, only AGENT would show up and remove all ambiguity.

Mostly I'm thinking of this as the method of inserting except what is within parentheses may be a unique situation in this instance, but later signs may include parentheses (or something to that nature, I'm mostly guessing because it's syntax-related and I'm somewhat ignorant of it)

P.S. I checked in the sign bank file for "LIBRARY* (LIBRARY+AGENT)" and it is marked as a two-handed sign.

**Comment by cneidle** [comment]
> On Jan 3, 2020, at 10:31 AM, Greg Dimitriadis <notifications@github.com> wrote:
> 
> @cneidle <https://github.com/cneidle> I think I have a few issues/questions.
> 
> There is in fact a record in the sign bank for {entry: AGENT, variant: AGENT} when you perform this search. Wouldn't the best thing to do be to select this variant for 'insert all data'?
> 
> 
Yes, it would.  But for some odd reason, I was not seeing that in the search results.

In other cases, we may have signs only in compounds and we may not have any isolated examples, so the problem remains for those cases.
> I see it as (possibly?) a problem that when you select 'exact word' it forces the exact word on the entries (tree branches) but not the variants (tree leaves) - should this be so?

Definitely not.  All searches should apply to all main entries and all entry/variants.  
> Making exact word limit the variants as well might solve this problem, because if the search results only showed what matched entry/variant exactly, only AGENT would show up and remove all ambiguity.
> 
> 
Yes - but as I just mentioned, we have cases where the part of the compound
does not exist independently in our data set.  (AGENT is a rare case where it
occurs in dozens of compounds.)
> Mostly I'm thinking of this as the method of inserting except what is within parentheses may be a unique situation in this instance, but later signs may include parentheses (or something to that nature, I'm mostly guessing because it's syntax-related and I'm somewhat ignorant of it)

NO.  We don’t want to insert anything that is in parentheses.
The parentheses in this case just gives contextual information
about where the actual gloss occurs.  It can be disregarded
for entering relevant information… 


> P.S. I checked in the sign bank file for "LIBRARY* (LIBRARY+AGENT)" and it is marked as a two-handed sign.
> 
> 

LIBRARY+AGENT is a compound.  It is made up of LIBRARY (1-handed) and AGENT (2-handed).
The entire compound uses both hands, but only because one of its parts is 2-handed.




Let me know if it would be helpful to discuss via Skype.

thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
@cneidle I see - if there are cases where there are only compounds containing the gloss we want, then this is a concern. However, I see a possible alternative. This would appear to be a use case for adding a local sign; i.e. if there happened to exist no entry/variant for AGENT/AGENT, so the user should add it as a local sign. 

Sorry for the misunderstanding with the parentheses - I was agreeing with you that the plan would be to not include the text within the parentheses. However, I'm not sure I see this as the best way to solve this particular problem (because of potential other cases involving parentheses used in a different context) as opposed to the local file way I proposed above.

**Comment by cneidle** [comment]
Hi,

The user has no way to do this, because there is no video the user can add.

Nor can the system automatically create an entry that includes a video, 
although the Sign Bank does create a place-holder entry, as you see below.

Here is an example of such a sign:  ASCEND
We only have that as part of a compound.  We do not have an independent
video for it.

**Comment by gregorydimitriadis** [comment]
@cneidle it is true that they would not be able to add the video, but they will add the data for the gloss variant as it should be. Isn't this the main use case for adding a local sign?

**Comment by cneidle** [comment]
Hi Greg,

We are not able to make use the local sign bank, for the reasons I mentioned.

And no single component of compounds is going to be used frequently enough
to make it worth trying something complicated.

HOWEVER, we really need, in general, to be able to enter information from signs that 
occur as components of compounds.  That is a general need, which use of a local Sign 
Bank does not address.  It should not be such a big deal, unless I am missing something… 

?

Perhaps it would be useful to discuss this?

Thanks !!

Best
  Carol

**Comment by gregorydimitriadis** [comment]
@cneidle I think my only concern was implementing the rule to ignore everything within parentheses. We can absolutely make it this way, and it will work - I just worried in the future it might come back to do something unexpected to a non-compound sign containing parentheses.

Will treat this issue as inserting compound signs to ignore the asterisk and everything inside parentheses (inclusively)

**Comment by cneidle** [comment]
Hi Greg,

Ok - we do not otherwise use parentheses in glosses, 
except at or near the beginning of a sign, to indicate things like
handshapes, e.g.,  “(S)MOSQUITO” and marked number of 
hands, e.g., “(1h)ADMIT"

Hopefully this can be distinguished from   *AGENT (LIBRARY+AGENT)

Basically we want to ignore everything that is a space followed by a string 
in parentheses.  In all cases where we want to ignore the material in 
parentheses, there is also no character immediately following the ),
In case that helps.

So let’s go with that option: to ignore the material in parentheses — assuming
that the distinction above can be implemented.  We also need to be 
pay attention to the properties of the component of the sign (e.g., LIBRARY is 1-handed).

SIgnStream only includes annotations of component parts, not properties
of compounds as a whole.  The compounds are formed only by linking
to signs using the SIgnSTream-provided linking mechanism in the 
utterance window, as you know.

THANKS !!

Best,
 Carol

**Comment by cneidle** [comment]
Entry of information from compounds should also be disallowed directly from the SIgnStream Sign Bank.

E.g., one should not be able to enter the information from TEACH+AGENT.

In SignStream, as you know, this cannot be represented as a single object...

TEACH and AGENT must be entered independently by the user, and then joined in the usual way.

THANKS.

**Comment by gregorydimitriadis** [comment]
@cneidle by information do you mean the entire sign bank entry, or just the 'data' at the bottom (sign type, passive base arm, etc)? From my understanding above, if someone selects "TEACH+AGENT" from the sign bank to insert, then it will insert the sign bank entry, but the 'entry/variant' field will just be "AGENT"

**Comment by cneidle** [comment]
Hi Greg,

It will be incorrect to insert ANYTHING from TEACH+AGENT.

The user should have to insert TEACH as an independent item 
and AGENT as an independent item and link the two.

Inserting any information from any compound, or from any compound part
(i.e., any item that includes an * at the beginning and/or the end) should
be disabled.

THANKS,
 Carol

**Comment by gregorydimitriadis** [comment]
@cneidle if that is the case - what is the original case described in this issue?

**Comment by cneidle** [comment]
From the things displayed in the Sign Bank, only individual signs should
be able to have their information entered in the Morph-Phon window.

If it would be easier to discuss this by Skype, I’m available :-)

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
@cneidle I believe I understand - we have the compound signs searchable in the sign bank, and we can select them and look at the information. But we will disable 'insert all data' for any compound sign which matches that format (asterisk at beginning and/or end)

Let me know if this is incorrect

**Comment by cneidle** [comment]
Yes - we should disable entry of information for any of the following, e.g.:

	TEACH+AGENT

	TEACH* (TEACH+AGENT)

	*AGENT (TEACH+AGENT)

Thanks !!

best,
 Carol

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

search entries from signbank with * can not be insert all data into morphphon window.

Closing.
