### ISSUE TITLE
Cory 111 Videos are Skipping

### ISSUE THREAD

**Issue by rklopez** [DCS-LCSR/SignStream3#32]
I just installed the new .jar. When I open the UAT app I go into an utterance (I have tried multiple ones). While trying to do nonmanuals I noticed that the video is skipping when I move forward. When I move backwards, it does not skip. This makes it basically impossible to do nonmanuals. I tried opening a different file (Cory 112) and that one seemed to work fine without skipping. I also unlinked and then relinked the video files, but this didn't seem to make much difference. 

For example, when I hit the arrow keys it goes from 00:00:19 to ...:21 ...:25 Instead of going  frame by frame as it should.

**Comment by kwasiopoku** [comment]
@rklopez is this similar to the bug #23 ?  I think this is something that has been around for a while and will be prioritized as part of a future sprint.

**Comment by rklopez** [comment]
No this is not. That was just the very beginning of the utterance, this new
bug is during the utterance, things will skip. Which makes nonmanuals
almost impossible.

Rebecca

**Comment by gregorydimitriadis** [comment]
Which file specifically was skipping like this? And when it's being used, is it just a single video file linked or more than one?

**Comment by gregorydimitriadis** [comment]
This bug will be moved to a later sprint due to the fact that the changes required to fix it will require many changes related to video processing in general. Augustine and I are currently looking into various potential ways to best to handle video going forward, and we will use this ticket as a placeholder for all of those ideas and issues which may arise.

**Comment by blazetravis** [comment]
Wow this one is a very big deal. This makes our lives so much easier. This bug is fixed!
