### ISSUE TITLE
High priority:  No video window opening!  No way to re-select

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#320]
I have opened one of the new SignStream DSP collections on a computer other than the one on which I had created it. No video opens.  There is no Macro Unit window at all, and no way to edit the Macro Unit to reselect the video...  All I see is this - note also that the data is also not visible at all, although there are annotations.

<img width="1371" alt="Screen Shot 2020-01-06 at 9 15 20 AM" src="https://user-images.githubusercontent.com/13629122/71823639-c26d6200-3065-11ea-9404-54d80ce61a61.png">

**Comment by gregorydimitriadis** [comment]
Hi @cneidle - not sure what this might be - can I get the collection file?

**Comment by cneidle** [comment]
Hi,

I discovered the source of this problem.

I had copied the SIgnStream folder into the dropbox folder and then onto the other computer.
That seems to have caused the problem (although I don’t know why).

When I copied it first onto a thumb drive and then onto the other computer, everything worked fine.

Sorry to have bothered you with this.

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
@cneidle Okay no worries - glad it is resolved!
