### ISSUE TITLE
High priority - Problems with missing handshapes from Sign Bank search display

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#321]
HI,

I know we had encountered this before, and I had though/hoped that this had been resolved. 
The problem seems to involve cases where the handshape label had a "/" in it.

Anyway, our colleagues at RIT have been using the Sign Bank for annotations, and they reported the following problems:

<img width="988" alt="Screen Shot 2020-01-06 at 11 04 09 AM" src="https://user-images.githubusercontent.com/13629122/71830410-acb36900-3074-11ea-832f-d3c3278830cf.png">

**Comment by gregorydimitriadis** [comment]
@cneidle I am looking in the sign bank for these sign and reproducing them also. It seems the issue is that the sign bank xml file itself does not contain the handshapes for these signs.

**Comment by cneidle** [comment]
This appears to be fixed (by Augustine).
