### ISSUE TITLE
version 3.2.5.2 - consistent problems with video 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#322]
<img width="1022" alt="Screen Shot 2020-01-12 at 7 22 48 PM" src="https://user-images.githubusercontent.com/13629122/72228050-2b2a7200-3571-11ea-8a55-a34a2c50d256.png">

**Comment by gregorydimitriadis** [comment]
@cneidle is this with every video/collection tried? Or a few in particular? Can I get a copy of those please?

**Comment by cneidle** [comment]
Hi Greg,

Hope you enjoyed your time away!


This happens a lot; does not depend on videos or collections.

However, we have been working with the DawnSignPress video collection.

It seems to happen when there is too much demand on the program (memory issue?)
E.g., when you have clicked a few times on things without waiting in between.
Closing the file and reopening resolves the problem.  


And for what it’s worth, the program crashing also is happening quite a lot,
For no apparent reason… 

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
@cneidle I see. Are these the 'converted' DSP videos?

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Video player code has been changed.  Sure this issue does not exist (although new issues might).

In any case, closing this issue.  Reopen if experiencing in new player code.
