### ISSUE TITLE
Incorrect information about sign type

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#323]
Working on JulB-vocab-050718_TC_hb and when glossing a sign that is a name sign, any sign glossed after this automatically gets labeled as a name sign in the lexical data window. See picture below:

![Screen Shot 2020-01-13 at 11 51 14 PM](https://user-images.githubusercontent.com/38887034/72324791-97d06a00-3660-11ea-815e-1e839756a069.png)

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

It appears that creating a named sign, does not automatically make future signs named.

Closing.
