### ISSUE TITLE
SignSTream has been crashing a lot

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#324]
for Indya, Carey, and me.   No obvious trigger... Also the video degrades frequently, and so SignStream needs to be restarted often for that reason...

**Comment by bugspotter33** [comment]
SS quit unexpectedly. Working on MM 053118 vocab file

**Comment by bugspotter33** [comment]
Videos in SS have been turning green or have a colored stripe across them after working in SS for a while. 

![Screen Shot 2020-01-19 at 9 40 03 PM](https://user-images.githubusercontent.com/38887034/72703420-60533900-3b0a-11ea-86f1-e72d49798b2f.png)

**Comment by bugspotter33** [comment]
SS quit unexpectedly with file JBPM 053118 vocab

**Comment by gregorydimitriadis** [comment]
@cneidle can I get a copy of the collections having issues?

**Comment by cneidle** [comment]
Sure - I will share the dropbox folder with those collections with you. 
Thus far we have been working on the collections in the VOCAB
subfolder.   I assume you already have the videos?  I will invite you 
to share the video folder as well, in case you need access to those.

And yes, they are the converted videos.

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
Are these the same videos I converted previously (into "...._VOCABULARY....-for-ss3.mp4" formats)?

**Comment by cneidle** [comment]
Yes, these are the videos you converted for us.

Thanks,
 Carol

**Comment by bugspotter33** [comment]
Working on file JBPM 053118 and this is what is happening after 5-10minutes of working in SS


![Screen Shot 2020-01-22 at 10 24 52 PM](https://user-images.githubusercontent.com/38887034/72965151-6ea28e80-3d70-11ea-967a-6ff5fe3376c1.png)

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe1

Video code was replaced.

Closing.  Open new issue if still experiencing.
