### ISSUE TITLE
Wrong data entries

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#325]
When searching for a sign in the signbank through SS and selecting INSERT ALL DATA so that the data is automatically entered into the Morph Info window, the handshape start and end doesn't always get updated for 1 handed signs that have a different start and end point. The example below shows the sign BETTER which has a different start and end handshape but the INSERT ALL DATA feature has the data saying the handshapes are the same. I changed it manually and saved it but just a heads up for any other one handed signs with different start and end handshapes make sure to double check the automatic signbank entries.

![Screen Shot 2020-01-22 at 11 41 44 PM](https://user-images.githubusercontent.com/38887034/72965554-7e6ea280-3d71-11ea-9902-4ede9e1cb504.png)

**Comment by bugspotter33** [comment]
This is also still an issue. Working on TG 012418


![Screen Shot 2020-03-11 at 5 59 07 PM](https://user-images.githubusercontent.com/38887034/76579419-666df200-6489-11ea-8dac-734ae08a1ab7.png)

**Comment by gregorydimitriadis** [comment]
@bugspotter33 noted, will check it

**Comment by bugspotter33** [comment]
This is still an issue. Working on Jul B 012418 sentences U11. The gloss is WHAT and the morp-info window displays the handshapes as different when they are the same

![Screen Shot 2020-04-03 at 5 22 42 PM](https://user-images.githubusercontent.com/38887034/78414554-72a12700-75d1-11ea-8a27-145fcb67a5ca.png)

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Diff start/end for 1&2 handedness appear to be inserted.

Closing.
