### ISSUE TITLE
Return of bug that I thought was resolved

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#326]
We are now working with the latest version of SignStream 3.2.5.2, and we are opening a collection that we had saved in the default location where SIgnSTream files are save -- the SS databases folder:

<img width="316" alt="Screen Shot 2020-02-12 at 8 07 22 AM" src="https://user-images.githubusercontent.com/13629122/74337674-bd8b8480-4d6e-11ea-9761-a6fc0cb2fe0d.png">

Double-clicking on the Utterance does NOT provide access to the Morph-phon window.

**Comment by cneidle** [comment]
We had also saved a copy of this file to the desktop, and that version also has the same issue.

We are working from Mac OS 10.4.6.  This problem  has occurred more often here than elsewhere.

**Comment by gregorydimitriadis** [comment]
@cneidle checking into it

**Comment by douglas-motto-at-rutgers** [comment]
Apparently there was some issue with the xml file.

Closing.
