### ISSUE TITLE
New Segment Tier does not zoom in and out the same as original

### ISSUE THREAD

**Issue by rklopez** [DCS-LCSR/SignStream3#33]
![screen shot 2015-09-09 at 2 23 37 pm](https://cloud.githubusercontent.com/assets/13489569/9770501/7d23bf5e-56fe-11e5-9816-6bf7231859fc.png)

As seen in this screenshot, the top segment is more zoomed in than the bottom. Moving the zoom button does not align them.

**Comment by gregorydimitriadis** [comment]
Is this indicated in the screenshot by the location of where the yellow background ends (and the more "brown" background begins) in Segment Tier 2 vs. in Segment 1 ?

**Comment by cneidle** [comment]
Yes - the entire utterance should be displayed within the same region.  Obviously it is also crucial that the temporal alignment indicator be in sync.  I didn't check that specifically when I was working briefly with Rebecca before, but I suspect that could be an issue here if one gets to the end of the sentence
sooner (horizontally speaking) in one sentence than the other...   THANKS.

**Comment by blazetravis** [comment]
The segments are now displayed in line, and the temporal alignment indicator adjusts both in sync. This bug is fixed.
