### ISSUE TITLE
Resize/scale frame images from sign bank for continuous images

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#331]
Search for a continuous sign in the sign bank and see the frame images are differerent sizes. SignStream can/should take those images and scale them so they are the same size.

**Comment by douglas-motto-at-rutgers** [comment]
As of ...

SignStream4_4.1.0_pre_2021_05_24_1819_794effbf
SignStream3_3.7.0_pre_2021_05_24_1815_897b87d3

told fixed.

Closing.
