### ISSUE TITLE
GIthub access

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#332]
Hi - This is Carol here with Tess and Rachel, and they logged in to github to report a bug, but are unable to see "issues".  In fact, I don't think they see "repositories" at all.  Could you please check to make sure they have full access?

**Comment by gregorydimitriadis** [comment]
I opened an incognito window (so no history/profile, etc) and I can view the ASL-DAI repo (it's public) and see the issues. The same should be the case for the new users - if they go to this link what do they see? https://github.com/DCS-LCSR/SignStream3/issues/332

**Comment by cneidle** [comment]
They are done working for today.  Will report back at the next opportunity.

Thanks,
 Carol

**Comment by douglas-motto-at-rutgers** [comment]
More than a year old. Closing.
