### ISSUE TITLE
beginning of video

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#333]

**Comment by cneidle** [comment]
I thought we had reported this before and that it had been fixed.  When we start a new collection, link in videos, and then, in database view, attempt to use the buttons just to the left of "play video" (in the upper right), they do not take you to the beginning or end of the video. The play video button itself IS working.

**Comment by cneidle** [comment]
Once some information has been entered into one of the utterances (e.g., a single gloss) and the file has been saved, those buttons work.  But you should not have to do that in order to use those buttons.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Toolbar was improved.  Current moves green bar, but video image may not change.  End "time" of video actually has no image.  Only start of every frame has an image and frames last X time.  So the end of the last frame actually has no image.

Will see about making image "blank" we no image can be displayed.  Keeping open.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_12_1056_cbb91a73

Image is blank at the end of the video.

Closing.
