### ISSUE TITLE
Data from signbank into morph-info window isn't being displayed

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#335]
I looked up the word BUY within SS and found the data in the sign bank. When I clicked INSERT ALL DATA nothing happens. The screen stays displayed and none of the handshape data is entered. Working on file DL-Sentences 121418 Utterance 13. 

![Screen Shot 2020-03-04 at 2 55 29 PM](https://user-images.githubusercontent.com/38887034/75931077-ed3b2300-5e28-11ea-8ba4-891b8885bcce.png)

**Comment by bugspotter33** [comment]
It looks like it is only specific towards signs with different left/right handshapes. For example, MEET and AGREE have the same handshapes on both hands, and there are no issues entering the data when clicking on INSER ALL DATA. However signs like BUY or TIME have different left/right handshapes, and the data can't be entered from the signbank automatically.

**Comment by bugspotter33** [comment]
Videos/picture displays aren't being shown from the signbank. Working on Ben 2.6 file. 



![Screen Shot 2020-11-14 at 6 41 46 PM](https://user-images.githubusercontent.com/38887034/99161677-6887f080-26a9-11eb-9bc8-ffbbf6f91c91.png)

**Comment by cneidle** [comment]
Hi Indya 

When this happens can you please check to see if you can access the DAI in your browser ?  And indicate that you have been able to do that in your bug report?  Sometimes the Rutgers server is temporarily inaccessible, and using this feature in signstream requires internet access to the DAI.  Thanks !!

**Comment by cneidle** [comment]
Hi Augustine,

I have confirmed that accessing the Sign Bank from within SignStream
is not working, despite the fact that the DAI is perfectly accessible via
internet.

The thumbnails and videos are not showing up.

Has something changed that would interfere with this access, as it
has been working fine?

Thanks,
 Carol

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

both issues seem to have been corrected.

Closing.
