### ISSUE TITLE
SS crashed

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#337]
Opened RB sentences 012518 to U4 and played the utterance twice and SS crashed. 

![Screen Shot 2020-04-23 at 5 11 27 PM](https://user-images.githubusercontent.com/38887034/80161587-bf02d580-8585-11ea-8758-c2e67b46028a.png)

**Comment by gregorydimitriadis** [comment]
@bugspotter33 the utterance was selected, and 'play event' was clicked twice in succession?

**Comment by bugspotter33** [comment]
Yes

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Video player code was redone.

Closing.  If issue still exist.  Open new issue.
