### ISSUE TITLE
v. 3.2.9.1 - problem attaching video

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#338]
I opened a previously annotated collection, and attempted to locate the video.
I was unable to save.  Clicking on the save button highlighted it but did nothing. 
Attempting to cancel, resulted in a dialog box again offering the option to save.
But attempting to save again did not work.

<img width="1353" alt="Screen Shot 2020-04-25 at 12 18 44 PM" src="https://user-images.githubusercontent.com/13629122/80284895-60596b00-86ef-11ea-813e-54ec539a8a5c.png">

<img width="1324" alt="Screen Shot 2020-04-25 at 12 19 03 PM" src="https://user-images.githubusercontent.com/13629122/80284898-63ecf200-86ef-11ea-88d8-1984aec73c82.png">

<img width="1352" alt="Screen Shot 2020-04-25 at 12 19 13 PM" src="https://user-images.githubusercontent.com/13629122/80284902-6c452d00-86ef-11ea-82cd-19e0b3c0c3ed.png">

**Comment by cneidle** [comment]
Although I did not manually save the file at all, when I reopened it, the video I had been attempting to attach opened up.  (This is probably in part related to the issue we have discussed before, where locating a video even without saving the collection, saves the located video -- although it should not.  But there is obviously more going on here... )

**Comment by gregorydimitriadis** [comment]
@cneidle do you have the original collection file (before the incidental saving)?

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Locate has been removed.  The video selection and validation process has been drastically changed.

Closing.  If any problem still exist.  Open in new issue.
