### ISSUE TITLE
Closing a file must close all associated windows 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#340]
I was testing the new version 3.2.9.1.   I had the handshape palettes open for one file.  I then went to open a new file.  The handshape palettes from the previous collection remained open!

I had reported a related issue previously, of a different window that remained open when one went from one file to the next...

<img width="1373" alt="Screen Shot 2020-05-03 at 2 31 47 PM" src="https://user-images.githubusercontent.com/13629122/80922413-f70ad500-8d4a-11ea-8cb4-0f61991365fe.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of  SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Only half fixed...will close the palette window when open a new...but when re-opening a morph-phone...it still exists.

Keeping open.

**Comment by gregorydimitriadis** [comment]
Will be fixed in versions:
3.7.0_pre_2021_05_25_1704_16f12c84
4.1.0_pre_2021_05_25_1708_694156a2
