### ISSUE TITLE
Display problem - for sign with same start and end handshape

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#341]
Start handshape not showing up in the Utterance window!

This from TH-sentences-062218_TB_hb

<img width="1021" alt="Screen Shot 2020-05-03 at 2 53 52 PM" src="https://user-images.githubusercontent.com/13629122/80922901-18b98b80-8d4e-11ea-9daf-699a74240dd5.png">

When I re-entered the lexical item, the missing handshape showed up properly...

<img width="1173" alt="Screen Shot 2020-05-03 at 2 54 07 PM" src="https://user-images.githubusercontent.com/13629122/80922894-0b040600-8d4e-11ea-9a8a-1c275301c740.png">

**Comment by cneidle** [comment]
Actually, i'm not completely sure of the problem.  There should actually be a different start handshape.  That one had disappeared from the Utterance window, and the sole remaining handshape was appearing as both start and end in the Morph-Phon window.  Not sure whether this had been mis-annotated (as having same start and end handshapes, but I doubt it, since it was probably entered from the Sign Bank) or whether the start handshape got lost and triggered that modification in the Morph-Phon window...

**Comment by gregorydimitriadis** [comment]
@cneidle is it reproducible? I tried getting the issue but I couldn't replicate it.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

The display problem does not appear to exist.

Closing.
