### ISSUE TITLE
For graphically imported fields - not showing up in the Field Spec List

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#342]
Hi -

I have imported a graphical file, and the fields are showing up in the Utterance Window, but 
not in the list of fields - so far as I can tell.  Am I missing something?

So for example, whereas I can hide one of those, I have no way to make it visible again...

<img width="1083" alt="Screen Shot 2020-05-03 at 4 58 13 PM" src="https://user-images.githubusercontent.com/13629122/80925645-891cd880-8d5f-11ea-8842-8031f937e3ee.png">

**Comment by gregorydimitriadis** [comment]
@cneidle the toggle for the graphical fields is on the yellow icon (second from the right)

**Comment by cneidle** [comment]
Beautiful!  Thank you.

I’ll add that to the User Guide  :-)

Thanks,
 Carol
