### ISSUE TITLE
Keyboard shortcut for Quitting SignStream 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#343]
does not do anything.

**Comment by cneidle** [comment]
Actually, trying to Quit SignStream from the menu also is not working for me.

Not sure if this is relevant, but I am working with a file that has a graph attached...  Will test now with other files.

**Comment by cneidle** [comment]
No, not having any luck quitting the program.  I can open a new file, which will close the one I was working with, but cannot directly quit SignStream.

**Comment by cneidle** [comment]
Quitting is working today.  Don't know what caused it to stop working yesterday...

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

command Q appears to work.

Closing.  If seen again.  Open new issue.
