### ISSUE TITLE
Unable to edit macro unit

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#344]
When I choose "Edit Macro Unit" from the menu, nothing happens at all.

If I click on "macro_unit_1" and then do that, I get the error message below:
<img width="787" alt="Screen Shot 2020-05-12 at 9 12 22 AM" src="https://user-images.githubusercontent.com/13629122/81695685-f0f2b380-9430-11ea-97a6-be444652985d.png">

**Comment by cneidle** [comment]
Seems to be happening just with this one file.  I opened the file, did a "save as".  The original file lets me open the macro unit.  The re-saved version (to which I had made no other changes) does not.  I tried re-saving another file, and the problem did not recur.

I can send you the file, if you like: Rachel_2012-01-27_sc51-gr.ss3

**Comment by gregorydimitriadis** [comment]
@cneidle indeed, please send the file - thanks in advance

**Comment by gregorydimitriadis** [comment]
@cneidle turns out what the issue with this was is related not to the save-as, but graph file logic. It was a bug in opening a collection with a graph file, and when it is unable to locate the graph file it threw the error. Easy fix, will be included in the next.

**Comment by cneidle** [comment]
Thanks!
  Carol

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

This issue has not been completely resolved.

Keeping open.

**Comment by douglas-motto-at-rutgers** [comment]
Correction...This issue appears completely resolved.
