### ISSUE TITLE
Search menus are not working properly

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#345]
In the search window, when a particular field is selected for searching, what should be displayed in the Values menus is a list of all values contained in the file, plus "any" and "specity".  That works properly for some, e.g.:

<img width="422" alt="Screen Shot 2020-05-13 at 9 30 46 AM" src="https://user-images.githubusercontent.com/13629122/81818946-aa6a8b00-94fc-11ea-8bb9-27a81bd39812.png">

These are also fine (although I think they are displaying all values, rather than only those contained in the search domain, but that's OK although not what was intended, nor what was implemented in SignStream 2.2.2):

Head movement: nod
Adverbial
Cheeks
Nose
Mouth
Eye gaze

Neck
Role shift
Body mvmt
Shoulders
All of the grammatical markings

But "**eye aperture**" and "**eye brows**" do not behave this way:

<img width="364" alt="Screen Shot 2020-05-13 at 9 34 13 AM" src="https://user-images.githubusercontent.com/13629122/81819167-f4ec0780-94fc-11ea-9734-302bd6ad1322.png">

<img width="383" alt="Screen Shot 2020-05-13 at 9 34 51 AM" src="https://user-images.githubusercontent.com/13629122/81819231-0af9c800-94fd-11ea-9762-199d83e66be6.png">

It would be great if you could fix this so that they behave like the others.  THANKS.

**Comment by gregorydimitriadis** [comment]
@cneidle suggested priority?

**Comment by cneidle** [comment]
How long do you think this would take to fix?  If it’s relatively quick, it would be great to take care of this...

Thanks!
  Carol

**Comment by gregorydimitriadis** [comment]
@cneidle Probably not long, so I'll look at it sooner rather than later.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Fixed.  Closing.
