### ISSUE TITLE
Strange Display for Compounds

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#347]
Working on file AJ 070518 sentences U38 and U39 and I was entering a compound for U39 and I noticed that the options to link two words together also included words from the previous utterance U38. For example HOME WORK is a compound but when trying to connect these two words I also have the option to connect the word VIBRATE from the previous utterance. 

![Screen Shot 2020-05-22 at 4 41 01 PM](https://user-images.githubusercontent.com/38887034/82716261-76edd600-9c4b-11ea-850e-a7c7a4376375.png)
 
![Screen Shot 2020-05-22 at 4 41 29 PM](https://user-images.githubusercontent.com/38887034/82716269-81a86b00-9c4b-11ea-8b90-5141e016df66.png)

Indya

**Comment by cneidle** [comment]
Thanks for reporting that. It should not be possible to create a compound by linking to something outside of the current utterance. 

>

**Comment by gregorydimitriadis** [comment]
Closing in favor of #356 which is broader.
