### ISSUE TITLE
Video Display/View occurrences isn't available

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#348]
Hi I am working in AJ sentences file 031918_TC_hb U2 gloss POSS-3p and I clicked on 'play sign video' and nothing was available and then I clicked 'view occurrences' and got a null message. This also occurred with U9 (2h)LOOK. 

![Screen Shot 2020-06-15 at 3 15 18 PM](https://user-images.githubusercontent.com/38887034/84713663-6239f080-af20-11ea-8063-bd31cfdfbb4c.png)

![Screen Shot 2020-06-15 at 3 15 09 PM](https://user-images.githubusercontent.com/38887034/84713664-649c4a80-af20-11ea-9f8e-6f130ae91fb6.png)

**Comment by cneidle** [comment]
Hi Indya

I believe this problem was fixed a little while ago. 

Are you still having this problem?

Thanks!
   Carol

**Comment by cneidle** [comment]
Sure enough - This is working from one of my laptops (as I reported to Doug a while ago), BUT not from the other one (running a slightly older Mac OS).  Don't know why that should be...

**Comment by cneidle** [comment]
Oops - I take that back!  I restarted my other computer, and it is now working OK on both computers.  It may be that I didn't wait long enough after clicking on "play video".  Sometimes the response from the Rutgers server can be extremely slow...   But it seems OK :-)    THANKS!

**Comment by bugspotter33** [comment]
Yes this is still an issue

**Comment by cneidle** [comment]
What exactly happens?   Have you tried waiting a couple of minutes after you click, in case there is slowness in the sever response?

Thanks!
  Carol

**Comment by bugspotter33** [comment]
Hi Carol,

I open up AJ sentences file 031918 click and open U2. click on the main
gloss POSS-3p, click search sign bank, click on POSS-3p:j and the button
'view occurrences 44' pops up. When I click on it a screen pops up that
says null and the other buttons don't work either. If I click on POSS-3p
the 'view occurrences 1' button works but the other buttons do not.

Indya

**Comment by cneidle** [comment]
Can we do a screen share via Skype so you can show me?

I am available now (with 5 minutes advance notice) or any time tomorrow. 

Thanks!
   Carol

**Comment by bugspotter33** [comment]
Hi Carol,

I haven't been able to use Skype in a few months. It doesn't allow me to
make or receive calls. I haven't tried opening it again since February so I
will try it again now.

Indya

**Comment by cneidle** [comment]
Have sent email with further details of problematic behavior in the Sign Bank.

**Comment by bugspotter33** [comment]
'Play sign video' and 'Play Composite Video' buttons aren't working. U2 file AH 080918 sentences main gloss KISS-FIST

![Screen Shot 2020-06-16 at 4 17 19 PM](https://user-images.githubusercontent.com/38887034/84837536-3cc6e880-afed-11ea-9bb8-15cf2142e976.png)

**Comment by bugspotter33** [comment]
I am noticing that many of the glosses are having this issue of missing video data when trying to enter/verify the sign information from the sign bank. Similar to the screenshot above, only the hand shapes are displayed but no video data is displayed. You can select view occurrences to see the video but the button doesn't always work and that's when the 'null' message is displayed.

**Comment by gregorydimitriadis** [comment]
@cneidle is this fully resolved now?

**Comment by cneidle** [comment]
Yes, I believe so - except for the bug reported separately for 2-handed alternating signs, which you are fixing :-).   Thanks!
