### ISSUE TITLE
SS isn't being displayed 

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#349]
When opening file AJ 031918 SS appears to be gray. If I click around to where I know the buttons should be , they work but everything is gray except for the main glosses. I've restarted SS and got the same results. Will try with a different file.

![Screen Shot 2020-06-16 at 6 32 10 PM](https://user-images.githubusercontent.com/38887034/84844868-3726ce00-b000-11ea-81d3-04ec72ebe2b4.png)

![Screen Shot 2020-06-16 at 6 31 57 PM](https://user-images.githubusercontent.com/38887034/84844876-40179f80-b000-11ea-94ba-8a1eb5223852.png)

**Comment by cneidle** [comment]
Hi Indya,

Can you please send a copy of that file to Greg via email?

I believe he has access to the videos; if not he can let me know.

Thanks!
  Carol

**Comment by cneidle** [comment]
Happening for me too, also with this file

<img width="1367" alt="Screen Shot 2020-06-20 at 5 05 41 PM" src="https://user-images.githubusercontent.com/13629122/85211551-61d29880-b318-11ea-8fe9-c88997199a33.png">

**Comment by gregorydimitriadis** [comment]
Checking. Seems to be a bug..tracking it down now.

**Comment by douglas-motto-at-rutgers** [comment]
Assuming fixed.

Closing.

**Comment by douglas-motto-at-rutgers** [comment]
if not...open new issue.
