### ISSUE TITLE
Cannot open separate Fields in New Segment Tier

### ISSUE THREAD

**Issue by rklopez** [DCS-LCSR/SignStream3#35]
Try to add nonmanuals to the second tier.
Open Fields button
Window shows fields selected in Segment 1
![screen shot 2015-09-09 at 2 26 00 pm](https://cloud.githubusercontent.com/assets/13489569/9770590/e9c4d4f4-56fe-11e5-982b-c5756a656558.png)
Press Cancel and nonmanuals from Segment 1 appear in Segment 2
![screen shot 2015-09-09 at 2 26 07 pm](https://cloud.githubusercontent.com/assets/13489569/9770597/f9f54a70-56fe-11e5-8c81-7453e6b57d78.png)

**Comment by blazetravis** [comment]
This bug is fixed.
