### ISSUE TITLE
Problem with "insert all data" from Sign Bank window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#350]
<img width="1511" alt="Screen Shot 2020-06-20 at 4 40 40 PM" src="https://user-images.githubusercontent.com/13629122/85211828-e7574800-b31a-11ea-8a57-e4890a50d102.png">

**Comment by kwasiopoku** [comment]
@gregorydimitriadis here are some additional information to help with debugging this issue.

My hypothesis was that the special characters "(2h)alt." in the label may be at the root of the issue reported above.  

Based on what Carol and I reviewed, the following sign occurrence from the signbank does not work when try to import all data within signstream

`<VARIANT ID='4330' DEFAULT_OCCURRENCE_ID='53799' OCCURRENCE_COUNT='1'>
       <LABEL>(2h)alt.SEARCH-FOR</LABEL>
       <OCCURRENCES>
       <OCCURRENCE ID='53799' >
        <OCCURRENCE_LABEL>(2h)alt.SEARCH-FOR</OCCURRENCE_LABEL>
        <D_START_HS>C</D_START_HS>
        <ND_START_HS>C</ND_START_HS>
        <D_END_HS>C</D_END_HS>
        <ND_END_HS>C</ND_END_HS>
        <IMAGES>
            <IMAGE ID='1' TYPE='START' URL='http://dai.cs.rutgers.edu//ss3thumbnails/sign_38514.png'/>
            <IMAGE ID='2' TYPE='END' URL='http://dai.cs.rutgers.edu//ss3thumbnails/last_sign_38514.png'/>
        </IMAGES>
        <VIDEOS>
            <VIDEO ID='1' TYPE='SIGN' URL='http://dai.cs.rutgers.edu//ss3front/sign_38514.mp4'/>
            <VIDEO ID='2' TYPE='UTTERANCE' URL='http://dai.cs.rutgers.edu//ss3front/2083.mp4'/>
        </VIDEOS>
        <COLLECTION>Cory_2013-6-27_sc107.xml</COLLECTION>
        <PARTICIPANT></PARTICIPANT>
        <SIGN_TYPE>LEXICAL</SIGN_TYPE>
        <TWO_HANDED>T</TWO_HANDED>
        <PASSIVE_BASE_ARM>F</PASSIVE_BASE_ARM>
        <MARKED_HANDS>T</MARKED_HANDS>
        <LEFT_RIGHT_HS>ALTERNATING</LEFT_RIGHT_HS>
        <START_END_HS>SAME</START_END_HS>
        <START_END_LEFT_HS/>
        <START_END_RIGHT_HS/>
       </OCCURRENCE>
       </OCCURRENCES>
      </VARIANT>`


However the follow sign occurrence which has similar sign label (along with special characters) seem to work when we import all data within signstream.

`<VARIANT ID='140' DEFAULT_OCCURRENCE_ID='309' OCCURRENCE_COUNT='2'>
       <LABEL>(2h)alt.USE-SIGN-LANGUAGE</LABEL>
       <OCCURRENCES>
       <OCCURRENCE ID='309' >
        <OCCURRENCE_LABEL>(2h)alt.USE-SIGN-LANGUAGE</OCCURRENCE_LABEL>
        <D_START_HS>S</D_START_HS>
        <ND_START_HS>S</ND_START_HS>
        <D_END_HS>crvd-5</D_END_HS>
        <ND_END_HS>crvd-5</ND_END_HS>
        <IMAGES>
            <IMAGE ID='1' TYPE='START' URL='http://dai.cs.rutgers.edu/asllvd/start_end_frames_img/Brady_2276.jpg'/>
        </IMAGES>
        <VIDEOS>
            <VIDEO ID='1' TYPE='SIGN' URL='http://dai.cs.rutgers.edu/asllvd//signs_mov_separ_signers/Brady_2276.mp4'/>
            <VIDEO ID='2' TYPE='SIGN' URL='http://dai.cs.rutgers.edu/asllvd//signs_mov/2276.mp4'/>
        </VIDEOS>
        <COLLECTION></COLLECTION>
        <PARTICIPANT></PARTICIPANT>
        <SIGN_TYPE>LEXICAL</SIGN_TYPE>
        <TWO_HANDED>T</TWO_HANDED>
        <PASSIVE_BASE_ARM>F</PASSIVE_BASE_ARM>
        <MARKED_HANDS>F</MARKED_HANDS>
        <LEFT_RIGHT_HS>SAME</LEFT_RIGHT_HS>
        <START_END_HS/>
        <START_END_LEFT_HS>DIFFERENT</START_END_LEFT_HS>
        <START_END_RIGHT_HS>DIFFERENT</START_END_RIGHT_HS>
       </OCCURRENCE>
       </OCCURRENCES>
      </VARIANT>
     </VARIANTS>`

**Comment by gregorydimitriadis** [comment]
Checking

**Comment by gregorydimitriadis** [comment]
It is a bug with alternating signs, it appears. Fixing now.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Alternating handshape data appear to insert from signbank correctly.

Closing.
