### ISSUE TITLE
Testing new version 3.3.0  7/16/20 - video window issue

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#351]
Closing the video window by using the red button in the upper left corner does not work

<img width="391" alt="Screen Shot 2020-07-16 at 7 52 42 PM" src="https://user-images.githubusercontent.com/13629122/87733472-ee4c6b80-c79d-11ea-8c68-f17bb7c6dfb2.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Closing the players work via the red button.

Closing.
