### ISSUE TITLE
Testing new version 3.3.0  7/16/20 - still not possible to search the sign bank for all sign types

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#352]
If a gloss had been marked as a loan sign, the sign bank is still inaccessible.

<img width="595" alt="Screen Shot 2020-07-16 at 7 54 36 PM" src="https://user-images.githubusercontent.com/13629122/87733597-41262300-c79e-11ea-8497-8e091b32c730.png">

Changing to a lexical sign does not make the sign bank available -- unless you save the entry, and then re-open the morph-phon window with it opening as a lexical sign.

<img width="600" alt="Screen Shot 2020-07-16 at 7 55 25 PM" src="https://user-images.githubusercontent.com/13629122/87733631-58fda700-c79e-11ea-8ff3-44836c8d671a.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of

SignStream4_4.1.0_pre_2021_05_28_2110_7a9f7c09
SignStream3_3.7.0_pre_2021_05_28_2112_68341ef3

Appears accessible all the time.
