### ISSUE TITLE
Back to database view from Utterance Window sometimes produces a blank screen

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#353]
This has happened to me 3 or 4 times today, from different files.
But it doesn't always happen.

I don't know what affects this, but... 

<img width="948" alt="Screen Shot 2020-07-17 at 3 55 09 PM" src="https://user-images.githubusercontent.com/13629122/87828799-b69bfd00-c84b-11ea-9916-3a0c2de3bb55.png">

<img width="1282" alt="Screen Shot 2020-07-17 at 4 22 56 PM" src="https://user-images.githubusercontent.com/13629122/87828807-bb60b100-c84b-11ea-819a-a5fc2e3ce833.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

This has likely been fixed.

Closing.
