### ISSUE TITLE
Showing wrong frame for start of utterance

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#354]
When you click on an utterance from the menu on the left of the Utterance window, SignStream should go to the first frame of that utterance.  Instead it consistently goes to a position of n+1 where n is the end frame of the previous utterance.

Example of what happens now when you click on an utterance

<img width="897" alt="Screen Shot 2020-07-27 at 7 32 13 PM" src="https://user-images.githubusercontent.com/13629122/88602194-4312a080-d040-11ea-8640-f6648bbbfe04.png">

What should be happening instead (the issue of the degradation of the video is a separate but very consistent problem today).

<img width="906" alt="Screen Shot 2020-07-27 at 7 32 28 PM" src="https://user-images.githubusercontent.com/13629122/88602250-63daf600-d040-11ea-88a6-a5a4125d4478.png">

**Comment by cneidle** [comment]
This remains a problem, just FYI.  This is what it looks like when you go to a specific utterance.  Thanks.
<img width="1365" alt="Screen Shot 2020-08-18 at 1 28 33 PM" src="https://user-images.githubusercontent.com/13629122/90545716-10e3f280-e157-11ea-9047-5a758fb92141.png">

**Comment by gregorydimitriadis** [comment]
@cneidle I can't seem to reproduce this one with the same collection and video. Is it still occurring in 3.1.1?

**Comment by cneidle** [comment]
I also was not able to reproduce it.

Will report back if/when this happens again.

Thanks!
  Carol

**Comment by cneidle** [comment]
This currently seems to be working fine :-)   Thanks.
