### ISSUE TITLE
Trouble with non-global annotators

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#355]
Hi,  There is a problem which occurs quite often, but not always.

I open a file that was annotated at RIT.  I attempt to add as annotator one that I have added locally.

Nothing occurs initially in the menu.

When I try. to add it, I get an error message.

<img width="1230" alt="Screen Shot 2020-07-31 at 1 42 27 PM" src="https://user-images.githubusercontent.com/13629122/89090921-f7c7fd00-d373-11ea-9089-646e756f6a5b.png">

<img width="787" alt="Screen Shot 2020-07-31 at 9 19 27 PM" src="https://user-images.githubusercontent.com/13629122/89090924-fbf41a80-d373-11ea-94d7-1cf7c1439112.png">

**Comment by cneidle** [comment]
There is still a very frequently occurring problem with the RIT files - with respect to opening a file, where one is forced to choose an annotator, and all previous annotators are rejected, forcing me to create a new annotator every time I open the file.

<img width="705" alt="Screen Shot 2020-11-21 at 4 27 32 PM" src="https://user-images.githubusercontent.com/13629122/99887980-ddfa4080-2c16-11eb-8aa8-24d17fb6cee3.png">

<img width="712" alt="Screen Shot 2020-11-21 at 4 27 43 PM" src="https://user-images.githubusercontent.com/13629122/99887983-e2265e00-2c16-11eb-89e4-5edda3b1d514.png">

<img width="692" alt="Screen Shot 2020-11-21 at 4 27 51 PM" src="https://user-images.githubusercontent.com/13629122/99887985-e6eb1200-2c16-11eb-955f-8606c5d1f2cb.png">

<img width="874" alt="Screen Shot 2020-11-21 at 4 27 59 PM" src="https://user-images.githubusercontent.com/13629122/99887988-ebafc600-2c16-11eb-918b-ec846c7755b0.png">

<img width="709" alt="Screen Shot 2020-11-21 at 4 28 14 PM" src="https://user-images.githubusercontent.com/13629122/99887996-f23e3d80-2c16-11eb-8d88-00d712a537b2.png">

<img width="327" alt="Screen Shot 2020-11-21 at 4 28 22 PM" src="https://user-images.githubusercontent.com/13629122/99887998-f79b8800-2c16-11eb-916f-4a587ebc47ea.png">

**Comment by cneidle** [comment]
Correction:  This seems to be not just per file.  As I open new files, I am having to create still more new annotators in order to be able to open them...
<img width="564" alt="Screen Shot 2020-11-21 at 4 38 38 PM" src="https://user-images.githubusercontent.com/13629122/99888119-28c88800-2c18-11eb-864d-87feb9b9517f.png">

**Comment by gregorydimitriadis** [comment]
@cneidle taking a look at this, but finding it difficult to reproduce this - a few questions:
* I assume you're running the latest SignStream version(?)
* I've been trying it with collections: PF13_V09_ANNOTATED and  PF17_V09_ANNOTATED - do you know if the error occurs for these?
* It seems the only way this error would occur is if: the collection file to be opened and your local annotators xml file have the exact same entry (ID + Label) but for some reason even though the app recognizes the entry, it ignores it and won't allow new additions - but of course as you note, it is for a multitude of labels, so it's likely not that.

Is there any collection it reliably occurs for?

**Comment by cneidle** [comment]
Running your latest version of SignStream (but this is not new to this version).
These are the files I was editing the other day, and this problem occurred at least about 85% of the time, probably more.  It was the very occasional file that did not give me this problem.

<img width="514" alt="Screen Shot 2020-11-25 at 10 43 29 AM" src="https://user-images.githubusercontent.com/13629122/100249980-2792a600-2f0b-11eb-9a6d-b5fd94a6bd36.png">

I just tested it with PF13_V09_ANNOTATED (quite an older version of that file; we have edited it since then), and the initial problem occurred - in that it was not possible to pick an existing annotator from the dropdown menu, but that it *did* let me choose from one of those that had been added recently.

<img width="446" alt="Screen Shot 2020-11-25 at 10 46 40 AM" src="https://user-images.githubusercontent.com/13629122/100250472-b43d6400-2f0b-11eb-9aa9-90c4f1d1c8fc.png">


<img width="365" alt="Screen Shot 2020-11-25 at 10 46 50 AM" src="https://user-images.githubusercontent.com/13629122/100250487-b7d0eb00-2f0b-11eb-9268-a8d4bab705f1.png">

**Comment by gregorydimitriadis** [comment]
As discussed via email, this is not reproducible. Leaving the issue open in case it recurs.

**Comment by cneidle** [comment]
FYI - I am having this problem again, systematically, with the RIT files (using v. 3.3.5).   SIGH.

**Comment by cneidle** [comment]
Example from today:

1) There is no way to select anything from the top drop-down menu - whereas available annotators, both global and local ought to be available there: 

<img width="892" alt="Screen Shot 2020-12-18 at 1 39 23 PM" src="https://user-images.githubusercontent.com/13629122/102649093-99d75e80-4136-11eb-9efd-d1f9e8720361.png">

I choose one, and get the error message below.

<img width="813" alt="Screen Shot 2020-12-18 at 1 39 28 PM" src="https://user-images.githubusercontent.com/13629122/102649089-993ec800-4136-11eb-8b3d-05a62f52cc2b.png">

<img width="831" alt="Screen Shot 2020-12-18 at 1 39 35 PM" src="https://user-images.githubusercontent.com/13629122/102649083-96dc6e00-4136-11eb-9dc9-55cb9be013bb.png">

I was then successful in adding the already locally defined "new".

**Comment by douglas-motto-at-rutgers** [comment]
Now works...but annotator and participant needs improvements.

**Comment by gregorydimitriadis** [comment]
This particular issue is resolved. Further participant/annotator issues are meant for #530
