### ISSUE TITLE
Compounds should not connect different utterances; Deleting part of a compound

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#356]
In the RIT file, I found a compound that linked the last gloss in one utterance and the first gloss in the next utterance.
My plan was to delete one part, resize the utterances, and put the second part in the same utterance as the first.
However, I discovered that deleting one part of the compound did not delete the compound link, and totally screwed up the file.  I reverted to the previous version of the file and de-linked the compound before deleting that part, and everything was fine.  SO, two things:  It should not be possible to link compounds across utterances; and deleting a part of a compound should also delete the link that connected that part.  Thanks!

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Utterance boundaries restrictions have been removed.  So non-issue now.

Closing.
