### ISSUE TITLE
High-priority fix needed:  general problems with visibility of final utterances in some files

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#357]
In the files from RIT, there is a systematic problem with many of them. There are two possible manifestations of this.  In both cases, nothing appears in the main portion of the Utterance Window from what has been transcribed in the final utterance, although in one case the annotations are visible in the menu on the left; in the other case,  nothing appears in the left-hand index either.  There are some cases where what appears can meet either of the previous descriptions.  Not clear what determines which way things appear.  In both cases, searching for annotated items in that last, invisible, utterance fails.

By the way, with these very long utterances, it is necessary to wait a long time after the file loads, for things to be processed and to appear in any reasonable way, but no amount of waiting fixes the final sentence.

Note also that the annotations are necessarily present in the file, since they appear correctly in the Excel file generated by the program that Iryna had developed for us, which allows us to extract the annotated glosses from SignStream files; see sample at the bottom below.

<img width="1352" alt="Screen Shot 2020-08-01 at 6 16 31 PM" src="https://user-images.githubusercontent.com/13629122/89124921-a1a8a600-d4a8-11ea-956a-f9902e1baca0.png">

<img width="1349" alt="Screen Shot 2020-08-01 at 6 26 49 PM" src="https://user-images.githubusercontent.com/13629122/89124925-a66d5a00-d4a8-11ea-9fb1-a06523991f33.png">

<img width="787" alt="Screen Shot 2020-08-01 at 8 02 14 PM" src="https://user-images.githubusercontent.com/13629122/89124926-a705f080-d4a8-11ea-9d07-2e6dcc10db6b.png">

<img width="863" alt="Screen Shot 2020-08-01 at 8 03 55 PM" src="https://user-images.githubusercontent.com/13629122/89124927-a79e8700-d4a8-11ea-8bfc-a2b945f50906.png">

---

<img width="1354" alt="Screen Shot 2020-08-01 at 4 31 38 PM" src="https://user-images.githubusercontent.com/13629122/89125070-ce10f200-d4a9-11ea-9ac2-eb7029510cd6.png">

<img width="396" alt="Screen Shot 2020-08-01 at 4 31 56 PM" src="https://user-images.githubusercontent.com/13629122/89125071-cea98880-d4a9-11ea-8ba2-53364b78396a.png">

**Comment by cneidle** [comment]
PS. For what it's worth, I tried adding an extra utterance to see if that would make the one that had previously been in final position visible, but that did not work, unfortunately.  See below.

I can send you a link to the Dropbox folders that contain these files and the corresponding videos, if that would be helpful.  Just let me know.   

Thanks very much!

<img width="1199" alt="Screen Shot 2020-08-02 at 11 32 11 AM" src="https://user-images.githubusercontent.com/13629122/89126476-f00f7200-d4b3-11ea-8ffe-3fa9db6ebd2b.png">

**Comment by cneidle** [comment]
I will share with you the Dropbox folder that contains the RIT SignStream files and the corresponding videos.
These are the ones that, at least as of yesterday, did not seem to have a problem with the final utterance:

<img width="775" alt="Screen Shot 2020-08-03 at 10 13 21 AM" src="https://user-images.githubusercontent.com/13629122/89192786-08929180-d573-11ea-83e1-20b7c0e4c0e0.png">


These are the ones that DID have a problem with the final utterance.  (I suggest that you disregard the ones in subfolders because they involve left-handed signing.  They have the same problems, but there are also other issues.)

<img width="791" alt="Screen Shot 2020-08-03 at 10 14 05 AM" src="https://user-images.githubusercontent.com/13629122/89192808-10eacc80-d573-11ea-8cde-25d8b95846d5.png">

**Comment by gregorydimitriadis** [comment]
@cneidle So, I unzipped the collection file (.ss3) and for U10 I see this:

```
<GLOSS-WINDOW-ITEM E="102372000" ID="47633301" LABEL="U10" S="97236000">
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="35"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="36"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="33"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="34"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="22"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="26"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="3"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="2"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="1"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="0"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="7"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="6"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="5"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="32"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="4"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="9"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="8"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="19"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="17"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="18"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="15"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="16"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="13"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="14"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="11"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="12"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="21"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="20"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="10"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="10000"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="10001"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="10501"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="1000"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="10502"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="2000"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="25000"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="25001"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="26000"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="26001"/>
<STATEMENT-FIELD ENTITY-IDS="" FIELD-ID="30000"/>
</GLOSS-WINDOW-ITEM>
```

Which basically shows that for U10, all the STATEMENT-FIELD objects are empty. The statement fields basically correspond to the manual and nonmanual fields on the view, and the entity's are the events in those fields. For comparison, a portion of U9 looks like:

```
<GLOSS-WINDOW-ITEM E="97216000" ID="47624289" LABEL="U9" S="86418000">
...
<STATEMENT-FIELD ENTITY-IDS="159174991725912216, 159174995874912280, 159174999537912343, 159175003467412372, 159175007659212395, 159175013584612428, 159175020159112465, 159175026597212486, 159175030777612547, 159175050502112832, 159175054266112927, 159175058384012942, 159175062447312983, 159175070645413056, 159175078758413073, 159175085490014280, 159175089277214317, 159175099745514472, 159175103608714569, 159175108338314612, 159175118371615916, 159175142057616058, 159175146529216084, 159175152422816261" FIELD-ID="10000"/>
<STATEMENT-FIELD ENTITY-IDS="159174997367112301, 159175001177512345, 159175009248712397, 159175016346412430, 159175028991012488, 159175033818812637, 159175052211412874, 159175060349312944, 159175064661012985, 159175081255213075, 159175087143614282, 159175092310614319, 159175105453214571, 159175109867614614, 159175150056416086, 159175154299416321" FIELD-ID="10001"/>

```

**Comment by gregorydimitriadis** [comment]
~~@cneidle in the first screenshot here, I see there was data for U10 - is it possible that go wiped somewhere in between? And if so, do you have a 'rollback' version of that collection available?~~

Edit: nevermind I see that was a different collection. I'm referring to V03 in my previous post.

**Comment by cneidle** [comment]
right.  V03 has 9 utterances.  thanks.

**Comment by gregorydimitriadis** [comment]
@cneidle so the same thing with collection "PF01_V02" -- I check out the xml for U8 and see it it empty.

**Comment by gregorydimitriadis** [comment]
@cneidle same with "PF15_V03" 

What is the script called that generated the excel file you posted? I think I have it, just not sure where..

**Comment by douglas-motto-at-rutgers** [comment]
Based on the discussion, assuming fixed.

Closing.
