### ISSUE TITLE
Priorities for bug fixes

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#358]
Hi Greg,

Priorities would be:

1)  Blank final utterance !!!!!

	[ There is no need for the specific RIT collection repair
	   I initially requested; that turned out to be part of this 
	   much more general problem, rather than an issue 
	  specific to that file.]

   This is a big problem, currently affecting about 25 files (50%).
   We need to resolve this before we can work with the RIT data.

2) Bug - adding participant deletes annotations

	That only occurred with one file (and for now, I can
	just leave it with no participant designated).

3) Flipping video tool - to be coordinated with Augustine.
     He made an attempt, but the result was not synchronized
     with the original video.  I don’t know whether he has an idea
     for fixing that problem…

4) Bug with adding an annotator upon opening the file.
      This occurs very generally.  Sometimes it rejects ASLLRP-BU,
      but it accepts RIT-BU; sometimes it is the reverse.  But this
      has so far not prevented me from being able to open any file.

THANK YOU !

**Comment by douglas-motto-at-rutgers** [comment]
Leaving open as a refactor of the participant and annotators.

**Comment by cneidle** [comment]
Not sure where this stands.  We should discuss.

**Comment by gregorydimitriadis** [comment]
Participant/Annotator discussions/refactor here: https://github.com/DCS-LCSR/SignStream3/issues/530

FLipping video spun off to: https://github.com/DCS-LCSR/SignStream3/issues/565
