### ISSUE TITLE
Renaming segment tier can delete the segment tier label

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#36]
Click on a segment tier in the tree structure of labels toward the left side of the SignStream window. Then attempt to rename it by clicking "Segment Tier" from the menu bar and then "Rename Segment Tier." Do not complete the operation though, and instead hit cancel. The label will be incorrectly deleted as a result of this - which is a bug. Correct result should be for nothing to occur.

**Comment by blazetravis** [comment]
This is still not fixed. The renaming, then canceling process still incorrectly deletes the tier.

**Comment by blazetravis** [comment]
Fixed.
