### ISSUE TITLE
PROBLEM - entry from Sign Bank 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#360]
Entering the information for THANK-YOU from the Sign Bank is not working. This is in PF20_01 from RIT

<img width="1462" alt="Screen Shot 2020-08-15 at 3 32 12 PM" src="https://user-images.githubusercontent.com/13629122/90320205-ebfc3f00-df0c-11ea-8b13-259ae0de23bd.png">

**Comment by gregorydimitriadis** [comment]
@cneidle @kwasiopoku I believe this to be an issue with the sign bank file. Currently there are 2 ways in the file to represent the same 'state' of an occurrence, with properties: two-handed and same left/right hs

See for instance the gloss Carol noted in this issue which has the issue - "THANK-YOU":
```
        <LEFT_RIGHT_HS/>
        <START_END_HS/>
        <START_END_LEFT_HS>SAME</START_END_LEFT_HS>
        <START_END_RIGHT_HS>SAME</START_END_RIGHT_HS>
```

But then the gloss "GOOD" (which works) has the same properties but is saved different in the file:
```
        <LEFT_RIGHT_HS>SAME</LEFT_RIGHT_HS>
        <START_END_HS>SAME</START_END_HS>
        <START_END_LEFT_HS/>
        <START_END_RIGHT_HS/>
```

The format for "GOOD" is what SignStream is currently expecting, and I believe what it should be. The values for START_END_LEFT_HS and START_END_RIGHT_HS shouldn't be used unless LEFT_RIGHT_HS is marked as "DIFFERENT" (or perhaps "ALTERNATING" as well, I'm not sure, Carol?)

**Comment by cneidle** [comment]
Hi Greg,

Sorry, I don't understand this.

These Sign Bank entries were generated from SignStream annotations…

It should not be possible to produce something in SignStream
that is not useable.

Thanks,
 Carol

**Comment by cneidle** [comment]
OOPS - on second thought:

I believe that a manual adjustment was made in the DAI
to this particular sign…

Will investigate with Augustine.

Thanks,
   Carol

**Comment by gregorydimitriadis** [comment]
@cneidle any update on this - is it signstream or sign bank related?

**Comment by cneidle** [comment]
I believe that this is a problem in the Sign Bank entry.  This is on Augustine's "to do" list, to fix prior to the next release of the Sign Bank.  I don't believe that this problem stems from SignStream, but if Augustine discovers anything that needs your attention, he will let you know :-).  Thanks very much.
