### ISSUE TITLE
Gloss/Video skipping

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#361]
The first sign in the first utterance of the video gets 'skipped' over when playing from the beginning. It is possible, however, to play the sign by itself normally. Could be either the gloss itself is skipping, or this is a xuggler/video issue. 

Collection: PF20_V01_ANNOTATED.ss3

Reported by Carol via email 2020-08-12

**Comment by gregorydimitriadis** [comment]
@cneidle was this issue noticed with any other than this collection?

**Comment by cneidle** [comment]
No - only this file.

Thanks,
 Carol

**Comment by cneidle** [comment]
Here is another file where that is happening:  PF15_V03.  SHAPE/STATUE does not play from the beginning, but does play when selected to play.


<img width="1289" alt="Screen Shot 2020-08-24 at 12 38 09 PM" src="https://user-images.githubusercontent.com/13629122/91072025-e38bbe80-e606-11ea-8f96-c775f86cf78f.png">

**Comment by cneidle** [comment]
here's another one:  PIG doesn't play when the video advances from the beginning...

<img width="1003" alt="Screen Shot 2020-08-24 at 9 57 47 PM" src="https://user-images.githubusercontent.com/13629122/91114052-fdec8900-e654-11ea-95e7-7a95ef78b8ae.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Video player was changed.  Assuming fixed.

Closing.   If still existing.  Reopen in new issue.
