### ISSUE TITLE
Gloss residue

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#362]
When deleting the contents of an utterance, the information of the type of gloss that was deleted gets left behind and I can't delete it from the utterance contents. See file MM sentences 062818 U25

![Screen Shot 2020-08-21 at 11 05 52 PM](https://user-images.githubusercontent.com/38887034/90950127-a4415000-e403-11ea-84c6-4a0bee2e2336.png)

![Screen Shot 2020-08-21 at 11 03 12 PM](https://user-images.githubusercontent.com/38887034/90950129-a9060400-e403-11ea-9503-30fef4c4b1ba.png)

**Comment by bugspotter33** [comment]
also in U27

**Comment by bugspotter33** [comment]
looks like all the 'out of sync' utterances in this file have this issue: U1, U3, U19, U25, U27, U37

**Comment by bugspotter33** [comment]
Same issue found in File MM sentences 051518 U13

**Comment by cneidle** [comment]
Hi

I have noticed this problem as well — very systematically.

HOWEVER, I believe it is a problem with screen redrawing.

The “lex” remnants do not show up when you leave the utterance and come back,
or when you close the file and reopen it.

Thanks,
   Carol

**Comment by douglas-motto-at-rutgers** [comment]
Need Greg to confirm that this was done properly.

**Comment by gregorydimitriadis** [comment]
Closing as fixed in recent versions.
