### ISSUE TITLE
RIT data - weirdness at the beginning of utterances

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#364]
Here's a new one:  IN PF20_V05, the utterance listing at the left is missing the first sign in two sentences!

<img width="761" alt="Screen Shot 2020-08-22 at 6 37 16 PM" src="https://user-images.githubusercontent.com/13629122/90966968-ba541c80-e4a6-11ea-9183-ee9c29d63837.png">

<img width="877" alt="Screen Shot 2020-08-22 at 6 36 02 PM" src="https://user-images.githubusercontent.com/13629122/90966972-bc1de000-e4a6-11ea-9f72-fa9078c45036.png">

**Comment by gregorydimitriadis** [comment]
@cneidle is this related to #361  (i.e. where the video skips over those glosses as well) or only related to the left-side-utterance-list?

**Comment by cneidle** [comment]
No problem with video skipping. Only affects left index 

>

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

This specific issue corrected...but similar ones may exist.

Open new issue if still existing.

Closed.
