### ISSUE TITLE
Deleting 2-handed signs

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#365]
When deleting a 2-handed sign, only the dominant hand information initially gets deleted.  The second hand needs to be subsequently selected and deleted.   (Both hands should be deleted when the 2-handed sign is deleted)

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Still exists.  Keeping open.

**Comment by cneidle** [comment]
Appears to be fixed.

**Comment by douglas-motto-at-rutgers** [comment]
Closing.
