### ISSUE TITLE
Compounds

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#367]
If it's trivial, would it be possible to display the "+" that gets inserted for a compound in red, e.g.?
So that it is easy to see when viewing the utterance whether there is a compound?

Also, when one element of a compound is deleted, the link to adjacent items should also be deleted.

Currently if we have

GLOSS1         GLOSS2+GLOSS3

 if GLOSS2 is deleted, GLOSS1 ends up linked to GLOSS 3:  GLOSS1 + GLOSS3.  That should not happen.  

Thanks!

**Comment by gregorydimitriadis** [comment]
@cneidle The red plus sign should be trivial. Deleting the residual plus sign after a gloss deletion - probably also trivial, but will let you know if not.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Appears fixed.

Closing.
