### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#369]
I know we have discussed this, but just wanted to make sure there's a record of the issue:  

Zoom is not working properly...  

Thanks!

**Comment by cneidle** [comment]
Zoom is WORSE, not better, with RIT files

I opened this one up, and can't even fit the first utterance in the window.  No way to reduce the zoom.

<img width="1356" alt="Screen Shot 2020-09-30 at 9 20 33 PM" src="https://user-images.githubusercontent.com/13629122/94755600-1130f980-0363-11eb-94bd-efda3be4403a.png">

**Comment by gregorydimitriadis** [comment]
@cneidle which file/video is this?

**Comment by cneidle** [comment]
The information is displayed in the title bar:  PF15_V02.

That would be

	PF15_V02.ss3
	P15_V02.mp4

Thanks,
 Carol

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Zoom code has been redone.

Closing.  If problems still exists, open new issue.
