### ISSUE TITLE
Delete Segment Tier functionality should display a warning

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#37]
There should be a verbal warning displayed in a dialog box during an attempt to delete a segment tier. Currently the result of clicking the menu bar option "Segment Tier" and then "Delete Segment Tier" will be to delete the label and row with no warning.

**Comment by blazetravis** [comment]
This is fixed. SignStream now displays a warning message.

**Comment by blazetravis** [comment]
Actually, this is not fixed. I tried this by opening up the Cory 107 file, clicking macro unit, clicking segment tier 1, clicking delete, and no message or warning popped up.

**Comment by blazetravis** [comment]
Fixed.
