### ISSUE TITLE
"Active utterance" problem with dialog

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#370]
We have not really been working much with dialogs, but we now have one we are finishing.

I opened both participant panes, and then closed one.  The remaining one does not seem to be recognized for things like 'plus utterance' or other commands that refer to the utterance (i.e., go to beginning or end of utterance).  Nothing happens when those buttons are clicked on.  I can provide the file by email; do you already have the 4 videos for 82?  Thanks!

<img width="1128" alt="Screen Shot 2020-09-24 at 5 49 46 PM" src="https://user-images.githubusercontent.com/13629122/94204006-729e2780-fe8e-11ea-98c2-1b802c5c70e1.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Still existing.  Keeping open.

**Comment by gregorydimitriadis** [comment]
Will be fixed in versions:
3.7.0_pre_2021_05_25_1704_16f12c84
4.1.0_pre_2021_05_25_1708_694156a2
