### ISSUE TITLE
Buttons for |- and -| utterance reference the PREVIOUS rather than the SELECTED utterance

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#372]
This so far affects only one file:  P20_V01_new

But it is very odd.  Play utterance does play the selected utterance.  But the buttons to to the start and end of the previous utterance.  Can send the file by email; the movie file is the one created by Jack yesterday.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_07_1730_e1dd7d21

I'm told this should no longer be a problem.

Closing
