### ISSUE TITLE
Can't open utterances

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#374]
Certain collections having issues when attempting to enter the utterance view.

**Comment by gregorydimitriadis** [comment]
Issue: handshape entities disappeared from the collection xml file.

Resolution: a recovery process on entering utterance view, which creates dummy ("?" value) handshapes for these entities, renames the gloss name to include "(recovered)" in the name, and shows the user a warning which explains this, so they can search through and fix them.

**Comment by douglas-motto-at-rutgers** [comment]
This is being rolled into the xml validator and possible automatic corrections.

**Comment by douglas-motto-at-rutgers** [comment]
https://github.com/DCS-LCSR/SignStream3/issues/467

**Comment by gregorydimitriadis** [comment]
This issue is no longer relevant, after validator issue.
