### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#375]
Not sure if this is a bug. I am working on Ben file 2.6 and I received the following message when opening SS:

![Screen Shot 2020-11-23 at 5 59 51 PM](https://user-images.githubusercontent.com/38887034/100190975-2da16c00-2ea4-11eb-9d58-521ecb65575e.png)

![Screen Shot 2020-11-24 at 10 24 26 PM](https://user-images.githubusercontent.com/38887034/100190981-3003c600-2ea4-11eb-99b3-24d8ce873e07.png)

Recovered signs are marked/glossed as "recoveredGLOSS" and then a question mark is entered instead of the handshape. I went in and changed the gloss and the handshapes. I just hadn't seen this message before.

**Comment by gregorydimitriadis** [comment]
@bugspotter33 Indeed, this was introduced for issue https://github.com/DCS-LCSR/SignStream3/issues/374

**Comment by douglas-motto-at-rutgers** [comment]
This is being rolled into the xml validator and possible automatic corrections.

**Comment by douglas-motto-at-rutgers** [comment]
See https://github.com/DCS-LCSR/SignStream3/issues/467

**Comment by douglas-motto-at-rutgers** [comment]
This is being rolled into the xml validator and possible automatic corrections.

**Comment by cneidle** [comment]
Something needs to be done about this.  Seems that it has been moved into a different ticket however.

**Comment by gregorydimitriadis** [comment]
Regarding #467 and these "recovered" glosses, in version 3.4.0 the validator will remove any previously "recovered" gloss's hand/shape information. Closing this issue in favor of the other.
