### ISSUE TITLE
No warning to save work if you accidentally choose "New blank collection" from the menu

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#376]
I was trying to open  a search window and accidentally released the mouse button for New Blank Collection.
This causes all unsaved work to be lost with no warning...  This should have the same warning message as if a new file were to be opened.  thanks.

**Comment by gregorydimitriadis** [comment]
@cneidle priority?

**Comment by cneidle** [comment]
Does not need to be done before the next release, unless it is a quick fix…

Thanks!
  Carol

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

The question is asked if it's believed dirty.  There may be situations that the dirty flag isn't set though.

Closing this issue as a matter of check dirt for "new" click.
