### ISSUE TITLE
Problem with changing sign type

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#377]
I was testing a new Sign Bank from Augustine.  He has added sign type information in many cases where it was lacking.  So I wanted to test adding a loan sign.  So I first changed it to a Classifier.  Then tried entering the information from the Sign Bank, which included Sign Type = loan.  So in principle, it should have changed it (back) to loan sign.  It appeared to do the Morph-Phon window, but it didn't register in the utterance window as such.  I thought it might just be that the screen had not refreshed to show the new information, but the CL marking in the utterance window persisted.  I suspect this may be related to other bugs we have reported about sign type information persisting when glosses are deleted... 

<img width="936" alt="Screen Shot 2020-12-03 at 7 02 10 PM" src="https://user-images.githubusercontent.com/13629122/101105062-9ec6da80-359a-11eb-8091-bed21be60447.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Works for dom, or non-dom, or two handed....so long as handedness does not change.

Changing 2handed from non-dom line to 1handed breaks.  (when switching types, this may be automatically change making it appear as a type problem.

Closing.  handed problem in another issue.
