### ISSUE TITLE
Jumping to specific utterance not working in new RIT files

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#379]
I got two new RIT files today, and double-clicking on a specific utterance from the database view does not work; it always opens up to the first utterance.  Likewise, clicking on a specific utterance from the menu at the left of the utterance window has no effect.  I tried opening these files with the previous version SignStream as well (3.3.4) and there is the same problem.  So perhaps there is something weird about these files, although I don't know why that should be.  Can share them with you...  thanks.
<img width="1108" alt="Screen Shot 2020-12-16 at 11 08 55 AM" src="https://user-images.githubusercontent.com/13629122/102374568-7aea9800-3f8f-11eb-91f8-3b42b0cd0cfb.png">

**Comment by cneidle** [comment]
FWIW, manipulating the Zoom seems to resolve this problem...

**Comment by cneidle** [comment]
Carey reported this same issue to me yesterday   Fortunately, I was able to tell him how to work around it.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

works for new collection files...unclear about older rit files.

Closing.   Open new if still existing.
