### ISSUE TITLE
Renaming segment tier also reorders it

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#38]
I opened an existing file (although was unable to re-associate a video file with it; that is a different issue).  

There was one previously establish segment tier, labeled "Segment 1".  I created a new segment tier, which appeared (incorrectly, as we have previously discussed, above it).  
<img width="271" alt="screen shot 2015-10-04 at 3 20 53 pm" src="https://cloud.githubusercontent.com/assets/13629122/10269699/48786b6c-6aac-11e5-987c-8cec2d3757d7.png">
However, when I renamed that first segment tier, it appeared, with its new name, above the other one.
<img width="414" alt="screen shot 2015-10-04 at 3 21 09 pm" src="https://cloud.githubusercontent.com/assets/13629122/10269700/49cf4dbe-6aac-11e5-99f5-08fa12118cfc.png">

**Comment by blazetravis** [comment]
This bug is fixed!
