### ISSUE TITLE
Jack - clicking on search results should open utterance window, not go to database view

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#382]
f<img width="1035" alt="Screen Shot 2020-12-25 at 12 01 18 PM" src="https://user-images.githubusercontent.com/13629122/103139353-48385200-46a9-11eb-87f9-0c661ed277ec.png">

Should open the relevant utterance, but instead goes to database view and does not display the actual utterance unless the Zoom is set appropriately:

<img width="1031" alt="Screen Shot 2020-12-25 at 12 01 28 PM" src="https://user-images.githubusercontent.com/13629122/103139355-4e2e3300-46a9-11eb-857f-2c92bdb86ade.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_07_1730_e1dd7d21

Click on search result goes to result in utterance.

Closing.
