### ISSUE TITLE
JACK - problem entering text data in the gloss field

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#383]
I tried entering some text.
Then I wanted to add a gloss before the first aligned gloss.
But option-clicking in that region would only show the text later on in the sentence that had not yet been aligned.

<img width="1006" alt="Screen Shot 2020-12-30 at 1 48 10 PM" src="https://user-images.githubusercontent.com/13629122/103374634-13ac0800-4aa6-11eb-8c11-74a8bef36dc8.png">

<img width="1013" alt="Screen Shot 2020-12-30 at 1 48 22 PM" src="https://user-images.githubusercontent.com/13629122/103374637-1870bc00-4aa6-11eb-8659-a747a4384445.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Creates new Gloss.

Closing.
