### ISSUE TITLE
JACK - ZOOM range insufficient

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#384]
can't zoom enough to see handshapes

<img width="1492" alt="Screen Shot 2020-12-30 at 1 53 34 PM" src="https://user-images.githubusercontent.com/13629122/103374827-887f4200-4aa6-11eb-98a9-731fd183f4fd.png">

**Comment by cneidle** [comment]
THIS IS NOW the maximum zoom allowed.  I cannot see start and end handshapes for this 2-frame gloss

<img width="84" alt="Screen Shot 2021-01-23 at 3 10 30 PM" src="https://user-images.githubusercontent.com/13629122/105612927-45ef1380-5d8d-11eb-9ace-f3828a323209.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Increased, but perhaps not enough.

Keeping open.

**Comment by cneidle** [comment]
This is still a problem with 11.3.1, 

<img width="257" alt="Screen Shot 2021-05-25 at 12 44 34 PM" src="https://user-images.githubusercontent.com/13629122/119536578-3c83b100-bd57-11eb-98ac-c9b48e43f3a7.png">

It is impossible to view handshapes at all for shorter signs.  This is not a problem in 3.3.5.

<img width="854" alt="Screen Shot 2021-05-25 at 12 43 26 PM" src="https://user-images.githubusercontent.com/13629122/119536437-16f6a780-bd57-11eb-8f3b-f4441ac4ae81.png">

<img width="1176" alt="Screen Shot 2021-05-25 at 12 38 25 PM" src="https://user-images.githubusercontent.com/13629122/119536604-43122880-bd57-11eb-86ec-e4fc06a7e4ab.png">

**Comment by cneidle** [comment]
Compare with 3.3.5 for top example:

<img width="950" alt="Screen Shot 2021-05-25 at 1 03 40 PM" src="https://user-images.githubusercontent.com/13629122/119538970-a56c2880-bd59-11eb-8751-ad9fb7fde48f.png">

**Comment by foltik** [comment]
As of `SignStream3_3.7.0_pre_2021_05_25_1704_16f12c84` and `SignStream4_4.1.0_pre_2021_05_25_1708_694156a2`, tripled the maximum zoom such that a single frame long event with two handshapes can always be displayed without collapsing any of the images.
