### ISSUE TITLE
JACK - field display

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#385]
I select fields to display.  i do some annotations, go to db view, and then return to the utterance, but fields that had not yet been annotated have disappeared. 

<img width="1134" alt="Screen Shot 2020-12-30 at 2 02 20 PM" src="https://user-images.githubusercontent.com/13629122/103375314-eeb89480-4aa7-11eb-8f2f-49346f9b379f.png">

<img width="1220" alt="Screen Shot 2020-12-30 at 2 02 28 PM" src="https://user-images.githubusercontent.com/13629122/103375327-f4ae7580-4aa7-11eb-886c-d62e703d48a5.png">

<img width="597" alt="Screen Shot 2020-12-30 at 2 02 35 PM" src="https://user-images.githubusercontent.com/13629122/103375330-f8da9300-4aa7-11eb-88bd-41c85b7b1c60.png">

<img width="1320" alt="Screen Shot 2020-12-30 at 2 02 41 PM" src="https://user-images.githubusercontent.com/13629122/103375338-fe37dd80-4aa7-11eb-8784-0df697ce913f.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Default shows enabled fields and fields with annotations.

Closing.
