### ISSUE TITLE
JACK - incorrect error message

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#387]
I clicked on < Next Utterance > and got the wrong error message

<img width="432" alt="Screen Shot 2020-12-30 at 2 50 11 PM" src="https://user-images.githubusercontent.com/13629122/103377805-67225400-4aae-11eb-91c1-38e30dd37ed9.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Corrected.

Closing.
