### ISSUE TITLE
JACK - buttons do not work in SIgn Bank search window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#388]
"Insert all data" works.
But not: 
<img width="580" alt="Screen Shot 2020-12-30 at 3 11 13 PM" src="https://user-images.githubusercontent.com/13629122/103378723-490a2300-4ab1-11eb-935e-afb18d2c94ce.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
buttons work.

Closing.
