### ISSUE TITLE
JACK - "about" box needs to be updated. (low priority, obviously)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#389]
<img width="285" alt="Screen Shot 2020-12-30 at 4 01 36 PM" src="https://user-images.githubusercontent.com/13629122/103380965-61ca0700-4ab8-11eb-993a-fc483b8076a8.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
About box updated.

Closing.
