### ISSUE TITLE
Problem accessing occurrences from Sign Bank search window from all most recent versions of SignStream

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#390]
Just recording this as a bug report, although I have also just communicated about this by email:
problem with “View occurrences” from Sign Bank search window.

Systematically getting this error message:

**Not Found
The requested URL /dai/s/occurrence was not found on this server.**

Thanks!

**Comment by gregorydimitriadis** [comment]
@cneidle I believe this was resolved separately, right?

**Comment by cneidle** [comment]
Yes - thanks
