### ISSUE TITLE
JACK - problems within first minutes of using the latest version

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#392]
I created a new file and created 5 utterances.  I then annotated the first gloss.  When I then tried to create a second gloss, by using Option-Click in order to start typing, the cursor started spinning and I had to restart.  I tried again.  I created 4 utterances, and the arrow keys work as long as something is selected in the database view window, but if a video window is selected, the arrow keys do not work.

I tried repeating those steps. I was able to create two glosses, but when I tried to create a third, the Option-click again had no effect. Nothing else works now either (arrow keys, selecting existing objects, etc. - nothing happens at all).

<img width="370" alt="Screen Shot 2021-01-23 at 2 52 33 PM" src="https://user-images.githubusercontent.com/13629122/105612524-bfd1cd80-5d8a-11eb-9a2c-a852de2ebc09.png">

It is possible to choose Quit from the SignStream menu, but the program also does not quit.  Must Force Quit.

**Comment by cneidle** [comment]
upon further investigation, option click does work if you click in a very precise place.  It seems that you have to click very low within the field for it to work.  You should be able to click anywhere between the top and bottom lines that delimit that tier.

ALso sometimes after typing in text for a gloss, it all disappears.   

In this version, the user is required to type RETURN for the gloss text to be recorded.  It should (as in current versions) suffice to click in another field; the gloss text should not disappear when the user does this.

ALSO some actions work differently on the linked tiers for 2-handed signs.  This should not be possible

<img width="516" alt="Screen Shot 2021-01-23 at 3 05 04 PM" src="https://user-images.githubusercontent.com/13629122/105612833-8601c680-5d8c-11eb-896c-1d31ebc37e3f.png">

I had attempted to set an endpoint at a place that was not allowed.  I got an appropriate error message and the top field was not modified, but the other 3 fields were set to the start point that i had requested  (but which should be disallowed in any case because of overlap)

**Comment by cneidle** [comment]
I typed in 3 glosses.  Everything looked normal.  I clicked on another utterance that was blank and came back to the one with my 3 glosses.  This is what i saw.  The zoom of course should not have changed.  but i don't even have any option to zoom in...  The zoom bar seems not to be showing in this screenshot, but it is at its maximum zoom.

<img width="1094" alt="Screen Shot 2021-01-23 at 3 17 41 PM" src="https://user-images.githubusercontent.com/13629122/105613109-73888c80-5d8e-11eb-82a1-04d69ec83705.png">

**Comment by cneidle** [comment]
i saved my file. closed and reopened SignStream.  tried to reopen my file.  cannot. the menu item apparently works but the file does not open

<img width="891" alt="Screen Shot 2021-01-23 at 3 24 45 PM" src="https://user-images.githubusercontent.com/13629122/105613196-412b5f00-5d8f-11eb-8cdf-98dec5fabe53.png">


<img width="662" alt="Screen Shot 2021-01-23 at 3 24 59 PM" src="https://user-images.githubusercontent.com/13629122/105613199-45577c80-5d8f-11eb-83d2-6f09ca7800f3.png">

**Comment by cneidle** [comment]
I will email the above file which i could not open, since i cannot attach it here

**Comment by cneidle** [comment]
I started a new collection:  test2-43.  I saved it.  I also saved it as test3-43.  Then I went to open test2-43, and the file did not open, although the existing video windows closed.  I then opened test3-43 and the file and videos did open.

When the video windows had closed, I went to the menu to try to edit the Macro Unit and reselect the videos.  But I got the spinning cursor and can do nothing but Force Quit.

So I restarted SIgnStream, and I opened test2-43 again.  The collection does not open but the Macro Unit window disappears.  I go to the menu for Edit Macro Unit and I get this:  

<img width="797" alt="Screen Shot 2021-01-23 at 7 32 56 PM" src="https://user-images.githubusercontent.com/13629122/105618696-42bd4d00-5db8-11eb-8239-7e23f2e21945.png">


Now, after restarting SignStream, I am also unable to open test3-43

**Comment by cneidle** [comment]
Jack - are you testing this program as you go ?????

**Comment by cneidle** [comment]
For non-manuals - the "add value" option does not work.

<img width="329" alt="Screen Shot 2021-01-23 at 7 38 59 PM" src="https://user-images.githubusercontent.com/13629122/105618203-b3fa0180-5db2-11eb-85c7-97c0dd7f04a3.png">

**Comment by cneidle** [comment]
The sign type should be aligned with the core portion of the gloss, not with the onset or offset.

<img width="538" alt="Screen Shot 2021-01-23 at 7 42 27 PM" src="https://user-images.githubusercontent.com/13629122/105618247-2539b480-5db3-11eb-962b-3b04a1f0f26f.png">

I see this is a problem with the current/prior version of SignStream, so not something introduced by Jack's implementation...
In principle, the sign type should be aligned with the start and end point of the gloss itself (excluding onset, hold, offset, etc.)

**Comment by cneidle** [comment]
FWIW - I take back the observation that it is easier to select the handshapes in this version. It still requires clicking in some very precise point within the rectangle of the handshape image.  Would be good to fix this...

**Comment by cneidle** [comment]
In a new file, I annotated two glosses within U1.  I then went back to the database view, and added a third utterance.
It obviously has nothing in it at this point.  I now look at the new utterance I had created, and it contains the second gloss from my first utterance !  This appears in the utterance portion of the display (but not in the left index):

<img width="728" alt="Screen Shot 2021-01-23 at 7 59 39 PM" src="https://user-images.githubusercontent.com/13629122/105618472-8b273b80-5db5-11eb-9a39-a9c1ad0c9b5c.png">

<img width="731" alt="Screen Shot 2021-01-23 at 7 59 33 PM" src="https://user-images.githubusercontent.com/13629122/105618478-92e6e000-5db5-11eb-98d6-f85d61046f9b.png">

<img width="187" alt="Screen Shot 2021-01-23 at 8 00 17 PM" src="https://user-images.githubusercontent.com/13629122/105618491-c295e800-5db5-11eb-849c-8ac1a313502b.png">


I think this is just an illusion, since I think it is showing the utterances in sequence.

But that brings up another issue:  There should be shaded regions between utterances.  These utterances have space between them... 

<img width="834" alt="Screen Shot 2021-01-23 at 8 02 01 PM" src="https://user-images.githubusercontent.com/13629122/105618502-e0fbe380-5db5-11eb-9337-8bea0fc5bd8b.png">

Compare with current version:

<img width="1244" alt="Screen Shot 2021-01-23 at 8 06 36 PM" src="https://user-images.githubusercontent.com/13629122/105618549-90d15100-5db6-11eb-852c-b246a7cfc5f6.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
click anywhere in field works.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
Creating a gloss...clicking away from text box submits the text and creates the gloss name.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
Alignment when setting (or attempting a setting) of boundaries corrected.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
Zoom is redesigned...should either do default behavior or remember zoom level.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
File save/open has be corrected.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
Resetting of videos/audio/graph of an existing collection corrected.
Opening and using macro editor improved.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
Add value to non-manuals from utterance view works.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
Gloss alignment of associated fields corrected.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
arrow keys corrected.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
selecting and showing of utterances corrected...partial zoom scroll issues.
