### ISSUE TITLE
Overlap should not be allowed for glosses

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#393]
I found two examples of something like this:

<img width="255" alt="Screen Shot 2021-01-24 at 9 45 17 AM" src="https://user-images.githubusercontent.com/13629122/105633979-b0559180-5e29-11eb-9007-25484b2d3a6d.png">

What appears to have happened is that there was one gloss on the dominant hand that was 1-handed.
And there was another gloss on the non-dominant hand that was, in fact, 1-handed, but which appears to have been annotated as 2-handed (as confirmed by the Gloss-Phon window, which listed 1"focus" as 2-handed, same handshapes).   So there were two overlapping sets of gloss information on the dominant hand.  This should not be allowed.    (I fixed it by modifying that sign to 1-handed.)   Thanks!

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Overlapping and alignment gloss issued should be all corrected.

Closing.

Closing
