### ISSUE TITLE
JACK: Current frame should always be within the field of view in the Utterance window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#394]
I expect this will be taken care of when you fix the zoom issue.  But I created a gloss, extended its endpoint using the buttons, and the current frame ceased to be within the viewable area of the gloss window.  Just FYI.  Thanks.

**Comment by cneidle** [comment]
And just a final comment on the Zoom:  If I am looking at an utterance, and I switch to another utterance and come back to the first, the zoom should be exactly as it was before.  (A logical extension of keeping the Zoom constant when moving from one utterance to the next, unless the user manually changes it.). Thanks.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Almost completely fixed.  The click and drag in the database view when creating an utterance does not scroll the screen.

Keeping open

**Comment by gregorydimitriadis** [comment]
Fixed as of:
SignStream4_4.1.0_pre_2021_05_24_1819_794effbf
SignStream3_3.7.0_pre_2021_05_24_1815_897b87d3
