### ISSUE TITLE
JACK-v.2-2-21. Cannot select new gloss

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#395]
First 20 seconds using the program with MacOS 10.12.6:

I opened a file and created a new gloss.  Clicking elsewhere left the text intact - so that's good.  But I was then unable to select the new gloss to set its start and end points.  And in fact, everything has totally frozen.  I can do nothing but Force Quit.  

<img width="783" alt="Screen Shot 2021-02-02 at 10 10 00 AM" src="https://user-images.githubusercontent.com/13629122/106619897-08ce1280-653f-11eb-8c38-79ec55b86043.png">

**Comment by cneidle** [comment]
Note that the above with with an H.264 movie.  I will continue testing with movies of other formats.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Fixed.

Closing.
