### ISSUE TITLE
Jack - 2/2/21 - problem with movie navigation - H.264

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#396]
I see this movie is H.264.  Perhaps this is the problem. Will try again with non-H.264 movie.  But I set up a gloss then used the arrow keys to advance, first by one frame, then by another.  This is what I saw, just FYI.

<img width="629" alt="Screen Shot 2021-02-02 at 10 18 22 AM" src="https://user-images.githubusercontent.com/13629122/106621306-6ca50b00-6540-11eb-9cf9-d2129e1d2e1b.png">

<img width="728" alt="Screen Shot 2021-02-02 at 10 18 27 AM" src="https://user-images.githubusercontent.com/13629122/106621617-baba0e80-6540-11eb-95ed-72f0cbd5267b.png">

**Comment by douglas-motto-at-rutgers** [comment]
Can not reproduce.  Believe fixed.

Closing.
