### ISSUE TITLE
Jack - 2-2-21 problem with implementation of Zoom

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#397]
There seems to be a random factor in which direction the Zoom expands in, and what remains visible after a Zoom.
This is what should NOT happen:

I have just coded this gloss, and then I increase the zoom:

<img width="424" alt="Screen Shot 2021-02-02 at 10 30 01 AM" src="https://user-images.githubusercontent.com/13629122/106622610-c3f7ab00-6541-11eb-9063-b52aa5bbdb41.png">

<img width="382" alt="Screen Shot 2021-02-02 at 10 30 08 AM" src="https://user-images.githubusercontent.com/13629122/106622670-d540b780-6541-11eb-8868-ec54b092e152.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_07_1730_e1dd7d21

No longer appears to happen.

Closing.
