### ISSUE TITLE
Jack - 2-2-21. Reopened file froze almost instantly.

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#398]
Had made a new file with MPEG-4 movie.  Saved.  

Reopened (now from Mac OS 11.2).  Froze almost instantly (when I attempted to use the arrow key).
Can do nothing but Force Quit.

<img width="817" alt="Screen Shot 2021-02-02 at 12 13 15 PM" src="https://user-images.githubusercontent.com/13629122/106636573-0de78d80-6550-11eb-8861-13b53382fa11.png">

**Comment by cneidle** [comment]
Here is a case where I had selected the non-manual item, went to the end of it, and then pressed the forward arrow key.
Program froze - must Force Quit.

<img width="1188" alt="Screen Shot 2021-02-02 at 1 52 41 PM" src="https://user-images.githubusercontent.com/13629122/106648297-16df5b80-655e-11eb-9cd1-a3394fd87fd5.png">

**Comment by cneidle** [comment]
Reopened.  Program froze again - not sure why

**Comment by cneidle** [comment]
Reopened file.  Played non-manual event.  moved back several frames with arrow key.  Used + button to try to adjust endpoint. Program froze.   Must Force Quit.

<img width="1006" alt="Screen Shot 2021-02-02 at 2 02 50 PM" src="https://user-images.githubusercontent.com/13629122/106649296-5a869500-655f-11eb-8e2f-960046bf8eb3.png">

**Comment by cneidle** [comment]
Repeated exactly the steps above.  After clicking on the + button to adjust the endpoint of the non-manual item, this is what I saw.

<img width="1357" alt="Screen Shot 2021-02-02 at 2 05 16 PM" src="https://user-images.githubusercontent.com/13629122/106649516-b2bd9700-655f-11eb-953c-721fad5f0c97.png">

**Comment by cneidle** [comment]
PS. The above is precisely the "weird thing" I referred to in the second item of #401.

**Comment by douglas-motto-at-rutgers** [comment]
As SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

The player locking up scenarios have been greatly reduced.

Closing.  Open new issue if seen again.
