### ISSUE TITLE
Utterance Window - gloss double-click to select

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#4]
Double-click on a gloss should not select any spaces

**Comment by blazetravis** [comment]
How do I test this bug? If it involves simply double-clicking on an existing gloss, when I do so, SignStream highlights the text label of the gloss and includes a space at the end.

**Comment by gregorydimitriadis** [comment]
As you noted in the other bug, for new glosses the whitespace will be absent. However, for pre-existing gloss names with the space there already, those will continue to be there.

**Comment by blazetravis** [comment]
Great. Then this bug is fixed.

**Comment by kwasiopoku** [comment]
@blazetravis I will close this ticket on your behalf at this time.  Later on, we will figure out why you cannot close the tickets.
