### ISSUE TITLE
Clean up temporary files created when saving

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#40]
In the use of SignStream, the application creates a "tmp_<database_name>.ss3" directory at the same level as the application itself, and never cleans it up, even after saving and closing completely.

**Comment by blazetravis** [comment]
How would you like me to best test this on my end?

**Comment by gregorydimitriadis** [comment]
If you're able to open up SignStream, create a new database, make one or two edits and save/close it - without a "tmp" file showing up next to the application - then we can say this is tested.

**Comment by blazetravis** [comment]
This bug is fixed.
