### ISSUE TITLE
Jack - 2-2-21. previously reported issue display of tab text in morph-phone window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#400]
<img width="348" alt="Screen Shot 2021-02-02 at 12 35 16 PM" src="https://user-images.githubusercontent.com/13629122/106639593-1f7e6480-6553-11eb-9288-2eb8fd6dc5b9.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

I'm told....This will not get fixed until an upgrade of the UI framework SS uses for tabs...or a custom hacked replacement for tabs is crested.  Both which will take a long time.

The weird highlighting occurs when the morph-phon window is not in focus....re-click it and the "blue" highlight reappears.

Closing.
