### ISSUE TITLE
Jack 2-2-21 Non-manual fields

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#401]
Should be able to click (and drag) anywhere within the field to add a new item.   

Add new item worked for one field, but not for another (although even there, I could add a new value by selecting an existing value first and then double-clicking on it and choosing 'add new value').

<img width="971" alt="Screen Shot 2021-02-02 at 12 39 17 PM" src="https://user-images.githubusercontent.com/13629122/106640424-0629e800-6554-11eb-9d90-ed92f66d5ff8.png">

**Comment by cneidle** [comment]
I created an item in a non-manual field, and selected it.  I then used the + and - buttons for the endpoint of that item and weird things happened.  

SEE COMMENTS 5 & 6 in #398.

When I went to try it again, the program had frozen.  I had to Force Quit.

<img width="542" alt="Screen Shot 2021-02-02 at 1 45 53 PM" src="https://user-images.githubusercontent.com/13629122/106647589-24e0ac80-655d-11eb-9462-9271bdb7052c.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

The alignment changing of boundaries should be corrected.

The adding new item, could not recreate.  Tested with a few fields and doesn't seem to currently exist.

In future, list the field it worked and not worked.

Closing. Open new issue if discovered again.
