### ISSUE TITLE
JACK-2-4-21 - now testing with Mac OS 11.2

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#403]
I went to open the same previous SignStream file that I was testing.  I opened a fresh copy of it with the latest version of SignStream from Jack on Big Sur, and I cannot view the data because the Zoom prevents it.the o

Just to be clear, I went back to open the version of this file that had been saved only in the old version of SignStream (although re-associating videos seems to get saved even though it shouldn't; so the older version of that file that I had opened have perhaps already been modified minimally when I opened it using Jack's new version on my other laptop; I immediately saved it in a different folder and had not tried to re-open the file that I had intentionally saved).

<img width="1068" alt="Screen Shot 2021-02-04 at 1 37 11 PM" src="https://user-images.githubusercontent.com/13629122/106939529-5fc61a00-66ee-11eb-9a26-c4fedd8f8d13.png">

I was unable to even click on anything in the database view to open an utterance but I did launch a search so as to get into utterances.

But the Zoom still prevents seeing anything significant.

<img width="857" alt="Screen Shot 2021-02-04 at 1 40 23 PM" src="https://user-images.githubusercontent.com/13629122/106939674-90a64f00-66ee-11eb-9b2a-93d5876a6654.png">

**Comment by cneidle** [comment]
I then opened a new blank file and linked in those same videos.  But the Zoom carried over, making this unworkable.

<img width="1057" alt="Screen Shot 2021-02-04 at 1 43 27 PM" src="https://user-images.githubusercontent.com/13629122/106940031-04485c00-66ef-11eb-9436-d79594f2991c.png">

**Comment by cneidle** [comment]
I then reopened the program entirely and set up a new blank file and it worked normally.

I tried to repeat the steps reported earlier - opening the program, starting to open a file an and cancelling, trying to edit the macro unit, then trying to open a new blank file, and trying to edit the macro unit.  Exactly the same thing happened as before, except that the system did not crash.  (It only crashed once earlier, it was not crashing predictably then.  It has never crashed this way on any previous version of SignStream.)

**Comment by cneidle** [comment]
I did try quitting SignStream, which was consistently causing the program to crash on the older OS, and the dialog box for saving files appeared properly without causing any problem.

**Comment by cneidle** [comment]
I attempted to open another old SignStream file (which had never been open with a version of SS other than 3.3.5).  I got this error message:  

<img width="1153" alt="Screen Shot 2021-02-04 at 2 01 59 PM" src="https://user-images.githubusercontent.com/13629122/106941959-93567380-66f1-11eb-8d24-d72f01fe2711.png">

Once I closed that window did a "save as" to save a separate copy of this file, I was able to link in the videos without a problem.

**Comment by cneidle** [comment]
Play utterance has the same effect as before in terms of what is visible.

<img width="1342" alt="Screen Shot 2021-02-04 at 2 05 13 PM" src="https://user-images.githubusercontent.com/13629122/106942316-0a8c0780-66f2-11eb-826e-c164b3358488.png">

<img width="1350" alt="Screen Shot 2021-02-04 at 2 05 22 PM" src="https://user-images.githubusercontent.com/13629122/106942328-0e1f8e80-66f2-11eb-80b9-4830cd4d5e44.png">

**Comment by foltik** [comment]
Could you send me the original (never opened with the new build) version of the collection you initially observed the zoom issue with?

**Comment by cneidle** [comment]
See below.

As I said, the process of reselecting the videos caused the modification date
to be updated, but that is all I did before saving it in a different location… 

THanks,
 Carol

**Comment by cneidle** [comment]
Follow-up to previous message:

Thanks to the magic of Dropbox, I’m attaching the file that was last modified Jan. 17,
and what happened to that file after I opened it (without saving!) at 10:30 am this morning.

Again, relinking videos causes the file to be saved, although it should not (a longstanding problem).

The file I sent a little while ago is the file after I opened it (again without saving)
from Big Sur this afternoon.

**Comment by foltik** [comment]
I'm not seeing the files you're mentioning, did you email them?

**Comment by foltik** [comment]
If you can reproduce them again, could you attach SignStreamOut.txt for the case where the zoom is broken when you open the old collection, and when you see the error about "Structure does not contain integer field..."?

**Comment by douglas-motto-at-rutgers** [comment]
If most of these issues are zoom related...Many zoom/scroll improvements have been made.

After releasing both the 4 and 3 versions we'll need someone with 11.2 to check any issues here.

Keeping open for now.

**Comment by douglas-motto-at-rutgers** [comment]
Believe fixed in the last versions.

Closing.
