### ISSUE TITLE
SS 3.3.5 - weirdness with sign type alignments 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#404]
Something very odd is going on here:  U19

<img width="215" alt="Screen Shot 2021-02-10 at 2 44 44 PM" src="https://user-images.githubusercontent.com/13629122/107563010-8aace400-6bae-11eb-86ae-4c074bfe4262.png">

<img width="1081" alt="Screen Shot 2021-02-10 at 2 40 26 PM" src="https://user-images.githubusercontent.com/13629122/107562884-5df8cc80-6bae-11eb-91b1-14b81cd91407.png">

I have also noticed that the non-dominant sign type field is frequently not showing.  I would assume that if dom sign type is displayed the non-dom sign type should also be displayed.  I explicitly display it but it often disappears again.

<img width="1094" alt="Screen Shot 2021-02-10 at 2 41 25 PM" src="https://user-images.githubusercontent.com/13629122/107562881-5d603600-6bae-11eb-96ee-61a1a35c073f.png">

I will email the file to Greg.  Thanks.

**Comment by cneidle** [comment]
another example - no non-dom sign type showing.  that should be visble by default

<img width="437" alt="Screen Shot 2021-02-13 at 3 52 10 PM" src="https://user-images.githubusercontent.com/13629122/107861443-b086f280-6e13-11eb-8054-59dc44e232d7.png">

**Comment by cneidle** [comment]
This is a very persistent problem.  The non-dominant sign type is typically hidden, even when you use the button to show all non-empty fields.  This was not a problem in 3.3.3.  Seems to have been introduced between 3.3.3 and 3.3.4, FWIW.

**Comment by gregorydimitriadis** [comment]
Also including in this issue: sign type labelling is often incorrect - particularly for sign type 'gesture'

**Comment by cneidle** [comment]
Right - the issue is that you select a type, esp. gesture, in the Morph-Phon window,
and enter, and it does not get entered.   Thanks!

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

I believe the display of types has been fixed.

Closing.
