### ISSUE TITLE
SS 3.3.5 - related to previously reported issue of multiple tiers not behaving the same wrt potential overlap

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#405]
I reset the endpoint of the sign highlighted in red, and the non-dominant hand gloss of the following sign jumped to look like this:

<img width="1122" alt="Screen Shot 2021-02-14 at 8 50 25 AM" src="https://user-images.githubusercontent.com/13629122/107878638-1ae67400-6ea2-11eb-90be-cf901c805d9a.png">

**Comment by douglas-motto-at-rutgers** [comment]
Assuming there was the 2h "part:indef" and the 2h "WHAT....with everything aligned under there main gloss boundaries...

Then moved the end of "part:indef" to the the same start time as "WHAT"...

... and then the alignment for "WHAT" becomes messed up.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Retested and no longer occurs.

Closing.
