### ISSUE TITLE
SS 3.3.5: adding field values in the Field Specifications Editor

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#406]
Adding new vales for role shift causes an extra blank value to be created (in error).
<img width="425" alt="Screen Shot 2021-02-15 at 2 56 57 PM" src="https://user-images.githubusercontent.com/13629122/107988842-de4c7280-6f9e-11eb-8ef4-5bf6f679a547.png">
<img width="425" alt="Screen Shot 2021-02-15 at 2 56 57 PM" src="https://user-images.githubusercontent.com/13629122/107988894-f4f2c980-6f9e-11eb-801e-4aa9979ac927.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Can add as many fields in the editor window...but when clicking "Done"...it will not save if any are empty.

Closing.
