### ISSUE TITLE
33.6 - List of known issues - for Carol to bring to the attention of students, so that they do not re-report them

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#408]
1. Appearance of font generally

2. Appearance of font label for the Morph-phon selected tab
<img width="605" alt="Screen Shot 2021-02-26 at 2 44 48 PM" src="https://user-images.githubusercontent.com/13629122/109347449-327a1100-7841-11eb-804f-8d6c6670b382.png">

Note that this problem occurs with Big Sur, but not with 10.12.6:

<img width="489" alt="Screen Shot 2021-02-26 at 4 19 26 PM" src="https://user-images.githubusercontent.com/13629122/109356311-86d7bd80-784e-11eb-8eb3-e6144a51216f.png">

3.  Inability to "Add new value" immediately upon creating a non-manual event.  It is, however, possible to do this by first assigning a known value, and then double-clicking to change the value - then "Add new value" works.  Alternatively, this can be done from the Field Specifications Editor.

4. To "select" a gloss, it doesn't work to click on the text of the gloss (as it should); you have to click on the line itself beneath the text. Although sometimes if you click enough times on the text of the gloss, it will get selected.

5. If you have made changes in the file you are working with that have not been saved, and choose (accidentally or on purpose) New Blank File from the menu, you will not be asked whether you want to save your changes; they will be lost.

6. Hard to create a non-manual event; need to click multiple times to get just. the right height for the click to work.

7. Need to be careful to close the search window before you open a new file.

8. Do not attempt to use the field specification editor, and do not attempt to enter new fields or values.

**Comment by douglas-motto-at-rutgers** [comment]
Font issues in certain Mac OS versions still exist.  See...

https://github.com/DCS-LCSR/SignStream3/issues/386

**Comment by douglas-motto-at-rutgers** [comment]
Appearance of font label for the Morph-phon selected tab.

I believe this only happens when the morphphon window is not in focus.

Will not get fixed until the framework is updated.  This is a Java Swing issue.

**Comment by douglas-motto-at-rutgers** [comment]
"Inability to "Add new value" immediately upon creating a non-manual event. It is, however, possible to do this by first assigning a known value, and then double-clicking to change the value - then "Add new value" works. Alternatively, this can be done from the Field Specifications Editor."

has been fixed.

**Comment by douglas-motto-at-rutgers** [comment]
"To "select" a gloss, it doesn't work to click on the text of the gloss (as it should); you have to click on the line itself beneath the text. Although sometimes if you click enough times on the text of the gloss, it will get selected."

In 
SignStream4_4.1.0_pre_2021_05_28_2110_7a9f7c09
SignStream3_3.7.0_pre_2021_05_28_2112_68341ef3

works.

**Comment by douglas-motto-at-rutgers** [comment]
"If you have made changes in the file you are working with that have not been saved, and choose (accidentally or on purpose) New Blank File from the menu, you will not be asked whether you want to save your changes; they will be lost."

Believed fixed.

**Comment by douglas-motto-at-rutgers** [comment]
"Hard to create a non-manual event; need to click multiple times to get just. the right height for the click to work."

In latest version, can not reproduce.  If still existing, need demonstration.

**Comment by douglas-motto-at-rutgers** [comment]
"Need to be careful to close the search window before you open a new file."

corrected in latest version.

**Comment by douglas-motto-at-rutgers** [comment]
"Do not attempt to use the field specification editor, and do not attempt to enter new fields or values."

Corrected in latest version.

**Comment by douglas-motto-at-rutgers** [comment]
Closing.
