### ISSUE TITLE
Testing 3.3.6 - in 10.12.6

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#409]
Problem recurs in this OS with a different file (File 60 - U 12).  To reproduce:  Create non-manual event.  Change the value by double-clicking to a new value.  Then try to create another event in the same field.  Labeling it is impossible.

<img width="895" alt="Screen Shot 2021-02-26 at 4 10 23 PM" src="https://user-images.githubusercontent.com/13629122/109355579-6b1fe780-784d-11eb-9a45-e678a6eec2d3.png">

<img width="914" alt="Screen Shot 2021-02-26 at 4 10 00 PM" src="https://user-images.githubusercontent.com/13629122/109355588-6f4c0500-784d-11eb-8ba9-aa56c742a9dc.png">

save and re-open:

<img width="1037" alt="Screen Shot 2021-02-26 at 4 14 14 PM" src="https://user-images.githubusercontent.com/13629122/109355781-c0f48f80-784d-11eb-8072-14824489f8e4.png">

**Comment by cneidle** [comment]
Seems to be fixed.

**Comment by douglas-motto-at-rutgers** [comment]
Closing.
