### ISSUE TITLE
Re-associate video with existing collection results in unintentional saving

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#41]
Take these steps to reproduce the issue:
1) Create a fresh collection, and link a video from a known location
2) Make a few annotations/utterances
3) Save the collection and close SignStream
4) Move the video from its original location to anywhere else
5) Re-open SignStream, and load up the saved collection
6) You will see the video will not load (because it can no longer be found) but the annotations are still visible
7) Attempt to relink the video by doing: Edit Macro Unit > Lookup and finding the video in its new location. Then click confirm.

You will see the video still does not load, and also the view of the annotations is messed up now (I saw it as being all scrunched up on the left side of the window). In addition, the collection was saved upon clicking confirm with this wrong configuration, and if you attempt to re-open SignStream and load the collection again, it will still look wrong.

Note: this same behavior does not occur if after step 6, you instead first "Remove" the video and then "Select" it from the new location. Then it will load the video and render all the saved annotations correctly.

**Comment by gregorydimitriadis** [comment]
Cannot currently reproduce the issues noted after Step 7 above. I am able to get the video to load, and the annotations are not displaying wrong at all.

As far as the saving goes, I believe this to be normal behavior. Each time the Macro Unit window is exited by entering, an immediate save occurs of the annotator library, participant library, and video library. In the process of updating the video library, the new video is also linked in the current database.

**Comment by gregorydimitriadis** [comment]
After taking another quick look, I noticed that upon re-selection of the video in the new location, the checkbox for "Display" of the video is not immediately checked. If you enter out of the macro unit window like so, then you will see the annotations all scrunched up on the left. If you manually check it, at any point after re-selecting the video, then everything will work as expected.

So my feeling for a fix on this is for the window to automatically check the checkbox for the videos selected after a lookup occurs. If this happens, then without doing anything after looking up the videos, there should be no issues.

**Comment by blazetravis** [comment]
This seems to be working as expected now.
