### ISSUE TITLE
Bugs in  new version of SS (testing files)

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#410]
Created a copy of Jonathan 91 file to test in new upcoming SS version.  (see screen shots)
Working in utterance #1 
I created a (2h)gloss when trying to unlock left-right hand alignments and add an onset, the onset line and the loan sign lines match up but not the handshapes

When unlocking the right gloss-phon alignments and adding an initial hold, the handshapes do not line up to the initial hold line, this is also the case when adding onset, final hold and offset lines

Cannot make a one framed entities in non manual fields (i.e 1 framed blink) Tried to create a multiframed entity and shorten it to one frame and this does not work either. 

For the 1 framed entities that have already been glossed, when you click on them and try to play them (play entitiy), the entire utterance gets played instead of the 1 frame that you have selected 

![Screen Shot 2021-03-07 at 4 06 40 PM](https://user-images.githubusercontent.com/38887034/110260723-3ce38b80-7f62-11eb-8e90-bfd4f19365d7.png)
![Screen Shot 2021-03-07 at 4 09 30 PM](https://user-images.githubusercontent.com/38887034/110260725-3e14b880-7f62-11eb-92fa-b2b696fe5632.png)
![Screen Shot 2021-03-07 at 4 09 47 PM](https://user-images.githubusercontent.com/38887034/110260727-3e14b880-7f62-11eb-8a29-d03b497440a7.png)
![Screen Shot 2021-03-07 at 4 10 03 PM](https://user-images.githubusercontent.com/38887034/110260728-3ead4f00-7f62-11eb-9293-d7a8b594044e.png)
![Screen Shot 2021-03-07 at 4 09 08 PM](https://user-images.githubusercontent.com/38887034/110260730-3ead4f00-7f62-11eb-8db0-7a37cbd49352.png)
![Screen Shot 2021-03-07 at 4 06 45 PM](https://user-images.githubusercontent.com/38887034/110260731-3ead4f00-7f62-11eb-928e-a495b5804eb0.png)

![Screen Shot 2021-03-07 at 4 20 46 PM](https://user-images.githubusercontent.com/38887034/110260738-44a33000-7f62-11eb-850a-07440e83d0ab.png)

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6098257/SignStreamOut.txt)

**Comment by bugspotter33** [comment]
Continued testing new SS working on a test file of Rachel 36. When trying to watch a video of a sign the video never popped up. The sign is READ_2  and there are occurrences but there isn't a video showing just a black screen

![Screen Shot 2021-03-10 at 5 45 55 PM](https://user-images.githubusercontent.com/38887034/110723953-c6e15d80-81c9-11eb-9cde-a6fa0163c7f6.png)

![Screen Shot 2021-03-10 at 5 51 50 PM](https://user-images.githubusercontent.com/38887034/110723969-cd6fd500-81c9-11eb-87cd-f559448519a2.png)

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6119910/SignStreamOut.txt)

**Comment by cneidle** [comment]
This is likely to be a problem with the Sign Bank. 

Augustine updated data recently, but I don’t believe he generated a new sign bank.  We will need to be careful about this.  

Augustine, could you please generate a current sign bank?

Thanks !!
  Carol

**Comment by bugspotter33** [comment]
Not sure if this is a bug or signbank issue. Working on testing out new SS with a test file of Rachel 36 U9 gloss is WEATHER and when i looked up the gloss in the signbank and played the sign video, a different gloss GO played instead of WEATHER. 
![Screen Shot 2021-04-03 at 9 50 12 PM](https://user-images.githubusercontent.com/38887034/113499038-72c75180-94c7-11eb-95fc-cce1c1fafe8d.png)


[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6254002/SignStreamOut.txt)

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Two handed alignment issues are believe corrected for unlocked hands and handshapes.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

can make 1framed non-manual fields.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

READ_2 loaded in signbank search.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17
(W)WEATHER loaded in signbank search.

**Comment by douglas-motto-at-rutgers** [comment]
Closing.
