### ISSUE TITLE
Program froze - Jack's test version 3.3.6

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#411]
Was annotating a sign.  I used command-Q to quit SignStream while the Morph-Phon window was still open. Everything froze.  Needed to force quit the program.
<img width="704" alt="Screen Shot 2021-03-19 at 11 15 38 AM" src="https://user-images.githubusercontent.com/13629122/111802855-d7b66100-88a4-11eb-98f7-fa60f9c58553.png">
[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6172285/SignStreamOut.txt)

I realize now that I was using the Feb. 26th version of the program, not the most recent.  I will see if I can replicate this with your newer version.

**Comment by cneidle** [comment]
I redownloaded the latest version of 3.3.6 from Jack to be sure I'm using the right one.  I deleted all previous versions from my desktop, as it was all confusing me.  I opened the program, attached 3 of our standard video files, and got the following error msg, although the video files did open:

<img width="788" alt="Screen Shot 2021-03-19 at 11 33 13 AM" src="https://user-images.githubusercontent.com/13629122/111806982-e56de580-88a8-11eb-9248-83702081a6f7.png">

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6172428/SignStreamOut.txt)

This is reproducible.

**Comment by cneidle** [comment]
The problem described in the first comment above did not recur when I tried, but perhaps there is some difference in the steps I took in the two cases...  So not absolutely certain that this is not a problem.

Actually, my best guess is that the dialog box about whether or not the user wants to save the file before quitting ended up being hidden behind another window.  So it seemed like I could do nothing, because I had not provided the required input.  This may have been because I went first to another application and then came back to SignStream...  Is there a way to ensure that a dialog box that requires attention is always front-most ?  I have had things like this happen before... FWIW.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_10_1855_c60918b0

I've been told that the freezing hasn't been experienced.  Assuming corrected.

I've been told the "Structure does not contain integer" has been fixed.

Closing
