### ISSUE TITLE
4.0  I typed in some text to the words field

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#414]
and then wanted to align each individual word. This is how it showed up, and I was then unable to select any of the text in order to align the individual words.  That should be possible... 

<img width="552" alt="Screen Shot 2021-04-14 at 4 07 18 PM" src="https://user-images.githubusercontent.com/13629122/114772404-c04f8400-9d3b-11eb-9deb-24ea806b8d83.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

All non-manual fields, include free, allow spaces within the label.
Predefined and Generic fields are based on this as well.

Gestures similar...with out asking for a label.

Discussion is needed.

**Comment by cneidle** [comment]
This appears to be working properly.
