### ISSUE TITLE
v. 4 - graphs start later than beginning of video 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#415]
Is the graph information correct ??  Why does the information not start at the beginning of the video?

<img width="1405" alt="Screen Shot 2021-04-14 at 4 16 38 PM" src="https://user-images.githubusercontent.com/13629122/114773333-eb86a300-9d3c-11eb-88c4-933576260d48.png">

**Comment by douglas-motto-at-rutgers** [comment]
This isn't a bug....there is no video of his face before the graph data appears.

Closing.
