### ISSUE TITLE
Repository for future features and enhancements for v.4

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#416]
I'm starting a list of things that we may wish to revisit in the future.  Listing them as they occur to me, so as not to forget.

1) In addition to Next {event, entity} it would be great to have a Previous {event, entity} button.
    It would also be useful to be able to jump forward and backward from one core event to the next.

2) Presumably the file type will change from .ss3 to .ss4, if we renumber the new version as SIgnStream 4.0.

**Comment by douglas-motto-at-rutgers** [comment]
moved to 
https://github.com/DCS-LCSR/SignStream3/issues/468
https://github.com/DCS-LCSR/SignStream3/issues/469

Issues better handled individually.

Closing.
