### ISSUE TITLE
Searching with 3.3.6 (official test version)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#417]
I was using the 3.3.6 version (which we had given to students for testing) to make a correction.  I changed the gloss from AFFORD to BILL/OWE, saved, and reopened the file.  The search results still find this sentence when searching for AFFORD.

<img width="1121" alt="Screen Shot 2021-04-25 at 11 28 27 AM" src="https://user-images.githubusercontent.com/13629122/115999406-91e26c00-a5b9-11eb-95eb-8340d66f11c1.png">

**Comment by cneidle** [comment]
[Jonathan_2012-11-27_sc97.ss3.zip](https://github.com/DCS-LCSR/SignStream3/files/6376577/Jonathan_2012-11-27_sc97.ss3.zip)

**Comment by gregorydimitriadis** [comment]
This should not be possible to reproduce in the newest version(s) - the search window will be closed in between saving/opening collections.

**Comment by cneidle** [comment]
Then this increases the importance of implementing a functionality that we had in SignStream version 2 -- and which has been on the "to do" list for SignStream 3 ever since:  the ability to save searches (obviously not for the current release, but ASAP thereafter), as the process of conducting a specific search through multiple collections is odious if this feature, which has been present through 3.3.5) is to be removed.  The original state (i.e., the file from which the search was first launched) was remembered, so you could return to it.  So this has not been simply completely closing one collection and opening another.  This was a different kind of operation.  Ah well.

**Comment by douglas-motto-at-rutgers** [comment]
Claimed fixed as of SignStream3_3.7.0_pre_2021_05_19_1003_86750a7c

Closing this issue. 

Saving search is in https://github.com/DCS-LCSR/SignStream3/issues/95.

**Comment by cneidle** [comment]
I had not looked at the top of this when I responded to Greg's comment.  The response from Greg is not appropriate for the problem that was reported here on top. That is a separate issue that Greg was referring to.

The problem that was reported is that the deleted item was still showing up, in the exact same file from which it had been deleted.  

This had nothing to do with closing SignStream collections and opening new ones.

The deleted item was still being found.

**Comment by gregorydimitriadis** [comment]
The first comment mentioned after saving/reopening the results were still there. However, even if I don't save and/or quit after the first search, if I edit and/or delete the gloss and then search again (i.e. leaving the search window open while I make edits in the main utterance view window), I do not find it in the results this second time. 

(For both ver3 and ver4)

**Comment by douglas-motto-at-rutgers** [comment]
In...

SignStream4_4.1.0_pre_2021_05_24_1819_794effbf
SignStream3_3.7.0_pre_2021_05_24_1815_897b87d3

...opening a search window...and then adding new glosses after...the new glosses can not be found.

Keeping open.

**Comment by gregorydimitriadis** [comment]
Will be fixed in versions:
3.7.0_pre_2021_05_25_1704_16f12c84
4.1.0_pre_2021_05_25_1708_694156a2
