### ISSUE TITLE
May 3, 2021 test version on OS 11.2.3 - bug with window resizing

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#418]
Testing May 3 test version on OS 11.2.3

(1) With respect to the version number – the next public release should still be in the 3.3 series; the research version, which will not be compatible with SignStream 3 files, should be 3.4.0.

(2) Bug in the behavior of video windows:  I linked in 3 synchronized movies, and click on the "small" button in the bottom right corner of 1.  That should have the effect of making all the video windows small, but it only acts upon the window containing the button I clicked on.  

<img width="1288" alt="Screen Shot 2021-05-03 at 12 23 35 PM" src="https://user-images.githubusercontent.com/13629122/116903425-67705e80-ac0a-11eb-8d80-84a09b5caa6b.png">

**Comment by foltik** [comment]
Fixed as of SignStream4_4.1.0_pre_2021_05_14_1715_39304367
