### ISSUE TITLE
start and end frame for newly created gloss not immediately selectable

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#419]
Immediately after creating a gloss, this is what I see; I can't select the start and end frames immediately - those buttons are disabled until there is another click...  

<img width="844" alt="Screen Shot 2021-05-03 at 12 41 33 PM" src="https://user-images.githubusercontent.com/13629122/116905496-0f872700-ac0d-11eb-83bb-c100c7e34606.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

The behavior now appears similar to 3.3.1.   A second click isn't necessary to enable the set buttons.

Closing.
