### ISSUE TITLE
Modes displayed 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#421]
I assume that this won't be an issue in the next release, because the gesture features will be hidden/removed, but right now- - and for future development of SS 4 -- If I select Sign language view only, and I annotate some glosses, go up to database view and then return to utterance view, the Gesture mode is displayed and my work in the Sign Language mode is not visible.  

Ideally, once anything has been coded in speech or sign mode, that mode should by default be visible when the utterance is displayed, and by default, if sign mode has data and speech mode does not, or vice versa, those modes and only those modes should be displayed by default.  It will be very rare to code items in both, but when that happens, they will both get non-empty very fast...

**Comment by cneidle** [comment]
And what is this middle region?

<img width="844" alt="Screen Shot 2021-05-03 at 12 41 33 PM" src="https://user-images.githubusercontent.com/13629122/116907555-bc62a380-ac0f-11eb-90f4-a7ef83a5335e.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

The panel views are remembered within the "same" session (between db and utteranceviews)...but are not currently saved and reloaded.

Keeping open.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_12_1056_cbb91a73

The panel views are remembered between saved and reloaded collections.

Closing.
