### ISSUE TITLE
Missing items from contextual menu for glosses

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#423]
Testing on 10.12.6 --

This from SS3:

<img width="368" alt="Screen Shot 2021-05-04 at 1 22 35 PM" src="https://user-images.githubusercontent.com/13629122/117044061-f8fbd100-acdb-11eb-989f-93df9ede816d.png">

This from the latest release - note missing Compound options; this menu should be as above:

<img width="388" alt="Screen Shot 2021-05-04 at 1 21 44 PM" src="https://user-images.githubusercontent.com/13629122/117044082-fef1b200-acdb-11eb-87e8-e15f47028416.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_07_1730_e1dd7d21

Compound is back for glosses.

Closing.
