### ISSUE TITLE
Field specifications - for role shift

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#424]
Role shift should have a prefix = "rs:"

So if the value is "other" it will appear as "rs:other" in the utterance window.

I am working with yesterday's brand new version (i.e., I have not edited anything) and this is what I see:

<img width="143" alt="Screen Shot 2021-05-04 at 1 29 55 PM" src="https://user-images.githubusercontent.com/13629122/117045058-14b3a700-acdd-11eb-93ff-76f944ac447e.png">
<img width="404" alt="Screen Shot 2021-05-04 at 1 29 45 PM" src="https://user-images.githubusercontent.com/13629122/117045060-154c3d80-acdd-11eb-9053-8d95d2c907ef.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_07_1730_e1dd7d21

Done.

Closing.
