### ISSUE TITLE
Search is not displaying results properly

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#425]
Testing in 10.12.6

<img width="995" alt="Screen Shot 2021-05-04 at 1 38 57 PM" src="https://user-images.githubusercontent.com/13629122/117045996-277aab80-acde-11eb-93e7-4c4c9d650160.png">

This item is present only in U1

**Comment by cneidle** [comment]
Clear Search does not clear the search

<img width="994" alt="Screen Shot 2021-05-04 at 1 42 41 PM" src="https://user-images.githubusercontent.com/13629122/117046398-a53eb700-acde-11eb-8321-6791aae12684.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Removed the "ALL" results...only entities with main event completely within utterances are returned.  event with main part within utterance, but phase outside, will still be found.

Clear Search reset both search query and search result.

Closing.
