### ISSUE TITLE
Fields set to display globally do not display

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#426]
10.12.6

<img width="1077" alt="Screen Shot 2021-05-04 at 1 44 45 PM" src="https://user-images.githubusercontent.com/13629122/117046750-0bc3d500-acdf-11eb-8682-3f9008b583c9.png">

**Comment by cneidle** [comment]
Actually not having much luck displaying non-manual fields at all:

<img width="1377" alt="Screen Shot 2021-05-04 at 1 47 37 PM" src="https://user-images.githubusercontent.com/13629122/117046998-5b0a0580-acdf-11eb-87ae-615b527e72d2.png">

**Comment by cneidle** [comment]
[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6423019/SignStreamOut.txt)

**Comment by cneidle** [comment]
The fields do show up when I save the file, close, and reopen.

**Comment by cneidle** [comment]
Search is not working for non-manuals either...  Raised eyebrows is present only in U3, but...

<img width="887" alt="Screen Shot 2021-05-04 at 1 54 37 PM" src="https://user-images.githubusercontent.com/13629122/117047852-55f98600-ace0-11eb-917f-8d9b1874d461.png">

**Comment by foltik** [comment]
Unable to reproduce the issues with displaying fields in SignStream4_4.0.0_convergence_2021_04_30_1705_4dc238f4, will need to be demonstrated to fix.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Global field display appears to be working.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

per utterance/segment and segment appear also to be working.

**Comment by douglas-motto-at-rutgers** [comment]
As of As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

per utterance/segment, per segment and global settings appear to save and load.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

"ALL" result in search has been removed.

**Comment by douglas-motto-at-rutgers** [comment]
Closing.
