### ISSUE TITLE
Database view

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#427]
10.12.6

The navigation bar for the Database window is like this in SS 3.3.5

<img width="1308" alt="Screen Shot 2021-05-04 at 2 12 50 PM" src="https://user-images.githubusercontent.com/13629122/117050152-08324d00-ace3-11eb-80fb-e24944ebe17e.png">

but like this in the newest version:

<img width="1397" alt="Screen Shot 2021-05-04 at 2 13 32 PM" src="https://user-images.githubusercontent.com/13629122/117050174-0ec0c480-ace3-11eb-9b91-414bb2228063.png">

Aside for the things I have already pointed out, there is no need for "Entity" at this level; it is meaningless.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

Removed the "Green Bar"/"Set To"....although if making future improvements to the Display Time Period, or to multiple current times, may want to consider putting it back in.

As for Entity in db view....would like to keep it there as to not have (to code) different toolbars from db to utterance views....Could gray out as a compromise...although in utterance view simple events are same as entities.


Closing....Currently Entity not grayed out in DB view.  If further changes desired...reopen.
