### ISSUE TITLE
Whitescreen erroneously appears while zooming and side-scrolling

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#43]
Steps to reproduce:
1) Open up any collection
2) Click into an utterance which does not start on frame 0 (so there is some of the video to the "left" of it)
3) Zoom in using the top-left zoom bar (directly above the nonmanual section names) and make the utterance extend beyond the point where the window ends
4) Side-scroll using either the video slider or the horizontal slider in the main SignStream window
5) If you scroll to the left of the beginning, you will start to see a whitescreen where the nonmanual and manual sections are supposed to be

Ideally, you should be able to side-scroll beyond the start/end of an utterance, but the utterance window shouldn't display anything beyond its own start/end boundaries.

**Comment by blazetravis** [comment]
This bug is fixed.
