### ISSUE TITLE
Problem with display of sign type

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#430]
First, sign type should be displayed by default.

It was not showing.

<img width="753" alt="Screen Shot 2021-05-04 at 2 48 27 PM" src="https://user-images.githubusercontent.com/13629122/117054315-f7380a80-ace7-11eb-834b-f1cd4a2ddd63.png">

I went to the field spec editor and checked those fields for display, and the fields showed up, but without the values.

<img width="878" alt="Screen Shot 2021-05-04 at 2 48 50 PM" src="https://user-images.githubusercontent.com/13629122/117054385-0c149e00-ace8-11eb-99ad-cb7312a4465b.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_07_1730_e1dd7d21

Sign type displays.

Closing.
