### ISSUE TITLE
Ability to enter handshapes by typing letters is gone!

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#431]
10.12.6

This from 3.3.5 - a very useful feature to allow for typing in handshapes by their corresponding letters.

<img width="1053" alt="Screen Shot 2021-05-04 at 5 15 24 PM" src="https://user-images.githubusercontent.com/13629122/117071003-82bb9680-acfc-11eb-8e77-9b20c6c9ba35.png">

Gone from the latest version:

<img width="1057" alt="Screen Shot 2021-05-04 at 5 14 17 PM" src="https://user-images.githubusercontent.com/13629122/117071019-8818e100-acfc-11eb-9f5c-99c72076d8df.png">

**Comment by cneidle** [comment]
Also, as previously reported #412, the size and spacing of the handshape palette information was much better in 3.3.5, as well as size and coloring of handshape images more generally.

3.3.5

<img width="459" alt="Screen Shot 2021-05-04 at 5 22 07 PM" src="https://user-images.githubusercontent.com/13629122/117071612-50f6ff80-acfd-11eb-92f0-7e7ca91721df.png">


latest version

<img width="780" alt="Screen Shot 2021-05-04 at 5 19 14 PM" src="https://user-images.githubusercontent.com/13629122/117071457-26a54200-acfd-11eb-90f8-9f85ec8d25bc.png">

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_12_1358_4383c01a

The spacing is due to the ability now to resize the window.

The letters by keyboard press was there but at the bottom of a scroll.  Changed that to always appear without needing to scroll.

Closing.
