### ISSUE TITLE
Entering gloss text requires carriage return or it is lost

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#432]
This was reported some time ago and I thought it had gotten fixed.

But if I type text into the Gloss field and click elsewhere (without typing a return), the data is lost.

<img width="541" alt="Screen Shot 2021-05-04 at 5 25 05 PM" src="https://user-images.githubusercontent.com/13629122/117072117-fd38e600-acfd-11eb-8507-ec63ed87a7aa.png">

<img width="655" alt="Screen Shot 2021-05-04 at 5 25 09 PM" src="https://user-images.githubusercontent.com/13629122/117072125-00cc6d00-acfe-11eb-8456-78e5b06f1f88.png">

**Comment by cneidle** [comment]
still a problem for where you have ti option click in order to be able to enter text.  Can take lots and lots of attempts before it works.

both of these problems previously reported in #392.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_07_1730_e1dd7d21

Fixed.

Closing.
