### ISSUE TITLE
Text missing at left of utterance window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#433]
Compare 3.3.5:

<img width="163" alt="Screen Shot 2021-05-04 at 5 29 00 PM" src="https://user-images.githubusercontent.com/13629122/117072367-51dc6100-acfe-11eb-9f40-87f15d3f7926.png">

to current version:

<img width="170" alt="Screen Shot 2021-05-04 at 5 28 36 PM" src="https://user-images.githubusercontent.com/13629122/117072387-5a349c00-acfe-11eb-9378-f3addb852283.png">

Text is cut off although there is plenty of room for it.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_07_1730_e1dd7d21

the "..." removed.

Closing.
