### ISSUE TITLE
Buttons to resize video windows have labels reversed in the 2nd May 3rd version

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#434]
11.3.1 

The button in the lower right corner of the video window to make the video small says "lg" and the one to make the video large says "sm".  

<img width="848" alt="Screen Shot 2021-05-09 at 1 09 10 PM" src="https://user-images.githubusercontent.com/13629122/117580859-f9bfa900-b0c7-11eb-92a3-316ff6512d15.png">

<img width="415" alt="Screen Shot 2021-05-09 at 1 09 16 PM" src="https://user-images.githubusercontent.com/13629122/117580871-017f4d80-b0c8-11eb-9d68-142e7547dae3.png">

**Comment by cneidle** [comment]
This bug still exists in release candidate 4.1.  It is also still the case that clicking on the button to resize the video windows only resizes the current window rather than all the windows (as it should do).

**Comment by gregorydimitriadis** [comment]
Will be fixed in the next release.

**Comment by foltik** [comment]
Fixed in `SignStream4_4.1.0_pre_2021_05_13_1245_71f3a686`

**Comment by cneidle** [comment]
Confirmed fixed.
