### ISSUE TITLE
Setting start or end of selected gloss does not work

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#436]
testing on OS 11.3.1 

I created the gloss.  Then clicked on it so that it is selected (and highlighted in red).  Clicking on the set start (or end) button has no effect.

The whole program has frozen now.   No other operations work immediately.  Although after some time this works again, although what I had typed into that utterance disappeared entirely.

<img width="401" alt="Screen Shot 2021-05-13 at 9 42 10 AM" src="https://user-images.githubusercontent.com/13629122/118134342-d0589300-b3cf-11eb-870e-44f88d3caf46.png">

Am quitting, attaching SignStream out file, and will restart.  So far, nothing has actually worked properly...

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6472770/SignStreamOut.txt)

**Comment by foltik** [comment]
Tested selecting and setting start/end of glosses to be working as of `SignStream4_4.1.0_pre_2021_05_13_1245_71f3a686`
