### ISSUE TITLE
Unable to open the file that I just saved.

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#437]
OS 11.3.1

<img width="823" alt="Screen Shot 2021-05-13 at 9 47 58 AM" src="https://user-images.githubusercontent.com/13629122/118134929-71dfe480-b3d0-11eb-81f1-583efacd4373.png">

**Comment by cneidle** [comment]
This problem persists.

<img width="828" alt="Screen Shot 2021-05-13 at 10 01 35 AM" src="https://user-images.githubusercontent.com/13629122/118136580-44943600-b3d2-11eb-8dfe-676cca0ee382.png">

**Comment by foltik** [comment]
Confirmed saving and loading works in `SignStream4_4.1.0_pre_2021_05_13_1245_71f3a686`.

Note that 4.1.0 cannot yet open .ss3 files, and 3.7.0 cannot open .ssc files.

**Comment by cneidle** [comment]
Confirmed fixed.
