### ISSUE TITLE
Once "open collection" is aborted, no way to select videos without restarting the program

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#438]
OS 11.3.1 

This is not a new issue, but it persists in this newest version.

I was going open a collection but clicked on "cancel" - now there is no way to edit the macro unit to add videos to the collection file that initially opened.

<img width="459" alt="Screen Shot 2021-05-13 at 9 50 10 AM" src="https://user-images.githubusercontent.com/13629122/118135413-fcc0df00-b3d0-11eb-99c7-8094a2a3633c.png">

**Comment by cneidle** [comment]
[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6472830/SignStreamOut.txt)

**Comment by foltik** [comment]
Fixed in `SignStream4_4.1.0_pre_2021_05_13_1245_71f3a686`

**Comment by cneidle** [comment]
confirmed fixed.
