### ISSUE TITLE
New Blank Collection does not work

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#440]
Choosing that option from the menu

<img width="208" alt="Screen Shot 2021-05-13 at 10 03 25 AM" src="https://user-images.githubusercontent.com/13629122/118136863-9210a300-b3d2-11eb-9b18-a16c0f783904.png">

does not display a macro unit window, and it is impossible to edit the macro unit from the menu.

<img width="322" alt="Screen Shot 2021-05-13 at 10 03 12 AM" src="https://user-images.githubusercontent.com/13629122/118136890-98068400-b3d2-11eb-9604-b7c9dd204c86.png">

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6472900/SignStreamOut.txt)

**Comment by foltik** [comment]
Fixed in `SignStream4_4.1.0_pre_2021_05_13_1245_71f3a686`

**Comment by cneidle** [comment]
confirmed fixed.
