### ISSUE TITLE
stepping unit when only a video file is linked in should be = one frame

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#441]
OS 11.3.1 

I imagine this will be resolved when the new version 3 is created, but if there is only a video file linked in and no audio file, then the step interval should be one frame for all operations (e.g, use of + or - buttons, arrow key, etc.)

**Comment by foltik** [comment]
This is the behavior as of:
`SignStream4_4.1.0_pre_2021_05_13_1245_71f3a686`
`SignStream3_3.7.0_pre_2021_05_13_1248_d68597c6`

**Comment by cneidle** [comment]
confirmed fixed.
