### ISSUE TITLE
Problem with Morph-Phon window losing its association with the gloss that was selected when it was opened.

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#442]
Unable to enter this from the MorphPhon window:

<img width="599" alt="Screen Shot 2021-05-13 at 10 14 43 AM" src="https://user-images.githubusercontent.com/13629122/118138390-4101ae80-b3d4-11eb-9370-c84dccc9be1f.png">

FWIW, I tried (2) again and did not have a problem.  I also noticed after I reported (2) that the current frame seemed to be in a different utterance.  I had not done anything that should have caused that to happen, but perhaps the problem in (2) was related to that.

**Comment by cneidle** [comment]
The speculation at the bottom of the previous comment has some confirmation.  I opened the MorphPhon window and changed the position of the current frame, and am unable to enter the information.  That should not be the case.
The association between the gloss that was clicked on when the MorphPhon window was open and the information in the. MorphPhon window itself should be maintained, regardless of current frame, and the entry of information should go to that originally opened gloss.

<img width="1367" alt="Screen Shot 2021-05-13 at 10 22 01 AM" src="https://user-images.githubusercontent.com/13629122/118139250-2bd94f80-b3d5-11eb-89a9-cd2f6507fa75.png">

**Comment by cneidle** [comment]
With respect to the last issue, scrolling back into range also does not make it possible to enter the information.

<img width="605" alt="Screen Shot 2021-05-14 at 10 08 52 AM" src="https://user-images.githubusercontent.com/13629122/118282646-8093cd80-b49c-11eb-9706-7782efe1463c.png">

**Comment by douglas-motto-at-rutgers** [comment]
Carol, Unclear if this is multiple issues.  If so, please create separate issues if so.

With regard to being unable to change the gloss, after opening the morphphon...did you click on an utterance in the utterance index (on the left)...and then it not work?

**Comment by douglas-motto-at-rutgers** [comment]
I believe Jack has direction to go...it's related to issue 258.  He'll require that events can not be selected or unselected while the morph is open and that should correct this.

**Comment by foltik** [comment]
As `SignStream4_4.1.0_pre_2021_05_14_1715_39304367` and `SignStream3_3.7.0_pre_2021_05_14_1713_f4fd6844`, the currently selected gloss or gesture cannot be deselected while the morph-phon or gesture info windows are open.

**Comment by cneidle** [comment]
confirmed fixed.

**Comment by douglas-motto-at-rutgers** [comment]
I think this is NOT fixed 100% yet.

**Comment by foltik** [comment]
Fixed remaining situations where other events could be selected or double clicked with the morph-phon window open in May 24th build.
