### ISSUE TITLE
Field selections do not stick

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#444]
1. I entered the following and clicked on DONE.

<img width="1079" alt="Screen Shot 2021-05-14 at 10 15 02 AM" src="https://user-images.githubusercontent.com/13629122/118284115-1419ce00-b49e-11eb-8794-f0b7ad3817ab.png">

It appears in the current utterance, and the subsequent utterance.

<img width="1007" alt="Screen Shot 2021-05-14 at 10 16 08 AM" src="https://user-images.githubusercontent.com/13629122/118284368-593e0000-b49e-11eb-8f10-6927f1cfcefd.png">

<img width="834" alt="Screen Shot 2021-05-14 at 10 15 13 AM" src="https://user-images.githubusercontent.com/13629122/118284288-46c3c680-b49e-11eb-974d-c54f5de70f3c.png">

2. When I save the file and reopen, only non-empty fields show up and the selections in the field selection editor are completely empty.

<img width="715" alt="Screen Shot 2021-05-14 at 10 23 58 AM" src="https://user-images.githubusercontent.com/13629122/118284514-838fbd80-b49e-11eb-9e03-63f8fe1d6678.png">

<img width="1179" alt="Screen Shot 2021-05-14 at 10 24 35 AM" src="https://user-images.githubusercontent.com/13629122/118284618-9efac880-b49e-11eb-8082-d2f0a945cf5f.png">

**Comment by douglas-motto-at-rutgers** [comment]
Carol, the signstream version 3 XML does not have the necessary items to save this information.

I'll speak with Jack about options.

**Comment by douglas-motto-at-rutgers** [comment]
Will see if it's something that can be incorporated into ver 3 xml without breaking anything else.

I the 3.3.1 code the select in the field editor was completely temporary....so at least...this selection stays within the session.

**Comment by foltik** [comment]
What we could do is have version 3.7 **modify** the old collection files to include the extra data describing which fields are displayed.

You would be able to save and load the displayed fields properly with 3.7, but old versions of SignStream would ignore this extra data and fall back to the original method of displaying non-empty fields.

**Comment by foltik** [comment]
Implemented the above method as of `SignStream3_3.7.0_pre_2021_05_14_1713_f4fd6844`.

If you do not want to modify old collections as described, be sure to make a copy of them before editing and saving with 3.7. Again, please make copies of __all__ collections before using them with any experimental release.

**Comment by cneidle** [comment]
Selections still do not stick.

Created new file.  Made field selection.

<img width="966" alt="Screen Shot 2021-05-14 at 9 56 38 PM" src="https://user-images.githubusercontent.com/13629122/118344965-6b03bf80-b4ff-11eb-84f2-0ae20de38aef.png">

Saved.

Reopened.

Field selections are gone.

<img width="993" alt="Screen Shot 2021-05-14 at 9 57 23 PM" src="https://user-images.githubusercontent.com/13629122/118344967-72c36400-b4ff-11eb-84cc-d577c7312323.png">

**Comment by douglas-motto-at-rutgers** [comment]
Confirm...not fixed as of SignStream3_3.7.0_pre_2021_05_14_1713_f4fd6844.

**Comment by foltik** [comment]
Mistakenly didn't include the code change in the previous build; included and fixed as of `SignStream3_3.7.0_pre_2021_05_19_1003_86750a7c`.
