### ISSUE TITLE
Field Selector - Manual options not provided

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#445]
The new version 3.7 only offers this:

<img width="1132" alt="Screen Shot 2021-05-14 at 11 48 19 AM" src="https://user-images.githubusercontent.com/13629122/118295938-6f51bd80-b4aa-11eb-9f90-8ec37f2a5213.png">

whereas previously, there was:
  dom location
  nondom location
  dom sign type
  ndom sign type

The default in any case should be to display the last two if and only if they are non-empty.  All other manual tiers are automatically displayed.

**Comment by douglas-motto-at-rutgers** [comment]
Carol,

As of SignStream3_3.7.0_pre_2021_05_13_1435_24758fd0

I do see these fields as being selectable and their defaults appear to be off.

<img width="1170" alt="Screen Shot 2021-05-14 at 1 06 05 PM" src="https://user-images.githubusercontent.com/13223830/118306058-d8d7c900-b4b6-11eb-8a1a-bebd72625cb3.png">

Can you provide more information about how you did not see them...did you do something before or open a collection file...something that may have caused this.

**Comment by cneidle** [comment]
I was looking at the file I just sent you: Cory 106 - and this still shows up the same way:

**Comment by douglas-motto-at-rutgers** [comment]
We see something odd with the collection file.  Thinking about the proper direction to go for a solution.

**Comment by douglas-motto-at-rutgers** [comment]
Believe to be an XML problem.

Need to think about how best to deal with all these XML problems.

**Comment by douglas-motto-at-rutgers** [comment]
Fields appear to need belong to a "group".  Some fields where previously editable and got edited, but the editing process was broken in such a way that the group was set to "".  This caused the application to fail when expecting a group to exist.

Handling orphaned groups, non-existing groups, and custom groups have been considered.

Solution for right now is for us to correct this specific XML file manually.   Please send.

If this is more that just this file, please inform.

**Comment by gregorydimitriadis** [comment]
@gregdimi verify exists in current working version

**Comment by gregorydimitriadis** [comment]
Working in current pending version. XML issues involving orphaned GROUP will be handled separately. Closing this out.
