### ISSUE TITLE
Field selector - buttons on the right

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#446]
In version 3, there should be no option to Set Field to Utterance Index.

However, the New Nonmanual Field button should be functional (which it is not).

<img width="287" alt="Screen Shot 2021-05-14 at 11 52 14 AM" src="https://user-images.githubusercontent.com/13629122/118296465-01f25c80-b4ab-11eb-82a2-9cb6562152af.png">

**Comment by douglas-motto-at-rutgers** [comment]
Will do.

**Comment by foltik** [comment]
The New Nonmanual Field button requires you to select a nonmanual group such as Face before becoming enabled. Was this the problem?

**Comment by cneidle** [comment]
Yes.  That was the problem.

Why is that necessary?  There’s a dropdown menu to select the region once
you get to the window for creation of a new non-manual item.








If it is necessary, it would be good to so indicate, e.g.


[New non-manual field]

Select Head, Face, Body, or Grammatical first


Thanks,
 Carol

**Comment by foltik** [comment]
I just added the dropdown for the group a few versions ago, so yes as of now it's no longer necessary. As of `SignStream4_4.1.0_pre_2021_05_14_1715_39304367`, buttons are no longer disabled. Dropdown in new field dialog uses selected group if valid, defaulting to Head for nonmanual fields and Generic for default fields.

As of `SignStream3_3.7.0_pre_2021_05_14_1713_f4fd6844`, utterance index button is removed.

**Comment by cneidle** [comment]
confirmed fixed.
