### ISSUE TITLE
Problem with Gesture Sign Type Entry

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#448]
<img width="843" alt="Screen Shot 2021-05-14 at 1 37 26 PM" src="https://user-images.githubusercontent.com/13629122/118308114-95328e80-b4b9-11eb-8ac8-33057683b52c.png">

**Comment by cneidle** [comment]
FWIW, NO PROBLEM entering Gesture sign type without any handshapes selected.  This only fails when handshapes have been selected in the MorphPhon window.

**Comment by gregorydimitriadis** [comment]
will be fixed in next release of both ver3 and ver4
