### ISSUE TITLE
Problem in dealing with phases (like final hold)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#450]
Compare how the sign ACCEPT  should appear (in 3.3.5), with a final hold (phase):

<img width="275" alt="Screen Shot 2021-05-14 at 6 01 55 PM" src="https://user-images.githubusercontent.com/13629122/118336126-13edf280-b4df-11eb-9610-1da1b052608a.png">

with how it does appear in the latest version of 3.7 (from 5 pm tonight) - the rightmost item shown here:

<img width="866" alt="Screen Shot 2021-05-14 at 6 03 10 PM" src="https://user-images.githubusercontent.com/13629122/118336137-181a1000-b4df-11eb-9c24-caae77693945.png">

I had noticed this in the version from earlier this afternoon but had not had a chance to document it until now.

**Comment by cneidle** [comment]
Another example (there are lots of them!) from 43, U21

<img width="382" alt="Screen Shot 2021-05-14 at 6 12 17 PM" src="https://user-images.githubusercontent.com/13629122/118336615-09802880-b4e0-11eb-9cc1-4f3cca815774.png">

**Comment by cneidle** [comment]
Same problem with phases for nonmanual events, e.g. offsets... 

<img width="617" alt="Screen Shot 2021-05-14 at 6 14 05 PM" src="https://user-images.githubusercontent.com/13629122/118336719-3a605d80-b4e0-11eb-8240-e719772e2938.png">

**Comment by douglas-motto-at-rutgers** [comment]
Are these examples just occurring when opening old collections/evens...or with new collections/events as well?

**Comment by cneidle** [comment]
This is what happens when collections created with previous versions of the program are opened.
But we need to be able to open and continue editing these older files, and there are huge numbers of items with phases in those files.

**Comment by gregorydimitriadis** [comment]
@cneidle what is the collection in use here? Can it be attached here? Thanks.

**Comment by cneidle** [comment]
This is Utterance 3 from Rachel 43.  But it happens 100% of the time in all files previously edited in 3.3.5.  I can't upload SIgnStream files here, but will send it by email.  Here's another example, from 1-Ben

<img width="1192" alt="Screen Shot 2021-05-19 at 2 08 11 PM" src="https://user-images.githubusercontent.com/13629122/118862885-3a7ba700-b8ac-11eb-97c8-5c0584c2c3b4.png">

**Comment by gregorydimitriadis** [comment]
So this was due to the values of the phases saved in the xml not being properly translated in/out from the collection file. This will be fixed in the next ver3 release.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream3_3.7.0_pre_2021_05_19_1728_c2f3e14a

Appears to be working with the Cory 106 ss3 file.

Closing.
