### ISSUE TITLE
Arrow keys do not work for navigation in left index

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#451]
The arrow keys do not work to move to the next or previous utterance in the left-hand index.

<img width="457" alt="Screen Shot 2021-05-14 at 6 10 20 PM" src="https://user-images.githubusercontent.com/13629122/118336426-aa221880-b4df-11eb-9a93-929b67a6969a.png">

**Comment by cneidle** [comment]
Arrow keys seem to work when new files are created, but not with the above (at least) previously annotated file.

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream3_3.7.0_pre_2021_05_14_1713_f4fd6844

doesn't appear to exist.  Up/Down utterance switching works for a new collections.

Is this the Cory XML?  Could be related to XML issues in that file.

Otherwise, does it work and then after doing some things it breaks?

Leaving open for the moment.

**Comment by cneidle** [comment]
No - arrow keys for moving up and down in the left index of utterances also do not work for me in newly created collections.

<img width="962" alt="Screen Shot 2021-05-17 at 10 36 38 AM" src="https://user-images.githubusercontent.com/13629122/118507054-e03be400-b6fb-11eb-94e0-ebb6c6d1d07c.png">

**Comment by cneidle** [comment]
It is very flaky.  It works less than 50% of the time. Sometimes clicking on the selected utterance before using the arrow key gets it to work for a while (that should not be necessary, in any case), and sometimes it does not. 

One case in which the arrow keys do *not* seem to work is first clicking on a specific utterance, e.g., U3, and then immediately trying to use the arrow key to go to the next or previous one.

**Comment by douglas-motto-at-rutgers** [comment]
In SignStream3_3.7.0_pre_2021_05_19_1003_86750a7c

This "at least" occurs after click on the prev/next buttons...then the arrow keys stop working...then you'd need to re-click the utterance index.

**Comment by cneidle** [comment]
Still do not work as of 5/21

Oh wow!  The up and down arrow change the selected/highlighted field !  The up arrow does this:

<img width="1441" alt="Screen Shot 2021-05-21 at 12 59 21 PM" src="https://user-images.githubusercontent.com/13629122/119172899-7772a580-ba34-11eb-9b6e-945b42c06387.png">

<img width="1437" alt="Screen Shot 2021-05-21 at 12 59 28 PM" src="https://user-images.githubusercontent.com/13629122/119172910-7b062c80-ba34-11eb-85ae-5ce3adca069a.png">

<img width="1454" alt="Screen Shot 2021-05-21 at 12 59 34 PM" src="https://user-images.githubusercontent.com/13629122/119172923-7e99b380-ba34-11eb-9aa8-93b76886dfcd.png">

**Comment by foltik** [comment]
The up and down arrow keys aren't a global hotkey, they apply to the UI element that has keyboard focus. This hasn't changed in the new versions.

If you click in the field list (red highlight on ndom hand in your last screenshot), then the arrow keys will apply to that instead until you click somewhere else.

Individual elements can be made to not take keyboard focus at all, which I can do for the prev/next buttons or any others you suggest.

**Comment by cneidle** [comment]
Up through 3.3.5, the up and down arrows change the selection of the Utterance on the left by moving it up and down.

You can have a gloss selected. Or a non-manual event. The arrow keys still have the same effect: moving up and down through the utterance list.

They do not apply to anything else.

This is not what is happening in the version you sent.

**Comment by douglas-motto-at-rutgers** [comment]
Fixed as of..

SignStream4_4.0.0_convergence_2021_05_12_1551_3d417a80

Closing
