### ISSUE TITLE
Issue for the future: display of multiple segment tiers

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#453]
Display options should be able to be retained if you go from utterance view to database view and back again.

<img width="1095" alt="Screen Shot 2021-05-14 at 9 42 57 PM" src="https://user-images.githubusercontent.com/13629122/118344717-c9c83980-b4fd-11eb-84cd-c811dfafa8c7.png">

<img width="1043" alt="Screen Shot 2021-05-14 at 9 43 05 PM" src="https://user-images.githubusercontent.com/13629122/118344721-cdf45700-b4fd-11eb-8ee2-5cdc557c7839.png">

<img width="987" alt="Screen Shot 2021-05-14 at 9 43 19 PM" src="https://user-images.githubusercontent.com/13629122/118344726-d2207480-b4fd-11eb-9994-3e0d643723d6.png">

This is perhaps related to another issue we had discussed, about being able to return from the database view to the previous view in the utterance window.  Not sure what, if anything, came of that discussion...  

Just noting this while it occurs to me.

**Comment by douglas-motto-at-rutgers** [comment]
If you click on any utterance from the database view, you only get that segment opened.  If "unlocked" it will zoom and scroll to that utterance.  If "locked" it will scroll to that utterance, but leave the zoom at the last setting.

If you click on "Go to utterance view", you get exactly all previous segments opened in the utterance view.  The zoom and scroll returns to were it was the last opened.
