### ISSUE TITLE
Readme for 3.7

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#455]
1. The Readme needs to be updated throughout to refer to SignStream® 3(.7.0) rather than SIgnStream® 4.

2. Are the video CODECs listed up to date?  This should be removed:

> -----AUDIO CODECS
> 
> Audio codecs that work with the application; if your standalone audio is in a different format, you should first convert it to one of these:
> 
> * WAV (.wav)
> 
> Additionally, the application can read any associated audio stream from a supported video codec.

3. Can you please update the KNOWN ISSUES and FEATURES TO BE IMPLEMENTED?   Many of the "known issues" are no longer issues, to my knowledge, and these should no longer be listed as "to be implemented":  

> (3) Functionalities for editing field types and properties in the Field Specifications Editor.
>( 5) Warning about existence of unsaved data when quitting the application.

4. RELEASE NOTES (which should be for Version 3)  are still listed as TBD.

**Comment by foltik** [comment]
Changed 4->3, removed audio section, removed old known issues. Leaving open for release notes and additional known issues.

**Comment by cneidle** [comment]
Are these not resolved ??

-----KNOWN ISSUES

1) Color selection of nonmanual fields may not work as expected.
2) When creating a new nonmanual field, many of the options to edit field parameters do not work.
3) Search window
  a) Clicking on the listing of sentences in the search results does not always open the correct sentence.
  b) Warning to users:  Closing the window displaying an utterance from the search results will quit the program, with no option to open a new search result.

need to complete Readme text

**Comment by gregorydimitriadis** [comment]
I think the color selection, while somewhat working, has some bugs remaining. I believe it works within the application before it is closed/quit, but then when re-opened the colors don't persist.

If this is 'okay' we can remove #2 as I believe the other properties work.

Regarding search: the quitting of the window will still occur. Clicking the listings to see the correct sentence - probably is working so can be removed.

**Comment by gregorydimitriadis** [comment]
The readme is up to date in latest release - version 3.4.0
