### ISSUE TITLE
Adding onsets and offsets not working properly - these are created way larger than they should be

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#457]
3.7.0_pre_2021_05_21_0908_cd9209c7

ios 10.12.6

<img width="1129" alt="Screen Shot 2021-05-21 at 11 14 18 AM" src="https://user-images.githubusercontent.com/13629122/119159895-b9481f80-ba25-11eb-95fc-5cc0a949810c.png">

<img width="1047" alt="Screen Shot 2021-05-21 at 11 15 10 AM" src="https://user-images.githubusercontent.com/13629122/119160076-e3014680-ba25-11eb-9b05-ef6c8b539597.png">

**Comment by cneidle** [comment]
Same thing happens with manual signs.  I added an onset and offset.  Same issue.  I then tried to add an initial hold, which is totally compatible with having an onset, and got this error message:

<img width="1126" alt="Screen Shot 2021-05-21 at 11 18 04 AM" src="https://user-images.githubusercontent.com/13629122/119160485-54d99000-ba26-11eb-8043-2d452f428c07.png">

**Comment by cneidle** [comment]
A not-unexpected corollary to the above:  It is not possible to add an onset unless there is a huge amount of free space available for it.

<img width="919" alt="Screen Shot 2021-05-21 at 12 44 03 PM" src="https://user-images.githubusercontent.com/13629122/119171272-590baa80-ba32-11eb-9d68-6073250fd993.png">

**Comment by douglas-motto-at-rutgers** [comment]
Can not reproduce in

SignStream4_4.1.0_pre_2021_05_21_0909_15a705be
SignStream3_3.7.0_pre_2021_05_21_0908_cd9209c7

Send collection.

What video are you using?...it says 30 FPS.

**Comment by cneidle** [comment]
Download full resolution images
Available until Jun 20, 2021
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FATzuz6kmnwUmlLzDC4fbNOrENoafAaRTW8QANdZ8tWLlYiQxos5mbP5J%2F%24%7Bf%7D%3Fo%3DAg2rsi95_sN3L4vQM-czeVP_LU0iOoDesKz2qd-rSmsg%26v%3D1%26x%3D3%26a%3DCAog4Ti65jElCFCa4fnD7CcHjlbvkClQB0ZUo_XobPRiUYgSdBCH_qWEmS8Yh46h2KIvIgEAKgkC6AMA_yVh6N5SBMQ2hp9aBGZs_klqJPvUfsN__3PXQRI6C6cDynas3zpK0_CzqzYcKhdI_sVn6ngTBXIk0gwTajOPKkuQcFg6b4JP40G4eFudL67OvYgQQ9tSbwNypYU8%26e%3D1624219600%26fl%3D%26r%3D70F60A2E-74AD-40DD-A1EA-887AEEF4DF8D-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D309D2BFD-1216-4681-A069-8CF12C65BF5F%26p%3D102%26s%3DCHYKo1FaiKi4w2TReZUUUYIh4Gk&uk=KbWmZLNghoNMxSKNaU0GCw&f=Images.zip&sz=1521837>Here’s the file - and the video

Am now working on OS 10.12.6




And by the way, I am also unable to edit Macro Unit.



Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAbQ1iGeA7uMbwhTVrC0jLHTioF0QATphdGN5f0CUaWO-bMs3dhaHCuAK%2F%24%7Bf%7D%3Fo%3DAi5B9aHTCMA1fxyGSsUClaIPWqxdyjqLJXOVbRhZgPi-%26v%3D1%26x%3D3%26a%3DCAog1rQ_qrkjM90ezwHU_bzZg3TN9-RLlQfna8pmsh4hlSoSdBD6_6WEmS8Y-o-h2KIvIgEAKgkC6AMA_0jivLJSBOKgXRBaBIcK4ApqJMKXXi7BSd9R7z2WXy1UXJjuJokqWYR4CHDvn3ufCJlMFF9WQ3IkrYUKAtkNNHYqG_e4fbCueTquz_Hw8Xa6F8adpPi0eLQ2784Z%26e%3D1624219600%26fl%3D%26r%3D757735F1-878F-489A-B709-63993C1A120F-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D309D2BFD-1216-4681-A069-8CF12C65BF5F%26p%3D102%26s%3DIsfiaElJPTBivMHXbRMup2grCAI&uk=KuRnZmzLP4UQEoi0xZZs8g&f=Collection_5_21_2021_11_9_3.ss3&sz=4016>Collection_5_21_2021_11_9_3.ss3
4 KB

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAQ44N04bdwBFHNKOz5QIl4_-3nlrAceDlBeN_PT8WBSIUb_w2j0r51cq%2F%24%7Bf%7D%3Fo%3DApOAyGiz8bZc-Lv5YUNrBtHXmSqhKxi4R0CFf1baSIGL%26v%3D1%26x%3D3%26a%3DCAoguX6YpZIMsTfSHtXLZgiYYYloIx4MWmWgywwS1QJUm5cSdBD2gaaEmS8Y9pGh2KIvIgEAKgkC6AMA_wFZtjxSBP7eeWtaBCvnVypqJBwL2O6_i4cvCCoxdgGOObQeunq8M8oVliT9O0MM81wNep-fQnIk4ikDhjV-EH7XoMgQIpyJ-6dv-kcCAvVQFplR9xQsroMe-KtX%26e%3D1624219601%26fl%3D%26r%3D582A1C0E-EA88-412B-B277-91321807DF6B-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D309D2BFD-1216-4681-A069-8CF12C65BF5F%26p%3D102%26s%3DYqXM1m21JilTOB4inrL1Kvz5bTE&uk=k_pJbY5S5kWv5MwryaO0qw&f=P07_V01_new.mp4&sz=217768321>P07_V01_new.mp4
217.8 MB

**Comment by douglas-motto-at-rutgers** [comment]
was able to reproduce with a 30FPS video file.

**Comment by foltik** [comment]
Fixed as of `SignStream3_3.7.0_pre_2021_05_21_1657_31230ca4`.
