### ISSUE TITLE
Problem in focus

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#459]
I made am minor adjustment in the start point of an utterance (making it start a frame or two sooner), and the view totally changed!  This should not happen.

<img width="1027" alt="Screen Shot 2021-05-21 at 11 45 20 AM" src="https://user-images.githubusercontent.com/13629122/119164259-3aa1b100-ba2a-11eb-8a8a-a60855771a57.png">

<img width="929" alt="Screen Shot 2021-05-21 at 11 45 47 AM" src="https://user-images.githubusercontent.com/13629122/119164297-442b1900-ba2a-11eb-863b-67f912cef32e.png">

This is what SHOULD happen - as it does in 3.3.5:

<img width="1105" alt="Screen Shot 2021-05-21 at 11 49 16 AM" src="https://user-images.githubusercontent.com/13629122/119164720-b4399f00-ba2a-11eb-8f3a-d451537f384c.png">

<img width="1144" alt="Screen Shot 2021-05-21 at 11 49 26 AM" src="https://user-images.githubusercontent.com/13629122/119164746-b865bc80-ba2a-11eb-8820-1b9819d7c85b.png">

**Comment by douglas-motto-at-rutgers** [comment]
Behavior observed in

SignStream4_4.1.0_pre_2021_05_21_0909_15a705be
SignStream3_3.7.0_pre_2021_05_21_0908_cd9209c7

**Comment by foltik** [comment]
Fixed as of `SignStream3_3.7.0_pre_2021_05_25_1704_16f12c84` and `SignStream4_4.1.0_pre_2021_05_25_1708_694156a2`.
