### ISSUE TITLE
Incorrect error message - in setting start point of utterance to be the frame AFTER the end of the previous U

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#460]
First I go to the end of the first utterance: 129.07 seconds

<img width="685" alt="Screen Shot 2021-05-21 at 11 53 17 AM" src="https://user-images.githubusercontent.com/13629122/119165253-4cd01f00-ba2b-11eb-8baf-7a051af01c73.png">

Then I advance by one, 129.10 seconds, and try to establish that frame as the start of the next utterance.

<img width="1168" alt="Screen Shot 2021-05-21 at 11 53 30 AM" src="https://user-images.githubusercontent.com/13629122/119165328-5e192b80-ba2b-11eb-932a-bde1357a467e.png">

**Comment by douglas-motto-at-rutgers** [comment]
Behavior not observed in...

SignStream4_4.1.0_pre_2021_05_21_0909_15a705be
SignStream3_3.7.0_pre_2021_05_21_0908_cd9209c7

Send collection file.

**Comment by douglas-motto-at-rutgers** [comment]
What video are you using?...it says 30 FPS.

**Comment by cneidle** [comment]
This occurred with the same file and video I just sent.

**Comment by foltik** [comment]
This buggy behavior is caused by the collection being broken because of #454. Shouldn't occur with fresh collections created with `SignStream3_3.7.0_pre_2021_05_21_0908_cd9209c7`

**Comment by cneidle** [comment]
You are correct.  I must have accidentally opened the wrong version of SS.  (Too many versions floating around.). This OK with the latest version.  Thanks.
