### ISSUE TITLE
Problem changing the start/end point of a sign when it has an onset/offset

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#461]
I reset the onset to be a reasonable length (about 10 frames or so), but cannot adjust the start point of the core event using the - button.  Same exact problem with the mirror image: trying to extend the endpoint by one frame.

<img width="450" alt="Screen Shot 2021-05-21 at 12 46 26 PM" src="https://user-images.githubusercontent.com/13629122/119171565-c0c1f580-ba32-11eb-9f41-eec326ac9716.png">

**Comment by douglas-motto-at-rutgers** [comment]
Not observing this behavior in...

SignStream4_4.1.0_pre_2021_05_21_0909_15a705be
SignStream3_3.7.0_pre_2021_05_21_0908_cd9209c7

Did you do anything else before this?

Send collection file.

**Comment by cneidle** [comment]
Same problem - new file - new version of SignStream.  Tried to adjust the endpoint of the gloss after adding an offset.

<img width="391" alt="Screen Shot 2021-05-21 at 4 40 49 PM" src="https://user-images.githubusercontent.com/13629122/119195908-5ec5b800-ba53-11eb-8ac9-0efbc3167836.png">

Also with video P07_V01    OS 10.12.6

**Comment by douglas-motto-at-rutgers** [comment]
This is likely related to

https://github.com/DCS-LCSR/SignStream3/issues/457

which involves a 30 fps video.

**Comment by foltik** [comment]
Looks to be working as of `SignStream3_3.7.0_pre_2021_05_21_1657_31230ca4` with the fix for #457.
