### ISSUE TITLE
Error trying to set start and end of utterance.

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#462]
I created a new file with the latest version of SIgnStream, Clicked to create U1 and then tried to set its start point.  Error.

<img width="276" alt="Screen Shot 2021-05-21 at 4 21 59 PM" src="https://user-images.githubusercontent.com/13629122/119194305-e1994380-ba50-11eb-96f2-3f41624e363d.png">

<img width="1047" alt="Screen Shot 2021-05-21 at 4 21 46 PM" src="https://user-images.githubusercontent.com/13629122/119194291-dcd48f80-ba50-11eb-9846-ba00287a8723.png">

Same problem trying to set the end point.

<img width="990" alt="Screen Shot 2021-05-21 at 4 24 23 PM" src="https://user-images.githubusercontent.com/13629122/119194425-08f01080-ba51-11eb-96d2-ee97dcf3d48c.png">

Video: P07_V01

**Comment by cneidle** [comment]
This same file - still with newest version of SignStream came to look like this!  Not sure how that happened, but it should not be possible.

<img width="1108" alt="Screen Shot 2021-05-21 at 4 55 35 PM" src="https://user-images.githubusercontent.com/13629122/119197255-72721e00-ba55-11eb-9412-548e9112af76.png">

**Comment by cneidle** [comment]
Will send this collection by email.

**Comment by douglas-motto-at-rutgers** [comment]
Again...likely an issue with 30 fps videos.

**Comment by foltik** [comment]
Fixed as of `SignStream3_3.7.0_pre_2021_05_21_1657_31230ca4`.
