### ISSUE TITLE
Unable to select the Translation field for editing

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#464]
OS 11.4.  SS- May26 

This is a new problem.  This has been working fine for a very long time (although this issue or something similar was previously reported).  Nothing happens when I click or double-click on the translation in any of the sentences in this file.

<img width="824" alt="Screen Shot 2021-05-26 at 12 42 14 PM" src="https://user-images.githubusercontent.com/13629122/119699225-ea5a9280-be1f-11eb-8d86-2da2928a057e.png">

**Comment by douglas-motto-at-rutgers** [comment]
Translation code was changed to allow the removal of events being constrained within utterances.  Issue could have been introduced.

**Comment by douglas-motto-at-rutgers** [comment]
Reproducible with old collection files.

**Comment by foltik** [comment]
Fixed as of `SignStream3_3.7.0_pre_2021_05_26_1633_f4b57607`.
