### ISSUE TITLE
Save as - default file name not appearing

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#465]
Mac OS 10.12.6 - THU May 27

I believe I reported this previously, but "Save as" should provide the current filename (not the containing folder name).

<img width="804" alt="Screen Shot 2021-05-27 at 10 57 09 AM" src="https://user-images.githubusercontent.com/13629122/119849543-b6907300-beda-11eb-85d1-b3e3f65773f0.png">

**Comment by foltik** [comment]
Fixed as of `SignStream3_3.7.0_pre_2021_05_27_1708_5e4dc83b`.

**Comment by cneidle** [comment]
confirmed fixed
