### ISSUE TITLE
File validation (!)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#467]
Not promising so far...

<img width="908" alt="Screen Shot 2021-05-27 at 5 35 25 PM" src="https://user-images.githubusercontent.com/13629122/119900109-0c344200-bf12-11eb-8322-3b66c92d9681.png">

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6556949/SignStreamOut.txt)

**Comment by cneidle** [comment]
<img width="982" alt="Screen Shot 2021-05-27 at 5 37 45 PM" src="https://user-images.githubusercontent.com/13629122/119900276-50274700-bf12-11eb-9cc9-55e3c4265cc5.png">

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6556960/SignStreamOut.txt)

**Comment by cneidle** [comment]
<img width="707" alt="Screen Shot 2021-05-27 at 5 39 25 PM" src="https://user-images.githubusercontent.com/13629122/119900459-8cf33e00-bf12-11eb-8f8d-a31cc2fae785.png">

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6556969/SignStreamOut.txt)

**Comment by cneidle** [comment]
it's not just old files that fail.

I tried opening a new file created earlier today with this morning's version of signstream.

same errors

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6557286/SignStreamOut.txt)

<img width="956" alt="Screen Shot 2021-05-27 at 7 36 48 PM" src="https://user-images.githubusercontent.com/13629122/119909555-232f6000-bf23-11eb-9b85-d5a07a324dbb.png">

**Comment by douglas-motto-at-rutgers** [comment]
I created a very simple new collection file in v3 and then reopened it without seeing errors.  Can you send us that "new" file you created?

**Comment by foltik** [comment]
Looking into the errors about overlap, which seem to be related to gloss text that hasn't had a start/end time set. All of the rest of the errors look like actual actual problems with the files.

Could you send the collection that shows the "Invalid framerate 0.0" error?

**Comment by cneidle** [comment]
can you tell me which file you want me to send?

**Comment by foltik** [comment]
Could you send the one that produced the errors shown in your third screenshot?

**Comment by cneidle** [comment]
will send this file

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6561144/SignStreamOut.txt)

<img width="712" alt="Screen Shot 2021-05-28 at 9 33 36 AM" src="https://user-images.githubusercontent.com/13629122/119991849-e81b4400-bf97-11eb-89f5-b6ee3388f0a8.png">

**Comment by douglas-motto-at-rutgers** [comment]
FYI...Some of these issues are NOT with the validator incorrectly detecting an error...they are bugs with the application that may have existed for a long time.

**Comment by cneidle** [comment]
Well there are large numbers of errors reported for ALL of our previously annotated files, which we need to be able to continue to use.   What is to be done ?

**Comment by douglas-motto-at-rutgers** [comment]
In many specific cases I recommend we correct the old xml collection files.


In the general case....

There's two known issues currently that would effect many old collection files.
One is a double entry of a gloss due to NO start/end time previously being set.
The other is that the translations were not directly related to the utterances.

We are considering what to do about these two problems.

**Comment by cneidle** [comment]
OK - thanks for considering the options.

While repairs of various kinds could be done to our own files,
others out there who have been using SignStream must not 
lose access to their own files.

So the solution has to be general.

**Comment by douglas-motto-at-rutgers** [comment]
The validator does not prevent using that file...it just says that if you use it you could have problems.

It's no different than if the validator did not exist...those problem with the application's understanding of the xml still exist (just as it did before).

In some cases...there's no other solution than to look at the xml and fix it.

**Comment by cneidle** [comment]
Well, if you’re saying that everyone who updates SignStream to the
new version is going to receive these messages upon opening their 
previous files, we need to alert them in advance about what to do 
when that happens.

This is definitely not a desirable user experience, and will not
reflect well on our program unless we have a very good way
for users to address it.

**Comment by douglas-motto-at-rutgers** [comment]
Let me recap.


The XML validation is in response to some problems being reported in which we ultimately discover that the issue appears to be with the contents of XML collection file, not the application....there have been many such situations.

Now with the validation, for certain problems in the XML, users are made immediately aware.

Without becoming immediately aware there is a real risk of the program crashing and data corruption in the collection file.  This has always existed and is not new.  What's the probability of that risk?...no way to tell, but it has occurred.

The message displayed when opening such a collection file states to contact the system administrator and send a file.  We can change that blanket message about what to do.

A user can also always ignore those problems and continue to use their files.  Some might not cause data corruption or a crash.



This is just a basic step to identify problems...particularly old problems.



It is not clear how the application will handle in all cases any data that isn't correct.  For example....there has been collection files in which two events have overlapping times.   I'm not sure how that file became into existence.  Such a problem, might crash the application, maybe disallow events to be used, break searching, or simply just display the events incorrectly.  It is impractical to know exactly how ever issue will effect the application, but it is easy to detect that there should NOT be two overlapping events.

So the first step is identify the problem.



Given the diversity of issues that could happen.  The blanket statement to contact the system administrator for help will cover all situations.  Again that wording can be changed.



For some of the specific cases selected, a more detailed description of the problem and possible solution can be added...but this is a case by case basis.  It would again be impractical to cover every problem that could ever exist.  And for some the solutions are not simple.



As for the general case problems, we are just identifying them at this time.  I spoke to Jack about perhaps not even mentioning them as an error, but rather a warning.  The next solution would be to "handle" these errors such that the user would not even be notified of them.  But to do this correctly takes thought.  If we do it incorrectly it would be just like causes data corruption.

**Comment by douglas-motto-at-rutgers** [comment]
Also, we need to validate that the validator is detecting correctly.

**Comment by cneidle** [comment]
I would like to set up a meeting that includes Dimitris to discuss this.

Please also see one question below.  

> On May 28, 2021, at 10:04 PM, douglas-motto-at-rutgers ***@***.***> wrote:
> 
> 
> Let me recap.
> 
> The XML validation is in response to some problems being reported in which we ultimately discover that the issue appears to be with the contents of XML collection file, not the application....there have been many such situations.
> 
> Now with the validation, for certain problems in the XML, users are made immediately aware.
> 
> Without becoming immediately aware there is a real risk of the program crashing and data corruption in the collection file. This has always existed and is not new. What's the probability of that risk?...no way to tell, but it has occurred.
> 
> The message displayed when opening such a collection file states to contact the system administrator and send a file. We can change that blanket message about what to do.
> 
> A user can also always ignore those problems and continue to use their files. Some might not cause data corruption or a crash.
> 
> This is just a basic step to identify problems...particularly old problems.
> 
> It is not clear how the application will handle in all cases any data that isn't correct. For example....there has been collection files in which two events have overlapping times. I'm not sure how that file became into existence. Such a problem, might crash the application, maybe disallow events to be used, break searching, or simply just display the events incorrectly. It is impractical to know exactly how ever issue will effect the application, but it is easy to detect that there should NOT be two overlapping events.
> 
> So the first step is identify the problem.
> 
> Given the diversity of issues that could happen. The blanket statement to contact the system administrator for help will cover all situations. Again that wording can be changed
> 
What “system administrator” are you referring to?

SignStream has been widely distributed.  Are you proposing to have
all users who get errors upon opening their previous files contact *you* ?

**Comment by cneidle** [comment]
You have listed this as an *enhancement* ?!

I cannot test older files because they do not open

<img width="653" alt="Screen Shot 2021-05-29 at 11 49 42 AM" src="https://user-images.githubusercontent.com/13629122/120076593-4d446780-c074-11eb-9447-9b1a311f51b3.png">

<img width="1449" alt="Screen Shot 2021-05-29 at 11 50 10 AM" src="https://user-images.githubusercontent.com/13629122/120076596-50d7ee80-c074-11eb-8e51-0d111e744e07.png">

I cannot view these annotations.

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6564936/SignStreamOut.txt)

**Comment by cneidle** [comment]
Enhancement?  Must be addressed before release.

**Comment by gregorydimitriadis** [comment]
File validation in general is complete, but issues may remain. A new issue #542 is opened to capture those.
