### ISSUE TITLE
Double-clicking on utterance in DB view fails to open it.

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#470]
[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6564970/SignStreamOut.txt)
<img width="1104" alt="Screen Shot 2021-05-29 at 12 21 12 PM" src="https://user-images.githubusercontent.com/13629122/120077453-7e269b80-c078-11eb-8105-202b2fc50732.png">

will email the file:

**Comment by cneidle** [comment]
Problem is not limited to that file.  Seems more general.  Also happens here, although I was able to double click on an utterance to enter it with an RIT (30 fps) video attached

<img width="639" alt="Screen Shot 2021-05-29 at 1 13 19 PM" src="https://user-images.githubusercontent.com/13629122/120078924-b41b4e00-c07f-11eb-9c1e-ab9743972512.png">

**Comment by cneidle** [comment]
Correction:  Double-clicking utterances to get to utterance view has now stopped working on this file as well.  Go to Utterance View also does not work in any of these cases.  FWIW, all of the testing today has so far been done with OS 11.4.

<img width="985" alt="Screen Shot 2021-05-29 at 1 30 35 PM" src="https://user-images.githubusercontent.com/13629122/120079509-3278ef80-c082-11eb-8cca-8dc2c0e2ef3e.png">

**Comment by cneidle** [comment]
Here's the out file for the above.

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/6565102/SignStreamOut.txt)

**Comment by cneidle** [comment]
Same problem in 10.12.6

**Comment by douglas-motto-at-rutgers** [comment]
Last minute change to correct previous bug with Utterance detection for events.  Can't go from DB to Utterance once an event is created.

**Comment by douglas-motto-at-rutgers** [comment]
Behavior doesn't seem to be in the v4 build.  Looks like previously applied fix for v4 was not included or incompatible with the v3 build.

**Comment by douglas-motto-at-rutgers** [comment]
As of

SignStream4_4.1.0_pre_2021_06_01_1629_48ea0870
SignStream3_3.7.0_pre_2021_06_01_1624_7ae614a9

applied the v4 patch to v3.

**Comment by douglas-motto-at-rutgers** [comment]
Believed fixed.

Closing, but reopen if still experienced.
