### ISSUE TITLE
June 1 Program seems to hang when Sign Bank search fails because DAI server is down

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#474]
<img width="947" alt="Screen Shot 2021-06-09 at 4 24 05 AM" src="https://user-images.githubusercontent.com/13629122/121319927-aca74080-c8da-11eb-9245-bf8aa6d9c292.png">

It is unresponsive for a very long time.

**Comment by douglas-motto-at-rutgers** [comment]
If DAI website is down, what do you want SignStream to do?

**Comment by cneidle** [comment]
There should be a message like: 

“The server required for use of the Sign Bank is down at the moment.  Please try again later.” 

And the user should not be frozen from continuing to use the program.

**Comment by gregorydimitriadis** [comment]
Tested on 2022-04-18 when dai filesystem was down, and did not experience hanging, just the expected messages about inaccessibility of the server

**Comment by cneidle** [comment]
hasn't this been fixed?   close??

**Comment by gregorydimitriadis** [comment]
It seems so. Closing
