### ISSUE TITLE
no existing handshape for this gloss

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#475]
The gloss GIRL-SCOUT doesn't have any handshapes glossed in the signbank so the morph-info window shows up blank. Also looking through our handshapes, we don't actually have the handshape produced for this gloss. Right now this gloss has the "???" labeled for the handshapes. File PF18_V03 U1

![Screen Shot 2021-06-30 at 5 30 09 PM](https://user-images.githubusercontent.com/38887034/124034706-69f3f800-d9b0-11eb-84d4-1f48e1f433a9.png)
![Screen Shot 2021-06-30 at 5 35 47 PM](https://user-images.githubusercontent.com/38887034/124034773-7f692200-d9b0-11eb-9e64-a0b1bfb47344.png)

**Comment by douglas-motto-at-rutgers** [comment]
Can we get a copy of the PF18_V03 collection file over email?

**Comment by gregorydimitriadis** [comment]
@gregdimi note to self: will verify that inserting from sign bank inserts no HS

**Comment by gregorydimitriadis** [comment]
@cneidle if the sign bank is not showing any handshapes (i.e. it has no handshape data) on inserting from the sign bank, is the desired action to insert all data except handshapes (i.e. leave handshapes on morph-phon alone, if they're already populated)?

**Comment by gregorydimitriadis** [comment]
Fixed in: 	SignStream3-3.4.0_pre_2022_04_14_1701_c5c3fd5f
