### ISSUE TITLE
play/pause button

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#476]
Working on RIT file PF18_V03 for any utterance: When an entity is selected to play and I try to pause it, the pause doesn't work until after several clicks so the utterance keeps playing until the the pause button decides to work. 

![Screen Shot 2021-07-01 at 3 47 36 PM](https://user-images.githubusercontent.com/38887034/124181716-bef44480-da6a-11eb-9d10-4e695b6d9088.png)

**Comment by douglas-motto-at-rutgers** [comment]
Can we get the PF18_V03 collection file and associated videos over email?

**Comment by bugspotter33** [comment]
I have attached the file requested.

Indya

**Comment by gregorydimitriadis** [comment]
Fixed in pending upcoming version.
