### ISSUE TITLE
significant lag in system response

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#478]
I have created a new file, attached 1 video, and am setting up utterances.  The response time lags a lot, making it difficult, e.g., to drag and release the mouse where you want to.  Similarly with attempt to drag the green alignment indicator.

**Comment by gregorydimitriadis** [comment]
@cneidle I don't see the lag with new collections. Do you see a difference with new collections vs. existing?

**Comment by cneidle** [comment]
I experienced this only with new collections.

I hadn’t managed to open any existing collections.

I haven’t had a chance to try the newer version you sent yet.

Will let you know if it is still an issue.

Thanks,
 Carol

**Comment by cneidle** [comment]
Opened up latest (11/2/21) version.  System was unresponsive for 2 minutes - before the cursor was again available.

**Comment by cneidle** [comment]
Lag entering information is not as bad as it was in the last version, but still significant lag in drawing lines for non-manual events.

**Comment by gregorydimitriadis** [comment]
Closing in favor of #486
