### ISSUE TITLE
losing unaligned gloss

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#479]
I typed in two unaligned glosses in between two aligned glosses.

I set the end point for the first so that it overlapped with the display of the second.  Then I moved the endpoint back to avoid display overlap.  The other gloss had disappeared.

PS. It's hard to set the endpoint where you think you are setting it, because there is such a lag in the display when you use the arrow keys to advance even by a couple of frames...
<img width="476" alt="Screen Shot 2021-10-31 at 4 52 25 PM" src="https://user-images.githubusercontent.com/13629122/139600959-31657220-eea7-411c-80d8-02d69415a1a7.png">

<img width="478" alt="Screen Shot 2021-10-31 at 4 52 38 PM" src="https://user-images.githubusercontent.com/13629122/139600965-d23df9ed-4c20-412c-8015-6966150e47d9.png">

<img width="500" alt="Screen Shot 2021-10-31 at 4 52 52 PM" src="https://user-images.githubusercontent.com/13629122/139600967-5581b1aa-35ad-4432-b01a-82d9d7ac38c0.png">

**Comment by gregorydimitriadis** [comment]
This has been resolved for 3.4.0. The text will remain even when 'squished' between two glosses - it will not be clickable if the two glosses share a start/end point, but on moving one a few frames back it will be possible to click the text to either delete it or set its time.
