### ISSUE TITLE
Zooming in past desired amount

### ISSUE THREAD

**Issue by Arrigosaur** [DCS-LCSR/SignStream3#48]
Default zoom (far) is set when I open an utterance, when adjusted to desired amount I have to be careful not to go past a certain amount (to the right) to be stuck in (near) zoom which is unadjustable even at it's furthest (to the left) setting.

**Comment by gregorydimitriadis** [comment]
Linking Justin's video of this bug occurring here for clarity (thanks again Justin):
https://youtu.be/c7XJHSIatSg

**Comment by blazetravis** [comment]
Fixed!
