### ISSUE TITLE
Error messages opening up previously created files

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#480]
<img width="819" alt="Screen Shot 2021-11-04 at 6 39 13 PM" src="https://user-images.githubusercontent.com/13629122/140430143-b5a72032-f984-41ac-a76f-6eea4ede1fcd.png">

<img width="773" alt="Screen Shot 2021-11-04 at 6 39 29 PM" src="https://user-images.githubusercontent.com/13629122/140430161-8931d0a7-43d4-472c-94b4-884e0454ecdf.png">

**Comment by cneidle** [comment]
Tried opening another file - got this - 

<img width="629" alt="Screen Shot 2021-11-04 at 6 43 23 PM" src="https://user-images.githubusercontent.com/13629122/140430465-8b07ae68-d96c-4314-9a41-df3b8dd0d459.png">

<img width="921" alt="Screen Shot 2021-11-04 at 6 43 34 PM" src="https://user-images.githubusercontent.com/13629122/140430475-b66f7c50-1cdf-4fa9-b8d9-5269b8929202.png">

<img width="786" alt="Screen Shot 2021-11-04 at 6 43 41 PM" src="https://user-images.githubusercontent.com/13629122/140430488-011c2fa7-807d-410a-81a6-2c392679ca87.png">

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/7479314/SignStreamOut.txt)

**Comment by gregorydimitriadis** [comment]
Should be resolved in recent versions.
