### ISSUE TITLE
3.3.7.  insert all data from Sign Bank window fails to insert handshapes

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#481]
<img width="1375" alt="Screen Shot 2022-01-15 at 2 21 58 PM" src="https://user-images.githubusercontent.com/13629122/149635161-010a35a7-c23d-4ff9-981b-4b64d5d4c70d.png">

**Comment by gregorydimitriadis** [comment]
Can reproduce

**Comment by gregorydimitriadis** [comment]
Fixed for next release

**Comment by cneidle** [comment]
fixed
