### ISSUE TITLE
Problem changing from 2 handshapes to 1

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#482]
I first entered 2 different handshapes for SEE.  Then deleted 1.  
<img width="462" alt="Screen Shot 2022-01-15 at 2 27 32 PM" src="https://user-images.githubusercontent.com/13629122/149635313-12178a7e-baa9-4d27-9050-f88483b3c3e0.png">

**Comment by cneidle** [comment]
Same problem just entering a single handshape (because start and end are the same) from the outset: again, the handshape is centered around the start and no end handshape appears.

<img width="585" alt="Screen Shot 2022-01-15 at 2 30 57 PM" src="https://user-images.githubusercontent.com/13629122/149635395-8609e581-f8c4-49e1-93b5-8a9fd3f2aa3d.png">

<img width="197" alt="Screen Shot 2022-01-15 at 2 30 31 PM" src="https://user-images.githubusercontent.com/13629122/149635396-588f3dc7-7ecc-4d30-a7cd-df1823db6169.png">

**Comment by cneidle** [comment]
extending from a 1-frame gloss to a longer gloss also fails to provide an end handsahpe.

<img width="123" alt="Screen Shot 2022-01-15 at 2 34 31 PM" src="https://user-images.githubusercontent.com/13629122/149635473-627c3909-fea1-407a-b910-a3c50618dd4b.png">

**Comment by cneidle** [comment]
I open an old file, and go to the morph phon window for a sign with same start and end handshapes.  I don't change anything except for clicking Enter or Bypass sign bank.  The same problem as above


<img width="147" alt="Screen Shot 2022-01-15 at 3 19 00 PM" src="https://user-images.githubusercontent.com/13629122/149636527-a77202c0-32a5-4536-922c-437ca886c81c.png">


<img width="263" alt="Screen Shot 2022-01-15 at 3 10 36 PM" src="https://user-images.githubusercontent.com/13629122/149636466-1831f9d7-591a-4671-aab4-7fe7a387467f.png">

**Comment by gregorydimitriadis** [comment]
Can reproduce

**Comment by gregorydimitriadis** [comment]
Fixed for next release

**Comment by cneidle** [comment]
fixed
