### ISSUE TITLE
WEIRDNESS with colors assigned to non-manual fields

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#483]
I edited the negation field to be pink. When I was done, the gloss line initially appeared in pink.  Then it disappeared.

I edited the headshake field to be blue.  Then that field initially showed up in the previously selected color.

Then it changed to the proper color.  I added a second headshake and it again showed up in the. color I had. selected for Negation

<img width="992" alt="Screen Shot 2022-01-15 at 2 38 45 PM" src="https://user-images.githubusercontent.com/13629122/149635642-3bce48e8-b812-42a8-a728-989c75359b4b.png">

<img width="470" alt="Screen Shot 2022-01-15 at 2 39 10 PM" src="https://user-images.githubusercontent.com/13629122/149635604-3b8ed1f6-580c-4c6b-8a3e-82ddafc55eaf.png">

<img width="564" alt="Screen Shot 2022-01-15 at 2 39 19 PM" src="https://user-images.githubusercontent.com/13629122/149635596-cd670da6-9bad-46bf-9816-44ec9d059f68.png">

<img width="416" alt="Screen Shot 2022-01-15 at 2 41 00 PM" src="https://user-images.githubusercontent.com/13629122/149635627-ab999a29-16d1-47c1-b461-98528aa0ed9e.png">

**Comment by cneidle** [comment]
I changed the order of those fields, and the blue color showed up as it should have before that.
<img width="569" alt="Screen Shot 2022-01-15 at 2 44 14 PM" src="https://user-images.githubusercontent.com/13629122/149635689-bb23efe4-5488-44e4-9d3c-957d4ad3de93.png">

**Comment by gregorydimitriadis** [comment]
Could not reproduce as is. I changed the color of a nonmanual field, hit done, and saw the color reflected on the field in the utterance view. I switched between database view and utterance view again and the color was still as I selected. 

When in your case did the color disappear?

**Comment by cneidle** [comment]
This seems to be ok.
