### ISSUE TITLE
does not reflect what we agreed on for save warning

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#487]
<img width="793" alt="Screen Shot 2022-01-15 at 3 23 19 PM" src="https://user-images.githubusercontent.com/13629122/149636612-dd5bc83e-09d3-4fa9-a336-6627f7546a53.png">

but when you update the text, please insert a comma before "which" in the first line

**Comment by gregorydimitriadis** [comment]
Message has since been changed.
