### ISSUE TITLE
Getting error msgs with files edited only with latest version !

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#488]
<img width="712" alt="Screen Shot 2022-01-15 at 3 32 28 PM" src="https://user-images.githubusercontent.com/13629122/149636876-60d3b60b-5894-4971-bbdf-1b547acd5a57.png">

<img width="1614" alt="Screen Shot 2022-01-15 at 3 32 51 PM" src="https://user-images.githubusercontent.com/13629122/149636880-c422657f-a0e5-470f-a5d3-a447bce207db.png">

for file:
  59_2022_14_12_20-2.ss3

**Comment by gregorydimitriadis** [comment]
Should be resolved for newest versions.
