### ISSUE TITLE
handshape not showing up at all in utterance for 1-frame gloss

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#489]
file 112, utterance 1; the second below is maximum zoom

<img width="843" alt="Screen Shot 2022-01-15 at 4 22 50 PM" src="https://user-images.githubusercontent.com/13629122/149638183-78858d49-b077-4ab5-bcbf-83c5e4e21741.png">

<img width="579" alt="Screen Shot 2022-01-15 at 4 22 58 PM" src="https://user-images.githubusercontent.com/13629122/149638185-f7650b1e-359c-49ff-811d-c7929755dc91.png">

<img width="965" alt="Screen Shot 2022-01-15 at 4 23 27 PM" src="https://user-images.githubusercontent.com/13629122/149638190-93244f40-ea76-4fba-8e29-3039000e460f.png">

**Comment by gregorydimitriadis** [comment]
Was this upon opening the file, or was this gloss (IX-3p:i) edited?

**Comment by cneidle** [comment]
It looks ok the I open the file.  But when I go into the morph phon window and come back out (without editing anything) this is what I see.

**Comment by cneidle** [comment]
I create the gloss.  Handshape does not appear.  testing with 1/21/22 version.

<img width="810" alt="Screen Shot 2022-01-22 at 4 46 33 PM" src="https://user-images.githubusercontent.com/13629122/150656534-60dc6c53-5a56-4489-b9b0-cb685ecd59bf.png">

Also, the font overall looks smaller and lighter in this version - i think.

**Comment by cneidle** [comment]
This seems to work on 1-28.  But the fix needs to be extended beyond 1-frame items...
<img width="125" alt="Screen Shot 2022-01-28 at 12 37 28 PM" src="https://user-images.githubusercontent.com/13629122/151595096-6c1f1e64-58a8-4159-aade-cf11b4253d72.png">

**Comment by gregorydimitriadis** [comment]
Closing this issue as working for 1-frame glosses.
