### ISSUE TITLE
Unable to add new manual gloss event if zoomed in

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#49]
Steps to reproduce:
1) Click-into some utterance. When it loads it should be zoomed out enough so that the utterance ends before the window does (indicated by some brown background space to the right of the yellow utterance space)
2) Attempt to add a new gloss at the right-most part of the utterance, just to verify that it is possible here.
3) Zoom in so the utterance extends off-screen
4) Attempt to do the same addition of a gloss in the same place
5) Notice that you are now able to add glosses if the place you are clicking is far enough to the right.

**Comment by blazetravis** [comment]
This bug is _not_ fixed. I am still able to add multiple glosses to the same spot. (tested using 1 frame glosses)

![screen shot 2015-11-17 at 1 37 28 pm](https://cloud.githubusercontent.com/assets/13489587/11220943/678efdee-8d30-11e5-84dd-6a572f729956.png)

**Comment by gregorydimitriadis** [comment]
Hmm that is indeed a bug, but not the one reported here. This bug was that the box to enter text was simply not appearing if one zoomed in too far.
So that part being fine, I'll make a new issue separately out of this overlapping text bug.

**Comment by blazetravis** [comment]
Alright, well I'm not quite sure how to proceed. Should this ticket simply be modified or renamed?

**Comment by gregorydimitriadis** [comment]
I'll close this one and make a new one. Thanks Blaze.
