### ISSUE TITLE
problem with Mouth field - values seem to be corrupted - SignStream v. 3.3.5 - dialog 82 file 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#493]
No (previously annotated) values for Mouth are visible.
The dropdown menu shows the full set of values, but selecting one does not cause it to appear.
The Field-Spec editor shows none of the values that should be there.
<img width="1101" alt="Screen Shot 2022-03-29 at 3 47 55 PM" src="https://user-images.githubusercontent.com/13629122/160696025-90877aed-1675-40a9-b9af-904c918ba01f.png">
<img width="434" alt="Screen Shot 2022-03-29 at 3 48 23 PM" src="https://user-images.githubusercontent.com/13629122/160696027-8dbc6e29-96ee-46fe-9488-3f3932c11b6a.png">
<img width="435" alt="Screen Shot 2022-03-29 at 3 48 03 PM" src="https://user-images.githubusercontent.com/13629122/160696028-f8e6d59c-acac-4315-b186-bb29f0e216c6.png">

**Comment by cneidle** [comment]
Mouth values ARE appearing in the other temporal partition

<img width="868" alt="Screen Shot 2022-03-29 at 4 00 22 PM" src="https://user-images.githubusercontent.com/13629122/160696990-1d70dde8-1231-43c4-aa13-4bde98835171.png">

_____________________________________________

<img width="733" alt="Screen Shot 2022-03-29 at 4 05 04 PM" src="https://user-images.githubusercontent.com/13629122/160697645-68976746-6588-40ea-8fe6-0a9c11f088b6.png">

**Comment by cneidle** [comment]
This is what I am seeing in the coding scheme file in the SignStream 3.3.5 folder.

<img width="629" alt="Screen Shot 2022-03-29 at 4 12 51 PM" src="https://user-images.githubusercontent.com/13629122/160698990-75e76ede-2b4c-43d7-9fed-93b4d8d88186.png">

<img width="657" alt="Screen Shot 2022-03-29 at 4 12 31 PM" src="https://user-images.githubusercontent.com/13629122/160698991-fd6db228-4a62-4a53-987b-9fe65d0d40e5.png">

**Comment by gregorydimitriadis** [comment]
Not occurring for current versions of code.

**Comment by gregorydimitriadis** [comment]
Going to close this - open back up if experiencing in any newer version.
