### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#496]
As we discussed, the new version should be 3.4.0

So messages should be adjusted accordingly.

<img width="830" alt="Screen Shot 2022-04-02 at 8 04 44 AM" src="https://user-images.githubusercontent.com/13629122/161382302-03e8da13-349e-47c9-9306-fd41db72b5d2.png">

**Comment by douglas-motto-at-rutgers** [comment]
Believe changed in SignStream3-3.4.0_pre_2022_04_04_1647_dd5956a3

**Comment by cneidle** [comment]
I subsequently discussed this with Greg.  At some point when you did not participate in the meeting. 

   he agreed:

With major changes including file extension, 3.4.0 seems appropriate.

**Comment by douglas-motto-at-rutgers** [comment]
yes...agreed...as stated, changed in SignStream3-3.4.0_pre_2022_04_04_1647_dd5956a3 to 3.4.0
