### ISSUE TITLE
Pretty awful user experience opening this file (cory 114)

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#499]
<img width="743" alt="Screen Shot 2022-04-02 at 8 29 11 AM" src="https://user-images.githubusercontent.com/13629122/161383472-831ba7ed-c2cb-404a-9a66-adccbcf4ba71.png">

_________________________

<img width="1635" alt="Screen Shot 2022-04-02 at 8 29 44 AM" src="https://user-images.githubusercontent.com/13629122/161383476-c41d3356-105b-4c11-abe0-150197e969cf.png">

<img width="1521" alt="Screen Shot 2022-04-02 at 8 35 02 AM" src="https://user-images.githubusercontent.com/13629122/161383589-7867673d-fed3-4e69-9dc4-5c0a4836f61c.png">

_________________________

<img width="664" alt="Screen Shot 2022-04-02 at 8 29 55 AM" src="https://user-images.githubusercontent.com/13629122/161383481-2c17b0a8-56e2-4ce2-9b5a-887fb1f17918.png">

___________________________

WE SHOULD DISCUSS

FYI

<img width="485" alt="Screen Shot 2022-04-02 at 8 37 22 AM" src="https://user-images.githubusercontent.com/13629122/161383691-da4a5d97-51e4-4cad-95f0-ccbb9c5682d1.png">

**Comment by gregorydimitriadis** [comment]
Fixed in upcoming release version 3.4.0_pre_2022_04_08_1303_81ad7079
