### ISSUE TITLE
Field-Spec Editor: Manual Fields

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#501]
Why is 'dom sign type' not checked by default?  See below for the newest version, as 
compared with what shows up in 3.3.5, at the bottom.

It seems to me to both dom sign type and non-dom sign type should both be checked by
default.  But in any case, dom sign type is showing up here although it is unchecked... 

<img width="1174" alt="Screen Shot 2022-04-03 at 12 59 56 PM" src="https://user-images.githubusercontent.com/13629122/161439321-b03e8b2c-0ad0-4155-b913-d13b4f1dfeed.png">

<img width="940" alt="Screen Shot 2022-04-03 at 1 00 53 PM" src="https://user-images.githubusercontent.com/13629122/161439327-16584a5e-9fa1-4923-b06c-c0d84dee2ff9.png">

**Comment by cneidle** [comment]
FWIW, the non dom sign type does show up when there is something entered 
on the non dom hand (as it should).

**Comment by douglas-motto-at-rutgers** [comment]
@greg...two issues...

1) defaults not set (we should discuss options)

2) annotations not detected correctly

**Comment by gregorydimitriadis** [comment]
We believe this to be working as intended according to the requirements - let's discuss later.
