### ISSUE TITLE
Another error upon opening a file saved with the new version of the program

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#502]
I had been editing DL-vocab-080718.  I entered some location info.  Saved.  Reopened.
Got this:

<img width="702" alt="Screen Shot 2022-04-03 at 1 07 13 PM" src="https://user-images.githubusercontent.com/13629122/161439558-fbebef28-f14a-4975-a178-4535715146b5.png">

<img width="893" alt="Screen Shot 2022-04-03 at 1 07 44 PM" src="https://user-images.githubusercontent.com/13629122/161439555-3eb81c7e-8b2e-4d7c-b777-e7b68b84337b.png">

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/8405092/SignStreamOut.txt)

**Comment by gregorydimitriadis** [comment]
Fixed in upcoming release version 3.4.0_pre_2022_04_08_1303_81ad7079
