### ISSUE TITLE
one field missing value in Field-Spec editor

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#503]
<img width="791" alt="Screen Shot 2022-04-03 at 1 25 46 PM" src="https://user-images.githubusercontent.com/13629122/161440519-28c38383-d926-4b10-8c23-95f1841b6ef4.png">

I discovered this when I added a new value from the utterance window, although thiss
also seems to be missing in SignStream 3.3.5

<img width="400" alt="Screen Shot 2022-04-03 at 1 17 09 PM" src="https://user-images.githubusercontent.com/13629122/161440516-18257793-6224-4382-9760-e9734434af88.png">

**Comment by douglas-motto-at-rutgers** [comment]
looks to be an issue from at least 3.3.5...@greg will need to consider a correction.

**Comment by gregorydimitriadis** [comment]
@cneidle what should the label be for this value? Going back as far as I can in SignStream versions with the coding scheme files I can't find an answer to this.

**Comment by cneidle** [comment]
"down" - from Appendix A here: http://www.bu.edu/asllrp/asllrpr11.pdf

thanks!

**Comment by gregorydimitriadis** [comment]
Change made in upcoming release 3.4.0_pre_2022_04_08_1303_81ad7079

**Comment by cneidle** [comment]
Looks fine now.  thanks.
