### ISSUE TITLE
Opening a new file failed to close all windows (specifically Modifications window) from file that was open at the time

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#504]
<img width="612" alt="Screen Shot 2022-04-03 at 1 37 15 PM" src="https://user-images.githubusercontent.com/13629122/161440747-d88bfd98-e553-43f4-bb63-2b3ffe252776.png">

**Comment by douglas-motto-at-rutgers** [comment]
@greg...I was able to reproduce this....open collection with mods...select annotator, but with macro editor still open...open mods popup....click open new....new opens...mod popup still there from old file.

**Comment by douglas-motto-at-rutgers** [comment]
As of version SignStream3-3.4.0_pre_2022_04_06_2213_a948edb0, this issue has been fixed as of the example in the previous comment and believed fixed for other situations.  If still experiencing please state the situation it was seen in.
