### ISSUE TITLE
Unable to select single unaligned word; spaces should not be allowed in selections

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#505]
<img width="345" alt="Screen Shot 2022-04-03 at 2 14 47 PM" src="https://user-images.githubusercontent.com/13629122/161442394-bd3fb17b-3675-4a86-82ba-5016a01e59cf.png">

Clicking once on "one" results in:

<img width="188" alt="Screen Shot 2022-04-03 at 2 15 04 PM" src="https://user-images.githubusercontent.com/13629122/161442383-11d1b5da-6a06-4ecd-b821-57efcf448f06.png">

<img width="922" alt="Screen Shot 2022-04-03 at 2 15 44 PM" src="https://user-images.githubusercontent.com/13629122/161442402-d63b0d2c-3b63-4461-a32c-481660664fb5.png">

---

NOTE - this works as it should in 3.3.5

<img width="588" alt="Screen Shot 2022-04-03 at 2 23 52 PM" src="https://user-images.githubusercontent.com/13629122/161442494-37b72dd1-5781-466a-8f4d-f438d3ed036b.png">

**Comment by cneidle** [comment]
See below.  Can select this whole string - it shows up in red.  But it cannot be deleted

<img width="634" alt="Screen Shot 2022-04-03 at 2 30 22 PM" src="https://user-images.githubusercontent.com/13629122/161442785-d56ef2f2-ff57-4749-b38d-ae4af9f23a2a.png">

Correction:  The above CAN be deleted once start and end times have been set.  
The same is true for a single entry, like:  ONE 
It is not necessary to set the start and end times to delete items in 3.3.5

**Comment by gregorydimitriadis** [comment]
Made change for upcoming test version. Could require additional fixes for edge cases.

**Comment by cneidle** [comment]
Selecting a single word seems to work now.  However, it is, unfortunately, possible to include a space in a gloss in the Morph-phon window...  which should be excluded

<img width="73" alt="Screen Shot 2022-04-11 at 3 27 01 PM" src="https://user-images.githubusercontent.com/13629122/162814940-4b65bdfc-32e2-4efa-8c96-bb3cef15a890.png">

**Comment by gregorydimitriadis** [comment]
@cneidle in that example, should the user be alerted to the presence of spaces in the text as they hit 'enter/bypass' and forced to change it? Or instead - the spaces will be automatically removed and the text would become "onetwo" ?

**Comment by cneidle** [comment]
Yes, please.  Thanks.

**Comment by gregorydimitriadis** [comment]
Will be fixed in SignStream3-3.4.0_pre_2022_04_13_1628_f2eef07d

**Comment by gregorydimitriadis** [comment]
Tested, appears fixed as of 3.4.0
