### ISSUE TITLE
File failed to open

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#507]
I associated video files and set up two segment tiers with utterances.
Did not enter anything into the utterances.  Saved and tried to reopen.

<img width="986" alt="Screen Shot 2022-04-05 at 11 10 23 AM" src="https://user-images.githubusercontent.com/13629122/161786394-0439c00c-8818-4f8f-9ab1-9e1b3f24411d.png">

[SignStreamOut.txt](https://github.com/DCS-LCSR/SignStream3/files/8419439/SignStreamOut.txt)

**Comment by douglas-motto-at-rutgers** [comment]
@greg....in SignStream3-3.4.0_pre_2022_04_06_2213_a948edb0....same issue with one utterance, including one gloss....save...reopen..."fail to open"

**Comment by douglas-motto-at-rutgers** [comment]
@greg....may need to first open an older ss3 file with validation needed like 8-ben....then create a new collection, save, reopen....error.

**Comment by gregorydimitriadis** [comment]
Fixed for upcoming release 3.4.0_pre_2022_04_08_1303_81ad7079
