### ISSUE TITLE
Search is now not working properly - not returning results by utterance

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#508]
<img width="1742" alt="Screen Shot 2022-04-11 at 3 32 03 PM" src="https://user-images.githubusercontent.com/13629122/162815983-ef7d5b1e-88c4-4be0-b077-2c26074b98cb.png">

**Comment by gregorydimitriadis** [comment]
Will be fixed in SignStream3-3.4.0_pre_2022_04_13_1628_f2eef07d

**Comment by gregorydimitriadis** [comment]
Fixed again in SignStream3-3.4.0_pre_2022_04_15_1219_e87f75dc - an addition was needed to ensure that the same entities show up in the search results or in the left-hand utterance index per utterance.
