### ISSUE TITLE
Unlocking glosses and deleting gloss 2 

### ISSUE THREAD

**Issue by kwasiopoku** [DCS-LCSR/SignStream3#51]
When a user unlocks gloss 1 and gloss 2, they should be able to delete just the gloss 2 without impacting gloss one and its handshapes

**Comment by cneidle** [comment]
But doesn’t that result in a problem, with sign classified as 2-handed
that only has information for 1 hand?

It seems to me that the right way to delete gloss 2  would be to change
the sign to 1-handed.

no?

Thanks,
 Carol

**Comment by kwasiopoku** [comment]
After discussing this with Carol, we agreed that this is not an issue.  Users should not be able to unlock glosses and delete gloss 2.  Deleting a gloss 2 should result in the deletion of the entire gloss.  Unlocking is only for the purpose of independently changing the properties of gloss 1 and gloss 2
