### ISSUE TITLE
Validation issues

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#510]
I opened 8-Ben.

Saw this error message - same message occurring twice.  The gloss in question behaves as if the 2 hands are locked, as they should be, without my making any modification.  Although there is an option to lock them

<img width="933" alt="Screen Shot 2022-04-21 at 12 38 36 PM" src="https://user-images.githubusercontent.com/13629122/164509540-c5e1df52-48d9-4af6-a763-ab8ebcb678b0.png">

**Comment by cneidle** [comment]
I opened 106 and saw this:

<img width="1088" alt="Screen Shot 2022-04-21 at 12 46 57 PM" src="https://user-images.githubusercontent.com/13629122/164510941-d7fd6f1f-52dc-4f13-a37c-f8e178a2e973.png">





This is what I see when I open the file in 3.3.5:

<img width="854" alt="Screen Shot 2022-04-21 at 12 48 18 PM" src="https://user-images.githubusercontent.com/13629122/164510818-d91d0b75-087e-45c5-af05-b200c31bae77.png">

The file contains exactly one participant.  Shouldn't that participant just be associated with the segment tier automatically ??

**Comment by cneidle** [comment]
PS to above:  Cory is defined as right-handed.

<img width="280" alt="Screen Shot 2022-04-21 at 12 50 57 PM" src="https://user-images.githubusercontent.com/13629122/164511170-6611ddef-89b2-499c-8aa8-c80a9593452c.png">

**Comment by cneidle** [comment]
Same as above for 3-Ben.  There is exactly one -- right-handed -- participant defined in this collection.
That should be the participants assigned automatically.  It is not helpful to add a different participant.

<img width="867" alt="Screen Shot 2022-04-21 at 12 56 08 PM" src="https://user-images.githubusercontent.com/13629122/164512161-6be836ed-fe0c-4710-b1bb-aa17f7a2f7cd.png">

<img width="457" alt="Screen Shot 2022-04-21 at 12 57 24 PM" src="https://user-images.githubusercontent.com/13629122/164512325-903cdac5-87fe-4bd5-b439-ba3e2ea75832.png">

There are quite a few files with this same issue.

**Comment by cneidle** [comment]
Other than the problem of not having the unique participant associated with the segment tier as above, the main problem is the unavailability of sign type.  Seems to me that this could also be dealt with automatically.  If prefix is fs- it is fingerspelled; if prefix includes  CL: it is a classifier; if prefix is # it is loan sign. If the gloss includes quotation marks, and it is not a classifier or the sign "WHAT", then it is a gesture.  Otherwise it can be assigned as a lexical sign.  This has already been implemented in the choice of default sign type for a gloss in the morph-phon window anyway, right?

**Comment by gregorydimitriadis** [comment]
I don't see the same errors with the versions of 8-Ben I have - can you send the one you used?

**Comment by gregorydimitriadis** [comment]
About the participant issue - it is possible to associate the single participant if existing. I think we went with the 'default' route because we didn't want to assume the single participant was meant to be associated.

**Comment by gregorydimitriadis** [comment]
Has the sign type issue been noticed in any collection as an error/modification?

**Comment by cneidle** [comment]
Yes 

For “BUOY” (several times) and for “part:indef” once, as I recall…

Here's one






C>

**Comment by cneidle** [comment]
You definitely should assume that the single participant is the one
to be associated…

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
I tested the 8-Ben collection you sent - and there is actually an issue with the locking there. If you try to move the time of the dom gloss portion, it won't move the ndom portion in sync. This is why it's being reported as an error, since it can't determine which is correct between the two.

**Comment by cneidle** [comment]
Ok - but it should only report the error once.

Thanks, 
 Carol

**Comment by cneidle** [comment]
Seems to me that this could be adjusted automatically.

If the start and endpoints are identical but there is no value
for whether the two hands are locked, the “locked” value 
could be added by default.

If the user wants to make the times different, they can unlock it.

No?

Thanks,
 Carol

**Comment by cneidle** [comment]
Conversely, if there is no value for locked/unlocked but the
start or end point is different on the two hands, set the value 
to unlocked...

**Comment by gregorydimitriadis** [comment]
Fixed in 3.4.0_pre_2022_05_02_1353_aa8247c2
