### ISSUE TITLE
Program crashed while I was trying to locate a movie file

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#511]
I had gotten an error message to relocate the movie file because movie properties were invalid.
I didn't immediately find the movie file, so I cancelled out of the dialog box for selecting it, and the program crashed.

<img width="1425" alt="Screen Shot 2022-04-21 at 1 23 18 PM" src="https://user-images.githubusercontent.com/13629122/164516646-aa558b33-64f9-44d5-8a17-ad183633bd9e.png">

sending SignStreamOut.txt by email.

File was LB-sentences-122818_TC.ss3

**Comment by gregorydimitriadis** [comment]
I'll need to have it force a video selection, otherwise an error like this is going to occur later in the process of opening and validating/converting the file.

**Comment by cneidle** [comment]
Yes - forcing a video selection is fine.  

But I should be able to cancel that dialog box and try again.

(I wanted to look again at the error message and search in various directories,
which is easier to do outside of that dialog box.  I was not proposing to 
continue with the file without selecting a video.)

The program should not crash.

There should be, if anything, another message saying “You will need to select
a video file.” Or whatever.
