### ISSUE TITLE
problem with newly edited file - sign type lost

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#512]
I opened an older version of a SignStream file (95_ and saved in the new version.

I added a gloss -- obviously with a sign type.   I saved the file.

This was not recognized when I tried to reopen that file.

<img width="825" alt="Screen Shot 2022-04-21 at 4 11 45 PM" src="https://user-images.githubusercontent.com/13629122/164544933-876d8833-b1b3-4b47-8770-b941f3c2c2d7.png">

<img width="993" alt="Screen Shot 2022-04-21 at 4 12 27 PM" src="https://user-images.githubusercontent.com/13629122/164544924-5f6c046b-2f5a-49dc-80c9-b0334795e8ab.png">

**Comment by gregorydimitriadis** [comment]
@cneidle can you send this file, please? Thanks

**Comment by cneidle** [comment]
Error does not seem to be recurring.  thanks.
