### ISSUE TITLE
Add ability to switch any gloss to a 1 frame gloss

### ISSUE THREAD

**Issue by kwasiopoku** [DCS-LCSR/SignStream3#52]
On the main utterance window, non 1 frame glosses should be able to be reduced to a one frame gloss.

This can be done if the gloss has the same start and end handshape.  If not, we need to add a warning that will alert to user to first set the gloss to have the same start and end handshape.  Once the handshapes are the same, the user can then reduce the gloss to a one frame gloss.

**Comment by blazetravis** [comment]
This enhancement is not complete. Currently main glosses CAN be reduced to one frame, however, no warning pops up preventing a gloss with 2 handshapes to be reduced to one frame.

**Comment by gregorydimitriadis** [comment]
I've added a warning box for this, and I'll push the code out soon. Leaving this issue open for now.

**Comment by blazetravis** [comment]
Looks good. This enhancement is complete.
