### ISSUE TITLE
Multiple segment tier views displaying same segment tier

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#521]
With two segment tiers existing (say ST1, and ST2)...in database view select an utterance in ST1....now in utterance view.  Click "Add" and add the ST2 segment tier....now see both in the utterance view.  On the drop down segment tier selection for ST1...change it to ST2....now seeing ST2 twice.  This is a known issue which causes bugs and corruption to have the segment tier opened twice in the utterance view 

-- DM

**Comment by gregorydimitriadis** [comment]
Added to Todo milestone on zoom call with Carol/Dimitri/Chuck 2022-09-27

**Comment by gregorydimitriadis** [comment]
Todo: revert code to where it was when it disallowed this scenario - i.e. disallow the combobox to show segment tiers which are already showing elsewhere in the window.

Est: 2 hours

**Comment by douglas-motto-at-rutgers** [comment]
I think this time estimate is light.

Est: 4 hours

**Comment by cneidle** [comment]
This is not completely fixed.  I was able to reselect Segment Tier 2 on top, although the display did not change (except for the menu now indicating incorrectly that Segment Tier 2 is being displayed when it is still Segment Tier 1).

I was correctly prevented from re-selecting Segment Tier 1 on the bottom.

<img width="229" alt="Screen Shot 2022-12-20 at 12 28 12 PM" src="https://user-images.githubusercontent.com/13629122/208729041-157898f9-3ec6-43b5-befa-58bade43889a.png">

**Comment by gregorydimitriadis** [comment]
Will do another pass on this currently to determine if that visual residue can be addressed. But the core aspect (of not displaying the data in two segment tiers) is fixed here, I believe.

**Comment by douglas-motto-at-rutgers** [comment]
Can confirm that the menu still displays the "duplicate TP/ST" option in the drop down selected....although so far, I have not be able to actually select the duplicate and have two identical TP/ST in the same utterance window.

This is in version...pre_2023_02_03_1540

**Comment by douglas-motto-at-rutgers** [comment]
Further....the menu options aren't updating correctly...
Create two TP
TP1 create one SP
TP2 create three SPs

go to utterance view
select TP2, SP1 and add TP2, SP2
change TP2,SP1 to TP1, SP1
the menu for TP2, SP2...does not have TP2, SP1...even though it's not shown anymore.

**Comment by gregorydimitriadis** [comment]
@douglas-motto-at-rutgers Because that is technically not this issue (which is about the data concern of having two simultaneous segment tiers open) I would suggest we move that to a separate issue. And if there are no errors remaining with the data concern aspect of this issue I would consider it complete.

**Comment by gregorydimitriadis** [comment]
Created that new issue. This issue is complete in terms of the data concern.

**Comment by cneidle** [comment]
The specific issue of preventing double display of the same segment tier seems to have been resolved.  

Visual residue remains.  

Have not tested anything with more than one temporal partition.

**Comment by gregorydimitriadis** [comment]
Released in 3.4.1
