### ISSUE TITLE
Space character in segment tier label

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#527]
Renaming a segment tier " " causes problems and should be disallowed.  Either the xml save removes the space, or the validator trims the string...in either case it then throws an error on load.

Edit 2022-09-29: also address other special characters, not just space

**Comment by douglas-motto-at-rutgers** [comment]
The space shouldn't be allowed to be entered. Trim the input and reject if empty on change/add.

**Comment by gregorydimitriadis** [comment]
Added to Todo milestone on zoom call with Carol/Dimitri/Chuck 2022-09-27

**Comment by gregorydimitriadis** [comment]
Todo: 'space' character plus special characters: (<  >  :  /  |  ?  *  &)

Regex check for these characters and strip them out on change/add.

Est: 3 hours

**Comment by douglas-motto-at-rutgers** [comment]
don't strip out anything.

validate and deny if invalid.

**Comment by gregorydimitriadis** [comment]
Todo: validating on input for labels* to allow alphanumeric values, plus: ! @ # $ % ^ & * ( ) _ - ' " ?
Along with no trailing/leading spaces

*Labels being for: segment tier, temporal partition, gloss labels, field names/labels

This will expand the scope, so new estimate
Est: 7 hours

**Comment by douglas-motto-at-rutgers** [comment]
This issue will address when newly entered values are added via the UI.

It will not validate or correct existing issues in existing XML collection files.

**Comment by douglas-motto-at-rutgers** [comment]
I believe utterance names, non-manual free text, and macro unit names should also be validated.

**Comment by gregorydimitriadis** [comment]
Utterance names cannot be entered.

**Comment by douglas-motto-at-rutgers** [comment]
In the 1-2 years, there was a way that I was able to change the utterance name.  That could have been a bug that was fixed though.

**Comment by cneidle** [comment]
That was definitely a feature that existed and that was intended.

In fact, I have made good use of that feature for annotating certain
types of files, e.g.

<img width="1258" alt="Screen Shot 2022-10-25 at 1 47 38 PM" src="https://user-images.githubusercontent.com/13629122/197845804-f3caad62-4727-429a-a8fc-8080bb0b440f.png">

**Comment by cneidle** [comment]
<img width="785" alt="Screen Shot 2022-10-25 at 1 53 18 PM" src="https://user-images.githubusercontent.com/13629122/197846715-410651df-c519-4218-a996-1b22226b97f3.png">

from https://www.bu.edu/asllrp/SignStream/3/SS_User-guide.pdf, p. 27

**Comment by douglas-motto-at-rutgers** [comment]
Greg, 1st test.  If the application does NOT currently allow name changes, then make another issue for that per the descriptions Carol references and keep this issue purely about fixing the validation in the various fields.

**Comment by gregorydimitriadis** [comment]
My mistake - utterance names can still be edited in the way Carol described here.

**Comment by cneidle** [comment]
New pre-release version: December 2022. Something is very wrong with the options for renaming temporal partition and segment tier.

I first tried this to see if spaces would be allowed in renamed items.  They were accepted.

<img width="327" alt="Screen Shot 2022-12-20 at 12 05 42 PM" src="https://user-images.githubusercontent.com/13629122/208725202-c775e44b-bc9c-46d7-ad0a-0695abff0b45.png">

Then I quit SignStream without saving the file and re-opened it.  

I tried to rename the segment tier, and got this strange error message:

<img width="233" alt="Screen Shot 2022-12-20 at 12 06 54 PM" src="https://user-images.githubusercontent.com/13629122/208725590-e4cfb09f-04ba-4371-bf2d-64130cc00eca.png">

When I try to rename the Temporal Partition, sometimes, but not always, I get this message: 

<img width="305" alt="Screen Shot 2022-12-20 at 12 13 26 PM" src="https://user-images.githubusercontent.com/13629122/208726075-0be062fe-857f-4547-a974-bff5081c3193.png">

AHHH:

It seems that if I have the segment tier within the temporal partition selected, I get an error message.
If I have the Temporal Partition selected, I can proceed.

I don't know why there should be any error message about Display Time Period, since there is no menu option to rename it at all.

And it seems to me that the Rename Temporal Partition command ought to apply if any segment tier within he temporal partition is selected; no error message should appear.

**Comment by cneidle** [comment]
There is also something odd about the display of selected tiers.
What determines where the red box is?

Segment tier 1 selected:

<img width="774" alt="Screen Shot 2022-12-20 at 1 06 37 PM" src="https://user-images.githubusercontent.com/13629122/208736122-0fa5cd17-b26b-4f03-a329-6d20dad121e4.png">

Segment tier 2 selected:

<img width="778" alt="Screen Shot 2022-12-20 at 1 06 49 PM" src="https://user-images.githubusercontent.com/13629122/208736132-3f1c6fd9-2c1a-4c86-8f16-fb53166af39c.png">

**Comment by gregorydimitriadis** [comment]
The red box determines the 'defaul't segment tier - i.e. when a user double clicks on the TP, which ST is entered by default is determined by the red box. It is settable in a menu option.

**Comment by gregorydimitriadis** [comment]
Regarding this:

> I don't know why there should be any error message about Display Time Period, since there is no menu option to rename it at all.

I can reproduce the errors about Display Time Period showing up under these circumstances: if I have a temporal partition label selected, and try to do a segment tier menu option (other than "New"). This is definitely incorrect - we can spin this off into a separate issue if we wish.

> It seems that if I have the segment tier within the temporal partition selected, I get an error message.
If I have the Temporal Partition selected, I can proceed.
> And it seems to me that the Rename Temporal Partition command ought to apply if any segment tier within he temporal partition is selected; no error message should appear.

This is how it works when I'm testing it - if you have a temporal partition label selected, you can do the temporal partition menu actions for that temporal partition. If you have a segment tier label selected, you can do the segment tier menu actions for that segment tier OR the temporal partition menu actions for its parent temporal partition. (Exception: "New Segment Tier" works while selecting a temporal partition. Not seeing errors regarding these. 

If possible can you make a video of this error occurring?


Regarding the spaces in text:

This issue was originally meant to eliminate blank/whitespace values for labels. So blank values are not allowed to be entered into any text field. Spaces are allowed in the intermediate of a label, such as "Temporal Partition 1". Other characters are validated against too, and if anything not in that list is found it would not change the label value. Spaces from the edges will be trimmed out.

**Comment by cneidle** [comment]
I think the confusing thing is that there is no reason for the user to assume that the menu item must refer to something that is actively selected.  If you have one temporal partition, one segment tier, etc. then it is reasonable to assume that the menu option "Re(name) Segment Tier" should rename the segment tier, regardless of whether it has been selected prior to launching the menu item.  

Perhaps it would be helpful to modify these menu items to say:

<img width="365" alt="Screen Shot 2023-01-19 at 1 59 22 PM" src="https://user-images.githubusercontent.com/13629122/213536106-fa5021e1-7659-4858-9df3-382447734f96.png">

Rename Selected Temporal Partition
Delete Selected Temporal Partition

<img width="352" alt="Screen Shot 2023-01-19 at 1 59 16 PM" src="https://user-images.githubusercontent.com/13629122/213536114-9aba222c-9a9d-44bc-8e74-9ad07ecce13b.png">

(Re)name Selected Segment Tier
(Re)name Selected Participant
Delete Selected Segment Tier

Thanks!

**Comment by douglas-motto-at-rutgers** [comment]
Moved the new issues to...

https://github.com/DCS-LCSR/SignStream3/issues/636

and

https://github.com/DCS-LCSR/SignStream3/issues/635

**Comment by douglas-motto-at-rutgers** [comment]
In pre_2023_02_03...

TP, ST and Macro Unit labels which are nothing but spaces, now have no effect when entered.  But should doing so report an error to the user?

**Comment by gregorydimitriadis** [comment]
> In pre_2023_02_03...
> 
> TP, ST and Macro Unit labels which are nothing but spaces, now have no effect when entered. But should doing so report an error to the user?

I'm going to make it show the same message as everywhere else when attempting to create a blank text, to be consistent.

**Comment by douglas-motto-at-rutgers** [comment]
The message about valid characters for a label doesn't really indicate that in a space in between characters is allowed.  This might not be the case though for everywhere this alert is displayed.

**Comment by cneidle** [comment]
this seems to me to have been resolved.

**Comment by gregorydimitriadis** [comment]
Released for 3.4.1
