### ISSUE TITLE
Adding text on top of text in gloss window

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#54]
It is possible to add multiple glosses to the same spot. (tested using 1 frame glosses)

![](https://cloud.githubusercontent.com/assets/13489587/11220943/678efdee-8d30-11e5-84dd-6a572f729956.png)

**Comment by blazetravis** [comment]
NOT fixed. Can still add one frame glosses to the same frame.

**Comment by blazetravis** [comment]
This bug is fixed!
