### ISSUE TITLE
Gloss Window combobox N/A option

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#55]
Currently it is possible for a user to manually select "N/A" as an option for all 3 comboboxes dealing with "start/end handshape" behavior (except in the cases it is greyed out automatically).

**Comment by cneidle** [comment]
Hi Greg,

I’m not sure if you were seeking input or reporting that as a bug.

(If the former, I don’t think that’s the desired behavior.
Except where it has been eliminated for a specific reason,
the user should not have an option to choose “N/A”.)

thanks!
  Carol

**Comment by gregorydimitriadis** [comment]
Indeed - reporting as a bug : )

**Comment by blazetravis** [comment]
Fixed!
