### ISSUE TITLE
Long utterances

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#553]
When an utterance is too long, weird UI issues occur.
TBD more items on this issue as to regarding what exactly users see in this circumstance. 
TODO: add specific collection files where this is reproducible.

**Comment by gregorydimitriadis** [comment]
TODO: verify with example collection (with actual data) - do issues occur?

**Comment by gregorydimitriadis** [comment]
Added to Todo milestone on zoom call with Chuck 2022-09-29

**Comment by cneidle** [comment]
Is this example helpful?

<img width="1444" alt="Screen Shot 2022-09-29 at 12 52 50 PM" src="https://user-images.githubusercontent.com/13629122/193091956-70c5c125-2956-4304-87a2-b9bef35d12f0.png">

Will send the SS file by email (5-Ben-Deaf-Grunts.ssc)

**Comment by douglas-motto-at-rutgers** [comment]
With the "5-Ben-Deaf-Grunts.ssc" file and associated mov, one issue that appears is that when clicking on an utterance from the database view, the window slider at the bottom starts off all the way to the left, no matter where the window is actually at.  This is more obvious when selecting an utterance latter in time.  In which case the slider should be toward the right of the range, and not at the left.

At first click on the slider, it corrects itself to the right position.

This is reproducible with this file/mov.  When trying to make a new collection file with the same movie, and a late utterance, the slider's initial position works as expected.

Unclear if this is an issue with this collection file alone...or any collection file with this many annotations, etc.

**Comment by douglas-motto-at-rutgers** [comment]
Caro, Is there any other specific issues you have observed and remember?  With this file explicitly or other long collection files?

**Comment by cneidle** [comment]
What Doug described seems general, and, I thought, intentional:  When you double-click anywhere on an Utterance line from the database view, you go to the beginning of that utterance in Utterance view.  

I have not really experienced what Greg reported above.

**Comment by douglas-motto-at-rutgers** [comment]
This behavior is not intentional.  Split this to a new issue

https://github.com/DCS-LCSR/SignStream3/issues/641

and sent video of demonstrating it.

**Comment by douglas-motto-at-rutgers** [comment]
Greg if we can't identify other specific issues with long utterances, this issue should be closed.

**Comment by cneidle** [comment]
The following doesn't appear to occur in all collection files, but in the 5-Ben-Deaf-Grunts file it does....


Open the 5-Den-Deaf-Grunts.ssc file.
Start in the database view.
Click on one of the Utterances toward the end of video....like U30
When the Utterance view opens, look at the bottom of SignStream window....the bottom slider indicator is all the way toward the left of the slider bar and of a specific small size.

A slider indicator on the left means that the time window I'm currently looking should be at the begging of the video...but U30 is at the end...so the slider indicator should appear toward the middle or right of the bar, which it is not.

Now click (aka tap) on the slider bar...not the slide indicator itself.  As so as you do, you'll see the slider indicator moves/jumps to where it should be correctly...to the middle or right of that slider bar.  You'll also notice the slider indicator's size might change (although we didn't change the zoom level).

This is where the slider indicator should have been positioned when entering the utterance view.




--------------------------------------------------------
Douglas Motto
***@***.***

Application Developer Supervisor -- LCSR/CS
Coadjunct -- SC&I, CS
Rutgers, The State University of New Jersey
------------------------------------------------

________________________________

**Comment by gregorydimitriadis** [comment]
I have definitely observed that in other files as well.
