### ISSUE TITLE
Able to create utterances of same name

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#562]
TBD details to reproduce

Identifier for utterance - is it used *always*?

**Comment by gregorydimitriadis** [comment]
Added to Todo milestone on zoom call with Chuck 2022-09-29

**Comment by gregorydimitriadis** [comment]
Todo: attempt to reproduce issue of creating utterance of the same name. If discovered, address fix. Regarding identifier, comb through code anywhere an utterance is reference to see if it is being done with its identifier, or some other aspect like its label. All references should be through identifier.

Est: 4 hours

**Comment by douglas-motto-at-rutgers** [comment]
Greg...I suggest take this in two parts...

1st just try to see if this can occur...through the UI and (if unsuccessful) through code.  Just provide a time estimate for that.

**Comment by gregorydimitriadis** [comment]
Est for reproducing: 2 hours

**Comment by gregorydimitriadis** [comment]
It is possible to produce two utterances with the same name. Long press click on a selected utterance to change the name to another utterance of the same name.

It does cause issues. After doing that, then saving and re-opening, one of the duplicately-named utterances is lost from the "Temporal Partition" rows on the database view. The utterances remain on the "Segment Tier" rows, however, so it doesn't appear as though data is lost. But it is a jarring visual issue.

**Comment by cneidle** [comment]
There is an error message when trying to rename an utterance to contain the same name as another utterance.
So this appears to have been fixed :-)   Thanks.

**Comment by cneidle** [comment]
This seems to me to have been resolved (although I am having a hard time selecting the utterance name text for renaming)

**Comment by douglas-motto-at-rutgers** [comment]
Hard time selecting utterance name text for renaming likely related to https://github.com/DCS-LCSR/SignStream3/issues/638

**Comment by gregorydimitriadis** [comment]
Released in 3.4.1
