### ISSUE TITLE
Force Annotator selection on startup

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#57]
This enhancement is the extension of the idea from bug #47 
- If there are no Annotators (e.g. in the example of a fresh collection), force the user to create one before proceeding
- Each time SignStream starts up, it should prompt the user to select who they are, from the list of Annotators associated with the MacroUnit
  - Have a new button to get to the “add annotator” screen, perhaps with a different logic guiding the close of that screen
- Whatever the user picks should display in the top menu bar, but it can be changed at any point throughout the session
- Annotator selection should not persist between sessions. Each time SignStream starts up, the user must re-select annotator.
- Get current annotator” should be included in the Singleton

**Comment by blazetravis** [comment]
This enhancement is now in place.

**Comment by blazetravis** [comment]
Although I will add that there is a persisting inconvenience when switching between annotators.

Once start up sequence has been completed and annotator has been selected, I tried to switch annotators in an utterance.

Here is the utterance before anything and after log in:
![screen shot 2016-01-26 at 1 14 57 pm](https://cloud.githubusercontent.com/assets/13489587/12590028/e2df9c6c-c42e-11e5-84ec-e8e7792340b0.png)

My first attempt to change annotator. Only I am listen, so I continue on to change edit the macro unit.
![screen shot 2016-01-26 at 1 16 00 pm](https://cloud.githubusercontent.com/assets/13489587/12590045/f6b3f828-c42e-11e5-9257-90a4a75b72f8.png)

Again, only me here. So I click add to add another annotator.
![screen shot 2016-01-26 at 1 16 23 pm](https://cloud.githubusercontent.com/assets/13489587/12590055/064ac64a-c42f-11e5-9771-a6c75a32b9ae.png)

I click any name and click add selection.
![screen shot 2016-01-26 at 1 16 48 pm](https://cloud.githubusercontent.com/assets/13489587/12590074/13b54c4c-c42f-11e5-851a-961f37e3f663.png)

It looks like that selection has been added to I'm ready to enter out.
![screen shot 2016-01-26 at 1 17 07 pm](https://cloud.githubusercontent.com/assets/13489587/12590087/1fd01746-c42f-11e5-850e-c5d344d26d10.png)

Get this, or some version of a totally blank-looking utterance.
![screen shot 2016-01-26 at 1 17 30 pm](https://cloud.githubusercontent.com/assets/13489587/12590101/2dbc48b6-c42f-11e5-85c3-d100e0070f99.png)

But then when I move the zoom bar, everything "pops" back into the window.
![screen shot 2016-01-26 at 1 17 49 pm](https://cloud.githubusercontent.com/assets/13489587/12590115/39e7fd92-c42f-11e5-976a-6625e4c5f743.png)

Strange.

**Comment by gregorydimitriadis** [comment]
The zooming behavior is mostly unrelated to the annotator changes, but a slight tweak will allow me to fix it. I'll consider this bug fixed, and the zooming fix will be included (at no charge) in the next rollout.
Closing this out.
