### ISSUE TITLE
Upgrade to macOS 13 on intel and arm (via rosetta)

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#572]
Upgrade and test for macOS 13 on both intel and arm

**Comment by gregorydimitriadis** [comment]
Added to Todo milestone on zoom call with Carol/Dimitri/Chuck 2022-09-27. Highest priority item for upcoming release.

**Comment by cneidle** [comment]
**Note: macOS Ventura to be released to all users on October 24**

https://9to5mac.com/2022/10/18/macos-ventura-october-24-release/

**Comment by gregorydimitriadis** [comment]
Todo: test the below functionality of signstream after verifying it at least runs on macos13:

install latest version signstream
install sign bank
open existing collection, save as-is
open existing collection, make changes, save
new collection files, save, close, re-open
create utterance
create glosses, of various handedness, properties, etc
open new blank collection, save
need to test without and with signbank...
test inserting from the sign bank
open dai from the sign bank
need to test installing signbank different ways
via help option/script
manually downloading file and placing it in
need to test upgrading signstream
via help option/script
need to test videos of different types
need to test known collection files of specific versions.
zooming in and out, in db view and utterance view
scrolling with green bar, does it move the window automatically
playing events, playing next events, etc
playing video at various speeds
custom field properties, saving collection, loading
reordering fields
test search
make new segment tiers
make new temporal partitions
local participant and annotators
entities at beginning and end of videos, create and play
(potentially will add more here)

Est: 10 hours for both the upgrade and the test

**Comment by douglas-motto-at-rutgers** [comment]
Keep log of exact tests performed in order to reproduce or retest later.

Keep log of exact versions (and examples) of setup tested, MacOS, SS, and files (collection, schema, videos).

**Comment by douglas-motto-at-rutgers** [comment]
clarification...

Also keep a copy of the test files used....pre and post tests performed.  So to be able to reproduce these tests later if needed.

**Comment by gregorydimitriadis** [comment]
Released for 3.4.1
