### ISSUE TITLE
Ability to create multiple Temporal Partitions

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#58]
- We could make this a new set of menu bar options at the top of screen
  - New TP, Rename TP, Delete TP, etc
- Make sure that “new segment tier” and “default segment tier” functionality work in the context of multiple TP’s
- May require a tweak of data structures used by TP, ST, gloss item objects
- Make sure that shift-clicking into an utterance does not load segments from other TP’s
- When a new TP is made, there should be a new ST made for it, with a default name, and it is itself the default segment tier for that TP

**Comment by blazetravis** [comment]
This seems to be running very smoothly!
