### ISSUE TITLE
Add a new option under the menu bar “Segment Tier” > “Set Default Segment Tier”

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#60]
- You must have a segment tier label selected for this to work
- This will update the segment tier object and set the parameter for default to true
- This will also update every other segment object (the ones which were unselected under the same TP) and set their object parameters for default to false
- Need some way to display which ST is default after it is set
  - Bold? (best option) Asterisk? Underline?

**Comment by blazetravis** [comment]
Enhancement seems to be working smoothly.
