### ISSUE TITLE
previous fingerspelling gloss remains in new morph-info window

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#613]
When entering a new main gloss into the Morph-Info window after I have previously entered information for a fingerspelled gloss, the information from the old gloss shows up in the "Palette" window without any handshapes just the word of the gloss. File RIT_P02-s02

![fingerspelling issue](https://user-images.githubusercontent.com/38887034/209604336-ded39d64-9838-475e-9f71-942d7e055841.png)

**Comment by douglas-motto-at-rutgers** [comment]
Confirmed on 3.4.1_pre.

See #579

**Comment by cneidle** [comment]
Yes, happens consistently.  Does not need to be fingerspelled sign.  E.g., the handshape X (not entered through typing the letter, and not a fingerspelled sign) shows up in the typing box of the next sign I attempt to finger spell.

<img width="444" alt="Screen Shot 2023-01-20 at 4 55 01 PM" src="https://user-images.githubusercontent.com/13629122/213812996-3dc56267-c829-4582-94c9-3591e683f725.png">

**Comment by cneidle** [comment]
This happens all, or almost all, of the time.

**Comment by gregorydimitriadis** [comment]
This has been fixed for the next release.

**Comment by gregorydimitriadis** [comment]
Released in 3.4.1
