### ISSUE TITLE
SS freezes

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#619]
Using the search feature of SS and it freezes when trying to scroll through highlighted utterances selected through the search feature. 

![Screen Shot 2023-01-17 at 8 52 25 PM](https://user-images.githubusercontent.com/38887034/213087684-34ef7fde-1d12-4b72-a73d-12045c5e4359.png)

**Comment by bugspotter33** [comment]
Had to force quit SS it froze.

**Comment by gregorydimitriadis** [comment]
Seems to be the same as #617 - closing this one in favor of that.
