### ISSUE TITLE
Ability to shift-click into one segment in isolation

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#62]
This enhancement will be the completion of tasks from bug #31 
- One segment meaning: a “segment bar” (which is any of the bars under the “utterance bar” in the Temporal Partition layer line)
- Doing so will display the usual UtteranceView window, but just the one segment
  - Temporarily shift-click into an utterance bar and shift-click into a segment bar may take the user to different windows, while the new UI is being built

**Comment by blazetravis** [comment]
This is complete.
