### ISSUE TITLE
Move current left-side panel in utterance view to the top row of the panel

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#63]
- Currently in the left-side panel is the collection name, and macro unit name
- Currently in the top row of the panel is the zoom slider and the measure bar
- We will be moving the collection name and macro unit name into the top row, on the same line as the zoom slider and measure bar. It will take up one line, just to act as a mechanism to return to the overview window
- In the overview window, maintain the left side panel as it is for now

**Comment by blazetravis** [comment]
This enhancement looks great. Thanks!
