### ISSUE TITLE
Create a new left-side bottom row panel

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#64]
- The bottom row of the panel will now contain the scroll bar on the right and a new panel for new/remove/up/down on the left
- Between the top and the bottom rows will be a variable number of rows of segments
- The bottom row will control the segment rows. ‘New’ will be a button to add a new segment row. ‘Remove’ will remove the selected segment row from view. ‘Up’ and ‘Down’ will move the selected segment row up or down.

**Comment by blazetravis** [comment]
The new panel looks great! I'm not sure how to test the new, remove, up, and dn buttons though. Any suggestions?

**Comment by gregorydimitriadis** [comment]
At the moment, the New/Remove buttons don't do anything (they'll be fleshed out in the next release).

But the up/down buttons do work - to test those, click on the left side panel for a row (the box with the TP and ST names, etc) to highlight it, then click up/down to move the row around.

**Comment by blazetravis** [comment]
Perfect. This is working well.

**Comment by gregorydimitriadis** [comment]
Moving this to Sprint 11, during which I will complete the functionality for the New and Remove buttons along with the other GUI changes occurring then.

**Comment by blazetravis** [comment]
All buttons are now working well!
