### ISSUE TITLE
Appropriate message for the general public

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#640]
Messages like this:

<img width="463" alt="Screen Shot 2023-02-06 at 5 29 07 PM" src="https://user-images.githubusercontent.com/13629122/217102105-bda0802e-520c-498c-b47a-47e09ab46491.png">

are fine for internal purposes, e.g., testing of pre-release versions.  

However, for public releases, this is not appropriate.

If you want people emailing files to "SignStream developers", then information needs to be provided about where such email needs to be sent.

thanks.

**Comment by cneidle** [comment]
Should be fixed before next release.

**Comment by cneidle** [comment]
Should be fixed before next release

**Comment by cneidle** [comment]
All messages that include

"please send SIgnStreamOut.txt to the developers" 

need to be reworded so that anyone outside of our team who gets such a message can interpret it and know what to do.  thanks.

**Comment by gregorydimitriadis** [comment]
@cneidle  The two messages which include this are:

"Media player encountered an internal error! Please send SignStreamOut.txt to the developers and restart SignStream."

and

 "Failed to open collection file!"Please send SignStreamOut.txt to the developers."

Is it sufficient to change these to:

"Media player encountered an internal error! Please restart SignStream."

and

 "Failed to open collection file!"Please restart SignStream."

**Comment by cneidle** [comment]
That sounds fine.

Perhaps insert:  “Apologies for the inconvenience.” Between the two sentences
for both revised message?

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
Released in 3.4.1
