### ISSUE TITLE
Pre-release 3.4.1. Multiple textboxes appear for renaming utterances, and no way to cancel or get rid of them.

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#649]
<img width="1043" alt="Screen Shot 2023-02-13 at 11 46 27 AM" src="https://user-images.githubusercontent.com/13629122/218519595-38f8ec48-5417-4efb-a8a4-50b27cfb3a90.png">

============================

<img width="1058" alt="Screen Shot 2023-02-13 at 11 47 23 AM" src="https://user-images.githubusercontent.com/13629122/218519622-9dc7fbfb-49e3-4dba-b3bf-c20a17091d09.png">

**Comment by cneidle** [comment]
In Utterance window, same issue with scrolling and placement.  But it is possible to cancel.  But if the user types nothing but a carriage return, this message should not appear (in database or utterance view):

<img width="323" alt="Screen Shot 2023-02-13 at 12 21 45 PM" src="https://user-images.githubusercontent.com/13629122/218528189-0ecae018-3927-45d1-8850-94691eeb89c3.png">


<img width="522" alt="Screen Shot 2023-02-13 at 12 20 39 PM" src="https://user-images.githubusercontent.com/13629122/218528218-40fd71f1-4f17-4a10-8060-785b9f2eb1bb.png">


<img width="580" alt="Screen Shot 2023-02-13 at 12 20 45 PM" src="https://user-images.githubusercontent.com/13629122/218528250-f9ee7a9d-f1c1-4e57-9fd2-8027a35b2595.png">

**Comment by cneidle** [comment]
Correction:  Not always possible to cancel from Utterance view...

<img width="521" alt="Screen Shot 2023-02-13 at 12 33 03 PM" src="https://user-images.githubusercontent.com/13629122/218530363-4135d0c7-5e53-4a54-9854-b5504689e48f.png">

<img width="605" alt="Screen Shot 2023-02-13 at 12 33 10 PM" src="https://user-images.githubusercontent.com/13629122/218530377-44d610c4-9559-4811-b92e-7c6c0c5a3c1c.png">

**Comment by cneidle** [comment]
Related to #611 #647 #624 #625

**Comment by gregorydimitriadis** [comment]
Believed to be related to: https://github.com/DCS-LCSR/SignStream3/issues/527

**Comment by gregorydimitriadis** [comment]
@cneidle how do you reproduce getting multiple text boxes open at once? If I attempt to do it on one utterance, the warning message pops up and I'm unable to keep clicking the screen until I close it.

**Comment by cneidle** [comment]
Hmm..  What you describe is what's happening for me now.  But the box still shows up in the wrong place, e.g., I click on U1, and see this:

<img width="943" alt="Screen Shot 2023-02-21 at 12 19 33 PM" src="https://user-images.githubusercontent.com/13629122/220415376-00d5e396-b458-40fd-ba83-0aaa47894e3f.png">

**Comment by douglas-motto-at-rutgers** [comment]
Marking this issue as code-complete.  If multiple boxes still can happen, please let us know.

The "wrong location of textbox" behavior is mentioned in...https://github.com/DCS-LCSR/SignStream3/issues/638

If issue "638" is also required in this milestone, we should move that issue in.

**Comment by douglas-motto-at-rutgers** [comment]
keeping open.

Per Greg...

I didn't comment on the github. But the multiple boxes is reproducible. Alt-click the dom/ndom gloss fields very quickly repeatedly. I can demonstrate if needed

-Greg

**Comment by gregorydimitriadis** [comment]
This is in progress, to be included in next release.

**Comment by gregorydimitriadis** [comment]
Released in 3.4.1
