### ISSUE TITLE
Left-side panels for selection of TP;ST;U

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#65]
Abbreviations: TP = Temporal Partition, ST = Segment Tier, U = utterance

This enhancement is the extension of bug #45 

Referring to all changes below as occurring within the utterance view.
- What we are referring to as the new “left side panel” and the old “utterance pane” will need to be joined into a single entity, or at least act in concert when the screen scrolls, etc
- Each row is a segment, the left side of which shows the TP;ST;U selection and the right side of which shows the segment template as it is now (without the segment control panel at the bottom)
- Each row must be selectable, and it needs to be visible that it is indeed selected. Once selected, a row can be removed, or moved up or down
- Color highlighting of clicked utterances. Perhaps red for clicked, blue for utterances being displayed as a result in other panes, and yellow for initially selected but currently out-of-view.
- Need comboboxes for TP and ST selection, and a list for utterance displays and selections

**Comment by blazetravis** [comment]
Everything is working well here, except as mentioned the new utterance panel.
