### ISSUE TITLE
Readme for 3.4.1 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#651]
needs to be updated.  

References to GitHub tickets toward the end need to be replaced with one-sentence summaries.

If this can be done sooner rather than later, I can start drafting documentation about what has changed in this new release.  

There are also some spelling errors (pls run spell-check).

Thanks!

**Comment by douglas-motto-at-rutgers** [comment]
@gregorydimitriadis

The Supporting OS section of the README needs to be updated.  The development team is no long developing and testing on anything older than macOS 13.

So while it "may" work on older OS versions, we don't know.  

Perhaps the README (and elsewhere) should reflect this.

**Comment by douglas-motto-at-rutgers** [comment]
@gregorydimitriadis Also update REAME per email regarding removing unused libraries.
