### ISSUE TITLE
Gestures: Palm orientation

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#654]
Related back to main gesture enhancements #648

Closely related to #655 (fingertip orientation)

In the current gesture implementation there is an orientation field (one for dom, one for ndom) which corresponds with the handshape field. This issue would refashion a generic orientation field into a specific orientation field for palm orientation. The linked issue for fingertip orientation would be building a new field entirely.

Involved in this is: getting the updated orientation images as part of specifications, using those in the coding scheme file, updating the images in the application, and updating in the code the relevant usages of these images.

**Comment by gregorydimitriadis** [comment]
@cneidle comparing this to how gestures has worked in the past:

When annotating a gesture, and selecting handshapes/orientations, what is the intended flow:

A person opens up the palette to select handshapes/orientations. They select a handshape. Are they required to select a corresponding palm orientation to match that handshape? Are they required to select a corresponding fingtertip orientation also? Are the orientations independent, or must co-occur? (as handshapes and (generic) orientations did in previous SignStream releases with gesture capabilities)

**Comment by cneidle** [comment]
This is what we have now, for co-speech gestures.

<img width="597" alt="Screen Shot 2023-02-20 at 4 34 33 PM" src="https://user-images.githubusercontent.com/13629122/220201719-b0b3e18e-fd10-40c4-8a60-ce61e78d9629.png">

It is possible to choose 'do not include' for the orientations.

But an orientation, if present, has to be paired with a handshape.

So for every handshape, there is either a specified orientation, or none (if 'do not include' is selected).

The difference would be that there would be an extra row.  So every handshape would be associated with one or both orientations (for either or both, "do not include" can be selected):

<img width="658" alt="Screen Shot 2023-02-20 at 4 34 40 PM" src="https://user-images.githubusercontent.com/13629122/220201893-27e28803-1434-4c63-b8c9-c1ed8a8730c2.png">

**Comment by gregorydimitriadis** [comment]
If a handshape is selected, (assuming no orienation for the gesture) would a user then have to selected 'do not include' for palm and 'do not include' again for fingertip? I think there will be two orientation "palettes" one for palm and one for fingertip.

**Comment by cneidle** [comment]
Yes on both counts, as shown in the picture above.

**Comment by douglas-motto-at-rutgers** [comment]
Do orientations have selectable palettes?  As shown by the dropdown next to "Orientations:".  Similar to "Handshapes:"

If selectable, are all orientations palettes selectable as a palm and fingertip?  Or some palettes just for palm or just for fingertip.

**Comment by cneidle** [comment]
Subsumed by #655.
