### ISSUE TITLE
Segment Control Panel changes

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#66]
- Next/Prev utterance buttons will be removed entirely, because they would be redundant - you can just click between utterances on the left
- All labels (e.g. “Temporal Partition 1   Segment Tier 1   U2” should be moved to the left-side selector panel, in combo-boxes and a list
- Annotator selector will go somewhere else
  - Likely the top navigation panel
- Participant will no longer be selectable. Instead it is just a text string
  - Participant name will be tied to segment tiers. When a new ST is created, user will need to select a participant which will be included in the text string of the ST name.
- Hide/Show behavior needs to be re-thought
  - Remove button to the right of “add new” button
  - Some way to select the row you wish to remove
  - Mouse-over text making it explicit no data will be deleted, only “hidden”
- Notes and Fields buttons
  - Notes can be a right-click option on each utterance in the left-side box
  - Fields will be taken care of separately in bug #61

**Comment by blazetravis** [comment]
Everything looks terrific here.
