### ISSUE TITLE
Reselecting "Diff't Handshapes Dom & Ndom" issue

### ISSUE THREAD

**Issue by douglas-motto-at-rutgers** [DCS-LCSR/SignStream3#669]
For an already existing 2 handed sign which was annotated with "Diff't Handshapes Dom & Ndom" and having different handshape images set for the don and nondom hand...

...if re-opening the Morph Phon window on such an annotated sign and RE-selecting "Diff't Handshapes Dom & Ndom", then preselected non-dominant hanshapes will be cleared out.

In SignStream 3.3.6, 2 handed signs with "Diff't Handshapes Dom & Ndom" with only handshapes on one hand (not both) would be allowed to be entered.  Starting in 3.4.0 such a sign would not be allowed to be entered with a warning message preventing it.

Not clear if a correction exists for data files edited/created in 3.3.6 or before versions.

In version 3.4.0 and later, this appears to be just a UI issue, but still an unlikely desired behaviour.

**Comment by douglas-motto-at-rutgers** [comment]
per 

https://github.com/DCS-LCSR/SignStream3/issues/622

there may be a correction needed in the collections files for when this may have occurred.

**Comment by gregorydimitriadis** [comment]
Released in 3.4.1
