### ISSUE TITLE
Switching from 2 to 1 handed automatically.

### ISSUE THREAD

**Issue by douglas-motto-at-rutgers** [DCS-LCSR/SignStream3#678]
I don't know if this is a bug or a feature.

SS 3.3.6 public versions would allow signs clicked as 2 handed to only have one hand have handshapes defined.  The other hand would be blank.  So collection files saved with that version would have data saved as so.

If reopening the collection file in any recent version of SS, when opening the morph phon window for that sign....the 2 handed option, is switched immediately to 1 handed...changing other settings as well in the window.  So that sign is now listed as 1 handed.

On save the change is permanent.

Not sure what happens if that sign is never opened and the file resaved.

**Comment by gregorydimitriadis** [comment]
Completed as part of #622

Released in 3.4.1
