### ISSUE TITLE
Scroll continuously horizontally in the Utterance window

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#68]
- Once the user is viewing utterances, need the ability to scroll left or right continuously as if moving through the entire video timeline between all utterances in the collection.
- In between utterance spaces will be the background shade of brown, which currently indicates the end of an utterance
- Maintain zooming behavior as it currently is
- Clicking to a new utterance “re-frames” the view back to the timeslice represented between the start and end of that utterance

**Comment by blazetravis** [comment]
This feature is working wonderfully.
