### ISSUE TITLE
Characters allowed within glosses:  worked properly in 3.4.0, not in 3.4.1

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#684]
This gloss can be properly entered in 3.4.0, but there is an error message in 3.4.1.
<img width="454" alt="Screen Shot 2023-06-23 at 12 51 40 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/c4a010d5-0d2b-4ff1-83f3-0cf64af858d7">

**Comment by gregorydimitriadis** [comment]
Is this and what remains of #677 the same?

**Comment by cneidle** [comment]
Yes - I believe that this is the same issue as what remains of #677

**Comment by gregorydimitriadis** [comment]
@cneidle can you reproduce this on 3.4.1? I cannot currently. (Specifically from the MorphPhon window)

**Comment by cneidle** [comment]
This is so strange !  I recall I did have problems with this,  it it seems to be working now !Sent from my iPhone; please excuse typos.On Oct 10, 2023, at 1:51 PM, Greg Dimitriadis ***@***.***> wrote:﻿
@cneidle can you reproduce this on 3.4.1? I cannot currently. (Specifically from the MorphPhon window)
