### ISSUE TITLE
The "insert all data" button does not work 

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#688]
File RIT P02S04 U2 I am working on the gloss NAME/CALL but when I try to click the 'insert all data' button it doesn't work. I just entered the handshapes manually.

![Screen Shot 2023-09-02 at 3 20 54 PM](https://github.com/DCS-LCSR/SignStream3/assets/38887034/f42e8433-64e7-4ee2-8964-517e19d47f1c)

**Comment by cneidle** [comment]
This is fixed in the latest SignStream Sign Bank
