### ISSUE TITLE
For Gesture prototype released in July 2023 

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#693]
1. Dynamic sizing utterance view  panels (for nonmanual, gloss, gesture) - remembered when returning and saving/loading the collection
     > This is already 'most of the way' there, but requires some finishing touches, bugfixes, etc

2. Duplicate handshape palette demonstrated in Gallaudet demo meeting (RE: 'weirdness' email)

3. Handshape palette overhaul/refactor - making look and feel consistent across glosses and gestures, resolving bugs and inconsistencies, increasing code quality and long-term maintenance capability
   > Also partially complete

**Comment by gregorydimitriadis** [comment]
Closing in favor of individual issues created and linked here.
