### ISSUE TITLE
Gloss Window - issues with Enter button

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#7]
1. Cannot enter out of gloss window if handshape images do not show up
2. After user has edited the gloss name, user is not able to press enter key to leave the menu and save changes (unless handshapes are selected)

TODO: First confirm if these behaviors are expected
TODO: If it is expected, perhaps move this issue to a Feature, implementing a dialog box to explain to the user what is possible

**Comment by gregorydimitriadis** [comment]
Can no longer reproduce the "cannot enter out of gloss window" behavior.

However, we will reserve this ticket for enforcing _when_ the enter button should be greyed out. For example, if gloss name is deleted and becomes empty - should grey out enter button.

**Comment by blazetravis** [comment]
Enhancement completed.
