### ISSUE TITLE
Sign Video error message

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#701]
Tried to view the gloss ALL-OVER and the play sign utterance and play composite video  gave me an error message. Working in file RIT_p02-s03 U70 gloss is marked as UNKNOWN but the meaning of the gloss is "all-over".

![Screen Shot 2024-01-24 at 8 17 07 PM](https://github.com/DCS-LCSR/SignStream3/assets/38887034/5f23859a-2169-4778-8893-45337d8df221)

**Comment by cneidle** [comment]
@kwasiopoku  We should generate a new Sign Bank file for SignStream after all the data changes are completed.  thanks!

**Comment by cneidle** [comment]
@bugspotter33  Thanks, Indya.  You can view this sign properly if you go to the DAI on the web: https://dai.cs.rutgers.edu/dai/s/signbank

**Comment by bugspotter33** [comment]
Happened again with the gloss CROWDED. FIle RIT_p02-s03  U17
![Screen Shot 2024-01-26 at 8 05 55 PM](https://github.com/DCS-LCSR/SignStream3/assets/38887034/b1c1e323-967b-4e2b-b2d1-27a53c2b5a64)

**Comment by cneidle** [comment]
The first one is OK now, with the latest Sign Bank, but there is still a problem with CROWDED_2

<img width="941" alt="Screen Shot 2024-06-19 at 4 00 42 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/e33d5a68-47e2-4105-a2ff-2bff478404c3">

Copying Augustine on this:  @kwasiopoku

**Comment by cneidle** [comment]
@gregorydimitriadis I checked this with Augustine, and he has no explanation for why SignStream is not playing this video, since the URL is good.  https://dai.cs.rutgers.edu/ss3front/sign_388288.mp4 plays fine...    ??

**Comment by cneidle** [comment]
Resolved, with new SignStream Sign Bank.
