### ISSUE TITLE
Insert All Data button is not working

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#702]
Working on SS 3.4.1 macOS Mojave file p02 s03
The gloss NAME/CALL was to be entered in U20 but when I tried to use the Insert all data button it did not work. I entered the handshapes manually. 

![Screen Shot 2024-02-03 at 1 04 56 PM](https://github.com/DCS-LCSR/SignStream3/assets/38887034/3b4df82c-02e7-4090-ac0f-851fe75a41c5)

**Comment by cneidle** [comment]
This is working now, with the latest SignSTream Sign Bank
