### ISSUE TITLE
Cannot install latest version

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#703]
Double clicking initially on the SignStream application causes this to display:

<img width="246" alt="Screen Shot 2024-07-09 at 2 56 17 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/8ba4e596-d602-42ad-b3a8-5092f7be1eeb">

I go to system preferences and authorize opening the program:  OPEN ANYWAY

<img width="657" alt="Screen Shot 2024-07-09 at 2 56 44 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/91f72aeb-5af0-4691-80a5-840471fcb707">

Nothing happens.

Double-clicking again on SignStream does not work.  Nothing happens when I click on "open"

<img width="257" alt="Screen Shot 2024-07-09 at 2 56 53 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/ec51b3e3-0aa2-4dbb-8611-19d44a50145c">

**Comment by gregorydimitriadis** [comment]
@cneidle resolved or got a workaround?

**Comment by cneidle** [comment]
False alarm.   I had forgotten disable quarantine.  Sorry !!!Sent from my iPhone; please excuse typos.On Jul 9, 2024, at 3:06 PM, Greg Dimitriadis ***@***.***> wrote:﻿
@cneidle resolved or got a workaround?
