### ISSUE TITLE
Testing version provided on July 9, 2024

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#704]
[updated for latest version provided by Greg]

1) From #696

The problem reported with "clear" for handshapes persists...

<img width="412" alt="Screen Shot 2024-07-09 at 3 42 33 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/88192a61-c670-4fb3-9ff6-13cf5a7d8dab">

as does this issue:

<img width="480" alt="Screen Shot 2024-07-09 at 3 57 52 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/c43d8ae0-b101-43d8-bf45-7f85bfce020f">

**Comment by cneidle** [comment]
2. Editing the translation in the translation field does not work.

<img width="203" alt="Screen Shot 2024-07-09 at 3 21 32 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/d9e6e900-7199-4bbc-98d6-af1f5940d8aa">

I try to edit this, but when I hit a carriage return to save, the text does not change.

<img width="754" alt="Screen Shot 2024-07-09 at 3 21 49 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/5348bc89-c2a4-459d-9010-0be14074c966">

Similarly if I try to delete something from the end of what I had entered.  Nothing happens.

<img width="332" alt="Screen Shot 2024-07-09 at 3 22 57 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/1b58cc8e-f76c-4cd6-a70e-045ff24251e2">

**Comment by cneidle** [comment]
CN - 7/16 - This seems to have been fixed:  

The problem with "do not include" options for orientation has not been taken care of. 
This should always be allowed.

<img width="812" alt="Screen Shot 2024-07-09 at 4 13 55 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/f4d1a317-092a-4838-8ce3-71df324b8cbe">

**Comment by cneidle** [comment]
Handshape palette display is way off; see #705

**Comment by cneidle** [comment]
Arrow keys still not working to navigate the left-hand index.

**Comment by gregorydimitriadis** [comment]
Sign bank search window is curently busted - when either "View Occurrences" or "Play Video" is used the window becomes unresponsive and you cannot close it.

   CN Observation:  Once you have closed the Sign Bank search window, the other search window can again be closed.  Of course, that should not be necessary...

**Comment by cneidle** [comment]
Difficulty renaming an utterance, see #706 .  Never mind.  I figured out the trick, which was not self-evident.  See #706 .  I can include that in the documentation.

**Comment by cneidle** [comment]
Bug with View menu when there is more than one segment tier:  see #707

**Comment by cneidle** [comment]
Adding these tips to the SIgnStream documentation (although it would certainly be preferable to fix the issue with quotation marks coming in as some other special characters -- or counting those special characters as acceptable for spaces occurring in between them).




<img width="1016" alt="Screen Shot 2024-07-12 at 4 12 17 PM" src="https://github.com/user-attachments/assets/a1a143e4-9880-44fd-8de1-ac7839bb3d92">



<img width="995" alt="Screen Shot 2024-07-12 at 4 12 05 PM" src="https://github.com/user-attachments/assets/3016f232-ed77-4318-9926-a50d8936d1c7">

**Comment by cneidle** [comment]
sometimes crashes on attempts to quit; see #711

**Comment by cneidle** [comment]
Some small changes needed in the text for windows that appear in relation to the video lookup. See #710 and #712

**Comment by cneidle** [comment]
There is a problem with the various field selection and display buttons disappearing when the non-manual pane is hidden.  See #708

**Comment by douglas-motto-at-rutgers** [comment]
> 2. Editing the translation in the translation field does not work.
> 
> <img alt="Screen Shot 2024-07-09 at 3 21 32 PM" width="203" src="https://private-user-images.githubusercontent.com/13629122/347119861-d9e6e900-7199-4bbc-98d6-af1f5940d8aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzcyOTEsIm5iZiI6MTcyMTEzNjk5MSwicGF0aCI6Ii8xMzYyOTEyMi8zNDcxMTk4NjEtZDllNmU5MDAtNzE5OS00YmJjLTk4ZDYtYWYxZjU5NDBkOGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEzMzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5OWI1MTUxODAyOTM5NzAzYWE3ODE0MGJlN2ZlNzMyNjVkZGJjN2NmN2QwZWE0MzRjMmUwNTNiMDNlY2I2NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fuSywYSoVTyfR7FhUD71ZAPL7YAs2aOdqmiALgIlwwk">
> I try to edit this, but when I hit a carriage return to save, the text does not change.
> 
> <img alt="Screen Shot 2024-07-09 at 3 21 49 PM" width="754" src="https://private-user-images.githubusercontent.com/13629122/347119969-5348bc89-c2a4-459d-9010-0be14074c966.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzcyOTEsIm5iZiI6MTcyMTEzNjk5MSwicGF0aCI6Ii8xMzYyOTEyMi8zNDcxMTk5NjktNTM0OGJjODktYzJhNC00NTlkLTkwMTAtMGJlMTQwNzRjOTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEzMzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNGNlM2UxNDUzMjM5NzU0MDM3YjFiYzZiNzE4NjQzYzc2ZjQzMTEzOTViNmJjNTc4ZTMwNWMzZTc1MjhlZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w3jOOjcJ5gHlGSQTzWVhQ_lw30SP1wYrVrSa0eanhg4">
> Similarly if I try to delete something from the end of what I had entered. Nothing happens.
> 
> <img alt="Screen Shot 2024-07-09 at 3 22 57 PM" width="332" src="https://private-user-images.githubusercontent.com/13629122/347120182-1b58cc8e-f76c-4cd6-a70e-045ff24251e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzcyOTEsIm5iZiI6MTcyMTEzNjk5MSwicGF0aCI6Ii8xMzYyOTEyMi8zNDcxMjAxODItMWI1OGNjOGUtZjc2Yy00Y2Q2LWE3MGUtMDQ1ZmYyNDI1MWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEzMzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZjMwYzU5N2QxNWI2ZmMyNjM0NzI5ZjM1YWU2ODc5Y2IxZWVjMDJhY2ZiNzU1ZWE1NGMxMWIyYWM4ZjNkMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mPIW-V2QXn5hfq0CoVBQDPVUqojbRqGJV0kWYoHlw8w">

appears to occur in 3.4.1 as well.

**Comment by cneidle** [comment]
Yes exactly!

This was a serious bug, reported some time ago, which needed to be fixed.

**Comment by douglas-motto-at-rutgers** [comment]
I was wrong here as well.  I was able to edit the translation successfully in 3.4.1.

**Comment by cneidle** [comment]
There were different problems with the translation field in 3.4.1.

Apparently attempts to resolve those have resulted in this new situation.
