### ISSUE TITLE
Serious problem with handshape palette display

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#705]
This is what we see in 3.4.1 (scrolling through with expand all triangles):

<img width="442" alt="Screen Shot 2024-07-10 at 1 05 13 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/4255495d-c364-4976-9395-9df354060e9d">

This is what is shown in the latest version you sent:

<img width="968" alt="Screen Shot 2024-07-10 at 1 10 01 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/f0001bba-d869-483a-9303-4809d60ac652">

Aside from the imbalanced display, many handshapes are missing and/or in the wrong order.

For example, these handshapes are missing (not a comprehensive list, just a comparison of the first column):

<img width="144" alt="Screen Shot 2024-07-10 at 1 13 18 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/f7dcdda6-1a8b-46b3-a8c2-4eb48e718733">

F/9 is in the wrong order, and not listed with its variants underneath it...

Other groupings are also quite wrong.  For example, "relaxed handshape" is listed under "R".

"5" is listed as expandable, but none of the variants are underneath it...

<img width="238" alt="Screen Shot 2024-07-10 at 1 22 25 PM" src="https://github.com/DCS-LCSR/SignStream3/assets/13629122/4ce05d31-72ff-418f-ad06-39cd51561d32">

  Etc.

Something is very wrong, in any case.  Thanks.

**Comment by gregorydimitriadis** [comment]
@cneidle can you reproduce the 5 and/or B not showing the things under it? I can't get that aspect to show, but I do see the bug where it over-fills the right-side column. Everything appears to be remaining clickable when I do that, though.

Do you have a definitive list of the handshape/group changes which are incorrect that you see here? Thanks in advance.

**Comment by cneidle** [comment]
This is all terribly wrong -- and terribly inconsistent.

[handshapes-seriously-broken.pdf](https://github.com/user-attachments/files/16238150/handshapes-seriously-broken.pdf)

I would suggest using the 3.4.1 handshape palette, and throwing out whatever is being used in this latest version.
"do not include" should also not be included for ASL handshapes (only for gestures).

The ASL numbers, letters, and unmarked handshape palettes are fine in the latest version.  It is just the ASL handshape palette that is totally totally broken.

**Comment by cneidle** [comment]
When you ask: 
> can you reproduce the 5 and/or B not showing the things under it? 

This is part of the problem!   The triangle expansions are totally inconsistent !   What appears under the triangle should be not only correct, but also consistent...   needless to say.

**Comment by cneidle** [comment]
And now seeing different errors looking at the ASL handshape palette from Gesture Mode - e.g.

expanding the "I" triangle:

<img width="247" alt="Screen Shot 2024-07-15 at 3 28 08 PM" src="https://github.com/user-attachments/assets/a6fec435-32c3-42f9-bc13-9f940b03cd42">

This is what *should be* under I:

<img width="147" alt="Screen Shot 2024-07-15 at 3 29 39 PM" src="https://github.com/user-attachments/assets/0f78d66f-8119-46d5-9961-b811f461c9e2">

The rest are separate entries, not under "I":

<img width="129" alt="Screen Shot 2024-07-15 at 3 29 48 PM" src="https://github.com/user-attachments/assets/d11cafbc-dcfb-4c4d-9be8-b2bb6912a3af">

**Comment by gregorydimitriadis** [comment]
I have a solution for the palette. It is not the prettiest thing, but it ensures that all handshapes remain visible and functional, although handshapes from the same 'groupings' or dropdowns may be split across columns. But everything that should remain visible and clickable regardless of which dropdowns are open is working.

**Comment by cneidle** [comment]
The ASL handshape palette from version 3.4.1 is perfect.

Why can we not use that one?

thanks.

**Comment by gregorydimitriadis** [comment]
It's not the palette that's the issue. It's a code thing, which takes in the palettes as they are specified in the coding scheme file, and renders them dynamically. Prior to this they were all hardcoded in the code, so changing them meant making a new version of code/release. Now changing them can be done with a replacement of the coding scheme file (which we don't do currently but could be done for quick patches).

**Comment by cneidle** [comment]
Ok.  Thanks.   Please let me know when it’s available to be tested.

**Comment by cneidle** [comment]
This looks pretty good so far.  But there is one error in the grouping.  In the July 16th version, several handshapes are grouped under I, which should be independent.  This is what is in the latest version:

<img width="283" alt="Screen Shot 2024-07-16 at 5 40 42 PM" src="https://github.com/user-attachments/assets/e5e30fa2-569a-4b47-8681-90d890c61d7d">

<img width="300" alt="Screen Shot 2024-07-16 at 5 40 35 PM" src="https://github.com/user-attachments/assets/3ac0d4b6-5313-4683-bd70-60947ebae006">

But the second group below should not be grouped under I: Horns, bent-Horns, and O/2-Horns

<img width="199" alt="Screen Shot 2024-07-16 at 5 40 02 PM" src="https://github.com/user-attachments/assets/2013329c-ef48-4850-8ada-912585e53fd5">

Thanks

**Comment by gregorydimitriadis** [comment]
@cneidle so is this right?

I:
* Y
* I-L-Y
* bent-I-L-Y

Horns:
* bent-Horns
* O/2-Horns

Such that, when collapsed, "I" and "Horns" would be showing just by themselves, and can be independently expanded and show the bulleted items below it in their respective groupings?

And second question: does this apply to both the gloss palette as well as the gesture palette?

**Comment by cneidle** [comment]
Hi Greg,

Yes, that’s good

> On Jul 17, 2024, at 2:17 PM, Greg Dimitriadis ***@***.***> wrote:
> 
> 
> @cneidle <https://github.com/cneidle> so is this right?
> 
> I:
> 
> Y
> I-L-Y
> bent-I-L-Y
> Horns:
> 
> bent-Horns
> O/2-Horns
> Such that, when collapsed, "I" and "Horns" would be showing just by themselves, and can be independently expanded and show the bulleted items below it in their respective groupings?
> 
> 

> And second question: does this apply to both the gloss palette as well as the gesture palette?
> 
> 

It applies to the “ASL Handshape” palette, which is available both when 
annotating signs and when annotating gestures.

**Comment by cneidle** [comment]
fixed
