### ISSUE TITLE
Up and Down buttons also not working

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#709]
Presumably related to the Arrow issue #500 ... but the Up and Down buttons at the bottom do not work 

<img width="212" alt="Screen Shot 2024-07-12 at 3 20 47 PM" src="https://github.com/user-attachments/assets/147681a3-16da-4003-b9fb-1b9232b1d2a9">

**Comment by gregorydimitriadis** [comment]
The Up/Dn buttons move the selected segment tier up or down in the list of segment tiers. The prev/next utterance buttons control the movement between utterances.

**Comment by cneidle** [comment]
oops!  sorry about that.  thanks
