### ISSUE TITLE
Part Issue #53, Part Issue #15

### ISSUE THREAD

**Issue by blazetravis** [DCS-LCSR/SignStream3#71]
I am now encountering a new bug which may be rooted in both a previously closed issue, as well as an existing not-close issue. ( #15 and #53 , respectively)

Steps to reproduce:
1. Enter into some already saved utterance of existing file (I used Cory 107, U76)
   ![screen shot 2016-01-21 at 11 58 27 am](https://cloud.githubusercontent.com/assets/13489587/12487729/715a3f62-c036-11e5-9f38-085c57da0154.png)
2. First, lengthen an existing 2-handed gloss with a one-handed final hold by one frame. (NOTE: I lengthened the entire locked gloss body, not the final hold on the left hand) See first display issue below:
   ![screen shot 2016-01-21 at 12 00 38 pm](https://cloud.githubusercontent.com/assets/13489587/12487776/a4460884-c036-11e5-8778-6a54444ae783.png)
3. Click into Morph-Phon to change handshapes
4. Clear old handshapes, and select ONE new handshape (NOTE: this gloss is a same start/end hs on both bands)
5. Enter out of Morph-Phon.
6. Get crazy output below.

![screen shot 2016-01-21 at 11 56 28 am](https://cloud.githubusercontent.com/assets/13489587/12487655/1295afa2-c036-11e5-9590-24cc0d135f38.png)

Here, it looks like the display issue we're having in issue #53 , as well as problems with interpreting/manipulating finals holds. Now, the top two main gloss bodies are aligned, but the third and fourth are way off. 

**Additionally, (this is the new bug) the original work that was only a one-handed final hold has been undone and converted into a two-handed final hold.**

None of the previous work with final holds should be undone unless the user manually does it himself.

**Comment by blazetravis** [comment]
Unfortunately this is a pretty serious issue as it limits the usability of the current UAT for Main Gloss checking for me. I would be happy to set up a Skype meeting to demonstrate this bug's reproducibility.

Thanks.

**Comment by gregorydimitriadis** [comment]
@blazetravis - I'm able to see the issue on my end too. That being the issue following step 6, so I will begin looking at that. But what is the display issue which occurs after step 2?

**Comment by gregorydimitriadis** [comment]
@blazetravis - Also, should the gloss as the beginning of your pictures be able to exist at all? How was the final hold added for one hand but not the other when the two hands are locked?

**Comment by blazetravis** [comment]
@gdimitriadis - The display issue is that the main gloss bodies are not uniform. They appear to be correctly extended for the gloss 1 and gloss 2, as well as the left hand, but the right hand has not been adjusted.

And yes, it should. Whenever you re-open SignStream, all glosses are by default locked. Someone had previously created that gloss by unlocking it. Later, when I reopened this utterance, I noticed that the body should have been one frame longer, so I attempted to extend it (in its locked-hands state) That's what led to the first issue. Re-doing the handshapes themselves led to the next few issues.

**Comment by gregorydimitriadis** [comment]
@blazetravis - Thanks, I believe I see now. The uniformity is indicated by the diamond-looking symbols. My guess is that after re-opening SignStream, the logic gets jumbled somehow. My question is: _should_ the application re-lock all glosses upon re-opening in the first place?

**Comment by blazetravis** [comment]
@gdimitriadis - I would say yes, both because that's how I've always used it and it makes intuitive sense to me. It makes editing a lot easier and mistakes less likely.

**Comment by gregorydimitriadis** [comment]
Fixed the final hold issues related to this ticket, but leaving the handshape image unresolved. That will be handled as part of bug #53

**Comment by blazetravis** [comment]
Excellent. While the handshape display issue persists, the final hold bugs are gone. Thanks for your extra work on this latest patch!
