### ISSUE TITLE
Video lookup: small request

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#710]

**Comment by cneidle** [comment]
Augustine has fixed the issue with the version number of the Sign Bank, and things are working now  !!

These are the different messages I see, depending on how many videos are associated with the file:

1) if there is only one:

(A) <img width="541" alt="Screen Shot 2024-07-13 at 5 26 31 PM" src="https://github.com/user-attachments/assets/c2a9bf46-319f-408e-aa3b-42ef2e23b1b1">


2) if there is more than one:

(B) <img width="475" alt="Screen Shot 2024-07-13 at 5 23 39 PM" src="https://github.com/user-attachments/assets/a805d553-a1e3-4fe1-b9b3-2a010ed66d79">


I think the messages should be consistent, in specifying that  "The video should be front facing and provide a maximally clear view of the signer's hands to ensure the best possible DAI search results."

I think it is weird to have that final sentence.

From within the Morph-Phon window, there is also the "Search Sign Bank" option, as well as the possibility of searching on the Web.  But I think it is confusing to say, "You can try searching the DAI... "   That seems appropriate, as you have it, when the search fails:


(C) <img width="546" alt="Screen Shot 2024-07-13 at 5 34 09 PM" src="https://github.com/user-attachments/assets/99942027-f61b-4232-a1d2-a27bd3224f2c">

SO, in that case where things fail, perhaps say:  You can try searching the Sign Bank using the "Search Sign Bank" button in the Morph-Phon window, or you can try other ways of searching the DAI from http://dai.cs.rutgers.edu/dai/s/signbank.

**Comment by cneidle** [comment]
So, to summarize the suggestions above, replace (A) above with:

> There is only one video loaded into SignStream. You will get best results when the video is front-facing and includes a clear view of the signer's hands.

replace (B) above with:

> Please select a video to use for the DAI search. You will get best results when the video is front-facing and includes a clear view of the signer's hands

replace (C) above with:

> DAI search failed: A user selection was not made in the allotted time.  Please try again.  If you did not find the sign you were looking for among the choices offered, you can try using the "Search Sign Bank" button in the Morph-Phon Window, or you can try other ways of searching the DAI from http://dai.cs.rutgers.edu/dai/s/signbank

**Comment by cneidle** [comment]
If the user selects "None" from the options provided, this is the message that remains visible:

<img width="935" alt="Screen Shot 2024-07-13 at 5 45 57 PM" src="https://github.com/user-attachments/assets/ff0c6bfd-83b0-4223-ad3a-41da3f83a518">

with no other error message appearing.  

That does not seem right.

It seems that there should be a message appropriate to the user having determined that the search in fact failed.

Something like:

> If you did not find the sign you were looking from among the choices offered, you can try using the "Search Sign Bank" button in the Morph-Phon Window, or you can try other ways of searching the DAI from http://dai.cs.rutgers.edu/dai/s/signbank


=========

FWIW, I found this in one of Augustine's old email msgs (6/14/23):  {
"status": 0,
"message": "Choice Made",
  "data" : {
  "session": "eb218594-4c29-46ca-aa09-1fa5bdb57a83",
  "type": "signbank",
  "schema_version": "1",
  "data_version": "18",
  "signText": "chosenSign"
  /**/ set "sign_text" to "null" without quotes if "None of those" is chosen by user.**
  }
}     
I

Augustine confirmed that this is the only case where that is returned.  So when that happens, the user should receive a message like the one I just suggested.   THANKS.

**Comment by cneidle** [comment]
Another very small change in wording:

<img width="658" alt="Screen Shot 2024-07-13 at 5 25 21 PM" src="https://github.com/user-attachments/assets/545ba30c-0eee-4611-9de0-2caa2a59d353">

Change the second line to:  

> "SignStream will now populate the **fields in the Morph-Phon Window** with the data associated with___ "

Explanation:  the term "gloss field" is not right.

thanks!

**Comment by gregorydimitriadis** [comment]
Regarding the selection of "None" what is currently returned from the DAI at the moment is:

{"status": 0,"message": "Choice Made","data" : {"session": "23F325B74C06A8E7A5E4A8E59095DA5C1721075858239.mp4","type": "signbank","schema_version": "1","data_version": "26","signText": "none"}}

Key part is "signText": "none"

So currently that aspect will not work. ~~That should be changed to "" to work with the current code.~~

However, sometimes when I test this, clicking None results in the DAI window closing in the browser, and no effect happening in SignStream, as the DAI keeps returning: "status": 1,"message": "Choice Made","data"

Edit 2024-07-16-7:23AM: My mistake, the signText should be -- "signText": null -- for it to work appropriately.

**Comment by cneidle** [comment]
With the version from July 16th:  The video lookup time out is not timing out.  The DAI window remains open, and functional (!) -- i.e., you can still select a sign and insert; although the time-out message does appear.

<img width="1759" alt="Screen Shot 2024-07-16 at 6 07 01 PM" src="https://github.com/user-attachments/assets/87d51697-8476-4173-b595-fb2a12d2b256">

**Comment by cneidle** [comment]
The wording changes for selection of video files are good.  But these are now the two possibilities, depending on how many videos are available in the SignStream file:

<img width="440" alt="Screen Shot 2024-07-16 at 6 26 12 PM" src="https://github.com/user-attachments/assets/2d0ff3bf-7307-4dac-95bd-e0c5e8e93b63">

----


<img width="1087" alt="Screen Shot 2024-07-16 at 6 26 55 PM" src="https://github.com/user-attachments/assets/7879b5bc-30fd-4719-a7e8-b1517476a20c">

Could you please resize the second one, so that it is like the first, and does not extend indefinitely to the right?  Thanks

----

The 'NONE' selection is still not working; we need to coordinate with Augustine.

**Comment by cneidle** [comment]
Everything is good here now -- EXCEPT for the last two items: the time out issue and the window resizing.
