### ISSUE TITLE
VIdeo Lookup:  Message when Compounds are Returned

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#712]
HI Greg, 

You had written to me by email (July 9, 12:33 pm):

> Regarding compounds, on looking at it I think we already accounted for it - the message/window to the user right now is:
> 
> 
> > Error - Compound Sign Returned
> > 
> > You selected the sign: <...signText...> It cannot be successfully entered directly into SignStream.
> > 
> > The DAI returned a compound as the result.
> > 
> > Solution: You will need to enter the gloss for each part individually and then combine them to form a compound in the utterance window. You may be able to find the compound parts separately in the Sign Bank (by clicking on Search Sign Bank) to facilitate data entry; however, if the sign exists in the Sign Bank only as part of a compound, the gloss will appear with an asterisk before or after the text of the gloss, and you will not be able to automatically enter the information from that sign. You will then need to enter the information manually.
> > 

That is just what is needed.  However, that is not what we actually get:

<img width="632" alt="Screen Shot 2024-07-13 at 7 03 44 PM" src="https://github.com/user-attachments/assets/f5d4b67a-695d-4d4c-93d2-e96ed223f0c3">

It would be great to replace the current message with the message you had proposed above.  (I edited your text above slightly.)

Thanks!

**Comment by gregorydimitriadis** [comment]
What collection was used and sign searched to get the compound back?

**Comment by gregorydimitriadis** [comment]
@cneidle What collection was used and sign searched to get the compound back?

**Comment by cneidle** [comment]
test-Jonathan_2012-11-28_sc90, appended here

U7 

Search sign DYE

Use cam1

Select option 3:  HAIR+DYE









DO you have the Jonathan sc90 videos or should I sent them also?

Thanks,
 Carol

**Comment by cneidle** [comment]
This has NOT been fixed in the latest version of July 16th

<img width="630" alt="Screen Shot 2024-07-16 at 5 56 26 PM" src="https://github.com/user-attachments/assets/115ce4c3-4c87-4fac-aecd-0f51ac11fa0b">

**Comment by cneidle** [comment]
Greg and I discussed this last night.  He will identify a compound as a gloss that includes a + in between two regions of text, and he will provide the message that we agreed to when such a gloss is returned:  

<img width="616" alt="Screen Shot 2024-07-17 at 3 56 14 PM" src="https://github.com/user-attachments/assets/7f597962-cda6-45d3-8063-d551fbd59cdb">



thanks

**Comment by cneidle** [comment]
This has been fixed now.   Thanks.
