### ISSUE TITLE
July 16, 2024 version:  SignStream Installation does not offer the user the option to install the Global Sign Bank

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#713]

**Comment by gregorydimitriadis** [comment]
@cneidle is this from a fresh installation (which would have no sign bank installed) or from a SignStream which has an existing sign bank file? If its fresh, it will not prompt the user to install automatically. If there's an existing sign bank file, but its older than the current version, then it should prompt the user to upgrade. I had tested the latter which to my knowledge is working.

**Comment by cneidle** [comment]
I’m talking about a fresh installation.

As I recall, the user was always prompted to install the Sign Bank before
SignStream launched for the first time.  No?

The user needed to type ‘yes’ in the terminal window.

**Comment by cneidle** [comment]
Oops - sorry

My memory is failing me.

From the 3.4.0 instructions:

Open a Finder window, and double-click on the SignStream folder (the folder you downloaded, which includes the application and related files). Do the following, in the order listed:

1) [Required] You will see a file called “DisableQuarantine.command”. Double-click on that. You may get a message asking if you want to open the file even though it is from an unidentified developer. If so, say YES. If you get a message that the file cannot be opened because it is from an unidentified developer:

a. Go into System Preferences > Security & Privacy > General

b. Under the section "Allow apps downloaded from" click "Open Anyway" for this file.
This will open in the Terminal application and run immediately, then close itself when finished.

2) [Optional] If you wish to download the ASLLRP Global Sign Bank, double-click on "GetSignBank.command". You will be asked whether you wish to download the Sign Bank and agree to abide by the terms of use. If you click ‘yes’, the download of the ASLLRP Sign Bank materials (and Sign Bank terms of use) will commence. Close the Terminal window.





Sorry about that!

**Comment by gregorydimitriadis** [comment]
Thanks, I'll close this
