### ISSUE TITLE
Need to test in Mac OS 14 and with ARM processors

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#714]
Note this had been reported previously for 3.4.1.  Is this still a problem?

o	On Macs with ARM processors: When the user clicks into an utterance for the first time from the database view, the zoom level will pan out to display the entire length of the video. After that, the zoom level will pan out to display just the length of the selected utterance.

**Comment by douglas-motto-at-rutgers** [comment]
Not able to reproduce.  Is this an existing collection file?  New collection?  Does it reoccur after reopening the file or recreating a new collection....or to make it happen do you have to shut down and reopen SS?

P.S.  There is a flicker when entering the utterance view.  This happens on intel and arm.  This specifically is not a zoom issue, but a window sizing issue.

**Comment by cneidle** [comment]
This was reported by someone other than me.  I have never had access to an ARM processor. 


>

**Comment by cneidle** [comment]
Where do things stand with respect to ARM testing?  Should the text in the README about this be modified accordingly ??   @douglas-motto-at-rutgers  @gregorydimitriadis 
thanks

**Comment by gregorydimitriadis** [comment]
We have tested on ARM in the last couple days, doing the usual sequence of events, and found no issues, so it appears to have no differences to running on older machines. We can probably remove that line from the README/docs.

**Comment by cneidle** [comment]
Great. Thanks. Sent from my iPhone; please excuse typos.On Jul 19, 2024, at 12:24 PM, Greg Dimitriadis ***@***.***> wrote:﻿
We have tested on ARM in the last couple days, doing the usual sequence of events, and found no issues, so it appears to have no differences to running on older machines. We can probably remove that line from the README/docs.

**Comment by cneidle** [comment]
@gregorydimitriadis   Should we removing that sentence in the Readme, other documentation, and web pages, based on the above ??

" - Note that SignStream® 3.5.0 has not yet been extensively tested with ARM hardware. There may be some differences in how the program works with this hardware. "

**Comment by gregorydimitriadis** [comment]
@cneidle Will do. Thought I had done it already, must have missed it.

**Comment by cneidle** [comment]
Thanks!

But this is still needed?
If you decide to use SignStream® 3.5.0 with the ARM processor: When you double-click on SignStream® for the first time--after following all installation instructions very carefully--you will be asked to install Rosetta (which emulates the Intel instruction set) if it is not already installed. You can then double-click on SignStream again to launch it. 
Just want to be sure.

Thanks,
 Carol
