### ISSUE TITLE
New Error with Handshape Entry in July 17th version

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#716]
I went to edit the handshapes for 

<img width="243" alt="Screen Shot 2024-07-17 at 6 27 10 PM" src="https://github.com/user-attachments/assets/e998913e-d9c4-461a-ab17-4aad00978026">

I tried to enter new handshapes (two of them), but got an odd and inappropriate error message

<img width="1011" alt="Screen Shot 2024-07-17 at 6 26 42 PM" src="https://github.com/user-attachments/assets/e4b1e6ba-9aa8-49b0-9671-2dae8815de49">

=====

<img width="323" alt="Screen Shot 2024-07-17 at 6 26 52 PM" src="https://github.com/user-attachments/assets/b1c1f8f9-2bca-4cdd-8e3f-2509ab91debc">

**Comment by cneidle** [comment]
Seems to be a consistent problem with finger spelled signs, but does not affect lexical signs.

<img width="1047" alt="Screen Shot 2024-07-17 at 6 36 12 PM" src="https://github.com/user-attachments/assets/9c20bb10-38e9-4c8b-81a7-51f41d9a18c8">

**Comment by cneidle** [comment]
Just to clarify:  Perhaps unsurprisingly, this is not linked to the sign type (fingerspelled vs. lexical). if you add letter handshapes to a lexical sign, then clear them, and then try to enter new handshapes, you get the same error message.  It is clearly something precipitated by the new way you are clearing the text line in the handshape palette.

**Comment by douglas-motto-at-rutgers** [comment]
Having difficulty reproducing.

I created a new gloss, 1 handed, same start/end, lexical.
I add A, B, and C handshapes. I Enter.  I Bypass Sign Bank Check.

I re-edit the gloss.  I click Select handshapes.  In palette window, I click "Clear".
I add N, and L handshapes. I Enter.  I Bypass Sign Bank Check.

No error.


I've tried with lexical vs fingerspelled.  Couldn't see the error either.  Is this gloss from a previous collection, or new.

**Comment by cneidle** [comment]
Has Greg changed something ??   It is not happening now...

**Comment by douglas-motto-at-rutgers** [comment]
The build last night added the fix to "clear" for letter handshapes.

**Comment by cneidle** [comment]
Yes - it is that "fix" that introduced this problem.  It is still happening with this file, which was originally created in a previous version of SignStream, but it was updated...

<img width="1187" alt="Screen Shot 2024-07-18 at 11 37 30 AM" src="https://github.com/user-attachments/assets/552b73eb-75c6-4a16-9171-7fb79efe9a90">

I will attach the file to email.

**Comment by cneidle** [comment]
Here is a file that is still reporting errors after “clear handshapes” for letters





I believe you have the videos for this already, but I can resend if you need.

Thanks, Carol

**Comment by douglas-motto-at-rutgers** [comment]
I can see the reproduce the issue in that file.

**Comment by douglas-motto-at-rutgers** [comment]
it's reproducible...even in new glosses.

create 1 handed gloss.  set as lexical. set differtent start/end handshapes.  add three different handshaps.  enter/save.

reedit gloss.  Switch to fingerspell...try to add a handshape.

**Comment by douglas-motto-at-rutgers** [comment]
greg found logic error...fixing now.  old data file is not corrupt.  This would not cause any new data corruption.

**Comment by cneidle** [comment]
great!

**Comment by cneidle** [comment]
fixed
