### ISSUE TITLE
Time-out

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#717]
I am starting a new ticket to continue discussion of this issue.

Doug wrote:

> Regarding the timeout...
> 
> https://github.com/DCS-LCSR/SignStream3/issues/710#issuecomment-2231911771
> 
> I re-read and re-tested.  
> 
> Once SignStream pops up the timeout box. No selections will be accepted on SignStreams end after the timeout.  Even if the user selects something in the browser after the timeout.  That is stated in the  pop up.
> 
> Your request of closing the window in the browser at the same time as SignStream timeout would take a non-trivial amount of work on both Augustine's and Greg's end.
> 
> Once we open the browser window on the user's machine, we have no direct control over it.
> 
> 
> The following is one way to do this indirectly that is the most in-sync (they close at the same time)...
> 
> When the timeout occurs on SignStream, we would have to send a request to the server cancelling the request.
> 
> The browser's web page would need to poll the server to see if the timeout occurs.  If so, then close or display a message, etc.

A few  comments:

As things stand, it is very confusing/misleading.

1) Current behavior - the DAI Search Timed Out window opens BEHIND the sign selection window, and is potentially completely obscured.

And if, after that, a selection is made, although this new information does not get inserted into the Morph-Phon window, a misleading message replaces the sign selection options:

<img width="966" alt="Screen Shot 2024-07-18 at 10 00 42 AM" src="https://github.com/user-attachments/assets/ed56c150-f417-4dc7-aecd-5b90d0d1af56">

2) I will discuss with Augustine whether it would be possible to have the time-out on the DAI side, coordinated with the time-out time on the SignStream side, result in an appropriate message replacing the sign selection options at that point.

3) If no other solution is found, to avoid this confusion, it would be preferable, at least: (1) if possible, to have that time-out window appear as the front-most window, AND (2) to modify the message provided by SignStream as follows:

> DAI Search Failed: A user selection was not made in the allotted time. 
> **PLEASE CLOSE THE SIGN SELECTION WINDOW.**
> You can start again. 
> 
> If you did not find the sign you were looking for among the choices offered, you can try using the "Search Sign Bank" button in the Morph-Phon Window, or you can try other ways of searching the DAI manually.  DAI Search: https://dai.cs.rutgers.edu/dai/s/signbank

The one thing that should NOT appear in that window is a message saying that the selected sign has been saved, when it has NOT been saved.

**Comment by douglas-motto-at-rutgers** [comment]
Anything in the browser is supplied by the DAI server.  Including the message in the browser after the selection.  Augustine would have to make any such changes.

The message change in SS, Greg can make.

The browser and SignStream are separate applications, once the browser opens it has the operating's system focus.  It's unclear if SignStream can re-obtain focus without a user's action.  We would have to look into that.

**Comment by gregorydimitriadis** [comment]
@cneidle I tried a couple things, but didn't have any luck with bringing the message window ahead of other applications (the browser). I believe it's not possible.

**Comment by cneidle** [comment]
I am going to meet with Augustine later tonight, around 9 pm, to work out a time-out on the DAI side, just a few seconds short of SignStream's 300 second time-out, after which the user will be taken to a page with an appropriate message, something like "The search has timed out without a selection being made; please close this window."  For testing purposes, the time-out will be shorter than that, so you may not want to test the video lookup later tonight.  I'll report back when we have a solution (hopefully).

**Comment by cneidle** [comment]
UPDATE:  Augustine will have the Sign options window time out 5 seconds before the SIgnStream time-out message is due to appear.  The window will be replaced by this message:  

> <img width="851" alt="Screen Shot 2024-07-18 at 10 05 05 PM" src="https://github.com/user-attachments/assets/6efa6d11-91aa-4a33-a4e9-bd9e53d09225">

There is something else that needs to be fixed on the DAI side for the connection with SignStream, which will be done before SignStream is released; but it will not have any impact on anything else on the SignStream side, and the current time-out message is fine.

**Comment by cneidle** [comment]
fixed
