### ISSUE TITLE
Specific zoom and scroll bar issue

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#72]
1) Open specifically Jonathan 90 (have not seen this issue in any other file), enter annotator information: 
![screen shot 2016-02-09 at 10 46 23 am](https://cloud.githubusercontent.com/assets/15836242/12921369/fff86eb8-cf1a-11e5-855c-649bb61c415e.png)

2) Attempt to zoom in with zoom bar (smallest amount of zoom in possible): 
![screen shot 2016-02-09 at 10 47 47 am](https://cloud.githubusercontent.com/assets/15836242/12921374/0256266e-cf1b-11e5-8fa1-72862793d803.png)

3) No scroll bar appears, try to zoom in more to access utterances: 
![screen shot 2016-02-09 at 10 48 23 am](https://cloud.githubusercontent.com/assets/15836242/12921384/11c8d056-cf1b-11e5-94cb-3d44f3dd5ba4.png)

4) Zoom in to max, utterances 1, 2, and 3 are visible and clickable, but still no scroll bar, so cannot access other utterances (40 utterances total): 
![screen shot 2016-02-09 at 10 49 04 am](https://cloud.githubusercontent.com/assets/15836242/12921402/2ad32efc-cf1b-11e5-84d3-84f21e3206ed.png)

**Comment by gregorydimitriadis** [comment]
Chelsea,

I believe I've seen this sort of bug before - it usually has to do with the format of the video being used.

Can I ask you to please check the names of the video files used for this collection, along with the directories they're in? I saw in the big collection of movie samples that there are varying version of these videos: "2012-11-27_JM1_0090..."  The first thing I would try is to try to switch out the videos for those of a different version, and see if that fixes the zooming.

And if that does not work, please send me the collection file (the original, before editing the videos in it) so I can take a closer look.

Thanks,
Greg

**Comment by hammondcl** [comment]
Me and Blaze just tried this fix with using different video files and it is resolved!

**Comment by gregorydimitriadis** [comment]
Excellent! Glad to hear it. I'll mark this as complete and close it.
