### ISSUE TITLE
Revising the README

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#721]
1. Please see "Improvements in version 3.5.0 relative to 3.4.1" at the top of #715 for suggested revisions to your: 

> Issues which have been fixed or newly implemented include:
> 
> * This release now works with MacOS 14.
> * There is an entirely new data type known as Gestures. These can be optionally edited in a separate view, and functions similarly to glosses, with some notable differences:
>   * In addition to handshapes, gestures also contain orientation data for fingertip and palm information.
>   * Gestures have optional Properties which can be added on, which provide more semantic information.
>   * etc
> * Integrated video lookup to DAI corpus
>   * This functionality can be used from the Morph-Phon window for glosses. For a predefined start and end of a gloss
> * Utterance View panels for Nonmanual, Gloss and Gesture views can be dynamically resized. The resizing will be persisted through opening and closing your collection.
> * Gloss translation field bugs have been resolved. In addition, translation fields now only display within the time bounds of the utterance to which it is associated.
> * Handshape palette view (for both Glosses and Gestures) has been altered slightly in appearance.

Please look at the items in #715 - there are a couple of questions.  Also, please let me know if you have information about the status of items that I am unsure of.  

I think it would be helpful to organize the KNOWN ISSUES section of the README better, and I will be able to offer suggestions about that, but first we need to establish which issues are still issues. 

Thanks in advance for sharing your sense of which issues still need to be included, and which seem to have been resolved and can be eliminated (or included in the section of issues that have been fixed).  

Please also suggest revised wording for the ARM-related items in the README.

I will need to produce documentation as well as updating the various webpages involved in the SignStream release, so it would be helpful to get your input on this.  Thanks.   @gregorydimitriadis

**Comment by cneidle** [comment]
Please also see suggestions in #715 for FEATURES TO BE IMPLEMENTED, which is minimal in the current README.

**Comment by cneidle** [comment]
QUESTIONS ABOUT THE README from July 30:

@gregorydimitriadis 

1)   - Note that SignStream® 3.5.0 has not yet been extensively tested with the new ARM hardware.

I raised this issue previously.  ARM hardware can no longer be said to be *new*.  I thought we were considering removing that warning, as Greg said he would do some testing.  What do you think?  Minimally, the term "new" should be deleted, I think.

2) There are some typos.   previoius, isntead (bottom of RELEASE NOTES)
Please run spellcheck on the text if you modify it further.

**Comment by cneidle** [comment]
I would suggest organizing the list of known issues, in the way I did in #715.  It is very hard to read through a random list of random issues.  Also, I would suggest including Github links only when absolutely necessary.  We really don't want to send the general public to these pages.  Although they are public, they have not been designed for public consumption.

I will update that section of the documentation and share it with you, with a view toward your consideration with respect to possibly replicating more or less the organization I have.  You have also not implemented the changes you suggested in your recent email to me about what should and should not be included.  More coming about this...

**Comment by cneidle** [comment]
My suggestion for the section on Known Issues in the Readme (please let me know if you think any of these should be deleted because they are no longer issues!).  

**Other known issues** 
-------

**•	Installation**
1.	Issues can arise when any directory on the path to your SignStream installation contains a quote character ( ' ) or a double quote character ( " ), so remove these characters from your directory names to avoid any problems. 
-------


**•	Macro-Unit Settings**

2.	There is an inconsistency in how edits or additions to the local participant list are treated.
-------
•	**Database and Utterance Windows**

3. In the Utterance View, the up/down arrow keys may not correctly move to the previous/next utterance in the left-hand index. Work-around: To activate the arrow key functionality in the left-most utterance index area, click once within the utterance display on the right.
4. The Utterance Index on the left side of the Utterance View is inconsistent in its text highlighting, sometimes black text on blue background and sometimes white text on blue background.
5. In the Utterance View, editing a nonmanual field value by double-clicking on it to open the field value selection list and selecting a value will result in the Utterance Index on the left incorrectly highlighting only the selected utterance (in blue), while not highlighting the visible utterances (in gray). 
6. Display glitch in the Utterance Window when entering gloss labels for more than one sign prior to setting the start and end points.  Setting the start and end points of one of those items may cause the other to be displayed in such a way that the text for both is overlapping.  Workaround: Align the text of the first gloss label before entering the next one. 
7. If you hide the Utterance Window (how you do this depends on your Mac OS, e.g., by clicking on the title bar, in older OSs, or by clicking on the red button at the upper left of the window), the hidden window is not recoverable.  You will need to Quit SignStream and reopen the utterance.  Although you will not have access to Save File through the menus (because the Utterance Window is hidden), when you quit the program, you will be given the option to save the file.  Be sure to save if you want to.  Workaround: Don’t hide the Utterance Window. 
8. Note that closing the Utterance Window will quit the program. That also means that during a search, closing the window displaying an utterance from the search results will quit the program, with no option to open a new search result. Closing the main SignStream window at any point will also quit the program.
9. In the Utterance View, when the green slider is near to the end of the video, some visual glitches may occur while the zoom level slider is being actively dragged. After the slider is released, the zoom level will be set correctly.
10. The icons for zoom locking/unlocking may be duplicated momentarily upon opening a new collection.
11. The green bar location is remembered when opening or creating a collection. When switching collections, the video will start at time zero, but the green line will remain in the middle where it was for a previously opened collection.  The position of the green bar is also remembered when a video file is replaced within a SignStream collection and re-displayed.

-------

**•	Having more than 1 Temporal Partition and/or Segment Tier visible in the Utterance Window**

12. Utterance highlighting is not consistent when multiple segment tiers are showing in Utterance View.
13. Adding multiple segment tiers to the Utterance View at once, or switching between temporal partitions from the dropdowns, could cause minor display issues in the dropdowns.
-------

**•	Morph-Phon and Sign Bank Windows**

14. Morph-Phon settings for a gloss can visually linger on the dialog window when opening up the Morph-Phon dialog again for a different gloss.
15. Morph-Phon Window "Enter" button behavior is not consistent in when it is enabled or disabled (requiring use of the Bypass Sign Bank button to enter data). 
16. The Local Sign Bank does not ignore the + sign that can occur at the end of a gloss label to indicate reduplication. In the Global Sign Bank, GLOSS and GLOSS+ and GLOSS++ are grouped under a single entry: GLOSS.  In the Local Sign Bank, if you have GLOSS+ at the time you save to local Sign Bank, it will be entered as GLOSS+.  So, you may have both GLOSS and GLOSS+ in the local Sign Bank, although that will never occur in the Global Sign Bank.  Workaround:  Since it is currently impossible to delete an entry from the Local Sign Bank, you should be careful not to include the + in the Morph-Phon window at the time you choose to enter a new sign into the Local Sign Bank.  In any case, after you enter the information from the Sign Bank, you will want to adjust the gloss label to include +’s as needed, to reflect the repetitions that happen at the end of that occurrence of the sign. 
17. Currently, when you “insert all data” from the Sign Bank:
a)	Only the start and end handshapes of the sign will be inserted into the Morph-Phon window. In case there are additional handshapes, e.g., for a loan sign, you will need to add them manually.
b) 	There may be errors in the insertion of information about sign properties when entered automatically from the Sign Bank (especially in regard to sign type for name signs that have a prefix before the ns- marking, e.g., “(M)ns-text” or “(2h)ns-text)”). Please be sure to verify that all information about sign properties displayed in the Morph-Phon window is correct before entering that information into the Utterance Window. 
-------

**•	Searching**

18.	In versions 3.4.0, 3.4.1, and 3.5.0, it is no longer possible to change the search domain, and thus no longer possible to carry out the same search on more than one SignStream collection. 
-------

**•	Other**

19. For some reason, launching SignStream® causes the Terminal window to be activated.  You should be aware of this, although it should not cause any issues.

**Comment by cneidle** [comment]
Is (9) above still an issue?

Delete (13) above?

**Comment by gregorydimitriadis** [comment]
Taking those out
