### ISSUE TITLE
Testing latest pre-release candidate from August 9

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#724]
I did a video search within SignStream, but I closed the DAI selection window without making a selection.
I could not do anything else.  I could not click anywhere else successfully, and the program crashed.

<img width="347" alt="Screen Shot 2024-08-10 at 11 43 09 AM" src="https://github.com/user-attachments/assets/d82b2bce-d2b2-4b5e-95f1-455439c36535">

Attaching the SignStreamOut file here:

[SignStreamOut.txt](https://github.com/user-attachments/files/16570117/SignStreamOut.txt)

**Comment by cneidle** [comment]
This is reproducible.  The Cancel button ought to be able to work in this situation...

<img width="957" alt="Screen Shot 2024-08-10 at 11 47 03 AM" src="https://github.com/user-attachments/assets/b8fb7b72-77c6-42cf-84dc-7442d22deebf">

=====


<img width="850" alt="Screen Shot 2024-08-10 at 11 48 13 AM" src="https://github.com/user-attachments/assets/60eb687d-2952-42e1-9c2e-29ac0c1fa3c1">

**Comment by cneidle** [comment]
Note that if I leave the totally inactive and unresponsive windows open for the full 300 seconds, it does eventually time out and I can proceed normally.  But the user does not know to do this, and should not have to...  There is not even any way to Quit SignStream (other than Force Quitting).

**Comment by cneidle** [comment]
I have been discussing with with Augustine @kwasiopoku , and he has modified the screen that is displayed for the SignStream search results to look like what is shown below.

However, so far as he knows, there is no way to actually prevent the user from manually closing the window, and no way that the DAI can know that the user has closed the window (as as to send SignStream the information that no selection was made).  

SO - it would certainly make sense to enable the "Cancel" button in the Morph-phon window to cancel activities on the SignStream side related to the video search and to close the Morph-phon window without making any changes -- to avoid the situation where the user gets stuck without being able to do anything if they do not follow the instructions and do close that window.  

Happy to discuss if you have some other idea/suggestion for dealing with this issue.  Thanks.

![image](https://github.com/user-attachments/assets/af9a9969-a2e7-47b6-838f-79e2e149644c)

**Comment by cneidle** [comment]
We have updated the SignStream Sign Bank.  Everything works fine.

But in the course of testing, I generated an error message.  The text of this message should be corrected
to avoid the duplicated sentence on top:

<img width="465" alt="Screen Shot 2024-08-11 at 4 02 48 PM" src="https://github.com/user-attachments/assets/85cc3ef3-fd08-4c99-a934-d0a2c5bfba6e">

Not critical, but while you're editing this, you could make the capitalization of "Sign Bank" consistent (with capital S and B).

Thanks very much.

**Comment by gregorydimitriadis** [comment]
@cneidle  Hi Carol, what version of macos was used with the DAI selection window issue?

**Comment by cneidle** [comment]
11.7.10

**Comment by gregorydimitriadis** [comment]
@cneidle is it possible to also try on the macos14.* machine?

**Comment by cneidle** [comment]
Same problem in 12.7.6

**Comment by gregorydimitriadis** [comment]
@cneidle Can I ask you try it again after restarting the machine? It's interesting because I had this issue on Thursday as well, Doug could not reproduce it (and still can't), but after I restarted my machine I was unable to reproduce it, so I thought maybe it was just something local to me that was causing it. So if you're seeing it, it could either indicate its something code-wise that I missed, or some state on our machines, and I'd like to eliminate the latter theory.

**Comment by cneidle** [comment]
@gregorydimitriadis   Same problem occurs consistently on all my Macs, also in 14.6.1 (see below).

Restarting these machines makes no difference.

<img width="1998" alt="Screenshot 2024-08-12 at 10 48 41 AM" src="https://github.com/user-attachments/assets/ff397f6f-367a-4dfd-a447-0e200147a696">

**Comment by gregorydimitriadis** [comment]
@cneidle Resolved. Will be making a new build to send to you in a few minutes.

**Comment by cneidle** [comment]
Excellent.  Thanks!
