### ISSUE TITLE
Serious problem!   installing SS 3.5.0 on Sonoma - does not work!

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#725]
Carey is running Sonoma. 14.6.1

He tried to install 3.5.0 - I did a screen share - he ran disable quarantine, and then getsignbank, and then the program seemed to be opening - it shows up in the dock, but then it disappeared.

[SignStreamOut.txt](https://github.com/user-attachments/files/17603067/SignStreamOut.txt)

**Comment by cneidle** [comment]
He will run 3.5.0 on his old laptop, running High Sierra, until we can resolve this.  But we need for him to be doing annotations!  And this is only a stopgap... Hopefully you can help to resolve this ASAP.  Thanks in advance.

**Comment by gregorydimitriadis** [comment]
@cneidle That is the same version I had/have on my machine: 14.6.1. I was able to download and open/run  3.5.0 just now. In addition to the steps you mentioned, I also had to (always have to) go into the System Settings > Privacy and scroll down to Security and allow the DisableQuarantine script to run. Also under Security is allowing "App Store and identified developers" has to be checked. Double check these things occurred for the attempt. I have a follow-up idea as well, but hoping this works first.

**Comment by cneidle** [comment]
We already did those things.   I am pretty sure we had allowed « App Store and identified developers ».  Carey can you try one more time ??Thanks   CarolOn Nov 4, 2024, at 10:22 AM, Greg Dimitriadis ***@***.***> wrote:﻿
@cneidle That is the same version I had/have on my machine: 14.6.1. I was able to download and open/run  3.5.0 just now. In addition to the steps you mentioned, I also had to (always have to) go into the System Settings > Privacy and scroll down to Security and allow the DisableQuarantine script to run. Also under Security is allowing "App Store and identified developers" has to be checked. Double check these things occurred for the attempt. I have a follow-up idea as well, but hoping this works first.

**Comment by cneidle** [comment]
Carey just reported that 3.5.0 is now working !Thanks,  CarolOn Nov 4, 2024, at 10:27 AM, Carol Neidle ***@***.***> wrote:﻿We already did those things.   I am pretty sure we had allowed « App Store and identified developers ».  Carey can you try one more time ??Thanks   CarolOn Nov 4, 2024, at 10:22 AM, Greg Dimitriadis ***@***.***> wrote:﻿
@cneidle That is the same version I had/have on my machine: 14.6.1. I was able to download and open/run  3.5.0 just now. In addition to the steps you mentioned, I also had to (always have to) go into the System Settings > Privacy and scroll down to Security and allow the DisableQuarantine script to run. Also under Security is allowing "App Store and identified developers" has to be checked. Double check these things occurred for the attempt. I have a follow-up idea as well, but hoping this works first.
