### ISSUE TITLE
Low Priority Frame Jump Issue

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#73]
We noticed this frame jumping issue in Rachel 43, U36. It seems to be isolated as we haven't found it elsewhere and it is low priority because it does not affect data, but we wanted to maintain a record of it in case something similar should come up somewhere else. 

1) Open Rachel 43, U36

2) When framing through with arrow keys on keyboard, SignStream screen, or video screens, when you get to time code 3:52;02 and press the frame forward key again, it snaps back to time code 3:51;26. The video files themselves end at 3:52;02, but rather than continuing to move forward, the screen snaps back to a previous time code. 

![screen shot 2016-03-01 at 10 23 18 am](https://cloud.githubusercontent.com/assets/15836242/13431610/1d6c2da8-df98-11e5-802d-d205ec24641b.png)

![screen shot 2016-03-01 at 10 23 37 am](https://cloud.githubusercontent.com/assets/15836242/13431553/e7060860-df97-11e5-9e7e-33136e02ab64.png)

**Comment by hammondcl** [comment]
The frame jump issue is resolved, but now U36 is only visible from the most zoomed out position, where the labels are not visible: 

![screen shot 2017-02-15 at 11 36 26 am](https://cloud.githubusercontent.com/assets/15836242/22984335/0eca19f0-f373-11e6-8d0d-1e94cf3b012b.png)

Zooming in either cuts off U36 partially: 

![screen shot 2017-02-15 at 11 34 24 am](https://cloud.githubusercontent.com/assets/15836242/22984369/238d1630-f373-11e6-9bc7-43b3aa66e18a.png)


Or completely: 

![screen shot 2017-02-15 at 11 34 45 am](https://cloud.githubusercontent.com/assets/15836242/22984377/2a96abbc-f373-11e6-812c-d41cd3a7faaa.png)


The utterance is accessible by entering U35 and using the "Next Utterance" button.

**Comment by gregorydimitriadis** [comment]
@hammondcl Hi Chelsea - would you mind making a separate bug for the zooming issue? I'll mark this one as closed for the looping frame at the end of the video. Thanks!
