### ISSUE TITLE
Display issues when using Next Utterance and Previous Utterance buttons

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#74]
We noticed a display issue specifically for the file Rachel 66. This is a low priority bug as well because there are work-arounds, but it is worth noting.

1) Open Rachel 66, U51. For some reason, SignStream only seems to bug out around this specific utterance in this specific file.
![screen shot 2016-03-01 at 10 35 12 am](https://cloud.githubusercontent.com/assets/15836242/13432093/23c41d12-df9a-11e5-9faa-82b86a2666a2.png)

2) Click "Next Utterance" button in bottom right of SignStream pane, see this strange display issue:
![screen shot 2016-03-01 at 10 35 26 am](https://cloud.githubusercontent.com/assets/15836242/13432114/3d514778-df9a-11e5-90f7-362ee5819567.png)

3) Click "Next Utterance" again, get a condensed version of that similar issue:
![screen shot 2016-03-01 at 10 35 39 am](https://cloud.githubusercontent.com/assets/15836242/13432140/6ded95da-df9a-11e5-8822-a4ae3eafe57e.png)

4) Go back to macro unit screen, reopen U51 (everything looks fine again):
![screen shot 2016-03-01 at 10 35 12 am](https://cloud.githubusercontent.com/assets/15836242/13432166/8347b488-df9a-11e5-953e-4ce60dbf9e32.png)

5) Click "Previous Utterance" button, get this: 
![screen shot 2016-03-01 at 10 37 31 am](https://cloud.githubusercontent.com/assets/15836242/13432188/9558e3b8-df9a-11e5-9e4e-a9de9fec4704.png)

6) Click "previous" again to get this:
![screen shot 2016-03-01 at 10 37 59 am](https://cloud.githubusercontent.com/assets/15836242/13432197/a187e4f4-df9a-11e5-9238-bf605f184a81.png)

7) Click one more time to get this:
![screen shot 2016-03-01 at 10 46 40 am](https://cloud.githubusercontent.com/assets/15836242/13432290/e967cdf2-df9a-11e5-8b58-f7485871fe6b.png)

At this point, neither the next or previous utterance buttons work. But, again, when you click back out to the macro unit, everything becomes fine again.

**Comment by gregorydimitriadis** [comment]
Due to the fact that within the next 1 or 2 sprint cycles the next/prev buttons will be obsolete, I am moving this bug to the Low Priority Pool.

Going forward, we will be able to sidescroll through the entire video in the utterance window, making the ability to go to the next/prev utterances unnecessary.

**Comment by hammondcl** [comment]
Terrific, thank you for updating me!

**Comment by gregorydimitriadis** [comment]
Chelsea,

With the newest version, most likely all issues with next/previous buttons have either been resolved or become moot. Just give it a test and let me know if I can close this one.

Thanks!
Greg

**Comment by gregorydimitriadis** [comment]
@cneidle Would I be able to close this bug since the current implementation of the next/prev buttons appear to be working fine?

**Comment by cneidle** [comment]
Hi Greg,

Do as you think best :-)

Chelsea won’t be working much until the end of July.
If she notices any further problems with this, she can
let you know.

thanks!

  cheers,
    Carol

**Comment by gregorydimitriadis** [comment]
Thanks Carol. Closing this one out for now.
