### ISSUE TITLE
Missing Nonmanual Information with newest update

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#75]
Labels on some nonmanuals are no longer showing up when an utterance is opened

1) Open Rachel 43

2) Open U4 (chosen because it is missing many labels)

3) Get this:
![screen shot 2016-03-18 at 4 55 57 pm](https://cloud.githubusercontent.com/assets/15836242/13891966/c1b628f6-ed2a-11e5-8c72-81d6117afb3c.png)

4) Double click line to relabel, only one option appears (the same label that is already present in the same line)
![screen shot 2016-03-18 at 5 00 05 pm](https://cloud.githubusercontent.com/assets/15836242/13891998/ee7873a8-ed2a-11e5-8074-7adbf942c96e.png)

**Comment by gregorydimitriadis** [comment]
Thanks Chelsea. Does this bug occur for any label other than 'body lean'? Or similarly, is it just this utterance which has the issue, or multiple?

**Comment by hammondcl** [comment]
Looking only at Rachel 43, all utterances that have coding for eyebrows, hm:jut, body lean, and shoulders are missing the labels for these bars. So far, it seems like only Rachel 43 and only those fields are affected.

In "eyebrows", the only data that seems to stay is if it is labeled "raised-furrowed", which is found in utterances 6 and 7
![screen shot 2016-03-22 at 9 22 42 am](https://cloud.githubusercontent.com/assets/15836242/13952931/a936193e-f00f-11e5-84a1-e4f2b323877f.png)

Utterances 19 and 24 are the only ones with coding for shoulders, but that too is missing. 
![screen shot 2016-03-22 at 9 21 42 am](https://cloud.githubusercontent.com/assets/15836242/13952909/852ff03c-f00f-11e5-8494-6af559171463.png)

It appears that "-for" in hm: jut stays (U, U9, U12, U22, U27, U30, U35)
![screen shot 2016-03-22 at 9 21 05 am](https://cloud.githubusercontent.com/assets/15836242/13952890/7052493a-f00f-11e5-8fe3-d765b8d3f51c.png)

**Comment by hammondcl** [comment]
I accidentally clicked "close", sorry!

**Comment by hammondcl** [comment]
At Carol's suggestion, I am emailing you the file of Rachel 43 so you can see it for yourself.

**Comment by hammondcl** [comment]
I was trying to see if there was a work-around and tried hiding the field, then went to show it again and realized that the option to add "eyebrows" as a field is no longer there, neither is body lean, shoulders, or hm: jut. These fields still exist in other files. 

![screen shot 2016-03-22 at 10 09 36 am](https://cloud.githubusercontent.com/assets/15836242/13954268/734cf7dc-f016-11e5-9570-72cdc506e511.png)

**Comment by hammondcl** [comment]
In another file, Rachel 50, the "topic/focus" field also maintains the lines but not the labels. I am not sure if this is due to a global change made or if it is related. I think it is related because once more, when you open the "Fields" menu, there is no longer an option to add a field for "topic/focus"

1) Open Rachel 50 (looks normal), then U1and get this (missing label over "topic/focus" line):
![screen shot 2016-03-23 at 11 52 33 am](https://cloud.githubusercontent.com/assets/15836242/13991346/2559fab0-f0ee-11e5-83c5-837abe9c9f7a.png)

2) Can now only label the line as "topic":
![screen shot 2016-03-23 at 12 00 47 pm](https://cloud.githubusercontent.com/assets/15836242/13991526/ec8dcf4e-f0ee-11e5-8f92-56f079e55257.png)

3) Open fields menu and see this (no longer a "topic/focus" field option):
![screen shot 2016-03-23 at 11 54 11 am](https://cloud.githubusercontent.com/assets/15836242/13991367/3aaa1c9c-f0ee-11e5-9c19-494e45881f7d.png)

This is the case in all utterances that have topic/focus information in this file. (All utterances **except** for U10, 12, 13, 15-19, and 23).

**Comment by gregorydimitriadis** [comment]
Thanks very much Chelsea; this is all very helpful. This seems like a larger and more disruptive issue than I anticipated at first, and I'll be looking deeper into this shortly.

**Comment by gregorydimitriadis** [comment]
After spending some time on this bug, I have discovered the cause. And luckily it was relatively simple, so I'll be able to group this into the rollout of Sprint 10 early next week.

**Comment by hammondcl** [comment]
Sounds great, thank you!

**Comment by blazetravis** [comment]
This looks to be all fixed. It looks like some of the grammatical topic information is simply lost, however. But now it looks like we can fix it and have the information stick. Thanks!
