### ISSUE TITLE
Problem With Non-Dominant One Handed Signs

### ISSUE THREAD

**Issue by blazetravis** [DCS-LCSR/SignStream3#76]
Today I encountered another bug regarding the Morph-Phon window and gloss information. Sometimes, a signer will sign something specifically with their non-dominant hand only. In this case, I create a gloss only in the left hand in the "gloss 2 row." When doing so, I encountered this bug.

Reproduce by:
1. Create a new gloss in the gloss 2 row.
![screen shot 2016-03-24 at 10 30 26 am](https://cloud.githubusercontent.com/assets/13489587/14020101/f0d0bfae-f1ab-11e5-9081-20b19c37c15e.png)
2. Set the gloss and shift click into the morph-phon window.
3. Change gloss information to lexical one-handed, with marked number of hands.
4. Select handshapes if you'd like, but the result is the same.
![screen shot 2016-03-24 at 10 30 50 am](https://cloud.githubusercontent.com/assets/13489587/14020106/fa143fd2-f1ab-11e5-9e78-9cf04eab06c4.png)
5. Enter out of the morph-phon window.
![screen shot 2016-03-24 at 10 31 04 am](https://cloud.githubusercontent.com/assets/13489587/14020118/0751833a-f1ac-11e5-83ec-acc746458d3c.png)
6. Try to set the length of the new gloss and potentially receive an overlap warning even though the gloss visually looks problem free.
![screen shot 2016-03-24 at 10 31 20 am](https://cloud.githubusercontent.com/assets/13489587/14020124/0b1a1ba8-f1ac-11e5-829f-725f840521f5.png)
7. Shift click back into the morph-phon window and see that SignStream has automatically changed the gloss information back to the default 2-handed, as well as unchecked the marked number of hands box (and if you chose handshapeS, it also populates the second hand as well)
![screen shot 2016-03-24 at 10 33 24 am](https://cloud.githubusercontent.com/assets/13489587/14020127/0e87cfc4-f1ac-11e5-9601-e74e2b0e5c41.png)

**Comment by gregorydimitriadis** [comment]
I'm able to reproduce this as well, but only sporadically. It seems the mis-populating of the MorphPhon screen only occurs for me when I move the end frame of the non-dom gloss to the start frame of another gloss. Is that the case you're seeing as well, or is it always (no matter which frame you move to) ?

**Comment by blazetravis** [comment]
Always on my end.

I found a case where you can reproduce it 100% of the time. Create a two
handed gloss that is a few frames long. Then unlock the hand alignment.
Create a final hold for the dominant hand that is several frames long. Then
create another one handed floss for the non dominant hand underneath the
final hold of the previous gloss. This procedure works for me every time.

**Comment by blazetravis** [comment]
This bug is fixed!
