### ISSUE TITLE
Search Functionality Phase 1

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#77]
Search items to accomplish under this ticket:

-Menubar option for beginning a new search
-Plain search panel opening
-Displaying panel structure, including results box with one dummy result
-Demonstrate switching the domain from withint the search panel
-Demonstrate saving the state of the user's current view when a search result is clicked
-Demonstrate toggling between saved state and search state
-Executing a predefined search query on live collection data

**Comment by blazetravis** [comment]
This is a very impressive feature. However, I found that if you attempt to search for something before you enter into the utterance view, SignStream freaks out a little. It will either display a totally blank, grey screen:
![screen shot 2016-06-08 at 11 51 39 am](https://cloud.githubusercontent.com/assets/13489587/15900974/6546f0de-2d6f-11e6-9878-f3c155e915d8.png)

Or, it will display a very zoomed out utterance view with multiple utterances being displayed and highlighted:
![screen shot 2016-06-08 at 11 50 21 am](https://cloud.githubusercontent.com/assets/13489587/15900942/4aacc1c2-2d6f-11e6-86be-7ca8b6d10d8d.png)

**Comment by gregorydimitriadis** [comment]
Thanks Blaze. Going forward I should be able to resolve these display issues along with expanding the search functionality itself.

**Comment by blazetravis** [comment]
Hello again. Today Carol, Chelsea and I got together to further test this feature. We encountered some more issues when switching between search domains and different levels.

Steps to reproduce:
1. Open UAT
2. Click New Search
3. Change Search Domain and select a file.
4. Get abnormal macro view of the file selected (does not show utterances)
   ![screen shot 2016-06-09 at 12 28 59 pm](https://cloud.githubusercontent.com/assets/13489587/15937666/ca60f018-2e3d-11e6-8b59-a7c3dc758de3.png)
5. Conduct Query Builder one-term search
6. Double click one of the results.
7. Get the grey screen result as above.
8. Click "back to database view" in the SignStream window and see normal macro view of the file.
9. Click "change search domain" within the query window an choose new file.
10. Get another black macro view.
11. Clicking search returns nothing this time.

OR, from step 8:
9. Click into one of the utterances.
10. Now click "change search domain" within the query window an choose new file.
11. Program crashes completely and needs Force+Quit to exit.

**Comment by gregorydimitriadis** [comment]
Blaze,

I can also reproduce this behavior. I've noticed a workaround to head off the problem: At step 4, when the odd view comes up, expand the triangle on the left side displaying the name of the collection and double click the "macro_unit" text. This will fully open the collection/videos/etc.

For step 11, perhaps the search returns nothing that time because nothing in the new collection matches the searched word?

For the alternative step 11, I don't believe the program crashes, but it does hang as it seems to be trying to paint all the handshape images before switching collections. I think it does that because it zoomed out all the way first which then triggered the painting, which may be the root cause. I'll look into that.

All these issues basically stem from the fact that the search will behave oddly if you try to load it up without first loading a collection. I'm unable to mimic the behavior from SS2 that allowed a search to begin in the absence of an already loaded collection. I'll try to iron out these weird behaviors nonetheless though.

**Comment by gregorydimitriadis** [comment]
In the upcoming release, new search features included:
-New GUI-driven query builder, with support for individual search rules, temporal groups and nontemporal groups
-Expanded search engine to account for all new cases from the query builder
-Return to original state/domain, even from another domain
-Saving upon domain switching

Also included:
-Fix for blank utterance view if search begins in database view
-Fix for zooming out too far on domain switching
