### ISSUE TITLE
Window for Edit Macro Unit - lookup and display of video filenames

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#81]
Is the lookup function supposed to be working?  If not, should that button be removed?
Also it would be great to increase the size of the window.  It's impossible to see the filenames of the movies that one needs to find (!).

These display problems are obviously inherited from Iryna, but it would be really good if we could fix them.   Thanks.

![screen shot 2016-05-17 at 2 49 03 pm](https://cloud.githubusercontent.com/assets/13629122/15335105/e2a95fb8-1c3e-11e6-9af7-6539b13af8b8.png)

**Comment by gregorydimitriadis** [comment]
Does the horizontal scrollbar on the panel with the filenames work?

As for the Lookup, it should be working. I've noticed it works as intended if set the directory to search as one higher than the directory you expect to find the file.

**Comment by gregorydimitriadis** [comment]
On new release of this fix: Macro Unit window will be resizable, to allow the user to expand as needed to display long filenames.

**Comment by hammondcl** [comment]
Macro Unit window is now resizeable
