### ISSUE TITLE
Arrow keys (L/R) become disabled after clicking utterance from left-side list

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#84]
The application does not recognize the left/right arrow keys after clicking an utterance from the list.

**Comment by hammondcl** [comment]
This part is functional, however as I reported the other day, the left/right arrow keys are not recognized with some frequency when clicking on the yellow SignStream window (unselects video window). It is particularly noticeable in Cory files.

**Comment by gregorydimitriadis** [comment]
In reference to #17 - now in the queue of issues again.

**Comment by aimeeaylward** [comment]
A similar issue is occurring on occasion; I have noticed this after deleting an event. When using the arrow keys to scroll, the vertical green bar does not move while instead the whole window shifts to the left or right. For example, from this screenshot 
![screen shot 2017-04-28 at 11 12 35 am](https://cloud.githubusercontent.com/assets/25349160/25535248/64137f04-2c04-11e7-8142-8ea5f67effd3.png)
to this one
![screen shot 2017-04-28 at 11 12 24 am](https://cloud.githubusercontent.com/assets/25349160/25535253/69383f4c-2c04-11e7-99c2-5ff222bd5887.png)
all I did was press the right arrow key one time. You can notice that the green bar remains in the same location but that the window behind it has shifted to the left (evident by the smaller amount of dark yellow space on the left). 
This is resolved when choosing a new utterance but will reoccur sometimes after deleting an event.
