### ISSUE TITLE
'Play Utterance' button in UtteranceView

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#85]
The button for 'play utterance' used to play the current utterance from start to finish (in the old system where only one utterance was displayed at once). Now with multiple utterances possibly visible on screen, the 'play utterance' button will not simply play what is viewable on-screen.

Update:
Instead of playing the parts viewable on-screen, 'play utterance' button will instead play the selected utterance (meaning, the utterance selected on the left-side list). If it is possible to have different colors for the different selected items in the utterance lists between different segment tiers, then that will help. The most recently clicked utterance should act as the selected utterance.

**Comment by hammondcl** [comment]
This is working correctly
