### ISSUE TITLE
Gloss Window - handshape NullPointerException

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#9]
Select a handshape in the gloss window, but it doesn't show up below, and instead a NullPointerException is visible on the console output. It is saved but not shown in the gloss window or utterance window (this is known because it shows up again if the gloss window is again brought up for that particular gloss)

**Comment by blazetravis** [comment]
This looks like a problem that is visible only on the programmers' side.
