### ISSUE TITLE
Translation Field entities are offset by 2 frames on either side

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#90]
This bug concerns the data stored in the xml files for the translation fields being incorrectly offset

Technical details:
FreeTextField class has stored all of its entity objects with offsets of -2_packetDuration for the start and +2_packetDuration for the end. This has resulted in all databases being saved with incorrect start/end times.
This has implications for Field.getEntitiesBetween() which accounts for the buffer when finding utterances within a given field based on a start/end time.

**Comment by gregorydimitriadis** [comment]
Since this was not student-reported: a good test to see if the fix was good is to simply create/edit/delete translation field text from various utterances to see if everything works as intended.

**Comment by hammondcl** [comment]
I believe this is working correctly. I just tested it as you suggested and nothing strange happened.
