### ISSUE TITLE
Need a script to replace all value names in 'topic/focus' fields

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#91]
In SS3 at the moment we have values in this field for top1/top2/top3. We want to do two things:

1) First disallow in the SS3 field selector everything except 'topic'

2) Then write a shell script which will run through a list of databases (in their xml/zipped form) and do and in-place String replacement of all extraneous topic values to just 'topic' - we will run this script over a collection of databases which Carol will provide so we only need to run it once.

**Comment by cneidle** [comment]
This is not an accurate description of what needs to be done.  I will need to provide you with a list of the global changes that need to be made to the field values.  Some of these involve some values of topics, but that is not exhaustive.  It won't be a long list, however.

**Comment by gregorydimitriadis** [comment]
@cneidle - thanks. Do they all involve changing the value names in some way?

**Comment by cneidle** [comment]
yes

thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
Moving to Sprint_23 tentatively to determine details which may be needed for this script.

**Comment by gregorydimitriadis** [comment]
Moving out of sprint cycle, awaiting further requirements of scripting needs.

**Comment by gregorydimitriadis** [comment]
@cneidle assuming this is either outdated or irrelevant by now - please confirm

**Comment by cneidle** [comment]
Yes, this was taken care of long ago.  Thanks.
