### ISSUE TITLE
Cory 107 - no videos opening and can't work with utterances

### ISSUE THREAD

**Issue by geograil** [DCS-LCSR/SignStream3#93]
I was trying to open Cory 107 and it had a host of issues. We were working with the file last on June 7th and it was totally fine. This time, it won't open the videos, won't let you open to a specific utterance, and then once in utterance view, you can't even move the time bar to work within the utterances. It also shows Utterance 1 as blank, but the master gloss list shows that it did have content. 

Steps: 

I went to Collection -> Open and selected the file. It then opened like this: 

![screen shot 2016-07-05 at 12 12 45 pm](https://cloud.githubusercontent.com/assets/19953651/16591556/76c0030a-42aa-11e6-9cea-1451b6862620.png)

Moving the zoom bar did not help. I Shift+Clicked the long utterance bar, which then opened it to this view:

![screen shot 2016-07-05 at 12 13 27 pm](https://cloud.githubusercontent.com/assets/19953651/16591672/ee60b26a-42aa-11e6-9efa-3f3009b279c4.png)

I tried clicking a specific utterance, but that did not change the view. It just highlighted what I clicked and the one below it in the left sidebar. I tried to click into an utterance to move the green time bar, but it would just snap back to the beginning. There is no scroll ability on the bottom, so even when you zoom it's basically just stuck like this: 

![screen shot 2016-07-05 at 12 14 00 pm](https://cloud.githubusercontent.com/assets/19953651/16591722/2702831e-42ab-11e6-827b-4c7ababd7d26.png)

**Comment by geograil** [comment]
Nevermind to most of this - the videos had to be located. However, Utterance 1 is still blank and we know there was coded data on it prior. 

![screen shot 2016-07-05 at 12 35 40 pm](https://cloud.githubusercontent.com/assets/19953651/16592138/3d12eb2e-42ad-11e6-920c-8aef8a13b83f.png)

**Comment by gregorydimitriadis** [comment]
@geograil Is there still no data in Utterance1 after closing and re-opening Signstream?

**Comment by gregorydimitriadis** [comment]
@geograil Could you please email me the collection file for this issue?

**Comment by gregorydimitriadis** [comment]
I've looked into this collection, opened it up and looked at the data inside (outside of the Signstream app) and unfortunately I can see no events (nonmanual or manual) associated with utterance U1. This means that opening this collection at any point in the future will result in a blank U1, and all data that was coded previously has unfortunately been permanently lost and needs to be manually re-entered.

I'm not sure what caused the blank data in the first place, although I suspect it may have had to do with some changes for bugs around the time this issue was reported involving database (collection) switching, which have since been resolved. So the issue shouldn't re-occur, in this or any collection, as the switching logic has been strengthened recently.

**Comment by hammondcl** [comment]
There still appears to be some issue with this file. The file seems to open fine and there are no more zoom issues. I was able to open an utterance, then clicked "Database View" to go back to the main screen and now am unable to open any utterance. Double clicking an utterance bar highlights it in red in the first row, then the highlight jumps down to the second row and nothing happens. The utterance never opens.

![screen shot 2017-02-15 at 11 15 58 am](https://cloud.githubusercontent.com/assets/15836242/22983859/7943597e-f371-11e6-8039-aa0dbcb7cc11.png)

**Comment by hammondcl** [comment]
This actually appears to be a more universal issue as I just opened Rachel 43 and tried to check the frame jump issue in U36, but could not open any utterances. I was checking other changes from this sprint in Rachel 43 earlier, however, and everything opened fine. I have quit and reopened SignStream and it is still an issue. Then I quit and reopened SignStream again and could open whatever first utterance I clicked, but none after clicking "Back to Database View"

**Comment by aimeeaylward** [comment]
This issue seems to be resolved. When we tried it again the second utterance opened without an issue.

**Comment by cneidle** [comment]
Hi,  This was reported closed, but in fact this file is still problematic.  

Current issue:  The green slider is still not appearing at all in the non-manual area in U1 of file 107.

Also to be investigated: Chelsea and Amanda will be entering information in U1, which is still blank, and will report if there is a further problem with having information retained in the manual and non-manual fields in U1.
