### ISSUE TITLE
Unnecessary nonmanual fields showing

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#99]
I noticed this bug last week and have just gotten a chance to play with it and figure out what is going on. It is present in all files that I have checked, so I believe it is a global issue. 

What's happening: When you open an utterance (any utterance, any file), there are many blank nonmanual fields that appear. If I hide these, they go away, but then that field is missing from all other utterances in the file, even if there is data in that field for the utterance. It seems as though each utterance has all nonmanual fields that exist somewhere in that file visible. Note: It seems like it is only the fields present in that file, not all fields.

Steps:
1) Open any file (Rachel 43 used because it is made up of very simple sentences so there are many blank NM fields in each utterance)

2) Open any utterance in that file (U1 used). Many blank NM fields visible (neck, hp: tilt side, hm: jut, hm: side <-> side, shoulders, body lean, rhq, negative, and nose)
![screen shot 2016-07-19 at 4 49 48 pm](https://cloud.githubusercontent.com/assets/15836242/16966048/d88ff3ca-4dd0-11e6-864b-6f47427e5370.png)

3) Hide one or more empty NM fields by selecting it and clicking the red (-) button. Field disappears from that utterance. (neck, hp:tilt side, and body lean hidden)
![screen shot 2016-07-19 at 4 53 04 pm](https://cloud.githubusercontent.com/assets/15836242/16966171/562ec5fe-4dd1-11e6-9d3c-ad1ea08e9173.png)

4) Fields are also hidden in all other utterances in file (U2 used as example)
![screen shot 2016-07-19 at 4 56 09 pm](https://cloud.githubusercontent.com/assets/15836242/16966262/be56edf0-4dd1-11e6-89a5-fc52fbafdd97.png)

5) When fields are re-added to this utterance (U2), coding information that originally existed reappears (body lean and hp: tilt side in this utterance)
![screen shot 2016-07-19 at 4 57 53 pm](https://cloud.githubusercontent.com/assets/15836242/16966316/fc450a70-4dd1-11e6-872a-f113694b16d3.png)

**Comment by cneidle** [comment]
Hi Chelsea,

Do you know about the “refresh” button — which shows for the utterance in question
all fields for which there is data.  

It’s the blue button on top of the field list — to the right of the green + and the red -.

Will that solve this issue for you?

The default should be to open an utterance as if that button had been activated, though,
I would have thought…   Greg?

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
Yes, I believe the refresh button should be used in this scenario.

As for when a new utterance is clicked, currently it doesn't reload the nonmanual fields at that point. Would we want this to occur? This wouldn't necessarily also apply to scrolling through the utterances manually.

**Comment by hammondcl** [comment]
The refresh button does adjust the displayed fields to only those active in the utterance, as it is supposed to do, but then when moving to another utterance, either by scrolling or by clicking the Next/ Previous Utterance button, only those same fields remain visible.

**Comment by cneidle** [comment]
Just hit the refresh button again :-)

Thanks,
    Carol

**Comment by hammondcl** [comment]
This issue can be closed as it was more a case of my misunderstanding than anything else!

**Comment by gregorydimitriadis** [comment]
Thanks! Closing..
